### ISSUE TITLE
[circle2circle] Create pass to remove duplicate consant nodes

### ISSUE THREAD

**Issue by BalyshevArtem** [Samsung/ONE#10009]
### What

Let's create circle2circle pass to remove duplicate constant nodes. This pass will delete all similar constant nodes and propagate the only one for all places, where original one was used. 

### Why

There are some models that have constant nodes, which values is the same, so they are duplicate. Deleting such nodes can save memory, both the runtime memory and the size of circle file, which is very important for systems with a small amount of memory, for example MCU.  

### Note

https://github.com/Samsung/ONE/pull/10008#issuecomment-1308875134

**Comment by seanshpark** [comment]
For better maintenance of this Pass, this is not mandatory but highly recommended,
it would be nice to have some `circle2circle-dredd-recipe-test`.
could you please add them (recipe and others) to the draft?

**Comment by BalyshevArtem** [comment]
done
