### ISSUE TITLE
[infra] Update CMake version

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#10015]
### What?

Let's update minimum requirement CMake version.

### Why?

We are using cmake version minimum requirement
- Runtime: 3.5.1
- Compiler: 3.3

By internal issue, we need to update external code download implementation to use ID/PWD. 
This feature requires cmake version 3.7. 

https://cmake.org/cmake/help/latest/command/file.html#download

```
USERPWD <username>:<password>
    New in version 3.7.
    Set username and password for operation.
```

And somtimes we met issues because of cmake version.

I suggest to update cmake version minimum requirement to 3.10 at once because ubuntu 18.04 is using this version. 
Please give your opinion about this.

@Samsung/nncc_committers @Samsung/one_onert

**Comment by hseok-oh** [comment]
https://github.com/Samsung/ONE/issues/9432#issuecomment-1185145216

(Compiler's requirement is updated by #9434)
```
- Current requirement
  - Runtime: `3.5.1`
  - Compiler: `3.1` -> `3.3`
- Default version on linux
  - Ubuntu 16.04: `3.5.1`
  - Ubuntu 18.04: `3.10.2`
  - Ubuntu 20.04: `3.16.3`
  - Ubuntu 22.04: `3.22.1`
  - Tizen 5.5/6.0: `3.9.4`
  - Tizen 6.5: `3.16.4`
  - Tizen 7.0: `3.21.3`
```

**Comment by seanshpark** [comment]
I think compiler is OK with 3.10
