### ISSUE TITLE
[CFE] dredd test support count for CircleConst

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#10014]
dredd test uses `circle-inspect` tool to print operators but as CircleConst is not an operator, it doesn't show it.
I'm not sure which may be the best solution but I can think is to add an option to `circle-inspect` to print `CONST` for each `CircleCons`.
We need to revise
- `circle-inspect` to add option something like `--constants`
- `dredd-rule-lib/rule-lib.sh` to add something like `const_count`

If you like, you can change them or wait for someone to do it.
I'll post an issue for this.

_Originally posted by @seanshpark in https://github.com/Samsung/ONE/pull/10008#discussion_r1020968813_

**Comment by BalyshevArtem** [comment]
draft:  #10008

**Comment by seanshpark** [comment]
done :)
thank you @BalyshevArtem !
