### ISSUE TITLE
[one-optimize] Constant folding for FullyConnected

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#10066]
## What

Let's implement constant folding for FC layer.

**Comment by jinevening** [comment]
`FoldDepthwiseConv2DPass` would be helpful for this taks.

**Comment by seanshpark** [comment]
@jinevening , I also have needs of kernel codes for shape inference of luci service.

How about adding another module like `luci-kernels` or `luci-comptute` to provide computation codes for multiple purposes?
- constant folding in pass
- shape inference in service
- kernel codes for luci-interpreter
- ...

**Comment by jinevening** [comment]
Look good to me. #10081 does not harm code structure, so can we go as-is and introduce the new module after this task is done? This task is for our customer's model support.

**Comment by jinevening** [comment]
Done.

**Comment by seanshpark** [comment]
@jinevening , could you please add a test in `luci_pass_value_test` ?

**Comment by jinevening** [comment]
I'll add a test.
