### ISSUE TITLE
CFE enable RUY for ARM cross build

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#10085]
This feature is disabled cause of compiler error.
Let's enable this when the problem is fixed.

This issue is added not to forget the task.

**Comment by seanshpark** [comment]
related #10050

**Comment by chunseoklee** [comment]
FYI, armv7l-linux build is successful with:

```
(tf-2.8) ~/d/ONE> /usr/bin/arm-linux-gnueabihf-g++ -v
Using built-in specs.
COLLECT_GCC=/usr/bin/arm-linux-gnueabihf-g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc-cross/arm-linux-gnueabihf/9/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --without-target-system-zlib --enable-libpth-m2 --enable-multiarch --enable-multilib --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --disable-werror --enable-multilib --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=arm-linux-gnueabihf --program-prefix=arm-linux-gnueabihf- --includedir=/usr/arm-linux-gnueabihf/include
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
                                                                                                                                                   [ 0s | 11월 22 10:21오전 ]
(tf-2.8) ~/d/ONE> git rev-parse --short HEAD
76ddbe340
 ```

**Comment by chunseoklee** [comment]
FYI, here is the gcc's build configuration of tizen : 

> bash-3.2# gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc-real
COLLECT_LTO_WRAPPER=/usr/lib/gcc/armv7l-tizen-linux-gnueabi/9.2.0/lto-wrapper
Target: armv7l-tizen-linux-gnueabi
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib --libexecdir=/usr/lib --enable-languages=c,c++,fortran --enable-checking=release --disable-libssp --disable-bootstrap --disable-libvtv --enable-plugin --disable-libcc1 --disable-libgcj --with-slibdir=/usr/lib --with-system-zlib --with-sysroot=/ --enable-__cxa_atexit --enable-libstdcxx-allocator=new --enable-version-specific-runtime-libs --enable-linker-build-id --without-system-libunwind --enable-threads=posix --disable-multilib --enable-lto --enable-libcc1 --enable-libgfortran --with-arch=armv7-a --with-tune=cortex-a8 --disable-sjlj-exceptions --with-bugurl=http://bugs.tizen.org/ --with-pkgversion='Tizen GCC 9.2.0 20190812 6.53' --target=armv7l-tizen-linux-gnueabi --host=armv7l-tizen-linux-gnueabi --build=armv7l-tizen-linux-gnueabi
Thread model: posix
gcc version 9.2.0 (Tizen GCC 9.2.0 20190812 6.53)

**Comment by seanshpark** [comment]
`-mfpu=neon` gives same error `'asm' operand has impossible constraints`

**Comment by seanshpark** [comment]
done
