### ISSUE TITLE
[one-optimize] Fold constant int8 + Dequantize Op pattern

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#10203]
## What

Let's support constant folding of int8 tensor + Dequantize pattern.

## Why

Some TF models have int8-quantized weights.

**Comment by seanshpark** [comment]
I'll work on this item :)

**Comment by jinevening** [comment]
Folding int8 tensor + Dequantize is already supported. @seanshpark Thanks for letting me know.
