### ISSUE TITLE
Compiler FE: Enable REDUCE_MIN Op

### ISSUE THREAD

**Issue by sun-sharma** [Samsung/ONE#1021]
- [x]  res/TensorFlowPythonExamples
- [x]  res/TensorFlowLiteRecipes
- [x]  tflchef
- [x]  tflite2circle
- [x]  tfldump, circledump
- [x]  luci.IR
- [x]  luci.Import
- [x]  luci.Export
- [x]  luci.logex
- [x]  luci.Service
- [x]  luci.tests

Ref #873

**Comment by ko-dimi** [comment]
@sun-sharma, ping on the status of this, can we borrow that from you, if you haven't started yet?
