### ISSUE TITLE
[luci] Set correct shape in ReplaceNonConstFCWithBatchMatMulPass

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#10241]
## What

Let's set correct shape in ReplaceNonConstFCWithBatchMatMulPass.

## Why

FC with keep_num_dims=false produces a tensor with reduced ranks. Currently, `ReplaceNonConstFCWithBatchMatMulPass` does not handle this case correctly.

To fix this, we can add Reshape Op after BatchMatMul, i.e., FC -> BMM + Reshape, to keep the shape of FC Op.

If the created Reshape Op is redundant (input shape == output shape), it can be removed by `RemoveUnnecessaryReshapePass`

**Comment by seanshpark** [comment]
>  it can be removed by RemoveUnnecessaryReshapePass

How are you going to enable this pass?

**Comment by seanshpark** [comment]
@jinevening , could you add a recipe and dredd test to check the new Pass?

**Comment by jinevening** [comment]
> How are you going to enable this pass?

Users should enable the pass.

>  could you add a recipe and dredd test to check the new Pass?

I see. This updates the existing Pass, so existing dredd test will be updated too.

**Comment by seanshpark** [comment]
> test (FullyConnected_007) will be updated.

As we took a short offline chat, let's add new recipe with new dredd test that introduces `Reshape` without any conditions :)

**Comment by jinevening** [comment]
I'll make a new test (FullyConnected_008) to test existence of `Reshape`.

**Comment by jinevening** [comment]
Done.
