### ISSUE TITLE
[circle-quantizer] Support ReduceProd Op

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#10305]
## What

Let's support ReduceProd Op

## Why

https://github.com/Samsung/ONE/issues/10304

- [x] luci-interpreter kernel #10310
- [x] QuantizeConstInputActivation
- [x] InsertQuantizeOp (for mpq) 
- [x] Fake quantization #10339

**Comment by BalyshevArtem** [comment]
All done, close it
