### ISSUE TITLE
[record-minmax] ERROR: Unsupported operator: 71 model/tf.math.reduce_prod/Prod

### ISSUE THREAD

**Issue by brauma** [Samsung/ONE#10304]
When trying to compile (`one-build -C build_config.cfg`) a model, I get an unsupported operator error from the record-minmax tool. To reproduce the problem from our complex speech separation model, I created this simple example code that yields the same error. 

I see in the [1.5.0 release notes](https://github.com/Samsung/ONE/blob/master/docs/release/1.5/release-note-1.5.0.md) that the ReduceProd operator became supported, but it looks like the record-minmax tool doesn't support it.

Is this actually an unsupported operator? If so, may I request support for it? 

Any help would be greatly appreciated!

- OS: Ubuntu 20.04.5 LTS
- Python: 3.6.15
- Tensorflow: 2.6.2
- ONE-compiler: 1.21.0

Error message:

```record-minmax: ERROR: Unsupported operator: 71 model/tf.math.reduce_prod/Prod```

Example test model:
```
import tensorflow as tf
import tensorflow.keras as keras

inputs = keras.layers.Input((10,10))
x = tf.math.reduce_prod(inputs, axis=1)
outputs = keras.layers.Dense(1)(x)
model = keras.Model(inputs=inputs, outputs=outputs)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with open('model.tflite', 'wb') as f:
    f.write(tflite_model)
```
Files attached:
- model.py 
- model.tflite
- build_model.cfg

[files.zip](https://github.com/Samsung/ONE/files/10373483/files.zip)

**Comment by jinevening** [comment]
> I see in the [1.5.0 release notes](https://github.com/Samsung/ONE/blob/master/docs/release/1.5/release-note-1.5.0.md) that the ReduceProd operator became supported, but it looks like the record-minmax tool doesn't support it.

The release note might have confused you. AFAIK, the note indicates support for import/export of operators. At v1.5.0, record-minmax (and other quantization tools) did not even exist :)

ReduceProd is not yet supported by our quantizer. I made https://github.com/Samsung/ONE/issues/10305 for ReduceProd support.

Could you give more information about "complex speech separation model"? It will be helpful to determine the priority of the task.

**Comment by jinevening** [comment]
I close this issue as #10305 is resolved.
