### ISSUE TITLE
[one-cmds] Generate log file for test

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#10344]
## What 

Let's generates the log files for each test.

## Why

As of now, some tests don't generate the log of its test.

https://github.com/Samsung/ONE/blob/a49eb91fe77e305068575afb65eea3bedf5d9503/compiler/one-cmds/tests/onecc_001.test#L34

But, it forces us to run again without `/dev/null` part if the test failed. And even though the test on the CI failed, we can't know about the exact reason.

So, let's make them generate the log file like below.

https://github.com/Samsung/ONE/blob/a49eb91fe77e305068575afb65eea3bedf5d9503/compiler/one-cmds/tests/onecc_030.test#L41

@seanshpark What's your take on this? Is it okay to proceed this task?

**Comment by seanshpark** [comment]
> it forces us to run again without /dev/null part if the test failed

yes, this is current problem :(

> Is it okay to proceed this task?

I think creating logs for all the tests looks OK :)
