### ISSUE TITLE
Compiler FE: enable Neg operator

### ISSUE THREAD

**Issue by ko-dimi** [Samsung/ONE#1034]
- [x] tflchef (#1338)
- [x] tfldump (nothing to do)
- [x] circledump (nothing to do)
- [x] luci.IR (#1340)
- [x] luci.Import #1481
- [x] luci.Export #1482
- [x] luci.logex #1483 
- [x] luci.Service #1484 
- [x] res/TensorFlowPythonExamples (#1337)
- [x] res/TensorFlowLiteRecipes (#1475)
- [x] tflite2circle (#1339)
- [x] luci.tests (#1558)

for #873
on behalf of a-kvochko

**Comment by binarman** [comment]
looks like we missed this operator =_=
@kvochko could you make rest of PRs?

**Comment by kvochko** [comment]
All done
