### ISSUE TITLE
[luci] Fuse InstanceNorm for Rank3 LayerNorm

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#10357]
## What

Let's fuse IN for a special case (Rank3 LayerNorm)

## Why

Our target model has the pattern.

**Comment by stamalakhov** [comment]
@jinevening 
M.b. i could try to resolve it in case it's actual?

**Comment by jinevening** [comment]
Let's hold this issue for a while. Our backend is handling decomposed LN. If it is converted to IN, we may need to update the backend too.

**Comment by stamalakhov** [comment]
> Let's hold this issue for a while. Our backend is handling decomposed LN. If it is converted to IN, we may need to update the backend too.

ok.
