### ISSUE TITLE
[one-optimize] Remove unnecessary Add

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#10358]
## What

Let's remove unnecessary Add (add constant 0)

![image](https://user-images.githubusercontent.com/5449554/213355917-e4f60396-828c-49ff-976e-77d8fd862ef2.png)

`--remove_unnecessary_add` option will need to be added to `one-optimize`.

## Why

To optimize our target model.

**Comment by stamalakhov** [comment]
@jinevening 
Is the task still actual?
is yes, 
then may be i can try to resolve it?

**Comment by jinevening** [comment]
Of course. Thank you :)

**Comment by jinevening** [comment]
Now we can close this issue. Thanks @stamalakhov !
