### ISSUE TITLE
[one-optimize] Make a basic option sets for safe optimization (O1)

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#10381]
## What

~Let's make pre-defined option sets for optimization.~

~We may group some options by level of optimizations, e.g., `-O`, `-O2`, or by source models, e.g., `--source onnx`, `--source tflite`.~

~Or we can use both. `--source onnx -O`.~

Updated 2023/02/17: Let's make a basic option sets for safe optimizations (O1), which do not change the execution result of models and finish within a reasonable time.

## Why

To make our customers easily select proper options. Note that our customers directly requested this feature.

We have discussed this topic for a long time, and it's time to proceed :)

Previous discussions
- https://github.com/Samsung/ONE/issues/5784
- https://github.com/Samsung/ONE/issues/7350
- #9191
- #9369
- ...

CC @seanshpark @mhs4670go

**Comment by mhs4670go** [comment]
Please refer to https://github.com/Samsung/ONE/issues/7513. As of now we have the infra that makes it possible to provide pre-defined options. Maybe -OONNX, -OTFL option could be one of candidates.

**Comment by jinevening** [comment]
@mhs4670go As discussed offline, #7513 supports functionality of `onecc` (previously `one-build`) to import another config file using CLI. I hope we can set default options inside the cfg file. For example,

```
[one-optimize]
input_path=...
output_path=...
source=onnx
```

**Comment by jinevening** [comment]
I'm considering pre-defined option sets for the below cases.

By the level of optimization,
`O1`: This option sets will include most optimization options which do not change the result of the model.
- We'll need to measure the compile time when applying `O1` to our target models. If it is too time-consuming, we may introduce `O2` and move some options from `O1` to `O2`.

By the source of model (`source` attribute),

1. `onnx`: `O1` + `convert_nchw_to_nhwc` related options
2. `tf`: `O1`
3. `tflite`: `O1`

@mhs4670go @seanshpark  @lemmaa  Could you give your opinions?

**Comment by seanshpark** [comment]
> Could you give your opinions?

(background: we cannot be perfect in the first place)
I think we can go with your proposal.
The problem: when something is wrong with some particular model but works OK with most...
Somehow we have to make a change, but what happens to most models working OK?

**Comment by jinevening** [comment]
> Somehow we have to make a change, but what happens to most models working OK?

I'm considering option sets that work for all of the current commercial models (I guess that is our best for now). If a new model causes an issue, let's resolve that at that time :)

**Comment by jinevening** [comment]
Let's narrow down the task to make a basic option sets for safe optimizations (O1).

Background: https://github.com/Samsung/ONE/pull/10463#issuecomment-1430628660

**Comment by jinevening** [comment]
Interface for group option has changed. Users can use `include` feature in `onecc` for group option. For example,

For example,
```
[onecc]
one-import-onnx=True
one-optimize=True
include=O1
```

**Comment by jinevening** [comment]
I close this as basic O1 feature is landed.
