### ISSUE TITLE
[circle-mpqsolver] Replace `ErrorApproximator` with `visq`

### ISSUE THREAD

**Issue by stamalakhov** [Samsung/ONE#10393]
### What

Replace `ErrorApproximator` with `visq`.
### Why
Because `ErrorApproximator` is not general enough to provide error estimations for all types of nodes, we need to replace it with `visq`.

**Comment by stamalakhov** [comment]
@jinevening 
Introduction of total error computer to `visq` component produced admissible results:
![image](https://user-images.githubusercontent.com/112689352/216008239-98ec06c9-ebbe-4dd9-9e84-c8451d918a2d.png)
But it is very disk intensive, actually for MobileNetV1 it took 30 Gb, and for CARTOON over 60 Gb (100 images only). So i don't have a chance to run it on my ssd, just using hdd.
May be for mpq_solver  we could estimate total error by inside mpq_solver using ExecutionObserver ?

**Comment by jinevening** [comment]
> May be inside mpq_solver we could estimate total error using ExecutionObserver and directly calling Interpreter with hooks attached?

I think that will significantly increase program complexity. Maybe you can make a separate module (or extend `visq`) to generate the information you want.

As to the disk usage of `visq`, I agree that is definitely an issue. One alternative may be to use partial dataset.

You can make partial h5 file using `h5copy`.

**Comment by jinevening** [comment]
> Or may be we can change visq component, so that it process quantization errors pairwise (float vs fake_quantized) on each sample sequentially?

This can also be a good alternative. Currenlty `visq` invokes `dalgona` with full data set. For per-sample analysis, `visq` will have to invoke `dalgona` per sample.

**Comment by stamalakhov** [comment]
> > Or may be we can change visq component, so that it process quantization errors pairwise (float vs fake_quantized) on each sample sequentially?
> 
> This can also be a good alternative. Currenlty `visq` invokes `dalgona` with full data set. For per-sample analysis, `visq` will have to invoke `dalgona` per sample.

Ok. I'll try this one.

**Comment by stamalakhov** [comment]
Seems like we can close this one, as for now bisection can be used with `visq` parameter for `auto` mode.
