### ISSUE TITLE
[onert] Revoke interpreter and set default backend

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#10409]
At first, interpreter was introduced for fail-through and thread-safe backend. But it is not maintained now so its kernel is very small set of cpu backend. And currently cpu backend works as default backend. 
For design simplification, I suggest to remove interpreter and include `cpu` backend in runtime core as default backend.

Please give here your opinion about this.

@Samsung/one_onert @lemmaa

**Comment by lemmaa** [comment]
Are there any expected disadvantages in removing the interpreter? Then there is no reason to stop it. :)

**Comment by hseok-oh** [comment]
Interpreter is removed. And as we discussed on offline, there is no default backend.
