### ISSUE TITLE
[CFE] Revisit docker script for nncc build

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#10425]
## What

Let's revisit the script where _nncc_ is built inside the docker container.

Related: https://github.com/Samsung/ONE/issues/10389#issuecomment-1414896045

## Why

https://github.com/Samsung/ONE/blob/325f167873ada19434950d97291071f64501c519/infra/scripts/docker_build_nncc.sh#L74-L75

In the script, _debuild_ is run with `--buildinfo-option=-ubuild --changes-option=-ubuild` options.

```bash
# --buildinfo-option=-ubuild
-uupload-files-dir
              Look for the files to be uploaded in upload-files-dir rather than ..  (dpkg-genbuildinfo needs to find these files so that it
              can include their sizes and checksums in the .buildinfo file).

# --changes-option=-ubuild
-uupload-files-dir
              Look  for  the files to be uploaded in upload-files-dir rather than ..  (dpkg-genchanges needs to find these files so that it
              can include their sizes and checksums in the .changes file).
```

These options were introduced for workaround.

_debuild_ creates its artifacts on the parent directory. But `./nncc docker-run` mounts only _ONE_ project directory, which is why current workaround is needed. The workaround makes the _debuild_ change the artifacts' path inside the project directory.

But, default _debuild_ behavior of above options has changed a bit from ubuntu 22.04. And it is seems hard to make it do the same behavior with the one from previous ubuntu version. Every time new version comes out, the behavior could change again, which would be a big costs. It'd better not to use the options.

So, let's use just `docker run` command instead of `./nncc docker-run` one. And, just not to use the options.

**Comment by hseok-oh** [comment]
I have plan to remove docker_xxx.sh build script, and use docker container as jenkins build agent directly. Runtime build scripts are already removed, and compiler also uses this feature. Remain is only compiler packaging script. I'm testing to resolve permission issue, but it needs some time to resolve issue because jenkins docker agent has difficult issue to use root user.

**Comment by mhs4670go** [comment]
@hseok-oh Oh, it would be very helpful! Then, should I just put this issue on hold? Or just go to proceed?

**Comment by hseok-oh** [comment]
> @hseok-oh Oh, it would be very helpful! Then, should I just put this issue on hold? Or just go to proceed?

If this is not emergency issue, please wait. IMHO, it may takes 1~2 week to resolve permission issue.

**Comment by hseok-oh** [comment]
Currently, CI infra is not using `./nncc docker-run` and `docker_build_<xxx>.sh` script any more.

**Comment by mhs4670go** [comment]
@hseok-oh With the change, now `debuild` command don't need unnecessary options to change the path of the artifact. But, the permission issue (https://github.com/Samsung/ONE/issues/10389#issuecomment-1409647524) still happens. This is because _cmake_ can't access the file system. I don't have any idea why for now.

So, I'm going to add an argument for the permission like below on jenkins. Please let me know if you have any ideas about this.

```groovy
docker {
  image 'rs7-runtimentools-docker-local.bart.sec.samsung.net/one-devtools:jammy-proxy'
  label 'builder'
  args '--privileged'
}
```

**Comment by mhs4670go** [comment]
The docker script has been deprecated because CI doesn't use the scripts anymore.
