### ISSUE TITLE
[onert-micro] Support models with GRU

### ISSUE THREAD

**Issue by BalyshevArtem** [Samsung/ONE#10465]
## What

Need to implement supporting of GRU operations in onert-micro.

## Why

Some target-benchmark models contain such operation.

## Example

As example lets take this model (from  #8747):

Here is a example code to generate with GRU : 

``` python
# !pip install tensorflow==2.7.0
import numpy as np
import tensorflow as tf

model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(28, 28), name='input'),
    tf.keras.layers.GRU(20, time_major=False, return_sequences=True),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax, name='output')
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.summary()

run_model = tf.function(lambda x: model(x))
# This is important, let's fix the input size.
BATCH_SIZE = 1
STEPS = 28
INPUT_SIZE = 28
concrete_func = run_model.get_concrete_function(
    tf.TensorSpec([BATCH_SIZE, STEPS, INPUT_SIZE], model.inputs[0].dtype))

# model directory.
MODEL_DIR = "keras_lstm"
model.save(MODEL_DIR, save_format="tf", signatures=concrete_func)

converter = tf.lite.TFLiteConverter.from_saved_model(MODEL_DIR)
tflite_model = converter.convert()

with open('model.tflite', 'wb') as f:
  f.write(tflite_model)

```

- model link with GRU : [gru.zip](https://github.com/Samsung/ONE/files/8368702/gru.zip)

## How
After converting to tflite model we have the next model:

![GRU_example](https://user-images.githubusercontent.com/43214667/218993024-397825f0-eeaa-499d-b221-ecbd8756d695.png)

So to support this model we need to support:
1) While operation
2) Gather operation
3) Maybe smth else (TBD)

So there is small plan to support GRU:
 - [x] Support and check inference with models with multiple subgraphs (for While op) 
 - [x] Support While op
 - [x] Support Gather op
 - [x] TBD 
 - [x] Check GRU model values
 - [x] Optimize this operation to reduce memory runtime consumption

**Comment by chunseoklee** [comment]
I will find a way to generate a model with single GRU op in tflite format.

**Comment by chunseoklee** [comment]
close since basic model above is now supported.
