### ISSUE TITLE
[one-quantize] Support fine-grained input/output quantization dtype

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#10493]
## What

Let's allow users to set dtype of each input/output

## Why

Current interface only allows to set the same dtype for all inputs (or all outputs).

From `one-quantize -h`
```
  --input_type INPUT_TYPE
                        data type of inputs of quantized model (supported:
                        uint8, int16, float32, default=quantized_dtype).
                        QUANTIZE Op will be inserted at the beginning of the
                        quantized model if input_type is different from
                        quantized_dtype.
  --output_type OUTPUT_TYPE
                        data type of outputs of quantized model (supported:
                        uint8, int16, float32, default=quantized_dtype).
                        QUANTIZE Op will be inserted at the end of the
                        quantized model if output_type is different from
                        quantized_dtype.
```

This works for most of simple CNN models. However, complex NN models (ex: RNN, transformer) will require a more fine-grained setting for input/output, especially with mixed-precision quantization.

**Comment by jinevening** [comment]
Interface will be like as below.

For a model with three inputs and three outputs,

cmdline
```
onecc quantize --input_type uint8;int16;uint8 --output_type int16;uint8;int16
```

cfg
```
[one-quantize]
...
input_type=uint8;int16;uint8
output_type=int16;uint8;int16
```

The order of inputs/outputs must be set correctly.

**Comment by seanshpark** [comment]
> onecc quantize --input_type uint8;int16;uint8 --output_type int16;uint8;int16

`;` is used to separate command

```
$ a;b;c
-bash: a: command not found
-bash: b: command not found
-bash: c: command not found
```

do not use this.

**Comment by jinevening** [comment]
Thanks. I'll use `,` as a delimiter.

**Comment by jinevening** [comment]
All done.
