### ISSUE TITLE
[Q] Compile into multiple backend binaries with one cfg file

### ISSUE THREAD

**Issue by jyoungyun** [Samsung/ONE#10537]
## What

Currently, the cfg file provides backend option for `codegen`, `profile`, and `infer` tools. The `onecc` executes each backend tool according to the backend option.

If I want to compile one cfg file to multiple backends binray, how can I do?

As far as I know, I need to create three different cfg files that contain each backend name.
I don't think this is efficient.

Is there any solution that can compile to multiple backend binaries using one cfg file?

If the `onecc` frontend tool supports the `backend` option, it can be compiled into multiple backend binaries with one cfg file.
If possible, could you consider supporting the `backend` option in `onecc` frontend tool?

**Comment by lemmaa** [comment]
This seems like a good example of what we're experiencing with actually supporting multiple backends. 👍

**Comment by mhs4670go** [comment]
Well, in a nutshell, you can do what you want to do with workflows feature rather than the cfg feature. You can see the examples in [here](https://github.com/Samsung/ONE/tree/3222491722fc813ffa72697ba21b8e841ca01faa/compiler/one-cmds/tests).

cfg feature is designed to call each _one-cmds_ tools only once. And, IMHO, I'd have multiple cfg file for multiple backends because it''d be more convenient for me. However, each person's taste is different, so workflows feature was introduced to support various use cases.

**Comment by seanshpark** [comment]
@jyoungyun , this is feature needed in `ONE-vscode` ?

**Comment by seanshpark** [comment]
One idea that pop-uped

as-is
```
[code-gen]
backend=trix
command=-O compild.trix .....
```
to-be
```
[code-gen]
backend=trix
command=-O compild.trix .....
backends=trix,trix-2,trix-3
trix=-O compild.trix .....
trix-2=-O compild.trix-2 .....
trix-3=-O compild.trix-3 .....
```
same key `trix` in `backends` will be ignored
```
[code-gen]
backend=trix
command=-O compild.trix .....
backends=trix-2,trix-3
trix-2=-O compild.trix-2 .....
trix-3=-O compild.trix-3 .....
```
-> we will have 3 outputs, trix, trix-2, trix-3
```
[code-gen]
backends=trix-2,trix-3
trix-2=-O compild.trix-2 .....
trix-3=-O compild.trix-3 .....
```
-> we will have2 outputs, trix-2, trix-3


any comments?

**Comment by jinevening** [comment]
@seanshpark I think introducing `backends` is a simple and good solution.

> same key trix in backends will be ignored

One concern is that users may be a little bit confused for the silent ignorance. I think it would be better to prevent such cases at all in the interface. For example, throwing an exception when `backend` and `backends` are used at the same time.

**Comment by seanshpark** [comment]
> For example, throwing an exception when backend and backends are used at the same time.

Ah, idea was both `backend` and `backends` can be used.
Anyway, I'd like to get more options about this :)

About throwing exception, we can (1) show `WARNING: same triv exist in backend and backends` and continue (2) show `WARNING: backend is ignored as backends exist` and continue (3) show `ERROR: please use one of backend or backends` and stop.

**Comment by jyoungyun** [comment]
> @jyoungyun , this is feature needed in `ONE-vscode` ?

Yes, this issue is came from ONE-VSCode.

I will support multiple backends in ONE-VSCode.
User can install multiple backends in ONE-VSCode. However, even if the user selects a specific backend, if cfg sets
 another backend as a backend, the cfg file cannot be compiled using the backend desired by the user. I want to solve this problem.

> to-be
> ```
> [code-gen]
> backend=trix
> command=-O compild.trix .....
> backends=trix,trix-2,trix-3
> trix=-O compild.trix .....
> trix-2=-O compild.trix-2 .....
> trix-3=-O compild.trix-3 .....
> ```

> Ah, idea was both `backend` and `backends` can be used.

I think the coexistence of `backend` and `backends` seems to be helpful for backward compatibility.

This way seems appropriate to express which backend this cfg file supports.

When a cfg file supports `trix1`, and `trix2`, how should the `onecc` command be used if the user wants to compile this file only with the `trix1` backend?
Do you consider adding the `--backend` option to the onecc frontend file?

**Comment by seanshpark** [comment]
> When a cfg file supports trix1, and trix2, how should the onecc command be used if the user wants to compile this file only with the trix1 backend?
Do you consider adding the --backend option to the onecc frontend file?

Ah...

So we have different problems
(1) cfg can provide multiple backends --> capability
(2) user wants to build with the cfg (with multiple backends) but actully want to build some of the backends

I think `--backend` option is about (2) problem. I think `--backend` is to specify only one (@mhs4670go , can you please confirm this?)
Do we need to codegen for two or more? or is only one is enough?
If two or more then we can expand `--backend` to handle multiple with CSV or add `--backends` option.

**Comment by jyoungyun** [comment]
> I think `--backend` option is about (2) problem. I think `--backend` is to specify only one (@mhs4670go , can you please confirm this?)
> Do we need to codegen for two or more? or is only one is enough?
> If two or more then we can expand `--backend` to handle multiple with CSV or add `--backends` option.

In ONE-VSCode scenario, I need to specify only one for backend tools.

When cfg has a `backend` with multiple backend names, how about setting a default behavior of compiling cfg using multiple backends?

I mean, 

a.cfg
```
[codegen]
backends=trix1, trix2
trix1=xxx
trix2=xxx
```
`onecc -c a.cfg`
-> we will have `trix1` and `trix2` outputs.

`onecc -c a.cfg --backend trix1`
-> we will have `trix1` output.

`onecc -c a.cfg --backend trix3`
-> Error

**Comment by seanshpark** [comment]
> When cfg has a backends with multiple backend names, how about setting a default behavior of compiling cfg using multiple backend

Yes, I have same thoughts :)

**Comment by mhs4670go** [comment]
Above suggestions look good to me. 

And, I have a question about the issue to understand the situation correctly. 

> User can install multiple backends in ONE-VSCode. However, even if the user selects a specific backend, if cfg sets
another backend as a backend, the cfg file cannot be compiled using the backend desired by the user. I want to solve this problem.

@jyoungyun Even if the user selects a specific backend, if cfg sets another backend as a backend, should it throw an error?

**Comment by jyoungyun** [comment]
> @jyoungyun Even if the user selects a specific backend, if cfg sets another backend as a backend, should it throw an error?

In this case, we need to set a policy.
There are many cfg files with specified backend. If we throw an error in all cases where backend is fixed, we need to update a lot of cfg files. However, if we modify to put `backends` keywords, it is not a problem as we can modify it together at this time.

**Comment by lemmaa** [comment]
> if cfg sets another backend as a backend, should it throw an error?

@mhs4670go , AFAIK, we already have a policy on this. Settings in `*.cfg` in one-cmds can be overridden by command-line options. Isn't it?

**Comment by mhs4670go** [comment]
@lemmaa 

> Settings in `*.cfg` in one-cmds can be overridden by command-line options.

This phrase is right. But, IIUC, "Even if the user selects a specific backend, if cfg sets another backend as a backend" is a bit different situation. 

What you said is about using _one-cmds_ individual tools - e.g. _one-optimize_, _one-import-tf_ - (rather than  _onecc_) with `*.cfg` and the command line arguments. In this case, the command line arguments can be overridden.

But, what we are talking about is about using _onecc_ with `*.cfg`. And, there is some mismatch between the user's selection on ONE-VSCode and the one on `*.cfg`. _onecc_ can't override sub-one-cmds tools' option by command line interface.

**Comment by lemmaa** [comment]
> But, what we are talking about is about using _onecc_ with `*.cfg`. And, there is some mismatch between the user's selection on ONE-VSCode and the one on `*.cfg`. _onecc_ can't override sub-one-cmds tools' option by command line interface.

I don't think the case is different. If the settings for the backend selected in one-vscode are not present in `*.cfg`, it should just throw an error. 

In this situation, it doesn't matter what the default backend value of `*.cfg` is.

**Comment by mhs4670go** [comment]
>  If the settings for the backend selected in one-vscode are not present in `*.cfg`, it should just throw an error. In this situation, it doesn't matter what the default backend value of `*.cfg` is.

Well, that is what I exactly asked for in https://github.com/Samsung/ONE/issues/10537#issuecomment-1482311133 and I agree on it. Maybe English caused some misunderstanding.

**Comment by jyoungyun** [comment]
@mhs4670go Could you support `--backend` option to override the backend option in cfg file a littler earlier? If possible, I'd like to support multiple backends on ONE-VSCode before TRIV2.4 official release. :)

**Comment by jyoungyun** [comment]
@mhs4670go Thank you for your supports.

I used this new `--backend` option with onecc tool and it worked well.

I occurred a question during using this tool.
When there is no backend that matches the cfg file, onecc compiles the cfg file before code-gen part and then spits out an error.
Is it your intention?

```
$ onecc -b aaa -C mv1.cfg 
WARNING:absl:Found untraced functions such as gen_tensor_dict while saving (showing 1 of 1). These functions will not be directly callable after loading.
Estimated count of arithmetic ops: 72.585 M  ops, equivalently 36.292 M  MACs
Recording 0'th data
Recording 1'th data
Recording 2'th data
Recording finished. Number of recorded data: 3
usage: one-codegen [-h] [-v] [-C CONFIG] [-b BACKEND] [--] [COMMANDS FOR BACKEND]
one-codegen: error: Not found the command of given backend
```

**Comment by lemmaa** [comment]
We need to expand this feature to `[one-profile]`.

**Comment by mhs4670go** [comment]
@jyoungyun Maybe the issue can be closed

**Comment by jyoungyun** [comment]
> @jyoungyun Maybe the issue can be closed

Sure. I will close this issue. Thank you for your support. :)
