### ISSUE TITLE
[circle-mpqsolver] Implement better logging

### ISSUE THREAD

**Issue by stamalakhov** [Samsung/ONE#10612]
### What

Implement better logging (`e.g how the configuration was found, or why search fails`)

### Why

Because users of `circle-mpqsolver` need detailed information about bisection runs.

**Comment by jinevening** [comment]
Could you share your plan about logging? It would be better to clarify the scope of this issue.

**Comment by stamalakhov** [comment]
@jinevening 
I'm going to provide better logging in `CircleMPQSolver`, it will describe actual parameters of `circle-mpqsolver` run.
May be there are suggestions what parts of the workflow should be improved?
BTW is there any need to output `depth parameterized` network? or intermediate `mpq` configurations?

**Comment by jinevening** [comment]
>  is there any need to output depth parameterized network? intermediate mpq configurations?

The intermediate networks and mpq configurations may be useful in some senses (debugging or analysis). Maybe you can simply dump intermediate data when an option is given. For example, in `one-quantize`, we save intermediate networks if `save_intermediate` option is given.

In addition, I think that for visualization it will be very useful to dump quantization errors (ex: the model-level qerror (mpeir, srmse, mse), layer-wise qerror from visq) of each intermediate network.

**Comment by stamalakhov** [comment]
> The intermediate networks and mpq configurations may be useful in some senses (debugging or analysis). Maybe you can simply dump intermediate data when an option is given. For example, in `one-quantize`, we save intermediate networks if `save_intermediate` option is given.

Ok. Thank you. 


> In addition, I think that for visualization it will be very useful to dump quantization errors (ex: the model-level qerror (mpeir, srmse, mse), layer-wise qerror from visq) of each intermediate network.

Yes. IMHO it will be very useful. Thank you.

**Comment by stamalakhov** [comment]
> In addition, I think that for visualization it will be very useful to dump quantization errors (ex: the model-level qerror (mpeir, srmse, mse), layer-wise qerror from visq) of each intermediate network.

@jinevening 
Currently `circle-mpqsolver` uses only `MSE` metric, is it needed to implement addtional target metrics `mpeir`, `srmse` for `circle-mpqsolver`?

**Comment by jinevening** [comment]
> it needed to implement addtional target metrics mpeir, srmse for circle-mpqsolver?

It would be an interesting feature, but not mandatory. Let's go with `mse` for now, and extend to other metrics later.

**Comment by stamalakhov** [comment]
Seems like we cam close this one due to #10620 being merged.
There will be another issue for intermediate results.
