### ISSUE TITLE
Compiler FE: Enable LESS_EQUAL Op

### ISSUE THREAD

**Issue by ko-dimi** [Samsung/ONE#1062]
- [x] tflchef #2012 
- [x] tfldump, circledump  (nothing to do)
- [x] luci.IR #2011 
- [x] luci.Import #2178 
- [x] luci.Export #2177 
- [x] luci.logex #2179 
- [x] luci.Service #2180 
- [x] res/TensorFlowPythonExamples  (was done before)
- [x] res/TensorFlowLiteRecipes #2176 
- [x] tflite2circle #2013 
- [x] luci.tests #2181 

for #1167

**Comment by binarman** [comment]
draft #1631

**Comment by binarman** [comment]
Everything is done, Thank you!
