### ISSUE TITLE
Bump up circle schema (0.4 -> 0.5)

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#10629]
## What

Let's update circle schema (0.4 -> 0.5) to sync with TF 2.10 (`v2.10.1`)

CC @seanshpark @lemmaa @hseok-oh

**Comment by hseok-oh** [comment]
There is 3 places related with circle schema

- Common (nnpackage definition): `nnpackage/schema/circle_schema.fbs`
  - Not used for build and test 
  - Draft: https://github.com/Samsung/ONE/pull/9156 
- Runtime: `runtime/onert/frontend/circle_schema/include/circle_schema_generated.h`
- Compiler: `res/CircleSchema/<version>/circle_schema.fbs`

**Comment by jinevening** [comment]
> Runtime: runtime/onert/frontend/circle_schema/include/circle_schema_generated.h

Do I have to generate `circle_schema_generated.h` manually? Or is there a script for that purpose?

**Comment by jinevening** [comment]
Places where mio-circle04 is being used.

```
$ git grep mio-circle04
.ahub/tcchecker-tca/config.yaml:      - /compiler/mio-circle04
compiler/circle-inspect/requires.cmake:require("mio-circle04")
compiler/circle-operator/requires.cmake:require("mio-circle04")
compiler/circle-tensordump/requires.cmake:require("mio-circle04")
compiler/circle-verify/requires.cmake:require("mio-circle04")
compiler/circlechef/CMakeLists.txt:  message(STATUS "circlechef: SKIP (missing mio-circle04)")
compiler/circlechef/requires.cmake:require("mio-circle04")
compiler/circledump/README.md:- mio-circle04
compiler/circledump/requires.cmake:require("mio-circle04")
compiler/luci/requires.cmake:require("mio-circle04")
compiler/mio-circle04/CMakeLists.txt:  message(STATUS "mio-circle04 skip: FlatBuffers 2.0 NOT FOUND")
compiler/mio-circle04/CMakeLists.txt:message(STATUS "Build mio-circle04: TRUE")
compiler/mio-circle04/CMakeLists.txt:# This example shows how to use "mio-circle04" library
compiler/mio-circle04/README.md:# mio-circle04
compiler/mio-circle04/example.cpp:// This example shows how to include and use "mio-circle04"
compiler/pota-quantization-value-test/requires.cmake:require("mio-circle04")
compiler/tflite2circle/requires.cmake:require("mio-circle04")
docs/release/1.20/release-note-1.20.0.md:- Refactor to mio-tflite280, mio-circle04 with version and helpers methods
infra/debian/compiler/changelog:  * Refactor to mio-tflite280, mio-circle04 with version and helpers methods
infra/nncc/Makefile.arm32:ARM32_BUILD_ITEMS+=;safemain;mio-circle04;mio-tflite280
infra/nncc/Makefile.arm32:ARM32_HOST_ITEMS+=;safemain;mio-circle04;mio-tflite280
infra/packaging/preset/20220323:  REQUIRED_UNITS+=("mio-tflite280" "mio-circle04")
infra/packaging/preset/20220323_windows:  REQUIRED_UNITS+=("mio-tflite280" "mio-circle04")
infra/packaging/preset/20221125:  REQUIRED_UNITS+=("mio-tflite280" "mio-circle04")
infra/packaging/preset/20221125_windows:  REQUIRED_UNITS+=("mio-tflite280" "mio-circle04")
infra/scripts/compiler_modules.sh:DEBUG_BUILD_ITEMS+=";safemain;mio-circle04;mio-tflite280;dio-hdf5"
infra/scripts/docker_collect_nnpkg_resources.sh:REQUIRED_UNITS+=("mio-tflite280" "mio-circle04")
```

**Comment by seanshpark** [comment]
`mio-circle04` current `CMakeLists.txt`
```
# TODO use nnpackage
# set(SCHEMA_FILE "${NNAS_PROJECT_SOURCE_DIR}/nnpackage/schema/circle_schema.fbs")
set(SCHEMA_FILE "${NNAS_PROJECT_SOURCE_DIR}/res/CircleSchema/0.4/circle_schema.fbs")
```
I forgot to change back to use `"${NNAS_PROJECT_SOURCE_DIR}/nnpackage/schema/circle_schema.fbs`
We may apply this change when 0.5 is ready in `nnpackage` :)

**Comment by seanshpark** [comment]
> We may apply this change when 0.5 is ready in nnpackage :)

Ah, to be exact, 
1/ `mio-circle04` should use `CircleSchema/0.4/circle_schema.fbs`
2/ `mio-circle05` should first use `CircleSchema/0.5/circle_schema.fbs`
3/ revise others to use `mio-circle05`
4/ and then use in `nnpackage` after it is updated to `0.5`

**Comment by hseok-oh** [comment]
>Do I have to generate circle_schema_generated.h manually? Or is there a script for that purpose?

Runtime member will do this.

**Comment by jinevening** [comment]
For reference: https://github.com/Samsung/ONE/pull/8668 (bump up to 0.4)

**Comment by seanshpark** [comment]
@jinevening , not to break Debian package release as work may take several days,
- introduce `mio-circle05`
- revise Debian package list to INCLUDE `mio-circle05` (NOT replace), and list in `infra` folder
- revise all other modules to use `mio-circle05`
- revise Debian package to REMOVE `mio-circle04`
- change to use schema file from `nnpackage` folder when upgraded

NOTES
- we do not need to remove `mio-circle04` folder
- when something goes wrong, no need to panic, fixing it will do

**Comment by jinevening** [comment]
@seanshpark  I'll follow your guide. Thanks!

**Comment by jinevening** [comment]
@seanshpark It seems that schema upgrade to 0.5 is done (of course we may need to update some modules to support new Ops and dtype).

`mio-circle04` is not used anywhere. Should I remove it?

**Comment by seanshpark** [comment]
> mio-circle04 is not used anywhere. Should I remove it?

Not necessary :) we can leave it as is .

**Comment by jinevening** [comment]
Thanks. Let's close this issue :)
