### ISSUE TITLE
Compiler FE: Support GeLU operator

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#10692]
## What

Let's support GeLU operator

TODO
- [x] tflite2circle
- [x] tfldump
- [x] circledump
- [x] res recipes
- [x] tflchef
- [x] luci/lang
- [x] luci/import
- [x] luci/service
- [x] luci/partition
- [x] luci/logex
- [x] luci/export
- [x] luci/tests
- [x] luci-interpreter
- [x] circle2circle
- [x] quantizer (verifier, fake quantization, const input)
- [x] luci-value-test
- [x] one-cmds (fuse_gelu)

**Comment by seanshpark** [comment]
please apply `compiler/luci/tests/test.lst` too

**Comment by jinevening** [comment]
All done.
