### ISSUE TITLE
[onert] Let's introduce `train` backend

### ISSUE THREAD

**Issue by ragmani** [Samsung/ONE#10788]
## What

Let's introduce `train` backend.

## Why
`train` backend would be a start point to support training in onert.

## Tasks
- [x] Make memory planner selectable #10791
- [x] Introduce `train` backend #10790 #10789

Draft : #10776

**Comment by glistening** [comment]
@ragmani Thank you for shorter name. But let's use `training` as you first choose. `train` is already occupied by :train:, :train2:

**Comment by ragmani** [comment]
Done
