### ISSUE TITLE
Nominating Sanggyu Lee (@glistening) to become a ONE committer

### ISSUE THREAD

**Issue by glistening** [Samsung/ONE#10805]
I'd like to become a ONE committer because I have non-trivial patches on one runtime, circle schema, which can be viewed here:
https://github.com/Samsung/ONE/pulls?q=is%3Apr+is%3Aclosed+author%3Aglistening+onert

I'll only merge commits related to onert with one or more approvals.

Could you give an opinion? From https://github.com/Samsung/ONE/wiki/Assigned-people

@lemmaa  of ONE project
@chunseoklee  of ONE runtime
@Samsung/one_onert

**Comment by lemmaa** [comment]
Considering his contributions so far, I have no doubt that he will perform his role well enough as a committer. I am truly grateful for his service.

**Comment by jyoungyun** [comment]
All maintainers thumbed up to this issue. So @glistening can be one of the ONE committer.
Please give him an authority.

/cc @Samsung/nnfw_committers @lemmaa 

There are several PRs waiting for his approval. :)

**Comment by ragmani** [comment]
Agree

**Comment by lemmaa** [comment]
With support from members, @glistening will contribute as a committer of onert. Congratulation!!!

**Comment by glistening** [comment]
Thank you for thumbing up and agreement!
