### ISSUE TITLE
Compiler FE: Enable HardSwish Op

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#10930]
Lets' enable HARD_SWISH Op

- [x] tflchef
- [x] res/TensorFlowLiteRecipes
- [x] tfldump (nothing to do)
- [x] tflite2circle (nothing to do)
- [x] circledump (nothing to do)
- [x] luci.lang
- [x] luci.import
- [x] luci.export
- [x] luci.logex
- [x] luci.service
- [x] luci.partition
- [x] luci.tests
- [x] luci_interpreter
- [x] luci-value-test
- [x] circle-part-value-test (optional)

2'nd step with decomposition
- [x] luci.pass to decompose
- [x] circle2circle
- [x] circle2circle-dredd-recipe-test
- [x] luci-pass-value-test

Additional work
- [x] one-cmds

`luci.pass to decompose`
- to run this Op in TRIX, we need to decompose this to primitive ops like Mul, Add, Rel, Minumum.

**Comment by seanshpark** [comment]
tflite code has this comment in `tensorflow/lite/toco/graph_transformations/identify_hardswish.cc`
```
// This transformation rule tries to identify the HardSwish structure generated
// by tensorflow.
// The formula of hardswish is:
// f(x) = x * relu6((x+3))/6
//
// We look for the following tensorflow subgraph:
// x * tf.nn.relu6(x + np.float32(3)) * np.float32(1. / 6.)
```
- we can assume TF generates decomposed network and tflite converter converts to 1 HardSwish Op.

https://github.com/tensorflow/tensorflow/blob/f0b8b9a1457bcc8d83716b2034d3d6501693c7d0/tensorflow/compiler/mlir/lite/transforms/optimize_patterns.td#L276
- this shows there are 5 patterns if TF

**Comment by jinevening** [comment]
> to run this Op in TRIX, we need to decompose this to primitive ops like Mul, Add, Rel, Minumum.

If the transformation is only needed for TRIX, why don't we implement the decomposition pass in TRIX?

**Comment by seanshpark** [comment]
@shs-park , can you please check done items in this top message?

**Comment by shs-park** [comment]
@seanshpark, Sure =)

**Comment by shs-park** [comment]
Does it also make sense to implement decomposition in ONE and TRIX, both?

**Comment by seanshpark** [comment]
> Does it also make sense to implement decomposition in ONE and TRIX, both?

ONE-compiler and TRIX backends is independent so both having decomposition is logically OK but can be waste of resource.

What I think is that
- this task is good for you to study about ONE-compiler and also looks good material for wring new Pass
- decomposition in TRIX backend would also be a good material to study backend compiler
- I think this depends on your will :)

**Comment by seanshpark** [comment]
I've updated items in the first comment. I'm not sure `circle-part-value-test` is necessary or not. If possible can you review other tests and decide the test is necessary or optional?

**Comment by shs-park** [comment]
> * I think this depends on your will :)

Ok, I will try to implement the both sides, but I don't know how much time it would take, lol.
Please let me know anytime if it turns out to be ugent.

**Comment by seanshpark** [comment]
> but I don't know how much time it would take, lol.

As this request is from one of our customer, I would say it is OK with current progress in ONE.
When ONE-compiler is ready with decomposition, there is no urgency in backend.
Um... one thing in my mind is that backend maintainer may ask why decompose this when frontend already do so.... I've no strong will when this happens, but to say, a good study course item for backend development...

@lemmaa , any comments?

**Comment by shs-park** [comment]
> I've updated items in the first comment. I'm not sure `circle-part-value-test` is necessary or not. If possible can you review other tests and decide the test is necessary or optional?

I think it could be optional.

As I understand it, the test involves graph partitioning based on multiple backend system.
Some operations seem to be more effective when running on CPU instead of GPU.
ReLU series operations, such as ReLUx, Elu and GeLU, were not found in the test, and I suspect the HardSwish operation would be as well.

By the way, just for a test, I've added `HardSwish` operation into `Part_Split_Add_000` and the test passed.
Please refer to the below image.

![test-part](https://github.com/Samsung/ONE/assets/136296779/91094800-42b5-4b8e-8754-18ce0fea98ca)

**Comment by seanshpark** [comment]
> decompose HardSwish as an optional optimization pass.

As I understand this means not to include in `-O1` group.

**Comment by shs-park** [comment]
@seanshpark, 
Should I add the `decompose_hardswish` option to `OPTIMIZATION_OPTS` in `compiler/one-cmds/onelib/constant.py`?

**Comment by seanshpark** [comment]
> Should I add the decompose_hardswish option to OPTIMIZATION_OPTS in compiler/one-cmds/onelib/constant.py?

Yes in `OPTIMIZATION_OPTS `. But NOT in `O1` :)

**Comment by shs-park** [comment]
It looks like everything is done in the list now =)

**Comment by seanshpark** [comment]
closing as done

**Comment by shs-park** [comment]
FYI, at this time, I've decided not to implement the HardSwish decomposing pass in TRIX due to difficulties in implementing HardSwish quantization which must be performed before being passed to TRIX.
