### ISSUE TITLE
Compiler FE: Fuse Slice with TransposeConv

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#10960]
## What

Let's fuse slice Op with TransposeConv.

The below transformation is possible.

Before
```
TConv (padding: valid) -> Slice (Slice edges)
```

After
```
TConv (padding: same)
```

It is especially effective when batchnorm (channel wise MUL/ADD) appears after `TConv -> Slice` pattern, because batchnorm can be fused with the preceding TConv.

Useful link to understand padding of TConv: https://towardsdatascience.com/understand-transposed-convolutions-and-build-your-own-transposed-convolution-layer-from-scratch-4f5d97b2967

**Comment by stamalakhov** [comment]
@jinevening 
M.b. i can try to resolve this issue?

**Comment by jinevening** [comment]
Of course. Thank you :)

**Comment by jinevening** [comment]
Let's close this issue. Thanks @stamalakhov
