### ISSUE TITLE
[CFE] prepare_test_materials.sh failure

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#10966]
Error in prepare script
```
Traceback (most recent call last):
  File "preprocess_images.py", line 30, in <module>
    PIL.Image.ANTIALIAS)).astype(np.float32)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
Raw data have been packaged to inception_v3_test_data.h5
Number of packaged data: 0
```

got this error from today in internal release CI.

**Comment by seanshpark** [comment]
Local test
> preprocess_images.py:30: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  PIL.Image.ANTIALIAS)).astype(np.float32)

**Comment by seanshpark** [comment]
@jinevening , can you fix this problem? this failure prevents from daily release in internal CI.

**Comment by jinevening** [comment]
@seanshpark  I made a fix (#10967). It worked well in my local environment. I think it will resolve the issue in internal CI too.

**Comment by seanshpark** [comment]
Still `AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'` error

**Comment by seanshpark** [comment]
@hseok-oh , is `bin/venv` cached in CI ? my local has no problem with this but CI still has same problem.

**Comment by seanshpark** [comment]
check again with latest ONE release after 2023-07-04.

**Comment by hseok-oh** [comment]
>is `bin/venv` cached in CI ?

No. It run on new docker container every time, and it does not use `bin/venv` cache.

**Comment by seanshpark** [comment]
Internal CI is now OK with `one-compiler (1.24.0~23070418)`
