### ISSUE TITLE
[one-optimize] Support a new pattern in FuseGeluPass

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#11002]
## What

Let's add a new pattern in FuseGeluPass.

tflite file: [GELU.zip](https://github.com/Samsung/ONE/files/11962886/GELU.zip)

## Why

Currently FuseGeluPass can handle a pattern generated when Gelu is imported from onnx model.

Old TF generates a different pattern to perform Gelu. Let's support it.

**Comment by seanshpark** [comment]
![image](https://github.com/Samsung/ONE/assets/4616940/232b6f7e-50b0-44f9-9340-374735c2f73a)

Ops
```
[0] MUL (code: 18, dep_code: 18, version: 1)
[1] CUSTOM(Erf) (code: 32, dep_code: 32, version: 1)
[2] ADD (code: 0, dep_code: 0, version: 1)
```

**Comment by seanshpark** [comment]
If anyone interested doing this, please take it by self assign :)
If not taken in a time, I'll do it :)

**Comment by seanshpark** [comment]
From the class `GeluPattern` ... what I can think of 
1/ Add another class `GeluPattern2` to match pattern of this issue
2/ Add `GeluPattern::matched2()` to match pattern of this issue
3/ Inside `GeluPattern::matched()`, call internal `match_type1()`, `match_type2()` ...
4/ ...

**Comment by seanshpark** [comment]
@BalyshevArtem , thanks for taking this issue!

@jinevening , I've found that we don't have luci-pass-value test for fuse GELU. was there any issue when you added the pass ?

**Comment by jinevening** [comment]
There is an issue. Erf Op (included in Gelu pattern) cannot be executed on the current venv (w/ TF 2.8.0).

**Comment by seanshpark** [comment]
As we cannot run value test, let's check if we can do some `circle2circle-dredd-recipe-test`

**Comment by seanshpark** [comment]
done
