### ISSUE TITLE
[CFE/circle-quantizer] Add weight quantize option

### ISSUE THREAD

**Issue by glistening** [Samsung/ONE#11057]
### What?

Adds weight-only quantization.
(q8 weight, f32 for activation, bias for some ops e.g. CONV, DCONV, ...)

### Why?

This option will generate hybrid model which can be used in `onert`.

### To Do

- Implementation will be almost same to quantize-dequantize-weights.
- Test will be added in `pota-quantization-test`.

cc @jinevening, @hseok-oh

**Comment by glistening** [comment]
### Break down
- [ ] Add quantize-weights option
- [ ] Add implementation
- [ ] Add test in pota-quantization-test

**Comment by glistening** [comment]
### More to do

- [ ] Determine quantization type based on `onert`.
- [ ] Update `circle-quantizer` README.md
- [ ] Update `onecc quantize` manual

https://github.com/Samsung/ONE/issues/11047#issuecomment-1639206478

**Comment by glistening** [comment]
@jinevening 

I've almost done in implementation. Now, I am going to prepare value tests. 
Here are my understanding after reading `pota-quantization-value-test/README.md`.

1. Test Process
Most steps (Fake quantize, Recording minmax, ...) are not required for weights quantization.

2. Golden data 
There is no `GenGoldenWeightsSym.py` or something.
They existed in https://github.com/Samsung/ONE/pull/3501, but I guess it is changed during review or as time goes.

3. No `int8` support
There is no support for `int8` for `dalgona` and several tools. It is natural. : )

--------

Thus, I would like to

- Generate golden weights using tensorflow lite converter.
  - `int8` weights quantization is exactly same to tflite quantization spec.
  - Only `int8` will be available. There are no such thing of `int16` hybrid in tflite.
- Dump the tflite's weights values in json
- Put the json under `expected_outputs/<model_name>/\<granularity\>/<quantized_type>/weights_quantization/<tensor_name>.json`
- Compare json (written as test_wquant.sh)

Please give your opinion.

**Comment by jinevening** [comment]
Looks reasonable to me.

**Comment by glistening** [comment]
Now, all implementation is done. Test will be covered in #11122. Let's update documentation if necessary.
