### ISSUE TITLE
[circle-mpqsolver] Implement onecc integration

### ISSUE THREAD

**Issue by stamalakhov** [Samsung/ONE#11146]
### What

Implement integration of `circle-mpqsolver` with `onecc`

### Why

Because users of `circle-mpqsolver` need to run it using `onecc`.

**Comment by stamalakhov** [comment]
@jinevening 
For a user of onecc is it supposed to be a subsection in `one-quantize` section?
Or it should be separate section of `onecc` configuration?
if it would be a separate section how about `one-mpqsolve` name for it?

**Comment by jinevening** [comment]
I think It would be better to make ampq feature as an option of `one-quantize`. If we make a separate section`one-mpqsolve`, the output would be the quantized circle, which is the same with `one-quantize`. It would be desirable to keep the same interface to generate the quantized circle.

Many options in circle-mpqsolver are compatible with existing options in one-quantize.

circle-mpqsolver options
```
-h, --help              Show help message and exit
--version               Show version information and exit
-V, --verbose           output additional information to stdout or stderr
--data                  Path to the test data
--data_format           Test data format (default: h5)
--qerror_ratio          quantization error ratio ([0, 1])
--bisection             Single optional argument for bisection method. Whether input
                         node should be quantized to Q16: 'auto', 'true', 'false'.
--input_model           Input float model with min max initialized
--input_dtype           Data type of quantized model's inputs (default: uint8)
--output_dtype          Data type of quantized model's outputs (default: uint8)
--output_model          Output quantized model
--visq_file             *.visq.json file with quantization errors
--save_intermediate     path to save intermediate results
```

So for example,

```ini
[one-quantize]
input_path=fp32 (min/max recorded model may be generated internally)
output_path=shared
input_data=shared
input_data_format=shared
input_type=shared
output_type=shared
save_intermediate=shared
...
ampq=True
ampq_qerror_ratio=
ampq_algorithm=bisection_auto
ampq_bisection_visq=(required for bisection_auto)
...
```

`ampq_` prefix can be used to designate ampq options. If you have another idea, please suggest :)

**Comment by stamalakhov** [comment]
> I think It would be better to make ampq feature as an option of `one-quantize`. If we make a separate section`one-mpqsolve`, the output would be the quantized circle, which is the same with `one-quantize`. It would be desirable to keep the same interface to generate the quantized circle.

Ok. I see. Thank you.

**Comment by stamalakhov** [comment]
Locally tested that `master` branch it's possible now to run one-cc configuration files with `ampq` option enabled.
