### ISSUE TITLE
[CFE] Upgrade TensorFlow to 2.12.x

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#11255]
Let's upgrade TensorFlow to 2.12.1
(Latest is 2.13.0 as of adding this issue)

To do
- [x] Test common-artifacts with TF 2.12.1 (test run on Docker)
   - [x] U18.04
   - [x] U20.04
   - [x] U22.04
- [x] Test one-cmds with TF 2.12.1 (test run on VM, installed + update)
   - [x] U18.04
   - [x] U20.04
   - [x] U22.04
- [x] Update codes
   - [x] add venv-2.12.1 in common-artifacts
   - [ ] revise tests to use venv-2.12.1
   - [x] remove venv-2.8.0
   - [x] remove jammy venv-2.10.1
   - [x] update one-cmds to use 2.12.1

Upgrading source to use TF2.12.1 can be done in next step
- current value test is OK with luci-interpreter

**Comment by seanshpark** [comment]
Check version status for Ubuntu 18.04:
- TBA

**Comment by seanshpark** [comment]
U20.04 Testing

```
VER_TENSORFLOW=2.12.1
VER_ONNX=1.14.0
VER_ONNXRUNTIME=1.15.0
VER_ONNX_TF=1.10.0
VER_PYDOT=1.4.2
...
${VENV_PYTHON} -m pip ${PIP_OPTIONS} install Pillow
${VENV_PYTHON} -m pip ${PIP_OPTIONS} install tensorflow_probability==0.16.0
${VENV_PYTHON} -m pip ${PIP_OPTIONS} install tensorflow_addons==0.20.0
...

--> failed in `prepare_test_materials.sh`
> Archive:  reshape_matmul.zip
  inflating: reshape_matmul.onnx
...
> one-import-onnx: StagingError: in user code:
> IndexError: tuple index out of range


and failed in `one-build` testing
> one-build: AttributeError: module 'importlib' has no attribute 'machinery'

**Comment by seanshpark** [comment]
@mhs4670go , do you know to fix `module 'importlib' has no attribute 'machinery'` error?

**Comment by mhs4670go** [comment]
> @mhs4670go , do you know to fix `module 'importlib' has no attribute 'machinery'` error?

I'm not sure why this happened suddenly but adding below line into `compiler/one-cmds/onelib/utils.py` resolves this problem.

```python
import importlib.machinery
```

**Comment by seanshpark** [comment]
also need this too
```py
import importlib.util
```

**Comment by seanshpark** [comment]
> IndexError: tuple index out of range

-->

**Comment by seanshpark** [comment]
Test result: 3 fails
```
one-import_neg_001.test FAILED
one-partition_neg_001.test FAILED
one-partition_001.test FAILED
```

**Comment by seanshpark** [comment]
> one-import_neg_001.test FAILED
-->
> 2023-08-16 19:27:52.106565: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
Ignore 'tcmalloc: large alloc' warnings.
To enable the following instructions: AVX2, in other operations, rebuild TensorFlow with the appropriate compiler flags.
tf2tfliteV2.py: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 32: invalid start byte

> one-partition_neg_001.test FAILED
--> failed downloading `https://github.com/Samsung/ONE/files/8608844/Net_InstanceNorm_003.zip`

with valid files
> one-partition_001.test SUCCESS
one-partition_neg_001.test SUCCESS

**Comment by seanshpark** [comment]
> one-partition_neg_001.test FAILED

--> failed downloading `https://github.com/Samsung/ONE/files/8608844/Net_InstanceNorm_003.zip`

with valid files
> one-partition_001.test SUCCESS
one-partition_neg_001.test SUCCESS

**Comment by seanshpark** [comment]
### Investigate why `module 'importlib' has no attribute 'machinery'` happens

TBA

**Comment by seanshpark** [comment]
As we will have new `one-prepare-venv` with higher version but freeze for U18.04,
I'll freeze existing `one-prepare-venv` to `one-prepare-venv.u1804`.

**Comment by seanshpark** [comment]
`one-import-onnx` needs revision
```
WARNING:absl:`0001_input` is not a valid tf.function parameter name. Sanitizing to `arg_0001_input`.
WARNING:absl:`0002_s0` is not a valid tf.function parameter name. Sanitizing to `arg_0002_s0`.
WARNING:absl:`0003_s1` is not a valid tf.function parameter name. Sanitizing to `arg_0003_s1`.
one-import-onnx: StagingError: in user code:


    IndexError: tuple index out of range
```

**Comment by seanshpark** [comment]
U22.04 one-cmds test

> one-quantize_016.test FAILED
> onecc_045.test

**Comment by seanshpark** [comment]
U1804
```
107/117 Test #107: luci_value_test ............................***Failed  130.85 sec
FAILED
- Conv2D_U8_000
```

**Comment by seanshpark** [comment]
As U20.04 and U22.04 both can use `python3` we can use `one-prepare-venv` for U20.04 and U22.04
and revise U18.04 to use `python3.8` as in `one-prepare-venv.u1804`

**Comment by seanshpark** [comment]
Test results with AArch64/Ubuntu22.04 on RPi4

Unit test OK
```
...
115/116 Test #115: visq_unittest ..............................   Passed    0.87 sec
        Start 116: luci_pass_value_test
116/116 Test #116: luci_pass_value_test .......................   Passed  287.64 sec

100% tests passed, 0 tests failed out of 116
```

Installation test TBA

**Comment by seanshpark** [comment]
done for now
