### ISSUE TITLE
Compiler FE: Enable space_to_depth Operator

### ISSUE THREAD

**Issue by ko-dimi** [Samsung/ONE#1126]
- [x]  res/TensorFlowPythonExamples (#1297)
- [x]  res/TensorFlowLiteRecipes (#1333)
- [x]  tflchef (#1299)
- [x]  tfldump (#1301 )
- [x]  circledump (#1302)
- [x]  luci.IR (#1298 )
- [x]  luci.Import (#1395)
- [x]  luci.Export (#1396)
- [x]  luci.logex (#1397)
- [x]  luci.Service (#1400)
- [x]  tflite2circle (#1300)
- [x]  luci.tests (#1434)

for #873
on behalf of a-kvochko

**Comment by kvochko** [comment]
All done
