### ISSUE TITLE
[luci/pass] Missing add_origin in ReplaceSubWithAddPass.cpp

### ISSUE THREAD

**Issue by shs-park** [Samsung/ONE#11265]
In [ReplaceSubWithAddPass.cpp](https://github.com/Samsung/ONE/blob/cf3837f4feb295a472505b01450019f8a8c8164a/compiler/luci/pass/src/ReplaceSubWithAddPass.cpp) file,
I can't find the `add_origin` setting, maybe it is missing?

**Comment by seanshpark** [comment]
> I can't find the add_origin setting, maybe it is missing?

Yup :)
Please fire a PR for this :)

**Comment by shs-park** [comment]
applied and close!
