### ISSUE TITLE
[one-quantize] Support name aliasing in quantization configuration file

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#11280]
## What

Let's support aliasing of layer names (ex: "alternate" or other name) in quantization config file.

## Why

@seanshpark 's comment

We have a plan to migrate to onnx2circle tool someday and this tool will have different naming rule.
IMHO, if we can provide multiple names for a node, we can have some room (but complicated) for smooth migration and less confusion.

So, current is like, for example

"names": [ "a", "b", "c" ],
if we can provide alternative names for the node, like, "a" can be "a1" or "a2",

"names": ["a", "b", "c" ],
"alternate": {
  "a" : ["a1", "a2"],
  "b" : ["b1", "b2"],
}
if a node with name "a" is not found then search in alternate
if a node is not found in also in alternate its invalid and stop the tool.

**Comment by seanshpark** [comment]
@jinevening , if it's OK, I'll work on this.

**Comment by seanshpark** [comment]
Prepare test materials
- use `onnx_conv2d_conv2d.onnx` model in `one-cmds`
- prepare two venv with TF2.8.0 and TF2.12.1
- ...

**Comment by seanshpark** [comment]
Test qconfig.json file for `T(0:12)`
```json
{
  "default_quantization_dtype" : "uint8",
  "default_granularity" : "layer",
  "layers" : [
    {
      "names" : [
        "onnx_tf_prefix_Relu_3;Add_1;convolution_1;Const_3"
      ],
      "alternate": [
        {
          "onnx_tf_prefix_Relu_3;Add_1;convolution_1;Const_3":
            [
              "onnx_tf_prefix_Relu_3;Add_1;convolution_1;Const"
            ]
        }
      ],
      "dtype" : "int16",
      "granularity" : "channel"
    }
  ]
}
```

**Comment by seanshpark** [comment]
First approach experiment:
```diff
     struct LayerParam
     {
       std::string name;
       std::string dtype;
       std::string granularity;
+      std::vector<std::string> altnames;
     };
```

**Comment by seanshpark** [comment]
Work items
- How to test this in CI ?
- ...

**Comment by jinevening** [comment]
We may need to determine how to handle the case that there is an existing tensor with the altname. Maybe throw an exception?

**Comment by seanshpark** [comment]
For multiple output testing, let's add Split Op.

**Comment by seanshpark** [comment]
> We may need to determine how to handle the case that there is an existing tensor with the altname. 

Such as this?
- TF2.8.0 produces "convolution_1;Const_1" and "convolution_2;Const_2"
- TF2.12.1 produces "convolution_1;Const_2" and "convolution_2;Const_3" 

Such that, something like this?
```json
      "names" : [
        "convolution_1;Const_1",
        "convolution_2;Const_2"
      ],
      "alternate": [
        {
          "convolution_1;Const_1": [ "convolution_1;Const_2" ],
          "convolution_1;Const_2": [ "convolution_1;Const_3" ]
        }
      ],
```

**Comment by jinevening** [comment]
If the above config is given for TF2.12.1, "convolution_2;Const_2" will be selected (it's in "names"), but "convolution_3;Const_3" may not be selected ("convolution_2;Const_2" is already selected, so "alternate" may be ignored).

---

Another negative example is that matching with multiple altnames. For example, let's assume a model has tensors named `b` and `c`. 

```json
      "names" : [
        "a"
      ],
      "alternate": [
        {
          "a": [ "b", "c" ]
        }
      ],
```

For the above config, "a" is not matched, so quantizer will see "alternate", and there are two matching tensors. We may need to properly handle such a case.

**Comment by seanshpark** [comment]
Nodes from TF2.8.0
```
O(0:2) CONV_2D 
    O T(0:8) onnx_tf_prefix_/relu1/Relu;Add;convolution;Const_1
O(0:4) CONV_2D 
    O T(0:13) onnx_tf_prefix_/relu2/Relu;Add_1;convolution_1;Const_3
O(0:5) SPLIT 
    O T(0:15) PartitionedCall:0_out_0
    O T(0:14) PartitionedCall:0_out_1
```

**Comment by seanshpark** [comment]
Problematic cases

onnx->circle: Tool1, Tool2, Tool3T

1/ where Tool1 and Tool2 produce same `T2` to different tensor
- Tool1: `T1`, `T2`
- Tool2: `T2`, `T3`
- map
   - `T1`: `T2`
   - `T2`: `T3`

2/ where 
- Tool1: `T1`, `T2`
- Tool2: `T3`, `T4`
- Tool3: `T4`, `T5`
- map
   - `T1`: `T3`, `T4`
   - `T2`: `T4`, `T4`

**Comment by seanshpark** [comment]
How to map?
- TBD

**Comment by seanshpark** [comment]
Another format
```json
{
  "default_quantization_dtype" : "uint8",
  "default_granularity" : "layer",
  "layers" : [
    {
      "names" : [
        "onnx_tf_prefix_/relu2/Relu;Add_1;convolution_1;Const_3",
      ],
      "alternate": [
        "tf2121": [
          "onnx_tf_prefix_/relu1/Relu;Add;convolution;Const_2"
        ],
        "o2c": [
          "onnx_tf_prefix_/relu1/Relu;Add;convolution;Const_1"
        ],
      ],
      "dtype" : "int16",
      "granularity" : "channel"
    }
  ]
}
```

**Comment by seanshpark** [comment]
How to store `alternate` data? ...

**Comment by seanshpark** [comment]
## Use new TYPE for `std::vector<std::shared_ptr<LayerParam>>`

Consideration:
- `compiler/circle-mpqsolver/src/core/Dumper.h` and `compiler/circle-mpqsolver/src/core/Quantizer.h` has
```cxx
namespace mpqsolver
{
namespace core
{
using LayerParam = luci::CircleQuantizer::Options::LayerParam;
using LayerParams = std::vector<std::shared_ptr<LayerParam>>;
```

New TYPE name?

**Comment by seanshpark** [comment]
done for now.
