### ISSUE TITLE
[CFE] TensorFlow 2.12.1 schema.fbs changes

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#11377]
Recent upgrade to TensorFlow 2.12.x has changes in schema.fbs and we need to solve related issues.

TF 2.12.1 hash 8e2b6655c0c488290179ab90a0daed0f6d3006f7

**Comment by seanshpark** [comment]
critical changes from 3 to 4

```diff
@@ -875,9 +923,13 @@
 }

 table TransposeConvOptions {
+  // Parameters supported by version 1, 2, 3:
   padding:Padding;
   stride_w:int;
   stride_h:int;
+
+  // Parameters supported by version 4:
+  fused_activation_function:ActivationFunctionType = NONE;
 }

 table ExpandDimsOptions {
```

**Comment by seanshpark** [comment]
Upgrading schema will take time but we have a release schedule ahead...
Can we support only this activation in `TransposeConv` ?
- we have only a day or two...
- look into `tflite2circle` and check...

**Comment by seanshpark** [comment]
Can we split fused TransposeConv+Relu to TransposeConv with ReLU?
- Need to add ReLUOp code to OpCode list if existing model doesn't have RELU --> maybe possible
- Need to add Tensor for output of ReLU and remap USER Op to that Tensor ... --> no framework for this support in `tflite2circle`

**Comment by seanshpark** [comment]
> I've heard that we can skip release this time. Could you share the release schedule so that I can help?

I haven't heard directly with release date but will be soon in a few days.
I looked into the `tflite2circle` codes if decomposition can be possible for `TransposeConv` but seems technically impossible. 

Currently I am thinking of adding new `mio-tflite2121` in regular way.

> I think we may extend circle node (CircleTransposeConv) too, which would affect O1 option (--fuse_activation_function). Or maybe we can update circle node later to avoid side effect this time.

Yes, until backend supports fused `CircleTransposeConv` with activation, it would be better not to support fused activation in `CircleTransposeConv` as temporary and then remove this later when things are ready in backend.

**Comment by hseok-oh** [comment]
We need circle schema version up to 0.6 to sync with TFLite 2.12.1 (or upper)

**Comment by glistening** [comment]
I don't understand why we need to update tflite schema and circle schema at this moment in hurry. Is there any model we need to support?

**Comment by seanshpark** [comment]
> ... at this moment in hurry

This change is not in a hurry. I expect this task may take several weeks.

> Is there any model to support, which requires recent schema

With current one-cmds tools running on TF2.12.1, one of our internal customer model fails cause of
activation field added to TransposeConv Op.

Upgrading circle schema will be done independently without runtime part.

**Comment by glistening** [comment]
Thank you for explanation. My understanding is:
- It is not supposed to be done in a few days, and 
- Applying new schema for runtime is not required.

**Comment by seanshpark** [comment]
This issue can be closed as child tasks are registered.
