### ISSUE TITLE
[circle-mpqsolver] Provide more unit tests

### ISSUE THREAD

**Issue by stamalakhov** [Samsung/ONE#11374]
### What

Let's introduce more unit-tests for 'circle-mpqsolver`.

### Why
We need to provide greater level of code coverage by unit-tests.

**Comment by stamalakhov** [comment]
@jinevening 
Do we need more tests for `circle-mpqsolver`?

**Comment by jinevening** [comment]
Recent result from http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-compiler-coverage/693/cobertura/

![image](https://github.com/Samsung/ONE/assets/5449554/ab076eea-96d3-4a19-973d-361b13ff7007)

Things got better than https://github.com/Samsung/ONE/pull/11452#issuecomment-1754262236. I think you can close this issue. Thanks!
