### ISSUE TITLE
Bump up circle schema version up to 0.6

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#11381]
We need circle schema version up to 0.6 to sync with TFLite 2.12.1 (or upper)

_Originally posted by @hseok-oh in https://github.com/Samsung/ONE/issues/11377#issuecomment-1698385140_
            
---

Previous bump up issue: #10629

**Comment by hseok-oh** [comment]
Refer https://github.com/Samsung/ONE/issues/10629#issuecomment-1506427407

- Common (nnpackage definition): `nnpackage/schema/circle_schema.fbs`
  - Not used for build and test 
- Runtime: `runtime/onert/frontend/circle_schema/include/circle_schema_generated.h`
- Compiler: `res/CircleSchema/<version>/circle_schema.fbs`

**Comment by hseok-oh** [comment]
The latest TensorFlow release version is 2.13.0. We can sync with this version IMO.

**Comment by hseok-oh** [comment]
I'll check runtime issue. Maybe there is no issue.

**Comment by hseok-oh** [comment]
No issue found on runtime.

**Comment by seanshpark** [comment]
compiler also with no issue as of now.

**Comment by hseok-oh** [comment]
Done
