### ISSUE TITLE
[onert/api] typos and incorrect params in doxygen documentation

### ISSUE THREAD

**Issue by jaemaning** [Samsung/ONE#11404]
i have a (dumb) question,

I saw a typos and incorrect parameters in the comment. When I was working on creating the `Doxyfile` of  `nnfw.h`

I was able to correct some typos, but I wasn't sure if I corrected the wrong parameters correctly, so I asked this question.

I would be grateful if you could judge by looking at the error below and the solution to the problem I fixed.

`ONE/runtime/onert/api/include/nnfw.h:312: warning: unable to resolve link to 'nnfw_run_asnyc' for \link command`
**typo issue : asnyc -> async**

`ONE/runtime/onert/api/include/nnfw.h:269: warning: unable to resolve link to 'nnfw_apply_tensor' for \link command`
**parameter name issue: cannot found "nnfw_apply_tensor", : "nnfw_apply_tensor" -> "nnfw_apply_tensorinfo"**

```
ONE/runtime/onert/api/include/nnfw.h:494: warning: argument 'information' of command @param is not found in the argument list of nnfw_query_info_u32(nnfw_session *session, NNFW_INFO_ID id, uint32_t *val)
ONE/runtime/onert/api/include/nnfw.h:494: warning: The following parameter of nnfw_query_info_u32(nnfw_session *session, NNFW_INFO_ID id, uint32_t *val) is not documented:
parameter 'id'
```
**parameter name issue: `@param[in] information ID to be queried` ->  `@param[in] id ID to be queried`**

```
/**
 * @brief     Retrieve uint32 type of nnfw information for given information ID.
 *
 * <p>Retrieves the information of property given by information id </p>
 *
 * @note: The input session could be null for global information (e.g. runtime version).
 *
 * @param[in] session session to be queried on.
 * @param[in] id ID to be queried
 * @param[out] val uint32 value to be returned.
 *
 * @return @c NNFW_STATUS_NO_ERROR if successful
 */

```

```
ONE/runtime/onert/api/include/nnfw.h:246: warning: unable to resolve link to 'nnfw_model_load_from_file' for \link command
ONE/runtime/onert/api/include/nnfw.h:250: warning: unable to resolve link to 'nnfw_model_load_from_file' for \link command
```
**typo issue : "nnfw_model_load_from_file" -> "nnfw_load_model_from_file"**

**Comment by hseok-oh** [comment]
>I was able to correct some typos, but I wasn't sure if I corrected the wrong parameters correctly, so I asked this question.

As you listed, those are all typo. Thank you find typos. 
Please make PR to fix these typos.

**Comment by ragmani** [comment]
@jaemaning 
You can close this issue if this issue has been resolved.
