### ISSUE TITLE
[onert] Build Error on Docker(nfw/one-devtools:focal) 

### ISSUE THREAD

**Issue by jeonghwanin** [Samsung/ONE#11405]
I attempted to build using the "docker run -it --rm -u root -v `pwd`:`pwd` -w `pwd` -e BUILD_TYPE=release nnfw/one-devtools:focal make -f Makefile.template all install" command.

I encountered the Following Error Message
<img width="556" alt="Build Error" src="https://github.com/Samsung/ONE/assets/99806622/1e88003d-984c-435d-be45-4fe0df86dc17">

There is not overlay directory.

<img width="340" alt="Nofile" src="https://github.com/Samsung/ONE/assets/99806622/7d1dc096-c270-4768-9cfc-74f3384335e5">

**Comment by hseok-oh** [comment]
That is intended message. 
`Makefile` always try to copy `libarm_compute*.so` files, but that is not generated and used for `x86_64` target.

**Comment by hseok-oh** [comment]
I'll update makefile to now show intended cp fail message.

**Comment by jeonghwanin** [comment]
Thank you !
I thought there was a build error.

**Comment by ragmani** [comment]
@jeonghwanin 
You can close this issue if this issue has been resolved.
