### ISSUE TITLE
[onert] Introduce MaxPool op for training

### ISSUE THREAD

**Issue by glistening** [Samsung/ONE#11427]
`onert` started to support training. It only covers a limited of operators at this moment.
Someone may start to support other ops by referring existing other training op implementation.

Related: #11389

**Comment by zetwhite** [comment]
I was looking into it. 
Is it okay to assign myself?

**Comment by zetwhite** [comment]
I think someone might wonder about the progress of this issue. 
So, Here is a note to share the progress.

-----------------------------------------------

I made a draft here with some uniitests here https://github.com/Samsung/ONE/pull/11480.
But I didn't check the integrated one(full pass test) which starts with `*.circle` file, yet. 

But as you might know, We have another work in office for two weeks. :cry: 
So, This work will be suspended for a while. I'll try to finish this one as soon as possible.

**Comment by zetwhite** [comment]
* (progress updated) 

https://github.com/Samsung/ONE/pull/11480(Draft) is ready.
It works well with under model and the training data.


[pool_mnist_model.zip](https://github.com/Samsung/ONE/files/12809198/pool_mnist_model.zip)

**Comment by zetwhite** [comment]
(progress updated) 

https://github.com/Samsung/ONE/pull/11480(Draft) is ready. It works well with under model and the training data.
So, I will make PRs from the draft from now on. 

* model and data : [pool_mnist_model.zip](https://github.com/Samsung/ONE/files/12809198/pool_mnist_model.zip)

```bash
➜ ~/Workspace/ONE/Product/out/bin/onert_train --modelfile pool_mnist_model/pool_model.circle --load_input:raw pool_mnist_model/mnist_x_train.1000.bin --load_expected:raw pool_mnist_model/mnist_y_train.1000.bin --data_length 1000 -v 100 --learning_rate 0.01 --epoch 10  
Model Expected Filename pool_mnist_model/mnist_y_train.1000.bin
Model Input Filename pool_mnist_model/mnist_x_train.1000.bin
Model Filename pool_mnist_model/pool_model.circle
Epoch 1/10 - 55.257ms/step - loss: [0] 13.8349
Epoch 2/10 - 55.186ms/step - loss: [0] 1.9618
Epoch 3/10 - 55.166ms/step - loss: [0] 0.8555
Epoch 4/10 - 55.243ms/step - loss: [0] 0.5257
Epoch 5/10 - 55.164ms/step - loss: [0] 0.3861
Epoch 6/10 - 55.200ms/step - loss: [0] 0.3138
Epoch 7/10 - 55.254ms/step - loss: [0] 0.2704
Epoch 8/10 - 55.807ms/step - loss: [0] 0.2402
Epoch 9/10 - 55.252ms/step - loss: [0] 0.2183
Epoch 10/10 - 55.230ms/step - loss: [0] 0.2015
===================================
MODEL_LOAD   takes 1.565 ms
PREPARE      takes 8.809 ms
EXECUTE      takes 17146.654 ms
- MEAN     :  17146.654 ms
- MAX      :  17146.654 ms
- MIN      :  17146.654 ms
- GEOMEAN  :  17146.654 ms
===================================
```

**Comment by zetwhite** [comment]
PR plan : 

- [ ] Introduce MaxPool c-kernels for training 
   - This PR only includes ckernel and related tests.
   - https://github.com/Samsung/ONE/pull/11666 
- [ ] Introude MaxPoolLayer for training 
   - This PR might include all remaining things in the draft 
   - WIP

**Comment by zetwhite** [comment]
https://github.com/Samsung/ONE/pull/11686 merged. 
So close this one.
