### ISSUE TITLE
[onert] cross-build runtime for aarch64 default option

### ISSUE THREAD

**Issue by phj799** [Samsung/ONE#11486]
[docs/howto/how-to-cross-build-runtime-for-aarch64.md](https://github.com/Samsung/ONE/blob/master/docs/howto/how-to-cross-build-runtime-for-aarch64.md)

I had a question while performing cross compile referring to the howto docs.
```
# tools/cross/install_rootfs.sh

...
usage()
{
    ...
    echo "LinuxCodeName - optional, Code name for Linux, can be: bionic, focal(default), jammy"
    ...
}
...
```

The shell script is written as follows:
bionics, focal (default), jammy

However, in the howto docs it is written as follows:
![image](https://github.com/Samsung/ONE/assets/100912732/f1b1f86c-3397-4934-8dd4-cb2eec9ab5dd)

The defaults are different, which one is correct?

I checked it using the method below, but I am not sure.
```
ubuntu@ubuntu:~/ONE/tools/cross/rootfs/aarch64$ cat ./etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
```

**Comment by glistening** [comment]
I guess document is likely not to be updated.
3 weeks ago, @hseok-oh updated the default in https://github.com/Samsung/ONE/pull/11261 for arm, but he did not update aarch64. There may be some reason.

**Comment by phj799** [comment]
I will refer to the arm document. Thank you.😁
