### ISSUE TITLE
Nominating Balyshev Artem (@BalyshevArtem) to become a ONE committer

### ISSUE THREAD

**Issue by BalyshevArtem** [Samsung/ONE#11531]
I'd like to become a ONE committer because I have non-trivial patches on onert-micro, luci-interpreter, which can be viewed here:
https://github.com/Samsung/ONE/pulls?q=is%3Apr+author%3ABalyshevArtem+is%3Aclosed

I'll only merge commits related to onert-micro with one or more approvals.

Could you give an opinion? From https://github.com/Samsung/ONE/wiki/Assigned-people

@lemmaa of ONE project
@chunseoklee of ONE runtime
https://github.com/orgs/Samsung/teams/ONE

**Comment by lemmaa** [comment]
@BalyshevArtem , thank you for your active participation. It would be a great addition to our community. :)

**Comment by jinevening** [comment]
I agree. 👍

**Comment by hseok-oh** [comment]
I agree.

**Comment by lemmaa** [comment]
Thanks to the support of members who give their 👍 , and in explicit statements of agreement, now @BalyshevArtem will contribute as a committer for ONE project. 

CONGRATULATIONS!!! 🎉🎉🎉

**Comment by BalyshevArtem** [comment]
Thank you all very much for your trust and agreement! Then close this issue
