### ISSUE TITLE
[circle-mpqsolver] Introduce pattern-based solver

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#11543]
## What

Let's introduce pattern-based solver.

## Why

We can use pre-defined patterns to improve accuracy of some operators (ex: Softmax, LayerNorm).

**Comment by stamalakhov** [comment]
@jinevening 
May be i could try to resolve this one?

**Comment by jinevening** [comment]
Of course :)

**Comment by stamalakhov** [comment]
Do you mean to attach some (e.g. `.json`) file with restrictions on node `quantization` type depending on nodes type (like Softmax..) and/or depending on their name (`frozen` nodes)? or am i missing something?

**Comment by jinevening** [comment]
The interface is not fixed. We may need to discuss that too. I'm thinking that this feature should not require users to write node names. It will automatically find target nodes based on some patterns.

One possible scenario is to introduce a new solver, e.g., PatternSolver.

```ini
[one-quantize]
input_path=model.circle
quantized_dtype=uint8
granualrity=channel
ampq=True
ampq_algorithm=pattern
mixed_layernorm=True
mixed_softmax=True
output_path=model.q.circle
```

---
For now, we have two target patterns (softmax and layernorm). But softmax pattern is not fixed, so it will be better to start with layernorm pattern.

Target pattern
- Mul-Rsqrt chain (Mul, Mean, Add, Rsqrt) -> int16
- The rest (Mean, Sub, Mul, Add) -> uint8

![image](https://github.com/Samsung/ONE/assets/5449554/0e9e90c7-f593-4108-a1da-4b4786b1e249)

**Comment by jinevening** [comment]
Here is fp32 circle model for the layernorm pattern.

[layernorm.zip](https://github.com/Samsung/ONE/files/12645758/layernorm.zip)

**Comment by stamalakhov** [comment]
> For now, we have two target patterns (softmax and layernorm). But softmax pattern is not fixed, so it will be better to start with layernorm pattern.
> 
> Target pattern
> 
>     * Mul-Rsqrt chain (Mul, Mean, Add, Rsqrt) -> int16
> 
>     * The rest (Mean, Sub, Mul, Add) -> uint8

Ahhh. Understood. Ok. Thank you.

**Comment by stamalakhov** [comment]
@jinevening 
In case we have some `circle-model` consisting of some nodes, and not all of them belong to some predefined pattern, in that case we are supposed to quantize them to default "uint8", or to reach required `accuracy` we're supposed to use e.g. `bisection` to choose quantization parameters for them?

**Comment by stamalakhov** [comment]
@jinevening 
is it important to find exactly `layernorm` pattern?  I mean model from https://github.com/Samsung/ONE/issues/11543#issuecomment-1722941372 seems to be one possible implementations across many others:

- It doesn't have `gamma` multiplier (which can be just a fusion of unit `gamma` multiplier)
- normalization can be done across more that one last/`not last` axes

 Seems like many patterns can be generated for `layernorm` operation. 

May be it would be better to search only for `Mul-Rsqrt chain (Mul, Mean, Add, Rsqrt)` and freeze its quantization to "int16"?
Or model from https://github.com/Samsung/ONE/issues/11543#issuecomment-1722941372 will be the only one supported?
Or do we need to support all possible patterns?

**Comment by jinevening** [comment]
>  We can transform it into single case, making qerror_ratio parameter optional parameter (default is 1, so that we quantize everything to "uint8" by default).

I agree with this. `qerror_ratio` seems redundant for pattern solver. Let's make it optional.

> is it important to find exactly layernorm pattern? May be it would be better to search only for Mul-Rsqrt chain (Mul, Mean, Add, Rsqrt) and freeze its quantization to "int16"?

Good question. The rationale behind the pattern is to keep the accuracy of mini-batch variance in layer norm (for transformer models). Mul-Rsqrt chain would be mainly used for layer norm, but I'm not 100% sure. There may be another kinds of normalization that does not need mpq. So, I think this time it would be better to find only layernorm pattern.

> It doesn't have gamma multiplier (which can be just a fusion of unit gamma multiplier)

Maybe we can ignore MUL (gamma) and ADD (beta) which appear at the last part of layernorm.

**Comment by stamalakhov** [comment]
> Maybe we can ignore MUL (gamma) and ADD (beta) which appear at the last part of layernorm.

ok. Thank you.

**Comment by stamalakhov** [comment]
@jinevening 
 May i ask you a couple of questions about SoftMax?
1. Pattern for recognition is from #11492?
2. If so than quantized model should look like this:
```
Input, ReduceMax -> Q8
Sub, Exp, ReduceSum, Div -> Q16
```
?

**Comment by jinevening** [comment]
Our model analysis team has proposed the below pattern.

```
Input, ReduceMax -> Q8
Sub, Exp -> Q16
ReduceSum, Div -> Q8
```

We may go with that pattern first, and improve if possible.

**Comment by stamalakhov** [comment]
> We may go with that pattern first, and improve if possible.

Ok. Understood. Thank you.

**Comment by jinevening** [comment]
Let's close this issue. Thanks! @stamalakhov
