### ISSUE TITLE
Compiler FE: Support nn.Linear + nn.GELU + nn.Linear Torch model

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#11542]
## What

Let's support import/optimize/quantize of the `nn.Linear` -> `nn.GELU` -> `nn.Linear` pattern in torch.

## Why

Existing `fuse_gelu` option only works for limited patterns. `nn.Linear` -> `nn.GELU` -> `nn.Linear` pattern is not supported.

A major issue is that some Ops of GELU are fused with adjacent FC layers during import (onnx->tflite), so GELU cannot be fused. 

Onnx pattern
![image](https://github.com/Samsung/ONE/assets/5449554/28f2b9a1-cb91-4a50-848e-69ae6a77c24c)

Circle pattern
![image](https://github.com/Samsung/ONE/assets/5449554/7264016e-b1e0-4325-8a3d-be4f9fb729db)
(Note that **Div before Erf is fused with the preceding FC**, and **the last Mul is fused with the next FC**)

There seems two options.
1. Implement a new pass to substitute the above pattern into FC + GELU + FC
  - This may handle nn.Linear -> nn.GELU -> nn.Linear pattern, which is very specific.
2. Use circle-mlir
  - This can handle more general patterns, but need some time to become stable (?). CC @seanshpark

**Comment by jinevening** [comment]
NOTE This task is not necessary if `experimental_disable_batchmatmul_unfold` is True.

**Comment by seanshpark** [comment]
@jinevening , do you have any captured image of `expected circle` model graph?

> Use circle-mlir

I expect _circle-mlir_ to be released next year.

**Comment by jinevening** [comment]
> do you have any captured image of expected circle model graph?

I don't have the expected graph, but there is one generated by previous one-compiler (1.25).

![image](https://github.com/Samsung/ONE/assets/5449554/7ee2d663-f1a2-4a44-bcf1-6a42879d0c43)

The above pattern is in fact the same with `FC (BatchMatMul + Add) -> Gelu -> FC (BatchMatMul)`, which I expect.

**Comment by jinevening** [comment]
All done.

I've checked that our target models (deit, efficientformer) have FC-Gelu-FC patterns with O1 option.
