### ISSUE TITLE
[q-implant] Integration op level tests for q-implant

### ISSUE THREAD

**Issue by FantBlog** [Samsung/ONE#11568]
for #11254 
draft #11530

## What
Let's develop the `q-implant-test`, unit tests of the q-implant module.

## Why
- To check q-implant is built well.
- To verify that the q-implant is functioning normally.

## Progress
- Working directory structure
```
compiler/q-implant
├── CMakeLists.txt
├── README.md
├── driver
│   └── Driver.cpp
├── include
│   └── QImplant.h
├── requires.cmake
├── src
│   └── QImplant.cpp
└── tests
    ├── CMakeLists.txt
    ├── import
    │   └── Conv2D_000
    │       ├── __init__.py
    ├── q-implant.sh
    ├── q_implant_test.py
    ├── test.lst
    └── test_utils.py
```

1. compiler/q-implant/CMakeLists.txt

    - Add `add_subdirectory(tests)`

2. compiler/q-implant/requires.cmake

    - We're going to use `common-artifacts`. So, add `common-artifacts`

3. compiler/q-implant/tests/test.lst

    - Add recipe to proceed q-implant with `addval` command

4. compiler/q-implant/tests/CMakeLists.txt

    - Add `q_implant_test`

5. compiler/q-implant/tests/q-implant.sh

    - Define unit tests sequence

6. compiler/q-implant/tests/test_utils.py 

    - Write the code to extract qparams.
(qparams consists of qparam.json and .npy files)

7. compiler/q-implant/tests/q_implant_test.py

    - Import `test_utils.py` to extract qparams
    - Proceed to `q_implant`
    - If there is a problem in progress, fail the test with the `quit(255)`.
    - If it works well, pass the test with the `quit(0)`.

<br/>
We will write the above process to "draft PR" soon.

## Result

- During the nncc test, q_implant_test is added as the 100th test.
- The files used in the test are stored in the 
    `build/compiler/q-implant/recipe-name` with qparams(qparam.json + .npy) and output.circle.

## Question
1. If we proceed with the method introduced above, `q-implant-test` will be added to the nncc test, can we do that?
2. We are thinking of tests that check if `qparams` are generated correctly and `output.circle` is generated correctly.
Are there any additional tests to consider?

**Comment by seanshpark** [comment]
Q) why is q-implanty/tests/CMakeLists.txt introduced? 
is not not possible to add tests inside q-implanty/CMakeLists.txt ?

> So, add common-artifacts

Q) what do you mean by this?

>     ├── import
>    │   └── Conv2D_000
>    │       ├── __init__.py

looks like copy from `res/TensorFlowLiteRecipes`.
Q) why are these copied?

**Comment by seanshpark** [comment]
Q) what are the actual test items? 

Q) how long would it take to add the tests for all recipes (operators) in MD (man-days) or in MW (man-weeks) ?

**Comment by seanshpark** [comment]
About `Progress`
- it would be better to describe how test the "correctness".
- current description looks how to implement
- it would be better to follow existing tool tests

About "unit tests"
- current "Progress" looks like tool integration testing
- for unit testing, please look inside `*.test.cpp` files in other tools using `gtest`

**Comment by FantBlog** [comment]
> Q) why is q-implant/tests/CMakeLists.txt introduced? is not not possible to add tests inside q-implant/CMakeLists.txt ?
> 
> > So, add common-artifacts

We distinguished between the cmake required for q-implant generation and the cmake for testing because the functions were different.
Would it be better to make it a separate module?


> Q) what do you mean by this?
> 
> > ├── import
> > │   └── Conv2D_000
> > │       ├── **init**.py
> 
> looks like copy from `res/TensorFlowLiteRecipes`.
> Q) why are these copied?


Currently, we are checking the operation in certain ops in a manualy to mimic `res/TensorFlowLiteRecipes`.
It is currently being developed by creating __init__.py through the generated TensorFlowLiteRecipes.
When the above method is developed, that part will be removed.

**Comment by seanshpark** [comment]
> Would it be better to make it a separate module?

I can't suggest as I don't know about what or how to test q-implant,
but current approach is different from existing ones that may confuse future development.

**Comment by FantBlog** [comment]
> > if qparams are generated correctly and output.circle is generated correctly.
> 
> Q) ~what are the actual test items? or how do you test these?~ what is the definition of `correct` ?
> 

The tests you are currently thinking of are as follows.

test items and definition of `correct`
1. Verify that the qparams required for input for the test have been generated
2. Check if the output circle from the q-implant output is generated
3. Verify that the scale and zerop of qparams.json and output.circle are the same
4. Verify that the data type of operations in output.circle has been changed to int type

how : Use python(test 1, 2) script(Use os.path) and c++(test 3, 4) script(Not yet developed)

> Q) how long would it take to add the tests for all recipes (operators) in MD (man-days) or in MW (man-weeks) ?
 `for all ` would be for all operators that we want to support for q-implant in `res/TensorFlowLiteRecipes`

I think it takes in 3MD, but we are thinking of developing a script to create test data by reading tflite files created through recipes.

**Comment by seanshpark** [comment]
> test items and definition of correct

Is there any example data(in text) for these? I'm not quite sure the meaning of each items.

> I think it takes in 3MD,

Can you list all necessary operators? (or recipe files?)

**Comment by seanshpark** [comment]
@jinevening , do we have to tool to write a qparam.json file from existing .circle file, for all the nodes?

**Comment by jinevening** [comment]
No we don't have one. Ssafy team will start with manually writing tests, and then check if it is feasible to make a tool to automatically generate test data.

**Comment by jinevening** [comment]
They will list up target operators soon, from mobilenet, resnet, and inception.

**Comment by Judgement9882** [comment]
## About op-level-test of q-implant.

We want to check if we can proceed with q-implant on the operator used in the frequently used MobileNet, ResNet, and Inception models.

We converted the model to circle and checked the operator through the circledump command.


## Model Source

#### MobileNet : ONE/runtime/contrib/TFLiteSharp/TFLiteTestApp/res/mobilenet_v1_1.0_224.tflite

#### ResNet : [ResNet_V2_101](https://www.tensorflow.org/lite/guide/hosted_models?hl=ko) 

#### Inception : [Inception_V3](https://www.tensorflow.org/lite/guide/hosted_models?hl=ko)


## Operators

#### MobileNet
```
Operator Codes: [order] OpCodeName (OpCode Enum)
[0] AVERAGE_POOL_2D (code: 1, dep_code: 1, version: 1)
[1] CONV_2D (code: 3, dep_code: 3, version: 1)
[2] DEPTHWISE_CONV_2D (code: 4, dep_code: 4, version: 1)
[3] SOFTMAX (code: 25, dep_code: 25, version: 1)
[4] RESHAPE (code: 22, dep_code: 22, version: 1)
```

#### ResNet

```
Operator Codes: [order] OpCodeName (OpCode Enum)
[0] ADD (code: 0, dep_code: 0, version: 1)
[1] CONV_2D (code: 3, dep_code: 3, version: 1)
[2] MAX_POOL_2D (code: 17, dep_code: 17, version: 1)
[3] MUL (code: 18, dep_code: 18, version: 1)
[4] PAD (code: 34, dep_code: 34, version: 1)
[5] MEAN (code: 40, dep_code: 40, version: 1)
[6] RESHAPE (code: 22, dep_code: 22, version: 1)
```

#### Inception

```
Operator Codes: [order] OpCodeName (OpCode Enum)
[0] AVERAGE_POOL_2D (code: 1, dep_code: 1, version: 1)
[1] CONV_2D (code: 3, dep_code: 3, version: 1)
[2] CONCATENATION (code: 2, dep_code: 2, version: 1)
[3] MAX_POOL_2D (code: 17, dep_code: 17, version: 1)
[4] SOFTMAX (code: 25, dep_code: 25, version: 1)
[5] RESHAPE (code: 22, dep_code: 22, version: 1)
```

Based on the information above, we made a list of operators to proceed with the test.

```
11 operators

[0] AVERAGE_POOL_2D
[1] CONV_2D
[2] DEPTHWISE_CONV_2D
[3] SOFTMAX
[4] RESHAPE
[5] ADD
[6] MAX_POOL_2D
[7] MUL
[8] PAD
[9] MEAN
[10] CONCATENATION
```

We use the input circles and qparam required for q-implant as follows.

- input circle
Use the circle file generated during the 'common-artifacts' build process.
(ex: Conv2D_000.circle)

- qparam
There is a directory called "import" and there are folders by module in it.
Run __init.py__ to create a qparam. 
(a manual code for each operator with Python to create param.json and .npy files.)

**Comment by jinevening** [comment]
Integration test for 11 operators are done.
