### ISSUE TITLE
[luci-interpreter] Operators to enable

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#1157]
This issue shows the status of operators supported in luci-interpreter. I've listed the operators in three popular models: mobilenetV2 (M), inceptionV3 (I), and ResNet50 (R) (**ResNet is a top priority for post-training quantization** #696).

Most of the operators in the list are already supported in the draft of luci-interpreter (#205), but I found that `Mean` and `Pad` were not implemented yet. For those who want to contribute to luci-interpreter, it would be more helpful to support them first.

| Operators  | Status (float) | Status (u8) | Model |
| ------------- | ------------- | ------------- | ------------- |
Add | O @s-barannikov  | O @s-barannikov   | R, M
AvgPool2D | O @s-barannikov  | O @s-barannikov  | M, I
Concat | O @s-barannikov   | O @s-barannikov   | I
Conv2D | O @s-barannikov   | O @s-barannikov   | R, M, I
DepthwiseConv2D | O @s-barannikov   | O @s-barannikov   | M
FullyConnected | O @s-barannikov   |   | R, I
MaxPool2D | O @s-barannikov   | O @s-barannikov   | R, I
Mean | @karthik-pen (#1669)  | @karthik-pen (#1669) | R
Pad | O @s-barannikov (#1509) | O @s-barannikov (#1509) | R
Reshape | O @s-barannikov   | O @s-barannikov   | M
Softmax | O @s-barannikov   |   | M, I
ArgMax | @struss (#1691 )  |  @struss (#1691 )  | R

**Update 2020/05/27**:  `ArgMax` operator was added to the table.

**Comment by jinevening** [comment]
@karthik-pen Sure. Please add me, @binarman , and @s-barannikov  as reviewers.

**Comment by s-barannikov** [comment]
What does R, M and I mean?

**Comment by s-barannikov** [comment]
I will implement `Pad`.

**Comment by lemmaa** [comment]
@karthik-pen , @s-barannikov , what if you write your github id in the appropriate cell of the table and mark it in progress? :)

**Comment by jinevening** [comment]
Execution time of each model in luci-interpreter

Model  | Debug mode | Release mode
-- | -- | -- 
InceptionV3 | 114 sec | 5.2 sec
MobileNetV2 | 6.9 sec | 0.4 sec
ResNet50 |  | 

(ResNet50 will be updated later)

luci-interpreter will run ~1,000 data samples to profile moving avg of min/max values for post-training quantization #696. For InceptionV3, the execution time for 1,000 data is ~5200 sec (~1 hour 27 min). Even considering the time to record min/max values, profiling would finish within several hours.

**Comment by s-barannikov** [comment]
From what I've seen, most of the time is spent on `Conv2D`. At least that operation needs to use optimized kernel (instead of reference), but it requires some additional steps to take (allocate Im2Col tensor and possibly create CpuContext to enable parallelism).

**Comment by s-barannikov** [comment]
@jinevening BTW Is it the time spent on "interpret()" call only?

**Comment by jinevening** [comment]
> BTW Is it the time spent on "interpret()" call only?

@s-barannikov You mean [this issue](https://github.com/Samsung/ONE/issues/1098#issuecomment-631374836?)? Then, yes.

I'm working on the driver (named `record-minmax`) to call the interpreter with profiling functionality. Let's gather them later.

**Comment by jinevening** [comment]
> BTW Is it the time spent on "interpret()" call only?

No, I measured the whole time spent for running `luci_eval_tester`

```
$ time build/release/compiler/luci-value-test/tester/luci_eval_tester build/release/compiler/luci-value-test/inception_v3.circle 1 build/release/compiler/luci-value-test/inception_v3.circle.input build/release/compiler/luci-value-test/inception_v3.circle.output

real    0m0.773s
user    0m0.633s
sys     0m0.140s
```

**Comment by binarman** [comment]
> real    0m0.773s

Looks better!

@jinevening did you try run network in multithread mode?

@s-barannikov how to enable parallel execution?

**Comment by jinevening** [comment]
> @jinevening did you try run network in multithread mode?

No. I'm not even sure if the Conv2D kernel runs with multi threads.

**Comment by s-barannikov** [comment]
@s-barannikov how to enable parallel execution?

There is no way to control it yet.

**Comment by jinevening** [comment]
@karthik-pen Can you tell me the progress of `Mean`?

**Comment by karthik-pen** [comment]
I will post the draft in some time. Sorry for the delay.

**Comment by jinevening** [comment]
All operators in ResNet50, InceptionV3, MobileNetV2 are now supported 👏 .

Look at [the above table](https://github.com/Samsung/ONE/issues/1157#issuecomment-633452085) to see the execution time of each model.

Thanks! @s-barannikov @karthik-pen @struss

**Comment by jinevening** [comment]
I close this issue because all of the target operators are supported and no more issues have been raised.
