### ISSUE TITLE
[onert] Mobilebert model profiling 

### ISSUE THREAD

**Issue by ragmani** [Samsung/ONE#11599]
## What
Let's do mobilebert model profiling

### Model
https://www.tensorflow.org/lite/examples/bert_qa/overview

## Why
For #11368, they found a mobilebert model executable with onert. However performance result is not as expected. I think we need to see if performance can be improved.

## How
1. Dump to a json file for chrome trace.
```bash
$ TRACE_FILEPATH=mobilebert ./Product/x86_64-linux.release/out/bin/onert_run lite-model_mobilebert_1_metadata_1.tflite
Model Filename lite-model_mobilebert_1_metadata_1.tflite
===================================
MODEL_LOAD   takes 119.357 ms
PREPARE      takes 87.594 ms
EXECUTE      takes 894.162 ms
- MEAN     :  894.162 ms
- MAX      :  894.162 ms
- MIN      :  894.162 ms
- GEOMEAN  :  894.162 ms
===================================
$ ls -al mobilebert.chrome.json 
-rw-r--r-- 1 jiseob.jang domain^users 1034235  9월 26 17:26 mobilebert.chrome.json
```

2. View the dump file with chrome trace
![mobilebert](https://github.com/Samsung/ONE/assets/18050611/9260bfeb-f901-4d0d-8aa7-b4fa33c4fbcc)

The operation that consumes most time is FullyConnected.

**Comment by hseok-oh** [comment]
I've tested this on my odroid-xu4 and parse chrome.json to get each operator's time and average time

```
Per-operator time:
  FullyConnected: 10709.532 ms
  Softmax: 499.779 ms
  Add: 134.523 ms
  Reshape: 119.935 ms
  Mul: 72.951 ms
  Slice: 62.347 ms
  Pack: 41.222 ms
  Transpose: 35.651 ms
  Sub: 5.586 ms
  Cast: 1.813 ms
  Gather: 0.439 ms
  Concat: 0.431 ms
  StridedSlice: 0.403 ms
  Pad: 0.301 ms
  Unpack: 0.054 ms
  subg: 0.011 ms
Average time for each operator:
  FullyConnected: 9.264 ms (1156)
  Softmax: 10.412 ms (48)
  Add: 0.214 ms (630)
  Reshape: 0.092 ms (1306)
  Mul: 0.188 ms (388)
  Slice: 0.081 ms (768)
  Pack: 0.429 ms (96)
  Transpose: 0.057 ms (626)
  Sub: 0.116 ms (48)
  Cast: 0.906 ms (2)
  Gather: 0.110 ms (4)
  Concat: 0.215 ms (2)
  StridedSlice: 0.101 ms (4)
  Pad: 0.075 ms (4)
  Unpack: 0.027 ms (2)
  subg: 0.011 ms (1)
```

**Comment by ragmani** [comment]
How did you parse chrome.json?

**Comment by glistening** [comment]
@ragmani Why don't you open chrome trace in chrome?

From https://github.com/Samsung/ONE/issues/4482, `ruy` backecnd may help.

Could anyone try to run with
```
BACKENDS=ruy;cpu ./Product/x86_64-linux.release/out/bin/onert_run lite-model_mobilebert_1_metadata_1.tflite
Model Filename lite-model_mobilebert_1_metadata_1.tflite
```

**Comment by ragmani** [comment]
> Why don't you open chrome trace in chrome?

I opened it, but I couldn't upload the captured image on VDI.

**Comment by hseok-oh** [comment]
>How did you parse chrome.json?

I made parsing python tool. 
I've updated result because there was a bug.

**Comment by ragmani** [comment]
> Could anyone try to run with ruy enabled explicitly?

There is no difference on x86_64 and it still uses only one thread.

**Comment by glistening** [comment]
> > Could anyone try to run with ruy enabled explicitly?
> 
> There is no difference on x86_64 and it still uses only one thread.
> 
> I checked and found that FullyConnected kernel is a neon kernel that does not use multi-threading.

Ah, I had to mention run on arm. Ruy uses neon. In addition, `xnnpack` is likely to be faster. 

I think a) optimizing Mobil Bert model (or something else) and b) Python binding are totally different tasks. To optimize some model, they need to learn something new (like profiling, porting optimized kernel, ...).

Also, if Python binding is not optimized, it may require additional overhead like copying input/output to/from `onert` core I don't take a closer look since I expected Python binding will be used for some developer tool, not for performance requiring task.

I think there may be another approach though I don't know SSAFY member's preference. Python has a lot of libraries (image processing, plot, ...) which is hard at least require more time in C++.

**Comment by glistening** [comment]
> I opened it, but I couldn't upload the captured image on VDI.

@ragmani Thank you for answer. I thought you can open it because I usually work on my native Ubuntu (w/o VDI) when I WFH.

**Comment by ragmani** [comment]
I checked that the model's performance was improved on rpi4 using the ruy kernel that uses multi-threading when executing with `OP_BACKEND_FullyConnected=ruy`.

```bash
$ BACKENDS="cpu;ruy" ./Product/armv7l-linux.release/out/bin/onert_run lite-model_mobilebert_1_metadata_1.tflite
Model Filename lite-model_mobilebert_1_metadata_1.tflite
===================================
MODEL_LOAD   takes 400.176 ms
PREPARE      takes 294.284 ms
EXECUTE      takes 6661.851 ms
- MEAN     :  6661.851 ms
- MAX      :  6661.851 ms
- MIN      :  6661.851 ms
- GEOMEAN  :  6661.851 ms
===================================
```
```bash
$ RUY_THREADS=4 BACKENDS="cpu;ruy" OP_BACKEND_FullyConnected=ruy ./Product/armv7l-linux.release/out/bin/onert_run lite-model_mobilebert_1_metadata_1.tflite
Model Filename lite-model_mobilebert_1_metadata_1.tflite
===================================
MODEL_LOAD   takes 401.156 ms
PREPARE      takes 1892.073 ms
EXECUTE      takes 1590.531 ms
- MEAN     :  1590.531 ms
- MAX      :  1590.531 ms
- MIN      :  1590.531 ms
- GEOMEAN  :  1590.531 ms
===================================
```
```bash
$ BACKENDS="cpu;ruy" OP_BACKEND_FullyConnected=ruy ./Product/armv7l-linux.release/out/bin/onert_run lite-model_mobilebert_1_metadata_1.tflite
Model Filename lite-model_mobilebert_1_metadata_1.tflite
===================================
MODEL_LOAD   takes 400.271 ms
PREPARE      takes 1889.499 ms
EXECUTE      takes 1585.222 ms
- MEAN     :  1585.222 ms
- MAX      :  1585.222 ms
- MIN      :  1585.222 ms
- GEOMEAN  :  1585.222 ms
===================================
```
```bash
$ RUY_THREADS=1 BACKENDS="cpu;ruy" OP_BACKEND_FullyConnected=ruy ./Product/armv7l-linux.release/out/bin/onert_run lite-model_mobilebert_1_metadata_1.tflite
Model Filename lite-model_mobilebert_1_metadata_1.tflite
===================================
MODEL_LOAD   takes 402.765 ms
PREPARE      takes 1876.800 ms
EXECUTE      takes 3367.152 ms
- MEAN     :  3367.152 ms
- MAX      :  3367.152 ms
- MIN      :  3367.152 ms
- GEOMEAN  :  3367.152 ms
===================================
```
