### ISSUE TITLE
[record-minmax] Introduce --minmax_data option

### ISSUE THREAD

**Issue by glistening** [Samsung/ONE#11644]
### What?

I would like to introduce new option `--minmax_data`. which, aims for embedding recorded minmax into input model.

### Why?

It will enable to use other runtime (e.g. `onert`) to record minmax for each input and op.
`record-minmax` will not use `luci-interpreter` for this case.
Instead, it will read the minmax recordings from `--minmax-data`.
Then, it embeds the value into corresponding op's `min/max`.

The output will be used as input for `circle-quantizer` w/o modifying `circle-quantizer`.

### Another (Previous approach)

@jinevening 

Internally, I was going to introduce another tool like `minmax-embedder`. But I suggest this approach to reduce the number of tools under `compiler`.

If you prefer to separate this feature, I will close and introduce `minmax-emedder`.

**Comment by glistening** [comment]
For more information, I would like to merge step 1 and step 2 from https://github.com/Samsung/ONE/issues/696#issue-616321441 to reduce the number of model re-writing.

#### BEFORE

1) `record-minmax` <sub> = step 1 </sub>: {input model} + {minmax file} → {input + minmax} model
2) `circle-quantizer`<sub> = step 2 </sub>: {input + minmax} model → {input + minmax + qparam} model


#### AFTER

1) `circle-quantizer`: {input model} + {minmax file} → {input + minmax + qparam} model

If you're okay for this change and is done, the change `record-minmax` will be removed.

**Comment by jinevening** [comment]
https://github.com/Samsung/ONE/issues/11644#issuecomment-1746072625 looks good to me! We may need to define the format of minmax file for the change.

---

> Internally, I was going to introduce another tool like minmax-embedder. But I suggest this approach to reduce the number of tools under compiler.
If you prefer to separate this feature, I will close and introduce minmax-emedder.

I think `record-minmax` becomes too complicated (it is already quite complicated..). Could you make a separate tool (minmax-embedder) if this item is not so urgent? The number of modules under compiler would be not an issue.

**Comment by glistening** [comment]
Okay. I will introduce `embed-minmax`. #11649 is the DRAFT (exactly, which was reviewed in our inner repo).
