### ISSUE TITLE
[one-optimize] Fuse horizontal FC layers

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#11705]
## What

Let's fuse horizontal FC layers

![image](https://github.com/Samsung/ONE/assets/5449554/c720a491-87e9-4902-99c5-22850febadfd)

## Why

The pattern appears at the last part of efficientformer.

**Comment by seanshpark** [comment]
Q) what is `to-be` graph?

**Comment by jinevening** [comment]
`to-be` graph should have a single FC.

`before`

```cpp
/*
 *
 *     +---- [In] ----+
 *     |              |
 *     V              V
 *   fc1 (w1, b1)   fc2 (w2, b2)
 *     |              |
 *     |              |
 *     +---> add <----+
 *            |
 *            V
 *          [Out]
 */
```

`after`

```cpp
/*
 *
 *     [In]
 *      |
 *      V
 *     fc3 (w1+w2, b1+b2)
 *      |
 *      V
 *     [Out]
 */
```

Shape/dtype of fc1, fc2, and fc3 should be the same.

**Comment by jinevening** [comment]
@BalyshevArtem Thanks for taking this task!

**Comment by jinevening** [comment]
Let's close this issue. Thanks! @BalyshevArtem
