### ISSUE TITLE
[one-quantize] Save recorded min/max

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#11717]
## What

Let's make an option to save min/max recorded during calibration

## Why

Min/max values are useful for optimization in some backends.

**Comment by jinevening** [comment]
@BalyshevArtem Thanks for taking this task!

**Comment by BalyshevArtem** [comment]
I think issue can be closed, as #11783 and #11793 are merged ? :)

**Comment by jinevening** [comment]
Yes. Thank you for contribution!
