### ISSUE TITLE
[one-quantize] How to improve the method of feeding reference data sets

### ISSUE THREAD

**Issue by lemmaa** [Samsung/ONE#11724]
Currently, the method of feeding reference data to quantize a model with multiple inputs is to concat the data in the order of the inputs and deliver the data in the order.

While this method has the advantage of preventing confusion in data fed simultaneously to multiple inputs of the model, it comes with the inconvenience of having to concatenate and process the raw data one by one.

Let's think about an alternative to the data fibbing method to improve this.

- Raw data must be usable as is without additional processing.
- There should be no confusion about the order of data passed to the various inputs to the model.
- It should be easy to expand to support N inputs.
- ...

Personally, I think it would be better to pass a list of input data for each input. The delivery methods that currently come to mind are as follows:

1. Pass data list as individual file
   - CLI options must be changed to allow multiple list files to be transmitted.

- input-0.lst

```
file-0001.bin
file-0002.bin
     .
     .
     .
```
- input-1.lst

```
image-001.data
image-002.data
     .
     .
     .
```

- input-N.lst

```
dat-001.bin
dat-001.bin
     .
     .
     .
```

2. Pass one file with a separate section listing the data for each input
   - It is possible to expand the list file processing method without changing the CLI option.

- inputdate.lst

```
[input-0]
file-0001.bin
file-0002.bin
     .
     .
     .


[input-1]
image-001.data
image-002.data
     .
     .
     .

[input-N]
dat-001.bin
dat-001.bin
     .
     .
     .
```

What do you think?

**Comment by lemmaa** [comment]
In method 2, there is also a way to use the ini format, although it adds some inconvenience. This method will be more helpful in making the order of each input data clear and error-free. 

- inputdate.ini

```
[input-0]
D00001=file-0001.bin
D00002=file-0002.bin
     .
     .
     .


[input-1]
D00001=image-001.data
D00002=image-002.data
     .
     .
     .

[input-N]
D00001=dat-001.bin
D00002=dat-001.bin
     .
     .
     .
```

However, additional review is needed on how to determine the key name.

**Comment by jinevening** [comment]
Just for note. There is a previous discussion https://github.com/Samsung/ONE/issues/9977#issuecomment-1338595317.

---

A major issue is that we need a rule to specify the order of data (ex: section name in https://github.com/Samsung/ONE/issues/11724#issuecomment-1764085250).

How about using a whitespace (or tab) as a delimiter of multiple inputs? For example, for a model with three inputs `a`, `b`, `c`, we can give `n` data as below.

`datalist.txt`
```
a[0].bin b[0].bin c[0].bin
a[1].bin b[1].bin c[1].bin
...
a[n-1].bin b[n-1].bin c[n-1].bin
```

A major advantage of this approach is that there is no need to consider the section name, and we can use a similar format with the existing interface.

**Comment by jinevening** [comment]
ini looks also good to me. We may add new `data_format`. https://github.com/Samsung/ONE/issues/11724#issuecomment-1765557580 is just suggestion.

**Comment by jinevening** [comment]
[Add_000.zip](https://github.com/Samsung/ONE/files/13211946/Add_000.zip)

**Comment by jinevening** [comment]
I've made draft (#11831) for the suggestion in https://github.com/Samsung/ONE/issues/11724#issuecomment-1765557580.

**Comment by jinevening** [comment]
https://github.com/Samsung/ONE/issues/11724#issuecomment-1765557580 is not supported in both `onecc quantize` and `rawdata2hdf5`. Can we close this issue?
