### ISSUE TITLE
[onert-micro] restore DC score

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#11744]
DC in SAM Score is dropped to 3.86 (Note that it was 4.18 at onert-micro 1.0.0 release)

[DC Score link](https://analysishub.sec.samsung.net/service/analyses/2432084) : Note that this link will be outdated soon. Any way, At this point, DC score is below 4 (3.86). Thus, we cannot release onert-micro with this score.

Let's restore this.

**Comment by chunseoklee** [comment]
<body link="#0563C1" vlink="#954F72">



No. | Metric | BlockKey | Path | LineStart | LineEnd | LineCount | Token | Violation
-- | -- | -- | -- | -- | -- | -- | -- | --
1 | DC | 1 | onert-micro/luci-interpreter/src/kernels/AveragePool2D.cpp | 42 | 116 | 75 | 469 | Y
2 | DC | 1 | onert-micro/luci-interpreter/src/kernels/MaxPool2D.cpp | 53 | 125 | 73 | 469 | Y
3 | DC | 7 | onert-micro/luci-interpreter/src/kernels/Split.cpp | 42 | 93 | 52 | 243 | Y
4 | DC | 7 | onert-micro/luci-interpreter/src/kernels/SplitV.cpp | 41 | 92 | 52 | 243 | Y
5 | DC | 2 | onert-micro/luci-interpreter/src/kernels/SVDF.cpp | 37 | 82 | 46 | 346 | Y
6 | DC | 3 | onert-micro/luci-interpreter/src/kernels/FloorDiv.cpp | 42 | 87 | 46 | 296 | Y
7 | DC | 3 | onert-micro/luci-interpreter/src/kernels/FloorMod.cpp | 42 | 87 | 46 | 296 | Y
8 | DC | 4 | onert-micro/luci-interpreter/src/kernels/Maximum.cpp | 37 | 78 | 42 | 278 | Y
9 | DC | 4 | onert-micro/luci-interpreter/src/kernels/Minimum.cpp | 37 | 78 | 42 | 278 | Y
10 | DC | 6 | onert-micro/luci-interpreter/pal/common/PALSub.h | 38 | 77 | 40 | 245 | Y
11 | DC | 6 | onert-micro/luci-interpreter/pal/common/PALAddCommon.h | 43 | 82 | 40 | 245 | Y
12 | DC | 2 | onert-micro/luci-interpreter/src/kernels/SVDF.cpp | 125 | 163 | 39 | 346 | Y
13 | DC | 9 | onert-micro/luci-interpreter/pal/common/PALDiv.h | 66 | 103 | 38 | 219 | Y
14 | DC | 9 | onert-micro/luci-interpreter/pal/common/PALMulCommon.h | 66 | 103 | 38 | 219 | Y
15 | DC | 13 | onert-micro/luci-interpreter/pal/common/PALMinimumCommon.h | 37 | 74 | 38 | 203 | Y
16 | DC | 13 | onert-micro/luci-interpreter/pal/common/PALMaximumCommon.h | 37 | 74 | 38 | 203 | Y
17 | DC | 14 | onert-micro/luci-interpreter/pal/common/PALDiv.h | 69 | 103 | 35 | 203 | Y
18 | DC | 14 | onert-micro/luci-interpreter/pal/common/PALSub.h | 43 | 77 | 35 | 203 | Y
19 | DC | 14 | onert-micro/luci-interpreter/pal/common/PALAddCommon.h | 48 | 82 | 35 | 203 | Y
20 | DC | 14 | onert-micro/luci-interpreter/pal/common/PALMulCommon.h | 69 | 103 | 35 | 203 | Y
21 | DC | 15 | onert-micro/luci-interpreter/src/kernels/Abs.cpp | 43 | 76 | 34 | 196 | Y
22 | DC | 15 | onert-micro/luci-interpreter/src/kernels/Logistic.cpp | 49 | 82 | 34 | 196 | Y
23 | DC | 40 | onert-micro/luci-interpreter/pal/common/PALReduceCommon.h | 33 | 66 | 34 | 134 | Y
24 | DC | 40 | onert-micro/luci-interpreter/pal/common/PALMean.h | 33 | 66 | 34 | 134 | Y
25 | DC | 5 | onert-micro/luci-interpreter/pal/common/PALAveragePool2DCommon.h | 28 | 57 | 30 | 267 | Y

</body>

**Comment by ragmani** [comment]
Can I do this task? I will restore the DC score.

**Comment by ragmani** [comment]
With a draft PR(#12214), DC in SAM Score is restored to 4.04.
![image](https://github.com/Samsung/ONE/assets/18050611/af598241-1e6e-490b-8a64-1fe86351639d)

**Comment by ragmani** [comment]
Done
