### ISSUE TITLE
Compiler FE: List up unused projects

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#11814]
Let's list unused compiler frontend projects to remove or disable build.

**Comment by seanshpark** [comment]
>  remove or disable build.

+1 to `disable build`

@lemmaa , your opinion ?

**Comment by seanshpark** [comment]
I'll work on this task :)

**Comment by seanshpark** [comment]
#11848 Draft implementation:
- exclude module (`compiler/something`) when there exist `exclude.me` file
- if `BUILD_WHITELIST` is given, ignore this feature, build all items in the list

@lemmaa , any comments?

**Comment by seanshpark** [comment]
@lemmaa PTAL

**Comment by lemmaa** [comment]
> Let's list unused compiler frontend projects to remove or disable build.

@hseok-oh ,  what's the purpose of this work? 

My guess is that there are many possible reasons for this, such as 

- Optimizing CI build resources, 
- Reducing the difficulty of source code maintenance, 
- Etc. 

In any case, the reason, purpose, etc. must be clear so that there is no confusion in the discussion and conclusion.

**Comment by lemmaa** [comment]
> #11848 Draft implementation:
> 
> * exclude module (`compiler/something`) when there exist `exclude.me` file in that folder
> * if `-DBUILD_WHITELIST=...` is given, ignore this feature and build all modules in the list
> * if `-DENABLE_EXCLUDE_ME=OFF` is given, ignore this feature and build all modules
> * excluded module may fail in build in the future but we won't know that
> * we can re-enable excluded module when ever needed again
>   * any build failure should be fixed at that time
> 
> @lemmaa , any comments?

@seanshpark , I agree with your draft design. However, it would be nice to check what @hseok-oh's original intention was and organize the details.

**Comment by hseok-oh** [comment]
> > Let's list unused compiler frontend projects to remove or disable build.
> 
> @hseok-oh , what's the purpose of this work?
> 
> My guess is that there are many possible reasons for this, such as
> 
>     * Optimizing CI build resources,
> 
>     * Reducing the difficulty of source code maintenance,
> 
>     * Etc.
> 
> 
> In any case, the reason, purpose, etc. must be clear so that there is no confusion in the discussion and conclusion.
> 
> And, what do you think are excluded? :)

Reason to remove: maybe not used any more
- ex) projects for caffe tools

Reason to disable build: reduce CI build resource
-  xx) `coco` and related, `ann-api` and related, etc...

**Comment by lemmaa** [comment]
> Reason to disable build: reduce CI build resource
> 
> * ex) `coco` and related, `ann-api` and related, etc...

In this case, isn't it necessary to automatically and regularly check the following cases among the target modules?

> * excluded module may fail in build in the future but we won't know that
> * we can re-enable excluded module when ever needed again
>   
>   * any build failure should be fixed at that time

For example, even if in frequent `PR check build` or `commit check build` are excluded, it is checked regularly on a daily or weekly basis and an issue is registered when a build break or test failure occurs.

> * if `-DBUILD_WHITELIST=...` is given, ignore this feature and build all modules in the list

I think this option would be appropriate for such support.

Taking this into consideration, it would be a good idea to categorize and organize the target list according to the original purpose of the issue.

- Required build target
- Subject to regular inspection
- Fade out target out of interest

**Comment by seanshpark** [comment]
> I think this option would be appropriate for such support.

Yup, `-DENABLE_EXCLUDE_ME=OFF` is for regular checkup to build all modules :)

**Comment by seanshpark** [comment]
I'll begin posting related changes.

**Comment by seanshpark** [comment]
These are the lists that will be excluded.

- [ ] ...

**Comment by seanshpark** [comment]
ping @jinevening , @mhs4670go

**Comment by seanshpark** [comment]
- [ ] pepper-assert
- [ ] pepper_env
- [ ] ...

**Comment by seanshpark** [comment]
done for now.
@hseok-oh , ok to close?
