### ISSUE TITLE
Compiler FE: Enable CumSum Op

### ISSUE THREAD

**Issue by batcheu** [Samsung/ONE#11842]
Lets' enable CUMSUM Op

- [x] tflchef
- [x] res/TensorFlowLiteRecipes
- [x] tfldump (nothing to do)
- [x] tflite2circle
- [x] circledump (nothing to do)
- [x] luci.lang
- [x] luci.import
- [x] luci.export 
- [x] luci.logex
- [x] luci.service
- [x] luci.partition
- [x] luci.tests
- [x] luci_interpreter
- [x] luci-value-test
- [x] circle-part-value-test (nothing to do, tested in draft PR)

**Comment by seanshpark** [comment]
@batcheu , the list in the first comment is the sequence of PRs to land.
But you will have failure in `common-artifacts`.
To resolve this, first add to exclude list in `common-artifacts`,
and then land necessary codes then remove from the exclude list.

Doing this will let CI test the landed codes. (we all know that draft is working)

**Comment by batcheu** [comment]
> @batcheu , the list in the first comment is the sequence of PRs to land. But you will have failure in `common-artifacts`. To resolve this, first add to exclude list in `common-artifacts`, and then land necessary codes then remove from the exclude list.
> 
> Doing this will let CI test the landed codes. (we all know that draft is working)

Okay, so let me check if I understand correctly.
First, I have to add a addtionnal commit adding CumSum in exclude.list into between updating `tlchef` commit  and adding a recipes commit.  And then in the final step, remove CumSum from exclude.list to let CI test the operation added.
Am I right?

**Comment by seanshpark** [comment]
> Am I right?

I think so :)

**Comment by batcheu** [comment]
Done ! ;)
