### ISSUE TITLE
[tf2tflite-value-pbtxt-test] Test intermittently fails in CI

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#11850]
## What

`tf2tflite-value-pbtxt-test` intermittently fails in CI. Let's check if we can resolve this issue.

## Why

This slows down our development speed.

**Comment by jinevening** [comment]
It happens in multiple networks, so disabling a specific test seems not a solution.

**Comment by seanshpark** [comment]
This module can be excluded from  #11848

**Comment by jinevening** [comment]
https://github.com/Samsung/ONE/pull/11922 is merged. Let's close this.
