### ISSUE TITLE
[one-optimize] Fuse Mul with Conv

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#11897]
## What

Let's fuse channel-wise Mul with Conv.

![image](https://github.com/Samsung/ONE/assets/5449554/ee07cb2e-6a60-42a3-9b9e-e304460e87bd)

## Why

Our target model has the pattern

**Comment by stamalakhov** [comment]
m.b. i can try to resolve this issue?

**Comment by jinevening** [comment]
Yes please. Thanks! :)

**Comment by stamalakhov** [comment]
@jinevening 
Is it channelwise constant scalar multiplication?

**Comment by jinevening** [comment]
It's mul with channelwise constant. Not scalar.

**Comment by stamalakhov** [comment]
> It's mul with channelwise constant. Not scalar.

Ok. I see. Thank you.

**Comment by jinevening** [comment]
Let's close this. Thanks @stamalakhov
