### ISSUE TITLE
Compiler FE: Enable ELU Operator

### ISSUE THREAD

**Issue by d-krylov** [Samsung/ONE#1190]
- [x] tflchef #1341
- [x] luci.IR #1342 
- [x] luci.Import #1343 
- [x] luci.Export #1346 
- [x] luci.logex #1347 
- [x] luci.Service #1345 
- [x] res/TensorFlowPythonExamples (already done)
- [x] res/TensorFlowLiteRecipes #1344 
- [x] tflite2circle (was done before)
- [x] luci.tests #1348 
- [x] tfldump (nothing to do)
- [x] circledump (nothing to do)

for #1167

**Comment by binarman** [comment]
all done

**Comment by binarman** [comment]
draft #1210
