### ISSUE TITLE
Introduce a new tool to generate h5 file (quantization dataset) from numpy files

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#12053]
## What

Let's introduce a new tool to pack numpy files to h5-format quantization dataset.

## Why

There is a similar tool, `rawdata2hdf5`, but users often try to convert numpy files rather than raw data.

So, it would be helpful to provide a new tool e.g., `numpy2hdf5`.

**Comment by jinevening** [comment]
Here is a script I locally used.

```python
import h5py as h5
import numpy as np
import argparse
import glob
import os

def get_parser():
    """Create and return given the argument parser"""
    parser = argparse.ArgumentParser(
        description='command line tool to convert numpy files to hdf5 file')
    parser.add_argument(
        "-i",
        "--input_dir",
        type=str,
        help=
        "Path to the directory where numpy files are saved",
        required=True)
    parser.add_argument(
        "-o",
        "--output_path",
        type=str,
        help="Path to the output hdf5 file.",
        required=True)
    return parser

def create_hdf5(input_dir, output_path):
    """Create the hdf5 file using raw data files listed in input_dir"""
    h5_file = h5.File(output_path, 'w')
    group = h5_file.create_group("value")

    numpy_paths = glob.glob(os.path.join(input_dir, '*'))

    num_converted = 0 
    for numpy_path in numpy_paths:
        numpy_data = np.load(numpy_path)
        sample = group.create_group(str(num_converted))
        sample.create_dataset('0', data=numpy_data)
        num_converted += 1

    h5_file.close()

    print("Numpy data have been packaged to " + output_path)
    print("Number of packaged data: " + str(num_converted))

def main():
    parser = get_parser()

    args = parser.parse_args()

    create_hdf5(args.input_dir, args.output_path)

if __name__ == '__main__':
    main()
```

**Comment by mhs4670go** [comment]
@jinevening Maybe we can introduce a new module for data format conversion where the scripts are all there. Or we could just one single driver for them. What's your take on this?

**Comment by jinevening** [comment]
That seems a good idea. It'll be good to introduce a unified driver (ex: `create-h5-dataset`), which combines `rawdata2hdf5` and `numpy2hdf5`.

**Comment by seanshpark** [comment]
As I understand these hdf5 files are for quantization. I hope `quantization` or abbreviation word is used, then that can help understand it's purpose.

**Comment by jinevening** [comment]
How about `one-create-quant-dataset`? It would be good to sync the prefix (`one-`) with existing one cli.

It would conduct the following conversions.

list of raw data -> h5 (`rawdata2hdf5`)
list of numpy files -> h5 (TODO)
...

**Comment by Seunghui98** [comment]
I created `one-create-quant-dataset`'s draft code the following structure. https://github.com/Samsung/ONE/pull/12186

- `compiler/one-cmds/one-create-quant-dataset`
  - `-i/--input_type` : Input type of either `rawdata2hdf5` or `numpy2hdf5` 
    - `rawdata2hdf5` : list of raw data files-> h5  
    - `numpy2hdf5` : list of numpy files -> h5
  - `-l/--data_list` : Path to the text file where lists the absoulte paths of data files to be converted.
  - `-o/--output_path` : Path to the output hdf5 file.


(for test)
- `compiler/one-cmds/tests/preprocess_images_numpy.py`
  - file that creates numpy files that go into input to test that input_type is `numpy2hdf5`
- `one-create-quant-dataset` test files - pos : 2 / neg: 5

**Comment by seanshpark** [comment]
Q) `rawdata2hdf5` or `numpy2hdf5` looks like functionality not input type.
`rawdata` or `numpy` looks like input type.

**Comment by Seunghui98** [comment]
@seanshpark 

> rawdata or numpy looks like input type.

As you said, `input_type` is `rawdata` or `numpy`, and `output_type` arguments are added to select `hdf5`.
it would be good to prevent users from getting confused.
Thank you for comments !

**Comment by Seunghui98** [comment]
@seanshpark 

Before uploading the code PR about `one-create-quant-dataset`, 
I am worried about where to put the guide description of `one-create-quant-dataset` in the structure. 😅

`rawdata2hdf5`, a tool similar to `one-create-quant-dataset`, has a readme file written separately  as [follows](https://github.com/Samsung/ONE/blob/master/compiler/rawdata2hdf5/README.md).
But `one-create-quant-dataset` goes into one-cmds, 
should I add a description of the tool to the existing [how-to-use-one-commands.txt](https://github.com/Samsung/ONE/blob/master/compiler/one-cmds/how-to-use-one-commands.txt)?
Or should I separately add a guide description in the form of `how-to-use-one-create-quant-dataset.txt`? :)

**Comment by seanshpark** [comment]
@jinevening any idea?

**Comment by seanshpark** [comment]
@Seunghui98 I can't catch you question. Who's the audience of this guide?

**Comment by seanshpark** [comment]
Q) is current draft fully implemented?
- where is `numpy2hdf5` ?
- what is the relation of existing `rawdata2hdf5` vs `one-create-quant-dataset` ?

**Comment by jinevening** [comment]
> should I add a description of the tool to the existing [how-to-use-one-commands.txt](https://github.com/Samsung/ONE/blob/master/compiler/one-cmds/how-to-use-one-commands.txt)?

+1 for this. `one-create-quant-dataset` is aligned with existing `one-XX` tools. Actually, a more popular document is ONE user guide. It would be good to add a new page there too :)

**Comment by Seunghui98** [comment]
@seanshpark 

> Who's the audience of this guide?

This guide is written for user of `one-quant-create-dataset`.

> Q) is current draft fully implemented?

I haven't made a draft for the user guide yet. 
Once the path of the user guide is determined, i planned to implement draft.


> where is numpy2hdf5 ?

`numpy2hdf5` is a function supported by the tool of `one-create-quant-dataset`. 
In the function implementation of numpy2hdf5, input corresponds to the numpy format in the draft.

> what is the relation of existing rawdata2hdf5 vs one-create-quant-dataset ?

the tool of `one-create-quant-dataset` has the conversion function of existing `rawdata2hdf5` and newly added `numpy2hdf5`.
The relation is that `one-cretae-quant-dataset` contains `rawdata2hdf5`. :)

**Comment by seanshpark** [comment]
> This guide is written for user of one-quant-create-dataset.

Who is the `user`? What kind of `user` are there?

> I haven't made a draft for the user guide yet.

Not the document, the implementation.

> so it does not exist in master but only in draft PR. 

the module `numpy2hdf5` like `rawdata2hdf5`

> The relation is that one-cretae-quant-dataset contains rawdata2hdf5. :)

Are you planning to deprecate `rawdata2hdf5` ?

**Comment by jinevening** [comment]
`numpy2hdf5` and `rawdata2hdf5` will be merged and served as one tool `one-create-quant-dataset`.  I think it would be better to deprecate `rawdata2hdf5`.

**Comment by Seunghui98** [comment]
@seanshpark 
> Who is the user? What kind of user are there?

At first, I thought of a user who uses one's quantize function.
So I tried to create a guide document under the `ONE/compiler/one-cmds` like `README.md` or `how-to-use~.txt`.
But like @jinevening 's comment, ONE-user guide is more popular, so I think it's better to write it separately here.

> Not the document, the implementation.

Oh.. okay. :)
The part about the implementation of `one-quant-create-dataset`is up to Draft PR, and 
i am currently uploading the PR by spliting it.

> Are you planning to deprecate rawdata2hdf5 ?
yes :) Since `one-quant-create-dataset` contains the same function, 
it seems better to deprecate `rawdata2hdf5`.
yes.

**Comment by Seunghui98** [comment]
@jinevening 

Should I delete the previously existing `rawdata2hdf5` tool? Or should I just let it go?

**Comment by seanshpark** [comment]
> Should I delete the previously existing rawdata2hdf5 tool? Or should I just let it go?

https://github.com/Samsung/ONE/issues/12053#issuecomment-1861900463 , @jinevening suggestion was to 
> I think it would be better to deprecate rawdata2hdf5.

you wrote at https://github.com/Samsung/ONE/issues/12053#issuecomment-1862135678 , 
> it seems better to deprecate rawdata2hdf5.`

why do you ask?

**Comment by Seunghui98** [comment]
@seanshpark 

> why do you ask?

At first, I thought that `deprecate` only means that `rawdata2hdf5` is not used. 
So I asked if I should delete it because we don't use `rawdat2hdf5`.

but, according to your comment, 
I found out if `deprecate` means **not use and delete** together. 
Thank you for letting me know. :)

**Comment by seanshpark** [comment]
What happens when an existing command is suddenly removed from installation?
- the command will be unknown
- bash will tell the command doesn't exist
- users will get confused "was" existing `rawdat2hdf5` doesn't work

We don't want users to be come like this situation.

What procedure do you think would be good for smooth deprecation?

**Comment by Seunghui98** [comment]
@seanshpark 

Thank you for your comments. :)

> What procedure do you think would be good for smooth deprecation?

I think it would be better to display the warning message that it is better to use `one-create-quant-dataset` than `rawdata2hdf5` when using `rawdata2hdf5`.

**Comment by Seunghui98** [comment]
@jinevening 

All the PRs related to this issue were merged and It was also reflected in `ONE_User_Guide`.
If there's no problem, Could you close it?

**Comment by jinevening** [comment]
Sure. Thanks for contribution! @Seunghui98
