### ISSUE TITLE
[luci] BatchMatMul shape inference

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#12060]
One of our internal model has problem with shape inference of BatchMatMul.

> circle2circle: ERROR: Internal Exception. x_rhs and y_lhs should be same 
> compiler/luci/service/src/CircleShapeInferenceRule.cpp:486

which is 
```cxx
  if (x_rhs.known() && y_lhs.known() && not(x_rhs == y_lhs))
    INTERNAL_EXN("x_rhs and y_lhs should be same");
```
https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/batch-mat-mul shows that there is no condition check for this...

**Comment by seanshpark** [comment]
Nodes from the model:
![a831d9c6-d5ca-4bd4-b92b-ab1c4c3e3bb5](https://github.com/Samsung/ONE/assets/4616940/14b89ae8-1385-41ba-9287-b60559bf5cbc)

**Comment by jinevening** [comment]
I guess that this issue can be closed?
