### ISSUE TITLE
Compiler FE: Enable LocalResponseNormalize Op

### ISSUE THREAD

**Issue by kvochko** [Samsung/ONE#1222]
- [x]  res/TensorFlowPythonExamples (#1402)
- [x]  res/TensorFlowLiteRecipes (#1431)
- [x]  tflchef (#1403)
- [x]  tfldump (#1404)
- [x]  circledump (#1406)
- [x]  luci.IR (#1412)
- [x]  luci.Import (#1468)
- [x]  luci.Export (#1469)
- [x]  luci.logex (#1472)
- [x]  luci.Service (#1473)
- [x]  tflite2circle (#1411)
- [x]  luci.tests (#1480)

For #277

**Comment by binarman** [comment]
second draft #1331

**Comment by kvochko** [comment]
All done
