### ISSUE TITLE
CFE: ConvertNCHWToNHWCPass with CircleSplitV

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#12248]
ConvertNCHWToNHWCPass with `CircleSplitV` is called twice for internal model.
So the axis is change like 1 -> 3 -> 2 which is incorrect.

**Comment by seanshpark** [comment]
ping @jinevening

**Comment by seanshpark** [comment]
@jinevening , I've check with unit test model (#12249) 
```
circle2circle --convert_nchw_to_nhwc SplitV_001.circle SplitV_001.opt.circle
```
this has not problem. 

may have to look for other related nodes ... -_-;

**Comment by jinevening** [comment]
Our target model has multiple split_v ops sharing a single axis node. So, the value of the axis node was updated multiple times, which is wrong.

#12254 will fix the problem.

**Comment by jinevening** [comment]
#12254 was merged. Let's close this issue.
