### ISSUE TITLE
[clang-format] Upgrading version

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#12311]
We are using clang-format 8. 
Ubuntu 22.04 official repo does not support clang-format 8 installation, and 24.04 will be released on next year.

It's time to upgrade clang-format version.

### Use ubuntu official repo

Unfortunately, there is no common clang-format version for 20.04, 22.04, and 24.04.

20.04: https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=clang-format (6.0, 7, 8, 9, 10, 12)
22.04: https://packages.ubuntu.com/search?suite=jammy&searchon=names&keywords=clang-format (11, 12, 13, 14, 15)
24.04: https://packages.ubuntu.com/search?suite=noble&searchon=names&keywords=clang-format (13, 14, 15, 16, 17)

### Use llvm repo

Refer https://apt.llvm.org/

20.04: https://apt.llvm.org/focal/pool/main/l/ (9 ~ latest)
22.04: https://apt.llvm.org/jammy/pool/main/l/ (13 ~ latest)
24.04: not yet

>Packages are available for amd64, i386 (except for recent Ubuntu), s390x and arm64 (aka aarch64). This for both the stable, qualification and development branches (currently 16, 17 and 18).

I prefer to use llvm repo, version 16 (stable branch). 
Please give your opinion.

**Comment by hseok-oh** [comment]
Previous discussion: https://github.com/Samsung/ONE/issues/5131 (3.9 -> 8)

**Comment by seanshpark** [comment]
> I prefer to use llvm repo, version 16

Do you mean to download executable from llvm repo? or something else?

**Comment by hseok-oh** [comment]
> > I prefer to use llvm repo, version 16
> 
> Do you mean to download executable from llvm repo? or something else?

Right. We can use llvm repo. 

example)
https://github.com/Samsung/ONE/pull/11781/files#diff-935bc253c52b1f77711f590f9ff6d5c8ce79840a1595ae28d747cdee7f27f75a

```
$ sudo apt-get install -y gnupg2 software-properties-common
$ wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
$ sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-16 main"
$ sudo apt-get update && sudo apt-get install -y clang-format-16
```

**Comment by glistening** [comment]
> Previous discussion: #5131 (3.9 -> 8)

Wow, 3 years ago.

> I prefer to use llvm repo, version 16 (stable branch).

+1

**Comment by hseok-oh** [comment]
Draft: #12332

We can select migration policy

1) Migrate all code at once 
    - Decide migration date, migrate at once
2) Migrate each directory: refer https://github.com/Samsung/ONE/pull/5223
    - Make new format file for new clang-format version
    - Add symbolic link to new format file for updated directory
    - Remove all symbolic link when all directories are updated

**Comment by glistening** [comment]
Both work for me.

**Comment by hseok-oh** [comment]
`clang-format` version is updated to 16.

@Samsung/one_compiler @Samsung/one_onert If you use format checker on your system, please install clang-format-16.
