### ISSUE TITLE
[compiler] Check upgrade to c++17

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#12455]
Let's check upgrade to c++17 turns out and deprecate using boost.

**Comment by seanshpark** [comment]
flatbuffers `Length()` is going to be deprecated and suggests to use `size()`

**Comment by seanshpark** [comment]
Ubuntu 18.04 link error when using `std::filesystem`
> undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
> undefined reference to `std::filesystem::create_directory(std::filesystem::__cxx11::path const&)'

**Comment by glistening** [comment]
Some of compiler (especially quantizer-related things) are used for on-device compiler. And Tizen does not support c++17 yet.

**Comment by seanshpark** [comment]
done for now
