### ISSUE TITLE
[onert] failed `dynamic_cast` actions differently depends on its type

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE#12638]
While working, I faced the following `tbackend` is a null pointer though std::bad_cast try/catch is there. I knew it had to throw but it just returned null pointer.

```cpp
    try
    {
      const auto backend = pair.first;
      const auto tbackend = dynamic_cast<const backend::train::ITrainableBackend *>(backend);
      tbackend_contexts.emplace(backend, tbackend->newContext(std::move(tdata)));
    }
    catch (const std::bad_cast &)
    {
      throw std::runtime_error("ExecutorFactory: Invalid backend - TrainableExecutor does not "
                               "support non-trainble backends");
    }
```

I investigated and then found this [doc](https://en.cppreference.com/w/cpp/language/dynamic_cast).

> If the cast is successful, dynamic_cast returns a value of type target-type. 
If the cast fails and target-type is a pointer type, it returns a null pointer of that type. 
If the cast fails and target-type is a reference type, it throws an exception that matches a handler of type [std::bad_cast](https://en.cppreference.com/w/cpp/types/bad_cast).

If I understand right, we need to fix code related to `dynamic_cast`.

/cc @Samsung/one_onert

**Comment by zetwhite** [comment]
My understanding is the same as yours.
It needs to be modified.

**Comment by hseok-oh** [comment]
Below uses `dynamic_cast` as you commented

https://github.com/Samsung/ONE/blob/3e47760e65b120efa7e05d5142211b125ebde2c1/runtime/onert/backend/train/BackendContext.cc#L87-L90

**Comment by YongseopKim** [comment]
I'll fix soon.

**Comment by YongseopKim** [comment]
Done
