### ISSUE TITLE
[doc] nnfw.readthedocs.io update fail

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#12700]
Updating `nnfw.readthedocs.io` is not working.

---

I have received the following response from the readthedocs support:

> You need to check that the webhook is configured correctly. It may be that your project doesn't have an integration setup, for that see https://docs.readthedocs.io/en/stable/guides/setup/git-repo-manual.html, or maybe your project is affected by https://blog.readthedocs.com/security-update-on-incoming-webhooks/ (which you should have received an email about it).

I cannot do that as I have no access to the readthedocs interface.

_Originally posted by @pfusik in https://github.com/Samsung/ONE/issues/12689#issuecomment-1966121655_

**Comment by hseok-oh** [comment]
cc/ @lemmaa

**Comment by lemmaa** [comment]
I updated the webhook of readthedocs.com. The document now builds successfully.

<img width="542" alt="image" src="https://github.com/Samsung/ONE/assets/1185333/9a117a11-b099-4ca5-a574-fae378a40c38">
