### ISSUE TITLE
[luci] Support INT4/UINT4 weights

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#12717]
Let's support INT4 dtype weight values.

This to clear
- file format; pack or not? --> pack two to one in file
- in memory as byte per item? --> yes
- ...

**Comment by hseok-oh** [comment]
Latest onnx main branch, onnx support INT4 and UINT4 (not released version yet)

https://github.com/onnx/onnx/blob/fd744fa1ca6737b952e40fbd1efff745e566ebcc/onnx/onnx.proto#L539-L541

**Comment by jinevening** [comment]
> file format; pack or not?

+1 for packing to reduce model size. tflite packs elements using `PackInt4ValuesDensely` (<-> UnpackDenseInt4IntoInt8)

> in memory as byte per item?

In `luci`, I think both (packed or unpacked form) are okay. Unpacked format would be easier for modifying values. On the other hand, packed format would occupy less memory.

**Comment by seanshpark** [comment]
While adding S4, INT4...

how to add for S4 ?
```cxx
template <> struct TypeMapper<int8_t>
{
  static constexpr loco::DataType get() { return loco::DataType::S8; }
};
```

**Comment by jinevening** [comment]
> how to add for S4 ?

Is it possible to skip updating TypeMapper?

Perhaps we should support U4 (uint4) too. Our model developer said that it is possible to use uint4 for weights. One advantage of U4 is that S4 (quantized) can be expressed with U4 (quantized).

**Comment by seanshpark** [comment]
> Is it possible to skip updating TypeMapper?

Not sure yet... I've to add types and see how the build and execution results comes out :)

> Our model developer said that it is possible to use uint4 for weights. 

Hum... might as well support also U4 too at this time?

**Comment by jinevening** [comment]
> support also U4 too at this time?

This issue is for S4, so let's focus on that :) U4 support is just FYI.

**Comment by seanshpark** [comment]
> TypeMapper for S4

`TypeMapper` is used `create_const_node()` to access values of constant.
As `S4` uses `int8_t`, interpretation from `int8_t` to `S8` doesn't care for accessing the values.
If this becomes false, I need to check again.

**Comment by seanshpark** [comment]
draft is almost ready but cannot run value test with tflite...
tflite fails to run FC with int4 weights as it doesn't support

**Comment by seanshpark** [comment]
As decision of INT and UINT4 is not clear yet... going to support both types :)

**Comment by seanshpark** [comment]
> support both types

Need to add to circle_schema.fbs ... we need to add new item.
```
enum TensorType : byte {
...
  UINT32 = 15,
  UINT16 = 16,
  INT4 = 17,
}
```

generated as
```cxx
enum TensorType : int8_t {
  TensorType_FLOAT32 = 0,
  TensorType_FLOAT16 = 1,
...
  TensorType_INT4 = 17,
  TensorType_MIN = TensorType_FLOAT32,
  TensorType_MAX = TensorType_INT4
};
```

**Comment by jinevening** [comment]
+1 for -1? Because we are adding circle-specific opcodes in the negative direction.

**Comment by seanshpark** [comment]
As `mio-circle08` is not release to official version, I'll add `UINT4` to this one.
- adding `mio-circle09` is to laborious -_-;

**Comment by seanshpark** [comment]
known changes are all landed
