### ISSUE TITLE
[luci-interpereter] Support hybrid U4 FC kernel

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#12804]
## What

Let's support hybrid U4 FC kernel (input fp32, weights u4, bias fp32, output fp32).

## Why

Similar to #12767 , we can use `circle-interpreter` for end-to-end test of UINT4 models. For that, we need to introduce a kernel for hybrid U4 FC in `luci-interpreter`.

**Comment by SlavikMIPT** [comment]
Closed with #12811
