### ISSUE TITLE
[one-optimize] Fuse Mul-Div

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#12841]
## What

Let's fuse `Mul -> Div` into `Mul`

![image](https://github.com/Samsung/ONE/assets/5449554/4bfbda42-7c53-4e51-823b-2943f329af9e)

## Why

`EfficientDet` model has the pattern.

**Comment by seanshpark** [comment]
I'll work on this for fast request :)

**Comment by seanshpark** [comment]
existing `FuseMulWithDivPass` a bit different one that is
```
Y = Div(dc, Mul(X, mc))
  = Div(dc',X)
```

for this issue, we have to process like
```
Y = Div(Mul(X, mc), dc)
  = Mul(X, mc')
```

**Comment by seanshpark** [comment]
done
