### ISSUE TITLE
[one-cmds] Support command schema for one-codegen

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#12886]
## What

Let's support a command schema feature for _one-codegen_.

## Why

When we write a _one-codegen_ section in the configuration file, below keys are required.

```ini
# only one backend
[one-codegen]
backend=dummyV2
command=-O onecc_048.tvn inception_v3.onecc_048.circle

# for multi-backend
[one-codegen]
backends=dummy,dummyV2
dummy=-o onecc_054.tvn inception_v3.onecc_054.circle
dummyV2=-O onecc_054.2.tvn inception_v3.onecc_054.2.circle
```

Then, _onecc_ internally calls the backend driver as if running the below commands in the bash. And, these work well.

```bash
$ ${backend}-compile ${command}
# For example, above first section will be called like below.
# dummyV2-compile -O onecc_048.tvn inception_v3.onecc_048.circle
```

But, actually, this kind of style doesn't match a bit with the styles of the other `one-cmds` tools. It would be like below if we make it get matched.

```
# command=-O onecc_048.tvn inception_v3.onecc_048.circle
[one-codegen]
output=onecc_048.tvn
input=inception_v3.onecc_048.circle
```

So, what I'm trying to achieve in this issue is to give a chance to match the style to the backend users. Moreover, it would be easier for the backend tools to collaborate with the other `one-cmds` tools later.

**Comment by mhs4670go** [comment]
## How

How to support this feature? I'm thinking of a schema file for the command. Each backend users who want to use this feature write a schema about their arguments of the backend driver. Then, _onecc_ would refer to that schema file and run the configuration file accordingly.

There are two things we need to decide - where and schema format.

### Where

There are few options.
1. Under the same directory with the driver
2. `/usr/share/one/command/`

I prefer the former.

### Format

Let's investigate and cover it in the following comments.

## Backward probability

### Running order

One concern is how to apply this feature with currently supporting keys in the _one-codegen_ section - `backend`, `command`, `backends`.

I decided to follow the steps.

1. Check if there is schema file.
4. If it exist, _onecc_ run the backend tools only according to that schema file.
5. If it doesn't exist, run the backend tools as normal.

### Configuration file spec

If a schema file is introduced, `backend` key can't be used anymore because some backend driver happen to have options named `backend` or `command`. So, for the backward compatibility, I think we need to introduce new spec for the configuration file.

The change looks like below. If `one-codegen` in the `onecc` section has string values rather than the boolean one, they are the names for the backend tools. And, only these backend tools - written in the `onecc` section - will be checked if they has a schema file for the command.

```ini
[onecc]
one-import-tf=True
one-optimize=True
one-codegen=dummy,dummyV2

[one-import-tf]
# ..
[one-optimize]
# ..

[dummy]
input=onecc_054.opt.circle
output=onecc_054.tvn

[dummyV2]
input_file=onecc_054.opt.circle
out=dummy.bin
```

**Comment by mhs4670go** [comment]
## Schema format

### Python argument parser

This method is to have backend users write a function that returns the argument parser.

```python
# /usr/share/one/command/dummy.py
def command_schema():
  parser = argparse.ArgumentParser()
    parser.add_argument(
        "-i",
        "--input",
        required=True,
        help="provide a path to .circle model.",
    )

    parser.add_argument(
        "-o",
        "--output",
        required=True,
        help="provide a path to .tvn model.",
    )

  return parser
```

Then, _onecc_ calls get the argument parser from above function and check if the keys in the configuration are valid. It is convenient but users have to write a python script who only use c++ in the tools. 

### INI

```ini
[input]
type=string
description=provide a path to .circle model.
required=True

[output]
type=string
description=provide a path to .tvn model.
required=True
```

### json or yaml

```json
{
  "input": {
    "description": "provide a path to .circle model.",
    "type": "string"
  },
  "output": {
    "description": "provide a path to .tvn model.",
    "type": "string"
  }
  "DSP_quota": {
    "type": "string"
  }
  "required": [ "DSP_quota" ]
  "positional": [ "input", "output" ]
}
```

**Comment by mhs4670go** [comment]
@ejjeong @parjong @Samsung/one_compiler Please feel free to give me an opinion for this feature.

**Comment by ejjeong** [comment]
### Question about the motivation

Just out of curiosity, may I ask why you want do it “now”? :)
I ask this because I wonder if it’s somehow related to the recent backend target expansion.

### Question about the scope

Do you target only `codegen`?
Or do you plan to expand it into e.g. `profile` and `infer`?
(If so, may I ask why? 😃)

### Question about the details

TBH I think I don't fully understand your suggestion yet 😢 

IIUC, in the scenario you suggested, there should be two schemas as below.
Also, there should be some rules that convert the option w/ schema1 into schema2.
But I failed to find the corresponding modules in the above description 😢

1. schema1 that describes “onecc cfg interface”
    * `input`
    * `output`
    * `DSP_quota` (an underscore btw `DSP` and `quota`)
    * `Otraffic` 
    * ...
2. schema2 that describes “backend cli interface”
    * no `input` (positional argument)
    * `--output`
    * `--DSP-quota` (a hyphen btw `DSP` and `quota`)
    * `-Otraffic` (single hyphen)
    * ...

It’d be helpful for me to understand what you suggest if you could provide a sample of a schema file for an "existing" onecc tool, e.g. “onecc quantize” command.
AFAIK the python `one-quantize` is responsible for MANUALLY filling such gaps between schema1 and schema2. (i.e., `onecc quantize` vs `circle-quantize`)

**Comment by mhs4670go** [comment]
@ejjeong 

> Just out of curiosity, may I ask why you want do it “now”? :)

No specific reason. As you said, I thought that it would be more convenient to support upcoming(?) target configuration feature with this command schema feature.

> Do you target only `codegen`?

I thought so in the first place. But, it would be better to think of such expansion as well when designing the detail.

> TBH I think I don't fully understand your suggestion yet

It should be only one schema that users have to make.

Let me show you the example with the case that you worried about.

```python
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('input')
parser.add_argument(
    "-o",
    required=True,
)
parser.add_argument(
    "--DSP-quota",
)
parser.add_argument(
    "-Otraffic",
    action='store_true',
)

args = parser.parse_args()
```

Then, command line can be like below.
```bash
$ python MyCommand.py -o ${OUTPUT} --DSP-quota ${QUOTA} -Otraffic ${INPUT}
```

**Comment by ejjeong** [comment]
Well, I think I'm still missing something :)
Who's responsible for converting the former into the latter? And how?

### User Input

```ini
[one-codegen]
output=onecc_048.tvn
input=inception_v3.onecc_048.circle
DSP_quota=True
Otraffic=True
```

### Expected command

```
$ python MyCommand.py -o ${OUTPUT} --DSP-quota ${QUOTA} -Otraffic ${INPUT}
```

**Comment by mhs4670go** [comment]
@ejjeong I leave the answers for the history.

> Who's responsible for converting the former (user input) into the latter (arguments)?

It is _onecc_. It converts the user inputs to the backend tool's commands according to the given command schema.

> And how?

This is a pseudo code that I'm thinking about. Accessing the `_action` attribute is a bit hack though. We can implement a custom action instead, which force users to give `action` keyword argument to the `add_argumnet` api.

```
import ArgShcemaClass # schema file

k_to_v = cfgparser.parse('llama.cfg')
parser = ArgSchemaClass.get_argparser()

command = []
for action for parser._actions:
  # action.dest -> Otraffic, DSP-qutoa, etc
  # action.option_string -> -Otraffic, --DSP-quota 
  value_from_user = k_to_v[action.dest]
  command += [action.option_string, value_from_user]

run('tv2-compile' + command)
```

> is it possible to remove all python wrappers like `one-quantize` and leave only the schema file?

Technically speaking it is possible. But, we won't. Because, AFAIK, `one-cmds` tools has been introduced for the two purpose.
1. To have a unified driver name.
2. To only expose options that we want to expose.
