### ISSUE TITLE
[luci/service] Non constant begin/size for `CircleSlice` shape inference

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#12961]
There exist some cases where begin/size is not constant for `CircleSlice` Op.
If this Op itself has it's own shape, we can reuse this shape for this case.
Let's make a fix for this.

**Comment by seanshpark** [comment]
For our internal model, `CircleSlice` unknown shape
- `circledump` shows `T(2:24) FLOAT32 (1, 1, 1) (-1, -1, -1)`
- which makes succeeding Op (`CircleConcatenation`) fail in assertion check.

**Comment by seanshpark** [comment]
We can...
1/ leave the code as-is
2/ use ownshape only if ownshape has no unknown dimension

**Comment by jinevening** [comment]
>  2/ use ownshape only if ownshape has no unknown dimension

I think this approach is a bit risky. If begin and size are not constant, that may indicate slice op's shape would be dynamic, i.e., we should set dimensions to unknown. Can I look at the target model?

**Comment by seanshpark** [comment]
> we should set dimensions to unknown. 

yes, for the model, it's dynamic shape.

> Can I look at the target model?

I've pinged you from internal repo.

**Comment by seanshpark** [comment]
With short discussion with @jinevening , when `begin`, `size` is not constant,
output would be dynamic shape. for this, current patch is needless.
