### ISSUE TITLE
[onert] Suggestion to modify unnecessary code according to pybind11 update

### ISSUE THREAD

**Issue by jaemaning** [Samsung/ONE#13115]
## Background

Recently, I discovered that a long-standing bug in pybind11 has been fixed. This fix eliminates the need to directly import Python development components (libs, headers) from various Linux environments.

Reference to the current implementation:
https://github.com/Samsung/ONE/blob/30d45e856c753501365130da9af4e55f10207e1f/runtime/onert/api/python/CMakeLists.txt#L5-L26

## Proposed Change

Given this fix, I suggest updating the code to the following:

```cmake
# Install pybind11
nnfw_find_package(Pybind11 REQUIRED)
if(NOT Pybind11_FOUND)
  message(STATUS "Build onert/python: FAILED (Pybind11 is missing)")
  return()
endif()
```

## Opinion

I would like to know your thoughts on this proposed change.

## Reference

For more details on the bug fix, please see: https://github.com/pybind/pybind11/pull/4805

**Comment by hseok-oh** [comment]
Thanks your suggestion. Then we need to use more latest pybind11 version, right?

**Comment by jaemaning** [comment]
I understand that ONE is currently using pybind v2.11.1.

https://github.com/Samsung/ONE/blob/0d7274ff3573335f5cc49462aba12b063712439a/infra/cmake/packages/Pybind11SourceConfig.cmake#L10-L11

And the above application requires the use of pybind 2.12.0 releasing version.

# Pybind11 Version 2.12.0 - bug fixes List
![image](https://github.com/Samsung/ONE/assets/96468321/f54c6a2a-e793-4e91-97b9-908fe317c795)

If it is okay to use the currently released version of pybind11 v2.12.0, I will test it.

## Reference
https://github.com/pybind/pybind11/releases

**Comment by hseok-oh** [comment]
Since we are using cmake 3.16.3 (ubuntu 20.04's default cmake version), we cannot use this feature.

**Comment by jaemaning** [comment]
oh, I didn't check the cmake version
Thanks for checking this

**Comment by hseok-oh** [comment]
@jaemaning Thank you for inform us about this. When we ready to upgrade cmake version, we can use this feature.
