### ISSUE TITLE
[onert][fine-tuning] Maxium number of trainable ops

### ISSUE THREAD

**Issue by mbencer** [Samsung/ONE#13140]
As discussed https://github.com/Samsung/ONE/pull/13094#discussion_r1632683367 we should consider if dynamic allocation of array with trainable ops is a  good idea.

Aspects to consider (at least from my point of view):
- responsibility and moment of releasing memory if a user call `nnfw_train_set_traininfo` explicitly
- responsibility and moment of releasing memory if circle+ is used
- binding such API (for example in Python)

// cc @ragmani @jyoungyun

**Comment by ragmani** [comment]
From my point of view, I think we can consider the following:
Currently, the nnfw API,
- No obligation of releasing memory
- Memory size issue of `NNFW_TRAINABLE_OPS_MAX_SIZE`
- Limited number of trainable ops (`NNFW_TRAINABLE_OPS_MAX_SIZE`)
```patch
+ /**
+  * @brief Maximum numer of trainable operations
+  */
+ #define NNFW_TRAINABLE_OPS_MAX_SIZE (256)
+
  /**
   * @brief Training information to prepare training
   * @todo  Add more training information
   *        (e.g. optimizer, loss function, ...)
   */
  typedef struct nnfw_train_info
  {
    /** Learning rate */
    float learning_rate = 0.001f;
    /** Batch size */
    uint32_t batch_size = 1;
    /** loss info */
    nnfw_loss_info loss_info{.loss = NNFW_TRAIN_LOSS_MEAN_SQUARED_ERROR,
                             .reduction_type = NNFW_TRAIN_LOSS_REDUCTION_SUM_OVER_BATCH_SIZE};
    /** optimizer type */
    NNFW_TRAIN_OPTIMIZER opt = NNFW_TRAIN_OPTIMIZER_SGD;
+
+   /** indexes of trainable operations */
+   uint32_t trainble_ops_size = 0;
+   uint32_t trainble_ops_idx[NNFW_TRAINABLE_OPS_MAX_SIZE];
  } nnfw_train_info;
```

Another option with dynamic allocation,
- Passing on responsibility of releasing memory to users or releasing memory when users call the specific API(i.g. `nnfw_train_set_traininfo`)
- Proper memory size for training ops
- No limited number of trainable ops
```patch
  /**
   * @brief Training information to prepare training
   * @todo  Add more training information
   *        (e.g. optimizer, loss function, ...)
   */
  typedef struct nnfw_train_info
  {
    /** Learning rate */
    float learning_rate = 0.001f;
    /** Batch size */
    uint32_t batch_size = 1;
    /** loss info */
    nnfw_loss_info loss_info{.loss = NNFW_TRAIN_LOSS_MEAN_SQUARED_ERROR,
                             .reduction_type = NNFW_TRAIN_LOSS_REDUCTION_SUM_OVER_BATCH_SIZE};
    /** optimizer type */
    NNFW_TRAIN_OPTIMIZER opt = NNFW_TRAIN_OPTIMIZER_SGD;
+
+   /** indexes of trainable operations */
+   uint32_t trainble_ops_size = 0;
+   uint32_t trainble_ops_idx *;
  } nnfw_train_info;
```

Or other options, but I have no idea how...
Please give your opinions or ways how to resolve this issue. @Samsung/one_onert

**Comment by ragmani** [comment]
@mbencer 
> - binding such API (for example in Python)

I didn't get exactly what things to consider. What are things to consider?

**Comment by mbencer** [comment]
> @mbencer
> 
> > * binding such API (for example in Python)
> 
> I didn't get exactly what things to consider. What are things to consider?

I haven't had here a deep analyzing, but my point is that probably in the future training API will be exposed in Python (like [inference API](https://github.com/Samsung/ONE/tree/master/runtime/onert/api/python/)). In such a case lifetime of dynamically allocated `trainble_ops_idx` will be controlled by Python Garbage Collector. Probably, it's not a problem at all (at least in a typical flow) but I wanted to emphasize that this decision can also affect binded APIs

**Comment by ragmani** [comment]
> I haven't had here a deep analyzing, but my point is that probably in the future training API will be exposed in Python (like [inference API](https://github.com/Samsung/ONE/tree/master/runtime/onert/api/python/)). In such a case lifetime of dynamically allocated trainble_ops_idx will be controlled by Python Garbage Collector. Probably, it's not a problem at all (at least in a typical flow) but I wanted to emphasize that this decision can also affect binded APIs

According to https://pybind11.readthedocs.io/en/stable/advanced/functions.html#return-value-policies, it seems that pybind11 can manage ownership and lifetime of C++ objects through _Return value policies_.  I don't know the details about it, but we can at least enable memories of C++ objects to be deleted by Python Garbage Collector or to be managed within C++ side.

**Comment by ragmani** [comment]
@mbencer 
I discussed about this issue with @Samsung/one_onert in our meeting. We decided not to use `trainble_ops_idx` array due to memory size issue and limited number of trainable ops. And, there was a consensus that dynamic allocation also is not a good solution due to managing issue of dynamic memories. There was also the idea of ​​providing an additional API to set trainable ops similar to what you initially suggested, but that way also seemed to have issues.
Anyway, after discussion, **we only provided the API as follows and postponed the decision on additional APIs** because we seemed to need more reviews.
```patch
- /**
-  * @brief Maximum numer of trainable operations
-  */
- #define NNFW_TRAINABLE_OPS_MAX_SIZE (256)
 
  /**
   * @brief Training information to prepare training
   * @todo  Add more training information
   *        (e.g. optimizer, loss function, ...)
   */
  typedef struct nnfw_train_info
  {
    /** Learning rate */
    float learning_rate = 0.001f;
    /** Batch size */
    uint32_t batch_size = 1;
    /** loss info */
    nnfw_loss_info loss_info{.loss = NNFW_TRAIN_LOSS_MEAN_SQUARED_ERROR,
                             .reduction_type = NNFW_TRAIN_LOSS_REDUCTION_SUM_OVER_BATCH_SIZE};
    /** optimizer type */
    NNFW_TRAIN_OPTIMIZER opt = NNFW_TRAIN_OPTIMIZER_SGD;

    /** number of trainable operations in reverse order*/
-   uint32_t trainble_ops_size = 0;
+   int32_t num_of_trainble_ops = 0;
-   uint32_t trainble_ops_idx[NNFW_TRAINABLE_OPS_MAX_SIZE];
  } nnfw_train_info;
```

The meaning of `num_of_trainble_ops` value as follows:
- positive values : The number of trainable operations in reverse order whithin a model graph(Sparse trainable ops are not supported yet).
- `0` : Full training(All trainable operations are trainable). 
- negative values : Error.

**Comment by jyoungyun** [comment]
Here is a meeting note. 😄 
https://github.sec.samsung.net/RS7-RuntimeNTools/secret/issues/290#issuecomment-2731006

**Comment by mbencer** [comment]
@ragmani Just for confirmation to avoid work duplication - can I take it or someone is already working on it?

**Comment by ragmani** [comment]
> @ragmani Just for confirmation to avoid work duplication - can I take it or is someone already working on it?

@mbencer Sure, no one is working on it. You can take it.

**Comment by jyoungyun** [comment]
I'm sorry for sharing the inaccessible link.
Two days ago, @Samsung/one_onert member discussed this issue. So here is the bottom line.

- conclusion
  - Add int32_t type variable for specifying how many layers it will train from the back
  - Remove trainable_ops_idx and trainable_ops_size variables from nnfw_train_info because of the memory issue
  - Not support getter and setter APIs for trainable ops (to be provided later when it is needed)

This conclusion is the same as @ragmani's [the above comment](https://github.com/Samsung/ONE/issues/13140#issuecomment-2175944483).

**Comment by mbencer** [comment]
I've prepared the PR which apply the new approach: https://github.com/Samsung/ONE/pull/13276.

Note that the new API adds some limitations: like we cannot now have now single-op model with disabled training (since `num_of_trainable_ops==0` means that all layers should be trained. It's rather not the case for a user but some changes in the tests were needed.

**Comment by ragmani** [comment]
This discussion landed as the below idea.

@Samsung/one_onert How about using zero value as a non trainable circle file?  And `-1` means that all layers should be trained.

| | before | suggestion |
|:--:|:--:|:--:|
| -N | Error (non trainable model) | Error |
| -1 | Error (non trainable model) | train whole model |
| 0 | train whole model | non trainable model |
| N | train only as many layers as described | same |

_Originally posted by @jyoungyun in https://github.com/Samsung/ONE/pull/13276#discussion_r1651799527_

**Comment by ragmani** [comment]
This discussion landed as the below idea.

@Samsung/one_onert How about using zero value as a non trainable circle file?  And `-1` means that all layers should be trained.

| | before | suggestion |
|:--:|:--:|:--:|
| -N | Error (non trainable model) | Error |
| -1 | Error (non trainable model) | train whole model |
| 0 | train whole model | non trainable model |
| N | train only as many layers as described | same |

_Originally posted by @jyoungyun in https://github.com/Samsung/ONE/pull/13276#discussion_r1651799527_

**Comment by ragmani** [comment]
If we don't have discussion anymore, I will close this issue.
