### ISSUE TITLE
[CFe] Fix ForwardTransposeOpPass with mixed 3D, 4D

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#13222]
There's a problem with mixed rank of 3 and 4 with `ForwardTransposeOpPass`

![image](https://github.com/Samsung/ONE/assets/4616940/ec94ac67-0d93-426d-adda-f3e83b922d62)

**Comment by shs-park** [comment]
Could you explain a little bit more about the captured image?
I could't understand because the `Transpose` op has same rank `3 vs 3`. (128x8x64 vs 8x128x64).
🥲

**Comment by seanshpark** [comment]
Problem is Reshape, I:3D -> O:4D. If we move Transpose forward, Transpose has to be changed from 3D to 4D and it's perm too, which depends on reshape shape, which looks quite complicated.

**Comment by seanshpark** [comment]
done
