### ISSUE TITLE
Restore onert-micro DC score to 4.0

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#13272]
After refactoring, onert-micro's DC score goes down to around 3.6.

With rough estimation, we should eliminate more than ~~100~~ 1000 duplicated lines. 

Here is a current top duplicated code at latest master :

Metric;BlockKey;Path;LineStart;LineEnd;LineCount;Token;Violation |   |   |  
-- | -- | -- | --
~~DC;1;onert-micro/onert-micro/src/execute/kernels/Add.cpp;26;67;42;415;Y~~ |   |   |  
~~DC;1;onert-micro/onert-micro/src/execute/kernels/Mul.cpp;27;67;41;415;Y~~|   |   |  
~~DC;2;onert-micro/onert-micro/src/execute/kernels/AveragePool2D.cpp;40;106;67;381;Y~~ |   |   |  
~~DC;2;onert-micro/onert-micro/src/execute/kernels/L2Pool2D.cpp;40;107;68;381;Y~~ |   |   |  
~~DC;2;onert-micro/onert-micro/src/execute/kernels/MaxPool2D.cpp;40;107;68;381;Y~~ |   |   |  
~~DC;3;onert-micro/onert-micro/src/import/kernels/BatchToSpaceND.cpp;34;88;55;334;Y~~ |   |   |  
~~DC;3;onert-micro/onert-micro/src/import/kernels/SpaceToBatchND.cpp;34;88;55;334;Y~~ |   |   |  
~~DC;4;onert-micro/onert-micro/src/execute/kernels/FloorDiv.cpp;36;95;60;316;Y~~ |   |   |  
~~DC;4;onert-micro/onert-micro/src/execute/kernels/FloorMod.cpp;36;95;60;316;Y~~ |   |   |  
~~DC;5;onert-micro/onert-micro/src/import/kernels/AveragePool2D.cpp;39;102;64;307;Y~~ |   |   |  
~~DC;5;onert-micro/onert-micro/src/import/kernels/MaxPool2D.cpp;38;101;64;307;Y~~ |   |   |  
~~DC;6;onert-micro/onert-micro/src/import/kernels/FloorDiv.cpp;34;79;46;284;Y~~ |   |   |  
~~DC;6;onert-micro/onert-micro/src/import/kernels/FloorMod.cpp;34;79;46;284;Y~~ |   |   |  
~~DC;7;onert-micro/onert-micro/src/execute/kernels/BatchToSpaceND.cpp;37;86;50;272;Y~~ |   |   |  
~~DC;7;onert-micro/onert-micro/src/execute/kernels/SpaceToBatchND.cpp;37;86;50;272;Y~~ |   |   |  
DC;8;onert-micro/onert-micro/include/pal/common/PALAveragePool2DCommon.h;33;62;30;265;Y |   |  
DC;8;onert-micro/onert-micro/include/pal/common/PALL2Pool2DCommon.h;33;61;29;265;Y |   |  
DC;8;onert-micro/onert-micro/include/pal/common/PALMaxPool2DCommon.h;32;60;29;265;Y |   |  
~~DC;9;onert-micro/onert-micro/src/import/kernels/AveragePool2D.cpp;39;88;50;265;Y~~ |   |   |  
~~DC;9;onert-micro/onert-micro/src/import/kernels/L2Pool2D.cpp;37;86;50;265;Y~~ |   |   |  
~~DC;9;onert-micro/onert-micro/src/import/kernels/MaxPool2D.cpp;38;87;50;265;Y~~ |   |   |  
~~DC;10;onert-micro/onert-micro/src/execute/kernels/Maximum.cpp;36;88;53;262;Y~~ |   |   |  
~~DC;10;onert-micro/onert-micro/src/execute/kernels/Minimum.cpp;36;88;53;262;Y~~ |   |   |  
DC;11;onert-micro/onert-micro/src/execute/kernels/Relu.cpp;38;85;48;260;Y |   |   |  
DC;11;onert-micro/onert-micro/src/execute/kernels/Relu6.cpp;38;86;49;260;Y |   |   |  
DC;12;onert-micro/onert-micro/include/pal/mcu/PALAveragePool2D.h;30;56;27;246;Y |   |   |  
DC;12;onert-micro/onert-micro/include/pal/mcu/PALMaxPool2D.h;30;56;27;246;Y |   |   |  
~~DC;13;onert-micro/onert-micro/src/import/kernels/ArgMax.cpp;34;74;41;244;Y~~ |   |   |  
~~DC;13;onert-micro/onert-micro/src/import/kernels/ArgMin.cpp;34;74;41;244;Y~~ |   |   |  
~~DC;14;onert-micro/onert-micro/src/execute/kernels/ArgMax.cpp;34;80;47;232;Y~~ |   |   |  
~~DC;14;onert-micro/onert-micro/src/execute/kernels/ArgMin.cpp;34;80;47;232;Y~~ |   |   |  
~~DC;15;onert-micro/onert-micro/src/execute/kernels/ExpandDims.cpp;37;76;40;220;Y~~ |   |   |  
~~DC;15;onert-micro/onert-micro/src/execute/kernels/Reshape.cpp;37;76;40;220;Y~~ |   |   |  
DC;16;onert-micro/onert-micro/src/execute/kernels/L2Normalize.cpp;38;82;45;202;Y |   |   |  
DC;16;onert-micro/onert-micro/src/execute/kernels/LogSoftmax.cpp;38;82;45;202;Y |   |   |  
~~DC;17;onert-micro/onert-micro/src/execute/kernels/AveragePool2D.cpp;106;127;22;200;Y~~ |   |   |  
~~DC;17;onert-micro/onert-micro/src/execute/kernels/MaxPool2D.cpp;107;127;21;200;Y~~ |   |   |  
DC;18;onert-micro/onert-micro/src/train/kernels/Conv2D.cpp;67;109;43;198;Y |   |   |

**Comment by chunseoklee** [comment]
https://github.com/Samsung/ONE/pull/13278 removes top 5 DCs and increases DC score from 3.68 to 3.72. I made a mistake in computing target # of removal lines ( not 100, it is 1000)

**Comment by chunseoklee** [comment]
FYI, applying 5 patches(13289~13293) into master produces DC score 3.8

**Comment by chunseoklee** [comment]
Applying all the PRs mentioned in this issue makes DC 4.05 !

**Comment by BalyshevArtem** [comment]
> Applying all the PRs mentioned in this issue makes DC 4.05 !

So, issue is done? :)
