### ISSUE TITLE
[Python API] How to properly build Python API

### ISSUE THREAD

**Issue by mbencer** [Samsung/ONE#13332]
1. The first problem:  it's not mentioned in the doc, but the Python API setup.py script seems to work only if runtime build via `make -f Makefile.template` command. Note that if the ONE is built via `./nnfw configure` with flag `-DBUILD_PYTHON_BINDING=ON` the folder structure (like `Product/x86_64-linux.release`) expected by [setup.py](https://github.com/Samsung/ONE/blob/670441e529bb74e71182559804b2000ad5546d8e/infra/nnfw/python/setup.py#L48-L49) does not exist.

2. Even if we use `make -f Makefile.template` approach, the hardcoded path is no not valid. Fixed in https://github.com/Samsung/ONE/pull/13330.
3. Even if the problem from point 2 is resolved, I still have a problem with undefined symbol:
```
    from nnfwapi.libnnfw_api_pybind import *
  File "/home/m.bencer/.venvs/npu/lib/python3.8/site-packages/nnfwapi/__init__.py", line 2, in <module>
    from . import libnnfw_api_pybind
  File "/home/m.bencer/.venvs/npu/lib/python3.8/site-packages/nnfwapi/libnnfw_api_pybind.py", line 11, in <module>
    from .x86_64 import libnnfw_api_pybind
ImportError: /home/m.bencer/.venvs/npu/lib/python3.8/site-packages/nnfwapi/x86_64/libnnfw_api_pybind.so: undefined symbol: _ZN12NNFW_SESSIONC1EPKcS1_S1_
``` 
Steps to reproduce:
1. checkout version from https://github.com/Samsung/ONE/pull/13330
2. Build runtime via `BUILD_TYPE=release make -f Makefile.template` command.
3. Build API wheel via `python3 setup.py sdist bdist_wheel` command.
4. Install wheel via `pip install dist/nnfwapi-0.1.0-py3-none-any.whl`
5. Try to call `from nnfwapi.libnnfw_api_pybind import *` in Python

**Comment by jiwaszki** [comment]
@mbencer these PRs: https://github.com/Samsung/ONE/pull/13435 and https://github.com/Samsung/ONE/pull/13468 should resolve your issues. Feel free to check it out!

**Comment by mbencer** [comment]
Confirmed that it works for me ;) Tested on clear environment with `--plat-name manylinux_2_35_x86_64` on `Python 3.10.14`.
