### ISSUE TITLE
CFE: Fuse Mul+Add+FC to FC

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#13411]
We have a model with Mul + Add + FullConnected, that can be fused to single FullyConnected.

![image](https://github.com/user-attachments/assets/b53600b4-b94a-4a9a-874e-6c5288eaa828)

**Comment by seanshpark** [comment]
`tensorflow/compiler/mlir/lite/transforms/optimize.cc` comment to refer

```
// FC(Add(lhs, rhs), filter, bias)
// .. with ..
// FC(lhs, filter, FC(rhs, filter, bias))
// .. if rhs, filter, and bias are all constants.
// The second FC will be constant folded to a single vector.
```
```
// FC(Mul(lhs, rhs), filter, bias)
// .. with ..
// FC(lhs, Mul(filter, rhs), bias)
// .. if rhs, filter, and bias are all constants.
```

**Comment by seanshpark** [comment]
value test fails with `Net_Add_FullyConnected_00?` ... um?

**Comment by seanshpark** [comment]
experiment with torch `matmul`

```py
class net_AddFullyConnected(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, input):
        a = torch.add(input, addition)
        b = torch.matmul(a, weights)
        return b


class net_FullyConnectedAdd(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, input):
        a = torch.matmul(input, weights)
        ab = torch.matmul(addition, weights)
        b = torch.add(a, ab)
        return b
```

these two gives same result

**Comment by jinevening** [comment]
It seems that this transformation is not valid for general shaped added constant. It would be ok to accept only 1D constant for added constant as TF does.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/lite/transforms/optimize.cc#L1260-L1265

**Comment by seanshpark** [comment]
done
