### ISSUE TITLE
[luci/pass] PadV2 paddings incorrect values when int64

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#13531]
We have `PadV2` op with `int64` paddings, shape 4,2, with
`[[0,0], [0,0], [0,0], [0,2]]`

that is converted to `Pad` with incorrect paddings
`[[0,0], [0,0], [0,0], [0,0]]`

**Comment by seanshpark** [comment]
`bool is_NCHW(const luci::CirclePadV2 *node)` fails
```cxx
auto data = paddings->at<loco::DataType::S32>(dim * 2 + i);
```

**Comment by seanshpark** [comment]
To solve this, we can
1/ Check S64 in `is_NCHW` method
2/ Revise `CanonicalizePass` to support `PadV2` and run before `convert_nchw_to_nhwc()`

I like to go with 2/

@jinevening , any comments?

**Comment by jinevening** [comment]
> We have PadV2 op with int64 paddings, shape 4,2, with
[[0,0], [0,0], [0,0], [0,2]]
that is converted to Pad with incorrect paddings
[[0,0], [0,0], [0,0], [0,0]]

Can I ask which pass does the conversion?

**Comment by jinevening** [comment]
Running canonicalization pass before `convert_nchw_to_nhwc` looks ok to me.

>  1/ Check S64 in is_NCHW method

I think it would be better to do this too. I'll add a check for this.

**Comment by seanshpark** [comment]
> Can I ask which pass does the conversion?

It's `SubstitutePadV2ToPadPass`

**Comment by jinevening** [comment]
> It's SubstitutePadV2ToPadPass

Thanks. We should fix a bug in the pass. Could you share a model to reproduce the problem?

---

BTW, why this issue tackles multiple problems? The main issue describes the problem of SubstitutePadV2ToPadPass. I think this comment (https://github.com/Samsung/ONE/issues/13531#issuecomment-2254692577) describes another problem. Did I miss something?

**Comment by seanshpark** [comment]
> BTW, why this issue tackles multiple problems?

Well, I think it's side effect of int64 paddings :)

> Did I miss something?

I think you're understandings seems OK.

**Comment by seanshpark** [comment]
> Could you share a model to reproduce the problem?

you can reuse `PadV2_002` in https://github.com/Samsung/ONE/pull/13532 or our internal `cast_model` file.

**Comment by jinevening** [comment]
#13542 (and additionally #13575) is merged, so I think this issue can be closed?
