### ISSUE TITLE
[luci-interpreter] MirrorPad differs from tflite results.

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#13603]
MirrorPad kernel result differs from tflite results.

**Comment by jinevening** [comment]
@seanshpark Could you describe the situation a little bit more? It would be great if you can share the problematic tflite model (or recipe).

**Comment by seanshpark** [comment]
you can check with
```diff
--- a/compiler/luci-value-py-test/test.lst
+++ b/compiler/luci-value-py-test/test.lst
@@ -93,7 +93,7 @@ eval(Mean_000)
 eval(Mean_001)
 eval(Mean_U8_000)
 eval(Minimum_000)
-#eval(MirrorPad_000)
+eval(MirrorPad_000)
 eval(Mul_000)
 #eval(Mul_U8_000)
 eval(Neg_000)
```

**Comment by seanshpark** [comment]
Code from onert-micro works OK. I'll post a PR shortly.

**Comment by seanshpark** [comment]
There is some problem with `getFlatIndex()`. return value exceeds input data size.

**Comment by seanshpark** [comment]
tflite shows same problem with the test model in luci-interpreter.
maybe input, padding size is invalid.
let's just follow data from tflite unit tests.

**Comment by seanshpark** [comment]
fix done
