### ISSUE TITLE
[luci-interpreter] Conv2D integer overflow

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#13668]
## What

Let's figure out it is possible to fix int overflow issue in Conv2D kernel.

The below model (single Op) causes segmentation fault when running on luci-interpreter (on record-minmax).

![image](https://github.com/user-attachments/assets/b89aadf8-bdcb-425b-b0ad-5b3206c42fa9)

The problem was integer overflow in tflite kernel.

```
#1  0x00007ffff6cce1eb in tflite::optimized_ops::ExtractPatchIntoBufferColumn<float> (input_shape=..., w=227, h=910, b=0, kheight=3, kwidth=3, stride_width=1, stride_height=1, pad_width=0, pad_height=0, 
    in_width=1026, in_height=1026, in_depth=256, single_buffer_length=2304, buffer_id=932067, in_data=0x7fffb227a010, conv_buffer_data=0x7ffd72279010, zero_byte=0 '\000')
    at /home/hjj/ONE/externals/TENSORFLOW-2.12.1/tensorflow/lite/kernels/internal/optimized/im2col_utils.h:81
81	      memcpy(conv_buffer_data + out_offset, in_data + in_offset,
(gdb) p out_offset
$23 = -2147483392
```

`out_offset`'s dtype is `int`, and overflow occurs.

## Why

This blocks quantization of vae decoder model (`Decoder` of `AutoencoderKL` in `diffusers` package)

**Comment by seanshpark** [comment]
> tensorflow/lite/kernels/internal/optimized/im2col_utils.h:81

I'm not sure we can fix this issue.
Anyway, event if we do, can our backend handle this size?

**Comment by jinevening** [comment]
>  Anyway, even if we do, can our backend handle this size?

If you're asking if it is possible, then I can say yes. But I don't know it would be usable in terms of latency or memory usage. I'm trying to figure it out.

> I'm not sure we can fix this issue.

I agree that it would be difficult to fix the external code. Even if we try to update TF, it would be not simple because the Conv2D kernel is a legacy kernel, so TF guys would not spend their time for that code.

Instead, it would be possible to bypass the problem, e.g., use reference kernel if overflow occurs or use another optimized Conv2D kernel ...

**Comment by jinevening** [comment]
Done with #13690.
