### ISSUE TITLE
[CFe] Fix mio-circle and mio-tflite module name

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#13665]
When `mio-circle` and `mio-tflite` began to use number suffix was that,
there was a major change in schema that prevented incremental changes of module by module.

As of now, I think we can stop adding new `mio-circleXXX` and `mio-tfliteYYY` modules by schema changes.
There are many module link changes and package changes that makes laborious changes.

If there is no objections, I'd like to stop this naming change and fix to `mio-cicle08` and `mio-tflite2121`.

**Comment by seanshpark** [comment]
I'll wait for a week.

**Comment by seanshpark** [comment]
We'll go with `mio-circle08` and `mio-tflite1212` for future versions.
Maybe we can go back to `mio-circle` and `mio-tflite` without numbers.

**Comment by jinevening** [comment]
>  Maybe we can go back to mio-circle and mio-tflite without numbers.

+1 for this :)
