### ISSUE TITLE
[one-optimize] Remove unnecessary transpose Ops

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#13663]
## What

Let's remove unnecessary transpose Ops.

![image](https://github.com/user-attachments/assets/d5cce341-b3bf-414c-a064-56c296ddadf0)

Transpose->Reshape->Transpose can be replaced with a single Reshape.

There is `RemoveUnnecessaryTransposeNetPass`, so it would be possible to extend the pass.

## Why

The pattern appears in vae model (UNetMidBlock2D with add_attention = True in `diffusers` package).

**Comment by jinevening** [comment]
@zetwhite Are you interested in this task?

**Comment by zetwhite** [comment]
@jinevening 

Yes. I'm interested in this task. 
But is it in hurry? Since I'll have a vacation this week, I might do this work next Monday.

Also, May I ask the `perm` value of last the last transpose? 
In the above picture, since two `128` are in shape, it is hard to distinguish the `perm` value.

**Comment by jinevening** [comment]
>  But is it in hurry? Since I'll have a vacation this week, I might do this work next monday(8/19).

No problem :) This task doesn't have a strict deadline.

> May I ask the perm value of the last transpose?

It's (0,2,3,1). If it was (0,3,2,1), i.e., two `128` were switched, the transpose Ops would be not unnecessary.

**Comment by zetwhite** [comment]
> The pattern appears in vae model (UNetMidBlock2D with add_attention = True in diffusers package). 

The target pattern is supported, now. - (related unit test: https://github.com/Samsung/ONE/pull/14167#discussion_r1789783645) 
Can I close this issue? @jinevening

**Comment by jinevening** [comment]
Yes. Thank you.
