### ISSUE TITLE
[CI/Actions] Q) why is my fork running Actions?

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#13705]
https://github.com/seanshpark/ONE/actions

@hseok-oh , my fork repo CI seems to run PR(?)s branch.

Is this necessary? Can I disable this?

**Comment by hseok-oh** [comment]
https://github.com/orgs/community/discussions/26704

They may be triggered by push event to master branch. The simplest solution is disable github action on your repo's setting. 
To handle this issue on this repo, we need to update all workflow by adding repository checking condition (`if github.repository == 'Samsung/ONE'`) to each job.
