### ISSUE TITLE
[SSAFY] Welcome SSAFY 2024 members

### ISSUE THREAD

**Issue by shs-park** [Samsung/ONE#13721]
Welcome to those who have chosen ONE as their 2024 `SSAFY` project.
In this project, we are going to start implementing the shape inference part to support more compatibility of models.

We would like to ask for many feedbacks from ONE members.

@lemmaa,
Could you please make a team for `SSAFY_2024` members?
These are the members of our team.

- @Hanjin-Choi 
- @icodo98
- @jongwonyang
- @kyeong8139
- @pcs1265
- @qsunki

**Comment by shs-park** [comment]
cc @zetwhite
🙂

**Comment by lemmaa** [comment]
> @lemmaa,
> Could you please make a team for `SSAFY_2024` members?

@shs-park , all done! 
Now @zetwhite and you are the maintainer of the team SSAFY_2024.

@halfoffaceeyes , @jongwonyang , @kyeong8139 , @pcs1265 , @qsunki , 
Welcome to ONE projcet! 
Please check your github primary e-mail box for an invitation and join the team.

@icodo98 has already joined. Welcome!!!

**Comment by icodo98** [comment]
Hi.
I'm glad to have a chance to contribute this awesome project. Thought I'm not good at C++, I'll try my best to contribute and develop this project.

**Comment by shs-park** [comment]
@Samsung/ssafy_2024, 
If you have any questions related to ONE, no matter how trivial, feel free to create an issue or write comments.
Thank you again to join this project.
=)

**Comment by seanshpark** [comment]
`@halfoffaceeyes` doesn't seem to exist.

**Comment by Hanjin-Choi** [comment]
Hi,
I'm very happy to be a part of this project.
I changed my username from 'halfoffaceeyes' to my Korean name yesterday, but I didn't realize that this would cause mentions to stop working.
From now on, I will be using the username "Hanjin-Choi", so please keep this in mind.
Thank, you.

**Comment by Seunghui98** [comment]
Welcome, @Samsung/ssafy_2024. 😉 🎉✨

I was a member of Samsung/ssafy_2022.  
and I am currently working in the department developing the ONE project at Samsung. 
I encourage you to learn development knowledge and gain practical experience during SSDC-SSAFY project.

**Comment by shs-park** [comment]
@Samsung/ssafy_2024, @Samsung/one_compiler,

As we wrap up the final presentation today, the 2024 SSAFY project has officially come to an end.

Over the past seven weeks, you've worked really well to align with our development culture,
while addressing the new shape inference feature and the various related issues that emerged.

Your contributions have been invaluable in advancing the development of this feature.

Although the official project period has concluded, the code you’ve worked on will continue to live on as long as the ONE project exists.
We hope that this experience has also been a meaningful addition to your own software development journey.

I’m not sure where your career paths will lead you, but I wish you all the best in your future.

Thank you again for your work.

And remember, this project is always open, so feel free to contribute anytime!
=)

**Comment by shs-park** [comment]
cc @lemmaa

**Comment by lemmaa** [comment]
Thank you to everyone who participated. :)
