### ISSUE TITLE
[luci] Two shape inference visitor exist

### ISSUE THREAD

**Issue by zetwhite** [Samsung/ONE#13730]
I found out that there are two visitors for shape inference. 
1. Introduced with initial commit 
	https://github.com/Samsung/ONE/blob/dec3d680708d45bf6ae75a61226b4fb0dfa96d75/compiler/luci/service/src/CircleShapeInferenceRule.cpp#L2055-L2060

2. Introduced with this PR (https://github.com/Samsung/ONE/pull/5257) 
	https://github.com/Samsung/ONE/blob/dec3d680708d45bf6ae75a61226b4fb0dfa96d75/compiler/luci/service/include/luci/Service/CircleShapeInference.h#L38-L40 

https://github.com/Samsung/ONE/pull/5257 said that a new circle shape inference is introduced to handle dynamic shape issues. So I wondered where is a good place to work on dynamic shape-related code. 

-------------------------------

(background) 

There are 2 backgrounds on this question. 

* I have this question while working on supporting `batchmatmul` on https://github.com/Samsung/ONE/issues/13697.
* I'm thinking about how to organize the @Samsung/ssafy_2024 project well. So I'd like to understand the current code well.  
   * Knowing other compiler member's opinions about this might be helpful to plan ssafy project.

**Comment by zetwhite** [comment]
* original QnA : 
  *  https://github.com/Samsung/ONE/pull/13698#issuecomment-2298901302 
  * https://github.com/Samsung/ONE/pull/13698#issuecomment-2299825294

**Comment by seanshpark** [comment]
@zetwhite , so, your question is `So I wondered where is a good place to work on dynamic shape-related code.` ?

**Comment by seanshpark** [comment]
from https://github.com/Samsung/ONE/pull/13698#issuecomment-2299825294

---

> So I wondered that you have a plan to move this.

Can you explain more about the background how you got this question?

---

New shape inference was introduced by @llFreetimell but only with `CircleIfOut` as of now.
Frankly speaking, I didn't understand how this works from the beginning as I thought I can let @llFreetimell be in charge in shape inference...

Anyway, we can, 
1) ignore `luci::sinf::Algorithm` and work like this PR. someday we can migrate to `luci::sinf`
2) implement in `luci::sinf::Algorithm`
3) remove `luci::sinf::Algorithm`
4) wait for " return of @llFreetimell " and make him lead this... I think this would be too late for our model support.

**Comment by seanshpark** [comment]
> So I wondered where is a good place to work on dynamic shape-related code. ?

I assume;

1) from `compiler/luci/service/src/Nodes/CircleIfOut.cpp` , 
2) from @llFreetimell 's intention

seems like files in `compiler/luci/service/src/Nodes/` for each Ops.

**Comment by zetwhite** [comment]
> @zetwhite , so, your question is So I wondered where is a good place to work on dynamic shape-related code. ? 

Yes. You're right.

**Comment by seanshpark** [comment]
@zetwhite , about unknown shape inference validation, I'm not sure existing tools can do what is expected by you.
That is, (1) what is the input? (2) what is the expected output? (3) validation test is passing as expected?

**Comment by zetwhite** [comment]
> about unknown shape inference validation, I'm not sure existing tools can do what is expected by you. 

Ah, Thank you for letting me know. 

I guess you may talk about that unknown-shapeed tests are excluded now. (e.g. https://github.com/Samsung/ONE/pull/5611) because `TestDataGenerator` can create only a defined(known) shape.  Did I understand correctly?

**Comment by jinevening** [comment]
@zetwhite I guess that @llFreetimell introduced a new visitor because he thought it would be easier to write new shape inference rules from scratch, rather than modify existing ones.

I think it would be easier to review implementation from scratch, than modification (please tell me if not :) ). I'll move a visitor to sinf::Algorithm.

**Comment by seanshpark** [comment]
> because TestDataGenerator can create only a defined(known) shape. Did I understand correctly?

`TestDataGenerator` is to generate sample, random data for that model, for value testing.
As I know data should be fixed size. It's a real world thing. I can't imagine some data having (virtual) unknown size.

What I was thinking is to validate shape inference logic is working as expected.
- There is a Op in a model with unknown shape. What is the expected output shape?
- There is a Op in a model with known shape. What is the expected output shape?
- How are we going to check result output shape is expected shape?

I'm not sure we can achieve this from a little adjustment of existing tools or need to build from scratch.

**Comment by llFreetimell** [comment]
@seanshpark @zetwhite @jinevening
Sorry for late response, I didn't notice that the github notification is not sent to my personal e-mail account... 
Since this issue has really long story, I wrote this comment briefly as much as possible.
If you have something not understanding or questions, please feel free to comment :)

---

### History

There were two main reason for refactoring shape/dtype inference of `luci` as written in #4726.
  - [Step 1] Duplicated shape information between `loco::AnnotatedItem` and `luci`
    - #4796
  - [Step 2] Supporting dynamic shape
    - #4372 (Mainly for supporting `shape_signature`)
    - ⭐  #5501 (Mainly for refactoring)
    - #5683 (Main for inference logic implementation)

And current status is only #5683 is not finished.

### Q&A

- Why not implemented in existing `CircleShapeInferenceRule` ?
  - I thought that refactoring was good option for supporing new features and adopting architectural decisions
- Why `CIrcleShapeInferencePass` is not used?
  - I had two choices
    - Moving all the inference logics to `CircleShapeInferfencePass` and deprecate `CircleShapeInferenceRule`
    - Wait until all the inference logics are implemented, and the enable them at once
  - I choosed second option because
    - There were release schedules and it seems little bit hard to test all of them before the deadline
    - Wanted to migrate with new inference logic supporting dynamic shape
    - Not urgent because models with dynamic shape were really rare
- Where is a good place to work on dynamic shape-related code?
  - Just for my preferences,
    - 😄  ignore luci::sinf::Algorithm and work like this PR. someday we can migrate to luci::sinf
    - 😄  implement in luci::sinf::Algorithm
    - 😭  remove luci::sinf::Algorithm
    - 😀 wait for " return of @llFreetimell " and make him lead this... I think this would be too late for our model support.
  - **However, I will fully respect any decision from here :) Because I am not well aware of current circumstances...**

**Comment by seanshpark** [comment]
> ... between loco::AnnotatedItem and luci

Ah,,,, we used `loco::AnnotatedItem` to store shape... 
Now `CircleNode` itself has shape info :)

**Comment by jinevening** [comment]
> 😄 implement in luci::sinf::Algorithm

@llFreetimell Glad to see you here :) As mentioned in https://github.com/Samsung/ONE/issues/13730#issuecomment-2300311180, I'd like to go with this option. And it seems that other members gave enough 👍.

**Comment by llFreetimell** [comment]
@jinevening 

Long time to see here :)
Thank you for the decision and I am sorry that I didn't finish the works somehow the situation was :(

If there are something for me to help you, just let me know!
Reviewing, questions, anything would be fine!
(Of course, other members too :D)

**Comment by jinevening** [comment]
> So I wondered where is a good place to work on dynamic shape-related code.

It seems that this question got an answer. `sinf::Algorithm` 

Let's close this issue.
