### ISSUE TITLE
Nominating Bazhenov Vyacheslav (@SlavikMIPT) to become a ONE committer

### ISSUE THREAD

**Issue by SlavikMIPT** [Samsung/ONE#13814]
I'd like to become a ONE committer because @BalyshevArtem has left our team and we have a need to promptly merge PRs to onert-micro

I'll only merge commits related to onert-micro with one or more approvals.

Could you give an opinion? From https://github.com/Samsung/ONE/wiki/Assigned-people

@lemmaa of ONE project
@chunseoklee of ONE runtime
https://github.com/orgs/Samsung/teams/ONE

**Comment by lemmaa** [comment]
I don't think @BalyshevArtem will leave our community, but I agree that he won't be as active in open source as he used to be, at least for the time being. So I agree that we need someone to help.

Thanks to @SlavikMIPT for volunteering.

Considering his contributions, https://github.com/Samsung/ONE/pulls?q=is%3Apr+is%3Aclosed+author%3ASlavikMIPT , I think @SlavikMIPT is more than qualified.

I can't find any reason to oppose this. :)

**All community members, please voice your opinions.**

**Comment by glistening** [comment]
I agree that @SlavikMIPT deserves to be a committer.

**Comment by lemmaa** [comment]
Thanks to the votes of all members who gave a 👍, @SlavikMIPT is now a committer for the ONE project. 

The entire community will appreciate and look forward to his contributions as a committer for onert-micro.

## CONGRATULATIONS!!! 🎆🎉🎆🎉🎆🎉
