### ISSUE TITLE
Compiler FE: Enable DepthToSpace Operator

### ISSUE THREAD

**Issue by d-krylov** [Samsung/ONE#1386]
- [x] tflchef #1546
- [x] luci.IR #1557 
- [x] luci.Import #1560 
- [x] luci.Export #1593 
- [x] luci.logex #1925
- [x] luci.Service #1594 
- [x] res/TensorFlowPythonExamples #1595 
- [x] res/TensorFlowLiteRecipes #1552 
- [x] tflite2circle #1551 
- [x] luci.tests #1596
- [x] tfldump #1888 
- [x] circledump #1884 

for #1167

**Comment by binarman** [comment]
draft in #1474

**Comment by binarman** [comment]
@d-krylov
Don't forget to commit dumpers, please

**Comment by binarman** [comment]
All done, closing
