### ISSUE TITLE
[luci] Let's 

### ISSUE THREAD

**Issue by icodo98** [Samsung/ONE#13917]

**Comment by shs-park** [comment]
> to fully support dynamic shape inference

Please consider you don't have to implement "all the features".

It's better to figure out what you want to do right now (e.g., what model you want to transform..),
figure out why it doesn't work, and implement only that part.

If you try to implement all the features that are too general,
you may not be able to test them enough,
which could cause serious problems later (in the future...).

> Some discussions are already taken place.

It would be good if you add some links to the discussions.

**Comment by shs-park** [comment]
Oh, you closed it 😅

**Comment by icodo98** [comment]
> Oh, you closed it 😅

Oh, you found it 😅

I was trying to open this issue for general principal to support dynamic shape inference of non-constant such as Reshape, Pad, ..etc.

However, I realized that it depends on operations and discuss it one by one is better.
As you said,

> Please consider you don't have to implement "all the features".
