### ISSUE TITLE
[compiler] Support the dynamic shape of StridedSlice

### ISSUE THREAD

**Issue by shs-park** [Samsung/ONE#13932]
## What

Let's try to support dynamic shape inference for the StridedSlice operation.
The main goal of this work is to support models inference of dynamic shapes from #13697.

The below image is a part of some model we are looking into,
and the dimension marked with red circle can be dynamic.
like `<1x18x?x80>`.

![image](https://github.com/user-attachments/assets/a92425ef-23bf-4fac-95b6-f42e70756911)

## Conditions

The StridedSlice operation cuts a portion of a tensor along a specific axis,
and since there are many cases, the implementation can be complicated.

In this issue, let's focus only when the following conditions are satisfied.

(I removed most of below conditions, because of https://github.com/Samsung/ONE/issues/13932#issuecomment-2329169156)

- ~`begin` is a constant (static)~
- ~`end` is a constant (static)~
- ~`end`~
  - ~`end` is a constant (static), only if the input shape is all static~
  - ~`end` is a input node, if any dimension of the input is dynamic~
- `stride` is a constant and all the values are `1`
- ~the input dimension of "axis" should NOT be dynamic, others can be dynamic~

---

## (Added)

Regardless of whether the input is static or dynamic,
if either `begin` or `end` is not constant,
the `output` of `StridedSlice` should be converted to dynamic shape.

This means all the dimensions should be `?`.
i.e., if the input rank is 3, the shape of output will be `<?x?x?>`

---

Related from #13697

**Comment by shs-park** [comment]
### Note

https://github.com/Samsung/ONE/pull/13914 was the first DRAFT to support this.

**Comment by shs-park** [comment]
I'm going to try to create a similar but simpler model to replicate this scenario.
I'll share it with you when I'm done.
😅

**Comment by qsunki** [comment]
Does the "axis" in the sentence 
> the input dimension of axis is NOT dynamic

refers to the "axis" in the sentence below?
> The StridedSlice operation cuts a portion of a tensor along a specific axis

**Comment by shs-park** [comment]
> refers to the "axis" in the sentence below?

yes!

**Comment by shs-park** [comment]
아래는 좀 더 자연스럽게 다듬은 버전입니다:

I found that if the dimension marked with the red circle is dynamic in https://github.com/Samsung/ONE/issues/13932#issue-2504473423, the end of StridedSlice cannot be a constant.

The end needs to be a node with a variable, in order to properly represent the unknown full range of that dimension.

For example:

Input shape: <Nx3x3>
begin: [0, 0, 0] <3>
end: [N, 3, 2] <3>
stride: [1, 1, 1] <3>
In this case, the shape of the output should be <Nx3x2>.

However, since the end includes a variable N, it cannot be a constant. Therefore, the end should be a dynamic node.

**Comment by shs-park** [comment]
## Conclusion

Regardless of whether the input is static or dynamic,
if either `begin` or `end` is not constant,
the output should be converted to dynamic shape.
(all dimension is `?`)

**Comment by qsunki** [comment]
When I tested this case with TensorFlow Lite, 
Input shape: `<Nx3x10>`
begin: [0, 0, 0] <3>
end: [3, 3, 10] <3>
stride: [1, 1, 2] <3>

the results were as shown below. 
![화면 캡처 2024-09-04 231520](https://github.com/user-attachments/assets/f29c0abc-b2e2-4d0a-990b-066b0316f988)

Wouldn't it be okay to allow `end` to be a constant, with the appropriate inference logic?

**Comment by shs-park** [comment]
> Wouldn't it be okay to allow `end` to be a constant, with the appropriate inference logic?

You are right.
It seems that all the shape inference cases are already implemented in case of `begin` and `end` are both constant.
You don't need to modify it.

The only problem seems to be this issue - https://github.com/Samsung/ONE/issues/13932#issuecomment-2329196073.

**Comment by shs-park** [comment]
> Wouldn't it be okay to allow `end` to be a constant, with the appropriate inference logic?

Oh, I mis-understood your question.
Sorry 😭

Yes, that's right.
But it's also correct that the dimension is `?`.
The actual shape is going to be determined at runtime anyway, so it'll work fine.

It's up to you to decide what to do, but we usually follow the policy of leaving it as is in this case. 😅

**Comment by qsunki** [comment]
> ## Conclusion
> Regardless of whether the input is static or dynamic, if either `begin` or `end` is not constant, the `output` of `StridedSlice` should be converted to dynamic shape.
> 
> This means all the dimensions should be `?`. i.e., if the input rank is 3, `<?x?x?>`

IMHO, In some cases, part of the output's dimensions can be determined.

Example 1: When the dimension of begin, end, or strides is smaller than the input's rank:
Input shape: `<N1x3x3>`
begin: `[0, 0]` `<2>`
end: `[N2, N3]` `<2>`
strides: `[1, 1]` `<2>`
output: `<?x?x3>`
The third dimension can be determined.

Example 2: When a new axis is added:
new_axis_mask=`1`
Input shape: `<N1x3x3>`
begin: `[0, 0, 0]` `<3>`
end: `[N2, N3, N4]` `<3>`
strides: `[1, 1, 1]` `<3>`
output: `<1x?x?x?>`
The added dimension can be determined.

**Comment by shs-park** [comment]
> IMHO, In some cases, part of the output's dimensions can be determined.

@qsunki,

Yes, some dimensions can be calculated as you mentioned.

I think we should first implement the requirements in [To-do](https://github.com/Samsung/ONE/issues/13932#issuecomment-2329196073) and then think about this further.

FYI, in the optimization process, not only `shape inference` but also `constant folding` is performed, and in this process, the `input` and `end` could be determined as constants, so it is a possible that the current inference code is already good enough.

For these detailed parts, it would be better to first proceed with the To-do requirement, then create a model corresponding to the actual test case you've mentioned, run it, and proceed further if there is a problem.

**Comment by glistening** [comment]
> I made a test model for this. Please find the below attached file.

You can generate tflite using `tflchef` and existing recipes.

For StrideSlice,


- You can use several example recipes like [StridedSlice_000/test.recipe](https://github.com/Samsung/ONE/tree/master/res/TensorFlowLiteRecipes/StridedSlice_000/test.recipe)
- Just modify a few bytes to `-1`.
- Then run [`tflchef`](https://github.com/Samsung/ONE/blob/master/compiler/tflchef/README.md)
- Then, run [`tflite2circle`](https://github.com/Samsung/ONE/blob/master/compiler/tflite2circle/README.md)
- Check it is correct using `netron`.

**Comment by icodo98** [comment]
> * Just modify a few bytes to `-1`.

I don't understand how to modify bytes in `.recipe`

I changed 
```
operand {
  name: "ifm"
  type: FLOAT32
  shape { dim: 1 dim: 3 dim: 3 dim: 2 }
}
```

to

```
operand {
  name: "ifm"
  type: FLOAT32
  shape { dim: -1 dim: 3 dim: 3 dim: 2 }
}
```

then `tflchef-file` fails with `Error parsing text-format tflchef.ModelRecipe: 4:16: Expected integer, got: -` .

How can I make a `recipe` with dynamic shape?

**Comment by qsunki** [comment]
> How can I make a recipe with dynamic shape?
```
  shape { dim: 0 }
  shape_signature { dim: -1 }
 ```

**Comment by glistening** [comment]
> Error parsing text-format tflchef.ModelRecipe: 4:16: Expected integer, got: - .

I don't know the details of `tflchef`. [^1]

[^1]: Basically I am a runtime guy, not frontend.

Out of curiosity, I searched and found `tflchef` defined the schema as:

https://github.com/Samsung/ONE/blob/72349cca95c720b09c69bc091b1e642cfb2a0b44/compiler/tflchef/proto/tflchef.proto#L41-L47

Please notice that `uint32` for `TensorShape`, while `ShapeSignature` is defined as `int32`.

I didn't know this. My guide was based on circle schema.

circle schema says:

https://github.com/Samsung/ONE/blob/72349cca95c720b09c69bc091b1e642cfb2a0b44/nnpackage/schema/circle_schema.fbs#L224-L228

It is the reason I said _a few bytes_.

Please modify `a few lines` as @qsunki wrote.

(Or you may edit a few bytes when editing circle directly using hex editor.)

**Comment by shs-park** [comment]
Close this issue as related PRs merged
