### ISSUE TITLE
[luci/service] Negative test case of pad operation's shape inference

### ISSUE THREAD

**Issue by icodo98** [Samsung/ONE#13977]
## What

Let's discuss about negative test case of for pad operation's shape inference.

## WHY

Currently, most of the code for shape inference relies on `assert` statements to assume the state of the inputs.
However, this approach creates issues when trying to write negative test cases.

## Related
* https://github.com/Samsung/ONE/pull/13949#discussion_r1751208617
* https://github.com/Samsung/ONE/issues/13697

/cc @zetwhite @shs-park

**Comment by zetwhite** [comment]
> Currently, most of the code for shape inference relies on assert statements to assume the state of the inputs. 

IMO, `assert` implies that the caller should assure(verify) it never happens. 
Maybe, `luci/importer` could verify what `assert` assures. 

I checked `luci/importer` codes, we could add invalid graph throw logic in `{Node}::build_node(..)`. 
(But since `{Node}::build_node(..)` gets a flatbuffer object(`circle::OperatorT`), it might be hard to write test cases. ) 

https://github.com/Samsung/ONE/blob/2693ed2c29937a51d14044e0c3fd26faf0a327e1/compiler/luci/import/src/Nodes/CirclePad.cpp#L32-L44

**Comment by icodo98** [comment]
> Currently, most of the code for shape inference relies on `assert` statements to assume the state of the inputs. 

IMHO, these `assert` statements are used in shape inference, so it would be good to focus on shape inference itself.

For now, this code checks whether node is ready for shape inference.

https://github.com/Samsung/ONE/blob/d8fa13140c8fc0413f5dbc7771f87a59d4f6067c/compiler/luci/service/src/CircleShapeInference.cpp#L48-L58

Maybe we can add some validation logic here....?

**Comment by zetwhite** [comment]
> Maybe we can add some validation logic here....?

May I ask what kind of validation do you plan to add? 

I thought that validation might be different for each node. (e.g. `FC` requires weight.rank() == 2) 
I wonder how node-specific restriction can be checked here.

**Comment by icodo98** [comment]
> I thought that validation might be different for each node. (e.g. `FC` requires `weight.rank() == 2`) I wonder how node-specific restriction can be checked here.

We can use visitor pattern for this too, Like,
https://github.com/Samsung/ONE/blob/d8fa13140c8fc0413f5dbc7771f87a59d4f6067c/compiler/luci/service/src/CircleShapeInference.cpp#L79-L81

In this case, we have to implement another class like `Algorithm`.
However, if this feels too much, I'm totally fine to follow @zetwhite opinon. 

BTW, I think easiest way is to change some old `assert` into `INTERNAL_EXN`.

**Comment by shs-park** [comment]
In the beginning of `pad_shape()` function from, https://github.com/Samsung/ONE/blob/c7f31efadee54c8e913372166ce18f5e9b312a61/compiler/luci/service/src/CircleShapeInferenceHelper.cpp#L164-L179

The below is a condition that must be satisfied by any normal model.
And if this condition is not satisfied, the codes that follow will also behave in an unknown manner.

```c++
LUCI_ASSERT(n == int32_t(input_shape.rank()),
              "paddings [n, 2] should have same value of input rank");
```

So I think it's better to terminate the program by raising an exception like `INTERNEL_EXN` for this `LUCI_ASSERT` part.

/cc @Samsung/one_compiler,
Any other opinions?

**Comment by seanshpark** [comment]
> raising an exception

+1

**Comment by icodo98** [comment]
> So I think it's better to terminate the program by raising an exception like `INTERNEL_EXN` for this `LUCI_ASSERT` part.

IMHO, what do you think about changing not only the mentioned line but also the other two lines to `INTERNEL_EXN`?

```c++
LUCI_ASSERT(paddings->rank() == 2, "paddings should be rank 2"); 

LUCI_ASSERT(v == 2, "paddings should be [n, 2]");
```

**Comment by shs-park** [comment]
> what do you think about changing not only the mentioned line but also the other two lines to `INTERNEL_EXN`

## 👍

**Comment by zetwhite** [comment]
> So I think it's better to terminate the program by raising an exception like INTERNEL_EXN for this LUCI_ASSERT part. 

I am not opposed to this opinion, but I leave a question for accurate understanding. 

Using `assertion` or `exception` implies different meanings : 
	1. using `assertion` in shape inference : importer / passes assure that an invalid graph will not be created.
	2. using `exception` in shape inference : some invalid graphs can be the inputs of shape inference, So, Let's actively find invalid graphs and throw errors. 

Is it find to understand that the scope/role of shape inference changes slightly from 1 to 2?

**Comment by shs-park** [comment]
> Is it find to understand that the scope/role of shape inference changes slightly from 1 to 2?

It doesn't seem like the scope or role has changed.
However, it might be a good idea to add exception handling for values passed into the shape inference pass that could cause issues with operations within the shape inference.

For example, the padding-related variable mentioned above is directly used in calculations later in the code, and if it contains incorrect values, it could lead to memory errors or other issues.

**Comment by seanshpark** [comment]
> importer / passes assure that an invalid graph will not be created.

importer shouldn't, but passes can create invalid graphs while doing decompose, conversion and fusion.

**Comment by zetwhite** [comment]
> For example, the padding-related variable mentioned above is directly used in calculations later in the code, and if it contains incorrect values, it could lead to memory errors or other issues.

Oh I see. Thanks for explaining :)

Another +1 for throwing exception

**Comment by icodo98** [comment]
> Oh I see. Thanks for explaining :) Another +1 for throwing an exception.

I made draft with throwing an exception. #14016 
PTAL. =)

**Comment by icodo98** [comment]
Close since #14016 merged.
