### ISSUE TITLE
[onnx-tools] Show tensor shape in onnx-dump

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#13973]
`onnx-dump.py` doesn't show tensor info (shape, dtype)
let's revise this tool to show them.

**Comment by seanshpark** [comment]
when dump `model.graph`, there is `value_info` like
```
value_info {
  name: "/Add_1_output_0"
  type {
    tensor_type {
      elem_type: 1
      shape {
        dim {
          dim_value: 1
        }
        dim {
          dim_value: 2
        }
        dim {
          dim_value: 3
        }
        dim {
          dim_value: 3
        }
      }
    }
  }
}
```

**Comment by shs-park** [comment]
> when dump `model.graph`, there is `value_info` like

- shape: `dim_value`s
- dtype: `elem_type`

Is it correct..?

**Comment by seanshpark** [comment]
> Is it correct..?

Yup :)

shape: `[1,2,3,5]` (rank 4)
dtype is `elem_type = 1`
- from googling, https://github.com/onnx/onnx/blob/4b2d50334914621835cc1e8dadd4fe82b6b9876c/onnx/onnx.proto3#L483-L512
```
message TensorProto {
  enum DataType {
    UNDEFINED = 0;
    // Basic types.
    FLOAT = 1;   // float
    UINT8 = 2;   // uint8_t
    INT8 = 3;    // int8_t
    UINT16 = 4;  // uint16_t
    INT16 = 5;   // int16_t
    INT32 = 6;   // int32_t
    INT64 = 7;   // int64_t
    STRING = 8;  // string
    BOOL = 9;    // bool
```

**Comment by icodo98** [comment]
> shape: `[1,2,3,5]` (rank 4) dtype is `elem_type = 1`

May I ask whether we should consider dynamic tensor shapes in this issue?

IMHO, `dim_param` in `tensor.dim` contains this information:
* https://github.com/onnx/onnx/blob/001550a325bc5ca0d3d0b09395d820439cb3bb37/onnx/onnx.in.proto#L693-L706

**Comment by seanshpark** [comment]
> May I ask whether we should consider dynamic tensor shapes in this issue?

Maybe yes, but not now.
This issue is to solve my internal problem with ONNX model.

**Comment by seanshpark** [comment]
done
