### ISSUE TITLE
[oneapi] Proposal of new functions for input/output resizing

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#1423]
This is going to be part of Release 1.6.0 feature.

I would like to propose this function for input/output resizing.

```c
// New interface
NNFW_STATUS nnfw_set_input_tensorinfo(nnfw_session *session, uint32_t index,
                                      const nnfw_tensorinfo *tensor_info);

// We already have getters
NNFW_STATUS nnfw_input_tensorinfo(nnfw_session *session, uint32_t index,
                                  nnfw_tensorinfo *tensor_info);
NNFW_STATUS nnfw_output_tensorinfo(nnfw_session *session, uint32_t index,
                                   nnfw_tensorinfo *tensor_info);
```

- NOTE : `nnfw_apply_tensorinfo` will be deprecated, `nnfw_set_input_tensorinfo` will replace it.

These functions may have different behavior according to the session's state.

| Session State                     | `nnfw_set_input_tensorinfo`                                         | `nnfw_output_tensorinfo`  | `nnfw_input_tensorinfo` |
|-----------------------------------|---------------------------------------------------------------------|---------------------------|-------------------------|
| After `nnfw_model_load_from_file` | Applied to Model (Static Inference, done after `nnfw_prepare`)      | ~~Model's output info~~       | ~~Current input info~~      |
| After `nnfw_prepare`              | Applied to Lowered Model (Dynamic Inference, done after `nnfw_run`) | Static Inference Results  | Current input info      |
| After `nnfw_run`                  | Same with above, for the next inference                             | Dynamic Inference Results | Current input info      |

- NOTE : "Current input info" could be model's original info or changed info by `nnfw_set_input_tensorinfo`

cc: @hyunsik-yoon

**Comment by wateret** [comment]
We have `nnfw_output_tensorinfo`. Reuse it?

**Comment by hseok-oh** [comment]
One option is to not allow calling `nnfw_output_tensorinfo` before `nnfw_prepare` - because there may no usage for user.

**Comment by wateret** [comment]
@hseok-oh Thank you for your opinion.

So then we may not allow calling `nnfw_input_tensorinfo` before `nnfw_prepare` as well? I think that makes sense for consistency.

It is nice to not make the users confused. But still calling `nnfw_set_input_tensorinfo` after `nnfw_prepare` could be confusing as its result will be applide after `nnfw_run`😢 . What do you think about this?

**Comment by hseok-oh** [comment]
@wateret 

>So then we may not allow calling nnfw_input_tensorinfo before nnfw_prepare as well? I think that makes sense for consistency.

>It is nice to not make the users confused. But still calling nnfw_set_input_tensorinfo after nnfw_prepare could be confusing as its result will be applide after nnfw_run. What do you think about this?

You're right.

Then we can divide API for model input/output tensorinfo getter. (ex. `nnfw_model_input_tensorinfo`, `nnfw_model_input_tensorinfo`)

Then

- `nnfw_model_input_tensorinfo`, `nnfw_model_output_tensorinfo`:  always return model's input/output tensorinfo after `nnfw_model_load_from_file`
- `nnfw_set_input_tensorinfo`: same
- `nnfw_input_tensorinfo`: return current input tensorinfo 
  - If there is no `nnfw_set_input_tensorinfo` call, return  `nnfw_model_input_tensorinfo`
  - If `nnfw_set_input_tensorinfo` is called, return latest tensorinfo by `nnfw_set_input_tensorinfo`
- `nnfw_output_tensorinfo`: return current output tensorinfo 
  - If there is no  `nnfw_set_input_tensorinfo` call, return  `nnfw_model_output_tensorinfo` (believe compiler's shape inference)
  - If `nnfw_set_input_tensorinfo` is called, require `nnfw_prepare` (static shape inference) or `nnfw_run` (dynamic shape inference) between `nnfw_set_input_tensorinfo` and  `nnfw_output_tensorinfo`

**Comment by wateret** [comment]
`nnfw_set_input_tensorinfo` has been introduced. And the semantics of the getters will be changed too, with the @hseok-oh 's way.
