### ISSUE TITLE
[tools] model-explorer circle adaptor

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#14307]
google has provided model graph viewer https://github.com/google-ai-edge/model-explorer .
our circle model viewing can be provided with provided adapter extension https://github.com/google-ai-edge/model-explorer/wiki/6.-Develop-Adapter-Extension as separate python package through `pypi`.

current status of model viewing with netron
- netron is excellent for viewing circle models
- recent huge LLM models have problems with loading time and OOM with large number or nodes (like 10,000 or higher)

I'd like to begin an adapter for circle model, maybe in `tools` folder :)

**Comment by seanshpark** [comment]
About model explorer: https://ai.google.dev/edge/model-explorer

**Comment by seanshpark** [comment]
items to work with
- [ ] build (prototype) of circle adapter
- [ ] produce python package
- [ ] .github/workflow to upload to pypi

**Comment by seanshpark** [comment]
where to reference?
- `src/server/package/src/model_explorer/builtin_tflite_flatbuffer_adapter.py`
- `ConvertFlatbufferDirectlyToJson` method and callers

**Comment by batcheu** [comment]
I've tested my initial version of circle adapter and it seems to be working ;)
* https://github.com/batcheu/ONE/tree/draft/me_adapter/tools/model_explorer_adapter

(Hmm.... I can't attach screenshot....)

It can also show a huge model (>1GB) either but it's very slow. (seems slower than netron)

**Comment by batcheu** [comment]
<img src="https://github.com/batcheu/ONE/blob/draft/me_adapter/tools/model_explorer_adapter/res/part_add_sqrt_000.png?raw=true">

**Comment by seanshpark** [comment]
experiments doing/done
- [ ] produce an example-package
  - discover issues and solve them while building an example-package from scratch
  - [ ] simple package with unit test
  - [ ] Workflow to publish to pypi.org
- [ ] produce an example-package, source inside `/tools/example-package` folder
  - [ ] simple package with unit test
  - [ ] Workflow to publish to pypi.org

**Comment by seanshpark** [comment]
Recently, we've added `__init__.py` file in `circle_adapter` folder, but seems guide (https://github.com/google-ai-edge/model-explorer/wiki/6.-Develop-Adapter-Extension) doesn't seem to mention this file...

**Comment by seanshpark** [comment]
As first version is published and we can go with further enhancements with new issues,
I think we can close this issue :)
