### ISSUE TITLE
[onnx-tools] Don't show BrokenPipeError

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#14306]
With using pipe like
```
onnx-dump.py model.onnx | more
```
and then cancel with `q` key shows unnecessary pipe error.

```
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

Let's silent this.

**Comment by seockho-kim** [comment]
In my environment, it works well.
Is there any condition to reproduce?

**Comment by seanshpark** [comment]
> In my environment, it works well.

Good to hear this :)

> Is there any condition to reproduce?

Not sure... maybe only in my env... -_-;

**Comment by seanshpark** [comment]
Hm... now I can't reproduce this error from my several venvs...

**Comment by seanshpark** [comment]
Anyway, reopen when reproduced...
