### ISSUE TITLE
[cirlce-interpreter] Run luci-interpreter in python directly

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#14352]
## What

Let's introduce a library to run circle-interpreter in python directly.

## Why

As part of the work to make our ONE tools python friendly, running circle-interpreter in python directly is a good first step.

If a circle binary is being in the memory, it should be exported first to `.circle` file to run circle-interpreter because circle-interpreter only receive a circle file path. 

This flow has a few problems. First, even though users just want to run circle model with numpy arrays in python interpreter, the flow forces users to dump circle file. Second, then, circle-interpreter re-loads the circle file for the inference, which causes to take double memory: the circle binary in python interpreter and the one in circle-interperter.

There is [ctypes](https://docs.python.org/3.13/library/ctypes.html) python library that **allows calling c or c++ functions in DLLs or shared libraries directly**. I'm going to introduce a library in circle-interpreter that can be used in python interpreter with ctypes library.

**Comment by mhs4670go** [comment]
I've decided to use CFFI instead of ctypes. CFFI seems to show better performance.

**Comment by jinevening** [comment]
Have you considered pybind11?

**Comment by mhs4670go** [comment]
@jinevening 

> Have you considered pybind11?

Yeah. I considerd [nanobind](https://github.com/wjakob/nanobind), too. Please refer to [this draft PR](https://github.com/Samsung/ONE/pull/14363).

> nanobind seems a good option but this is not appropriate for supporting multiple python versions under the same ubuntu distribution. Users should use same python version that is used when compiling the c++ library. To cover this, compiling the library with at least two python versions is necessary. For example, if the compilation is done in ubuntu 20.04, I need to compile the library with Python 3.8 (default version) and Python 3.10 (commonly used these days).

**Comment by jinevening** [comment]
@mhs4670go  Thanks for reply.

Let me leave some details that I found (please correct me if I'm wrong).

Approach 1. pybind (or nanobind) deploys a binary module. Users can directly import module from the binary module, but the binary module is dependent on Python version. So, to support different python versions, multiple binary modules should be deployed.

Approach 2. Using cffi, it is possible to get access to c++ shared library (.so), which is not dependent on Python version. We can deploy the shared library and let users load the shared library using cffi.

We're going to follow the approach 2.
