### ISSUE TITLE
[tools/mec] Display the metadata regarding operator's inputs.

### ISSUE THREAD

**Issue by batcheu** [Samsung/ONE#14427]
In current Circle graph in model explorer, it shows inputs' name as its tensor name.
It would be more helpful if it has input name following the operator's signature.

**Comment by batcheu** [comment]
<img src="https://github.com/batcheu/ONE/blob/draft/me_adapter/tools/model_explorer_circle/res/scr_input_meta.png?raw=True"/>

**Comment by seanshpark** [comment]
:congratulations: :rocket:
