### ISSUE TITLE
[onert] Expand loading API

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#14466]
### What?

Let's expand specification of `nnfw_load_model_from_file` from loading nnpackage directory to model file and nnpackage directory.

### Why?

We introduced `nnfw_load_model_from_file` API to loading nnpackage directory and zipped file(not supported now). We have internal API to loading model file (circle, tflite, etc) for test driver, but we don't support by our official/experimental API. But supporting model file is useful for user, especially python API user. So I suggest to expand API spec to support model file loading.

**Comment by hseok-oh** [comment]
cc/ @Samsung/one_onert

**Comment by zetwhite** [comment]
Introducing `load_from_circle..` looks useful. :+1: 

For now, to run a circle file in genai-playground(sorry for the internal words), it always generates nnpkg every time. If `load_from_circle..` is introduced, it can be simplified.

**Comment by hseok-oh** [comment]
> Making `load_from_circle..` public API looks useful. 👍
> 
> For now, to run a circle file in genai-playground(sorry for the internal words), it always generates nnpkg every time. If `load_from_circle..` is introduced, it can be simplified.

I want to use `nnfw_load_model_from_file` to load model file as well as nnpackage. Because
1) Simple usage for user
2) Support/deprecate file type in `nnfw_load_model_file`, instead of introduce/deprecate API for model type
3) API name is already `from_file`

**Comment by zetwhite** [comment]
> I want to use `nnfw_load_model_from_file` to load model file as well as nnpackage

Sure! `nnfw_load_model_from_file` looks good to me :)

+) Just for note(to clearfy my intention), My original [comment](https://github.com/Samsung/ONE/issues/14466#issuecomment-2546992726) just meant that it would be nice to have an API that could receive a (circle) file. I'm not supposed to suggest a new API name for it. Sorry for the little confusion.

**Comment by hseok-oh** [comment]
>I'm not supposed to suggest a new API name for it. Sorry for the little confusion.

I also just suggested my preference, not requirement. @chunseoklee @glistening Please give any opinion about this if you have.

**Comment by chunseoklee** [comment]
I do not remember the rationale behind current implelentation. Anyway, I do not have any objection.

**Comment by hseok-oh** [comment]
API is updated.
