### ISSUE TITLE
Compiler FE: Shape inference with unknown

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#1610]
There are models that have unknown shape.
- `shape()` is nullptr or has 0 elements (rank 0) or 1 element with value 0
   - not sure 1 element with value 0 is unknown shape
- our shape inference code in _luci_ doesn't work correctly when unknown shape exist

This issue is about finding what to do and how to do.

Related issues
- #1562

**Comment by seanshpark** [comment]
[res/TensorFlowPythonModels/examples/UnknownExpandDims/__init__.py ](https://github.com/Samsung/ONE/blob/master/res/TensorFlowPythonModels/examples/UnknownExpandDims/__init__.py) is an example of code to produce `ExandDims` operator with unknown shapes.

**Comment by seanshpark** [comment]
Circumstances
- `loco::Node` records infered shape as annotation
   - we can get this by `loco::shape_known()` and `loco::shape_get()` methods
- `luci::CirclrNode` has shape as attribute and get from `rank()` and `dim()` methods
- in import stage, all `CircleNode` will have shape attribute
- circle::Tensor` object `shape()` method from schema_generated header may return nullptr
   - recently I added 'no_shape()` attribute if this is nullptr

And
- If a node shape attrubute is unknown, we shouldn't run the shape inference for that node
- we don't know if the shape is unknown or it is scalar; both are coded in same way
- there are test codes that don't set shape attribute

**Comment by seanshpark** [comment]
I've trided to apply this but shape inference related test codes failed
```diff
diff --git a/compiler/luci/service/src/CircleShapeInferenceRule.cpp b/compiler/luci/service/src/CircleShapeInferenceRule.cpp
index f3901f9..a1e1fa1 100644
--- a/compiler/luci/service/src/CircleShapeInferenceRule.cpp
+++ b/compiler/luci/service/src/CircleShapeInferenceRule.cpp
@@ -2010,11 +2010,19 @@ bool CircleShapeInferenceRule::recognize(const loco::Dialect *d) const

 bool CircleShapeInferenceRule::infer(const loco::Node *node, loco::NodeShape &shape) const
 {
+  LOGGER(l);
+
   assert(node->dialect() == CircleDialect::get());

   ShapeInferenceAlgorithm alg;
   auto circle_node = loco::must_cast<const CircleNode *>(node);
-  shape = circle_node->accept(&alg);
+
+  INFO(l) << ">> Node: " << circle_node->name();
+  if (circle_node->rank() == 0 || (circle_node->rank() == 1 && circle_node->dim(0) == 0))
+    shape = own_shape(circle_node);
+  else
+    shape = circle_node->accept(&alg);
+  INFO(l) << ">> Shape: " << own_shape(circle_node) << ", infer: " << shape.as<loco::TensorShape>();

   return true;
 }
```

**Comment by s-barannikov** [comment]
AFAIK shape `[0]` is a legacy way to denote a scalar, `[]` is the new way.
Note that both [0] and [] are **known** shapes.

**Comment by s-barannikov** [comment]
Could you consider this suggestion https://github.com/Samsung/ONE/pull/1384#issuecomment-633724292 ?
It is very simple and compatible with TFLite. I can't see any potential drawbacks...

**Comment by seanshpark** [comment]
> There are basically no unknown shapes in TFLite.

The problem comes for ExpandDims https://github.com/Samsung/ONE/issues/1562#issuecomment-634543784 where input `axis` is 1 and input is `[]`. and this doesn't make sense.

**Comment by seanshpark** [comment]
> Could you consider this suggestion #1384 (comment) ?

`[]` is not always scalar so I can't accept your suggestion.

**Comment by seanshpark** [comment]
@s-barannikov , if you are interested, or as interpreter may have to deal with this, please produce tflite file from https://github.com/Samsung/ONE/issues/1610#issuecomment-635104331 and investigate it.

**Comment by s-barannikov** [comment]
> @s-barannikov , if you are interested, or as interpreter may have to deal with this, please produce tflite file from [#1610 (comment)](https://github.com/Samsung/ONE/issues/1610#issuecomment-635104331) and investigate it.

Thanks, I've just checked it out. I admit I was wrong, there is indeed a tensor with absent shape which is unlikely to be scalar.
That is interesting case, converter could not infer even the number of dimensions. I guess we cannot infer them either without actual execution :(

**Comment by s-barannikov** [comment]
Interpreter is not prepared for this yet. I will address this issue once quantization support is implemented.

**Comment by seanshpark** [comment]
I'm not sure but our runtime is dealing with this as `Dynamic Tensor`.
TensorFlow lite has codes and comments about this.

**Comment by seanshpark** [comment]
done for now...
