### ISSUE TITLE
[luci-interpreter] Operators to enable (2)

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#1612]
Next step of #1157.

You can learn how to add operators to luci-interpreter from [previous PRs](https://github.com/Samsung/ONE/pulls?q=luci+interpreter+kernel+in%3Atitle+is%3Apr+is%3Aclosed).
(ex: Pad #1509, AveragePool2D #1218, Reshape #1099, FullyConnected #1087)

If you want to participate in operator implementation, pick an operator, put your name into the PR column and replace it with the link to the PR once you are done.

**Top priority**
Operators | Status (float) | Status (uint8) | PR
-- | :--: | :--: | --
logistic | done | done | #1810 
transpose | done | done | #1858
transpose_conv | done | done | #2033

**Long-term goal** (in order from easy to difficult)

Activations | Status (float) | Status (uint8) | PR
-- | :--: | :--: | --
elu | done | &mdash; |#2147
leaky_relu | done | done |#2160
prelu | done | done | #4039
relu | done | done |  #4150 
relu6 | done | done | #4192
tanh | done | done | #3622

Element-wise | Status (float) | Status (uint8) | PR
-- | :--: | :--: | --
logical_or | only bool | only bool | #4716 
div | done | done | #4425 
equal | done | done | #4336
floor | done | &mdash; | #4402
floor_div(floordiv) | done | &mdash; | #4421
greater | done | done | #4336
greater_equal | done | done | #4336
less | done | done | #4336
less_equal | done | done | #4336
not_equal | done | done | #4336
pow | done | &mdash; | #4361
rsqrt | done | &mdash; | #3992
sqrt | done | &mdash; | #3904 
sub(subtract) | done | done | #4464

Space transformation | Status (float) | Status (uint8) | PR
-- | :--: | :--: | --
depth_to_space | done | done | #3466 
resize_bilinear | done | done | #4163 
resize_nearestneighbor | done | done | #4106 
reverse | done | done | #3435 
slice | done | done | #3385 
space_to_depth | done | done | #3230 
split | done | done | #1742
squeeze | done | done | #3212 
strided_slice | done  | done  | #3049 

Other | Status (float) | Status (uint8) | PR
-- | :--: | :--: | --
l2_normalize | done | done |#2394
l2_pool | done | &mdash; |#2321
local_response_normalize | done | &mdash; |#2350

**Comment by s-barannikov** [comment]
@jinevening Why exactly these operators? Are they from some target models?
The thing is, adding an operator to interpreter is quite a time consuming task (at least at first, until one becomes more familiar with tensorflow lite codebase), we should choose operators to support sparely.

**Comment by struss** [comment]
I found that `deconvolution` is same with `conv2d_transpose`.
https://www.tensorflow.org/api_docs/python/tf/nn/conv2d_transpose

**Comment by jinevening** [comment]
@struss , I removed deconvolution in the table, because circle schema does not have deconv Op. Thanks.

**Comment by s-barannikov** [comment]
@jinevening 
There is no `relun` op in TFLite and I can't find in in TensorFlow. Is it OK to remove it?

**Comment by jinevening** [comment]
> There is no relun op in TFLite and I can't find in in TensorFlow. Is it OK to remove it?

Sure, thanks.

**Comment by s-barannikov** [comment]
@jinevening Everything seems to be done.

**Comment by jinevening** [comment]
> Everything seems to be done.

Great! I didn't expect that we can finish the list so soon. Thanks for the hard works from SRR and @struss . 👍 

It seems that `logical_or` was excluded from the list at some point. I'll close this issue when `logical_or` is implemented.
