### ISSUE TITLE
[onert] Directory structure of passes & converters

### ISSUE THREAD

**Issue by hyunsik-yoon** [Samsung/ONE#1616]
@glistening raised this issue at https://github.com/Samsung/ONE/pull/1559#issuecomment-634995515

> At a first glance on shape inference, I've found shape inference is under `util/shapeinf`.
> 
> Some passes are under `src/ir/pass` (e.g. `ConstantInsertionPass`, `PermutationOperationPass`).
> Some are beneath `src/compiler` (e.g. `Fp32ToFp16Converter`, `OperationValidator`).
> Shape inference is under `src/util/shapeinf`.
> 
> 1. Why shape inference is under `src/util`?
> 2. What is the difference between those under `pass` and `compiler`?

**Comment by hyunsik-yoon** [comment]
For shape inference, I wrote my answer for _shape inference_: 
https://github.com/Samsung/ONE/pull/1559#issuecomment-635063582

Shortly, my opinion for _shape inference_ is that we could have dirs as follows:
- `compiler/pass`
- `exec/pass`

**Comment by glistening** [comment]
@hyunsik-yoon Thank you for creating issue. However, I am not insisting to restructure the directory at this moment. We can work on this later after getting high-priority things done.

**Comment by hyunsik-yoon** [comment]
@glistening I will put `future` also.

**Comment by wateret** [comment]
> - `util` : general shape calculation
> - `compiler/pass` : shape inf for compilation phase
> - `exec/pass`: shape inf for exec phase

So I guess `compiler/pass` and `exec/pass` both uses the things in `util`?

**Comment by hyunsik-yoon** [comment]
> So I guess compiler/pass and exec/pass both uses the things in util?

Correct.

More specifically for shape inference, 
- `util/ShapeInference.h/cc` : general shape calculation
- `compiler/pass/StaticShapeInference.h/cc` contains compilation time shape inference for all ops
- `exec/pass/DynamicShapeInference.h/cc` contains exec time shape inference for all ops

**Comment by wateret** [comment]
Here's my personal opinion :)

> * `util` : general shape calculation

I agree.

> * `compiler/pass` : shape inf for compilation phase
> * `exec/pass`: shape inf for exec phase

I agree except the name "pass". FYI `ir/pass` is for a graph transformation pass that takes a graph and transforms it to another graph.

**Comment by hyunsik-yoon** [comment]
> I agree except the name "pass". FYI ir/pass is for a graph transformation pass that takes a graph and transforms it to another graph.

Then I will put them into 
* `compiler/StaticShapeInference.h/cc` : shape inf for compilation phase
* `exec/DynamicShapeInference.h/cc`: shape inf for exec phase

**Comment by wateret** [comment]
@hyunsik-yoon Looks good, but I thought we are having a `cc` files per operation. Then the directory could be messy.

**Comment by hyunsik-yoon** [comment]
related commits were merged.
