### ISSUE TITLE
[runtime] Tracking static analysis warning

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#1635]
This issue is to track internal static analysis warning on runtime build

**Comment by hseok-oh** [comment]
Analysis result at 6c69521 

- `tests/nnfw_api/src/RegressionTests.cc`: resource leak

**Comment by hseok-oh** [comment]
Analysis result at 1bf9f07

- Exception without catch
  - `tlite_loader.cc:218` `ANeuralNetworksExecution.cc:101`
- Resource leak
  - `RegressionTEsts.cc:26` `RegressionTEsts.cc:33`

**Comment by hseok-oh** [comment]
Analysis result at 9f71611646200181ad9f2ec672f4b34088412e5c
- svace: 1 critical, 1 major
  - `FullyConnectedLayer.cc`
  - `ShapeInference.cc`
- svace security: no warning
- coverity: 2 critical
  - `Data.h`
  - `FullyConnectedLayer.cc`

**Comment by hseok-oh** [comment]
Analysis result at d96ab686207a5a76fd72ae62c531d8c50b4d84a5: 0 criticals on svace, svace secutiry, coverity

**Comment by hseok-oh** [comment]
Analysis result at fe5ab2be0a10d5334f51bf7551eca9f43eb09c63 
- 1 major warning on svace
  - `compute/cker/include/cker/operation/Helper/PhiloxRandom.h`:264  INTEGER_OVERFLOW
   - Mark as `intentional`
- 1 major warning on coverity
  - `compute/cker/include/cker/operation/SplitV.h`:46 Useless call
- No warning on svace security

**Comment by hseok-oh** [comment]
Analysis result at 198e4f622d13703428bb00c82862edd8bd64192b

- 7 critical warnings and 1 major warning  on coverity
  - `jsoncpp.cpp` (4 criticals): ignore 
  - `OperationFactory.cc` (2 criticals): param initialize
  - acl-ex `CLReduceOperation.cpp` (2 criticals): 
  - `cpu backend `OpeationUtils.h` (1 major):
- No warning on svace and svace security

**Comment by chunseoklee** [comment]
For 1.9.0 release, we should resolve 12 major defect on latest master : 

https://code.sec.samsung.net/ahub/service/analyses/175944

**Comment by glistening** [comment]
Some defects in `View.h` caused by #3987.

**Comment by chunseoklee** [comment]
@ragmani PTAL https://code.sec.samsung.net/ahub/service/analyses/175944

**Comment by ragmani** [comment]
> https://code.sec.samsung.net/ahub/service/analyses/175944

It is false positive. The `coverity` did not recognize `using Reader<T>::at;`.

**Comment by hseok-oh** [comment]
Analysis result at 4dd6618b78dd4f0655e57ca3e203a60f41f05831

- 1 critical and 5 major warnings on svace
- 6 critical and 1 major warnings on coverity 
  - Ignore 3 critical and 1 major warnings: comes from `cpuinfo` library

**Comment by hseok-oh** [comment]
Static analysis result will be handled on release issue
