### ISSUE TITLE
Discusson on Op: Flatten

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#1674]
@binarman wrote https://github.com/Samsung/ONE/issues/1167#issuecomment-635999572

> **Flatten**
  I was looking at (https://www.tensorflow.org/api_docs/python/tf/compat/v1/layers/Flatten).
  toco converts it to reshape (already supported).
  **Should we mark it as already enabled?**

**Comment by seanshpark** [comment]
> Should we mark it as already enabled?

I think so. I've checked with https://www.tensorflow.org/api_docs/python/tf/keras/layers/Flatten and got `Reshape` in pbtxt file.

Think this maybe from https://pytorch.org/docs/master/generated/torch.flatten.html

@lemmaa , can you please check this from our customer too ?

**Comment by lemmaa** [comment]
@seanshpark , OK, let's check it out, but for customers, the Tensorflow operator is a requirement, so it doesn't seem to matter much. In my opinion, in this case it would be negligible if we didn't have to deal with the Flatten intentionally as following.

- Flatten is a special case of reshape, so we can create a dedicated kernel that can handle this more efficiently.
- For `circle2circle` pass, the Flatten should be maintained for some purpose. Of course, in this case, we will need to handle it as exceptional case in tf2tflite conversion.

This is the only case I can think of right now.

**Comment by seanshpark** [comment]
@lemma, `flatten` python API drops TensorFlow `Reshape` Op in .pb/.pbtxt
This means, we don't need to do additional task for this
- batch_normlization and fused_batch_norm is also like this

> Flatten is a special case of Reshape...
> For circle2circle pass, the Flatten should be maintained for some purpose

Do you mean like this?
- Introduce Circle IR for Flatten
- Introduce a Pass to convert Reshape that seems to be from Flatten and save as CircleFlatten
- Import Flatten as Flatten

**Comment by lemmaa** [comment]
> @lemma, flatten python API drops TensorFlow Reshape Op in .pb/.pbtxt
> This means, we don't need to do additional task for this

@seanshpark , ah, it's my misunderstanding. I understood Tensorflow to give Flatten as .pb/.pbtxt, and toco converts Flatten to Reshape to make .tflite.

> Do you mean like this?

No, I don't think so anymore. We can think of the default input format as .pb. So, can we get a .pb model with Flatten?

**Comment by seanshpark** [comment]
> So, can we get a .pb model with Flatten?

There is no `Flatten` in TF/TFlite inside but only python script API, as I know.

**Comment by seanshpark** [comment]
I think we can close this issue.
