### ISSUE TITLE
Discusson on Op: MatMul

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#1675]
@binarman wrote https://github.com/Samsung/ONE/issues/1167#issuecomment-635999572

> **MatMul**
  I suppose this is about [tf.linalg.matmul](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul) operator
  Some forms of Matmul can be converted to FullyConnected(already supported).
  But others are not. so matmul is a custom op. Example of such form is in attached archive.
  **Should we support MatMul custom op?**

**Comment by seanshpark** [comment]
@parjong, can you check this?

**Comment by parjong** [comment]
>Should we support MatMul custom op?

Unfortunately, I cannot answer this question. I also have no further information except that ``matmul`` should be supported till 21/03.

**Comment by seanshpark** [comment]
@lemmaa , can you please check our customer what they want ?

**Comment by seanshpark** [comment]
From generated tflite file from `matmul.py` by @binarman,

Operators are OK
```
[0] FULLY_CONNECTED (code: 9, version: 1)
[1] TRANSPOSE (code: 39, version: 1)
```
But we need to support COMPLEX64
```
T(0:0) COMPLEX64 (3, 3) B(6) Identity
T(0:1) FLOAT32 (3) B(1) MatMul_bias
T(0:2) COMPLEX64 (3, 3) B(5) x
    Quantization: min(0) max(255)
T(0:3) COMPLEX64 (3, 3) B(8) x/transpose
T(0:4) INT32 (2) B(7) x/transpose/perm
T(0:5) COMPLEX64 (3, 3) B(4) y
    Quantization: min(0) max(255)
T(0:6) COMPLEX64 (3, 3) B(2) y/transpose
T(0:7) INT32 (2) B(3) y/transpose/perm
```

**Comment by seanshpark** [comment]
> But others are not. so matmul is a custom op. Example of such form is in attached archive.

@binarman , I've ran the example `matmul.py` with TF2.2 and got above tflite file.
What version did you run?

**Comment by seanshpark** [comment]
```py
input_x = tf.compat.v1.placeholder(tf.float32, shape=(3, 3), name="input_x")
input_y = tf.compat.v1.placeholder(tf.float32, shape=(3, 3), name="input_y")
output = tf.linalg.matmul(input_x, input_y, transpose_a=True, transpose_b=False, name="output")
```
With this script,

From TF 1.13.1 virtual env, I got `Custom MatMul`
```
[0] CUSTOM(MatMul) (code: 32, version: 1)
```

From TF 2.2 virtual env + our `tf2tfliteV2` I got
```
[0] FULLY_CONNECTED (code: 9, version: 1)
[1] TRANSPOSE (code: 39, version: 1)
```

```
python one/build/debug/compiler/tf2tfliteV2/tf2tfliteV2.py \
--v1 \
--input_path ./generated/matmul_11.pb \
--output_path ./generated/matmul_11.tflite \
--input_arrays input_x,input_y \
--output_arrays output
```

I think it is OK when we use our `tf2tfliteV2` tool.

**Comment by seanshpark** [comment]
@binarman , @parjong , if you guys are OK,
I'll mark `MatMul` with `(FullyConnected + Transpose) done`

**Comment by seanshpark** [comment]
Anyway if we read the file as `CUSTOM(MatMul)`, if the user is using old TF versions,
we may need to convert this to `FULLY_CONNECTED` + `TRANSPOSE`

**Comment by seanshpark** [comment]
I think we can close this issue :)
