### ISSUE TITLE
Discusson on Op: MaxPoolWithArgMax

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#1676]
@binarman wrote https://github.com/Samsung/ONE/issues/1167#issuecomment-635999572

>   I was looking at [tf.nn.max_pool_with_argmax](https://www.tensorflow.org/api_docs/python/tf/nn/max_pool_with_argmax)
  This operator is converted to custom operator.
  **Should we support MaxPoolWithArgMax custom op?**

**Comment by seanshpark** [comment]
@parjong , this too.

**Comment by parjong** [comment]
The answer is same (https://github.com/Samsung/ONE/issues/1675#issuecomment-636549765).

@seanshpark Why don't you use #1675 for this kind of discussion ;-D

**Comment by seanshpark** [comment]
> @seanshpark Why don't you use #1675 for this kind of discussion ;-D

I don't know multiple operators can be talked in one issue. It might get confused.

**Comment by parjong** [comment]
Okay, I got it ;-)

**Comment by seanshpark** [comment]
@lemmaa , can you please check our customer what they want ?

**Comment by lemmaa** [comment]
@seanshpark , sorry for checking late. We need time to discuss this kind of issue with VD. Rather than individual responses, it is better to discuss after the whole has been gathered. I think we also need a time to check the whole section of development areas where our understanding is unclear, conflicting requirements, or missing. Thank you for organizing it well already. :)

**Comment by mhs4670go** [comment]
FYI, we are supporting this now as a custom OP. 
```
$ ~/ONE/build/compiler/luci/tester/luci_writetester max_pool_with_argmax.circle max_pool_with_argmax_o.circle
[INFO] Circle from 'max_pool_with_argmax.circle' to 'max_pool_with_argmax_o.circle'
$ ~/ONE/build/compiler/luci/tester/luci_readtester max_pool_with_argmax.circle 
[INFO] Circle is 'max_pool_with_argmax.circle'
```
![image](https://user-images.githubusercontent.com/24587354/83705536-32513a00-a650-11ea-94e6-0da0a85395b5.png)

**Comment by seanshpark** [comment]
Closing
