### ISSUE TITLE
Discusson on Op: Permute

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#1677]
@binarman wrote https://github.com/Samsung/ONE/issues/1167#issuecomment-635999572

>   I didn't find Permute operator in core TF, but it is present in keras: [tf.keras.layers.Permute](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Permute)
  It is converted to Transpose, that is already supported.
  **Should we mark Permute as already enabled?**

**Comment by binarman** [comment]
I also don't see permute in any of our target networks. Maybe we postpone this operator until we get better understanding of requirements?

**Comment by seanshpark** [comment]
> Maybe we postpone this operator until we get better understanding of requirements?

OK, let's postpone this too. I'll mark and close this issue.
