### ISSUE TITLE
Discusson on Op: RealDiv

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#1678]
@binarman wrote https://github.com/Samsung/ONE/issues/1167#issuecomment-635999572

>   As @kvochko mentioned in #1650 this operator is converted in ordinary div.
  **Should we mark RealDiv as already enabled?**

**Comment by seanshpark** [comment]
> Should we mark RealDiv as already enabled?

Yes, `RealDiv` is `Div` in tflite/circle. I've marked as done

**Comment by seanshpark** [comment]
@binarman , you can close this issue when you read.

**Comment by binarman** [comment]
> Yes, RealDiv is Div in tflite/circle. I've marked as done

Great, Thank you!
