### ISSUE TITLE
[onert] Modify dynamic tensor allocation not to dealloc static tensor

### ISSUE THREAD

**Issue by hyunsik-yoon** [Samsung/ONE#1708]
Let's fix the following problem:

**Model**
```
         #0 = tensor of shape []
         #1 = tensor of shape [1, 2, 3]
         #2 = add (#0, #1)
         #3 = add (#2, #2)
```

**Problematic code:**

`nnfw_run()` in the code below currently crashes because
1. all tensors in the above models are static 
2. dynamic shape inferencer tries to dealloc statically allocated tensor... then crash.

```
nnfw_load_model(...);
nnfw_prepare(_session);   // mem allocation for static tensor is done
nnfw_apply_tensorinfo(_session, 0, input0_ti); // input0_ti has shape [2, 2, 3]
nnfw_run(_session); // crash!
```

**Comment by wateret** [comment]
As discussed offline, I will take a look.

**Comment by wateret** [comment]
This is not exactly what we've talked about. I guess this can be closed? 😄  @hyunsik-yoon

**Comment by hyunsik-yoon** [comment]
@wateret you may want to create a new issue. :-)
