### ISSUE TITLE
[onert] Add Shape inference for Comparison

### ISSUE THREAD

**Issue by KimDongEon** [Samsung/ONE#1816]
I will add shape inference for Comparison

Comparison is support with six sub-operations.

must pass the dynamic test for the six sub-operations.

#1882 
- [x] Equal
- [x] NotEqual
- [x] Greater
- [x] GreaterEqual
- [x] Less
- [x] LessEqual

Signed-off-by: Dongeon Kim good.kim@samsung.com

**Comment by glistening** [comment]
@KimDongEon Could you please do for `Greater` also? They are in same IR and Layer. (`Comparison` and `CompareLayer`)?

**Comment by KimDongEon** [comment]
@glistening I will add comparisons to support  suboperation
