### ISSUE TITLE
Compiler Frontend support for YUV to RGB

### ISSUE THREAD

**Issue by AShedko** [Samsung/ONE#1833]
TF OP: https://www.tensorflow.org/api_docs/python/tf/image/yuv_to_rgb

On the topic of supporting YUV to RGB op in Luci IR:
Given that toco transforms it into `reshape(S0,FC(W,reshape(S1,x)))` how should we implement it?
Should we follow toco and transform it to a subgraph, or a custom operator?

**Comment by binarman** [comment]
+cc @seanshpark @parjong

**Comment by AShedko** [comment]
![image](https://user-images.githubusercontent.com/7196534/83622987-687fb280-a599-11ea-9f6a-5997562f8c18.png)

**Comment by seanshpark** [comment]
I think; as we support `Reshape` and `FullyConnected`, no new Op support is necessary.
1) add an TF example : `yuv_to_rgb` already exist; nothing to do
2) add a recipe `NET_YUVtoRGB` and see if it works :) if not, let's fix the bug...

**Comment by parjong** [comment]
For float model, I also agree with @seanshpark ;-)

Unfortunately, we need a **quantized** version of this operator ``).

**Comment by binarman** [comment]
@parjong
Should we add it as a circle-specific operator (like instance norm) in that case?

**Comment by seanshpark** [comment]
I think like `FullyConnected_U8_000` model

**Comment by binarman** [comment]
@parjong
Does quantized FC + reshapes satisfies your requirements or you prefer to work with fused operator?
If you don't have strict requirements yet, we can postpone this discussion for later.

**Comment by parjong** [comment]
> Should we add it as a circle-specific operator (like instance norm) in that case?

I have no idea, but I guess so.

Here is some rationale behind the above argument (that I can think of as of now).

Let's refer to the above model as ``M``.

Given a reference **float** input ``FI``,  do inference with ``M`` and say that its result is ``FO``.

Then, quantize the model with the following quantization parameters:
- input scale SI
- input zero point ZI
- output scale SO
- output zero point ZO

Do the inference with quantized model ``QM`` as follows:
```
QI = quantize{SI, ZI}(FI)
QO = infer{QM}(QI)
FQO = dequantize{SO, ZO}(QO)
```

We can use the approach that @seanshpark suggested above if ``FQO`` and ``FO`` are _reasonably(?)_ similar, but I'm not sure whether this holds ``).

**Comment by parjong** [comment]
> Does quantized FC + reshapes satisfies your requirements or you prefer to work with fused operator?
If you don't have strict requirements yet, we can postpone this discussion for later.

Frankly speaking, I have no requirement haha... That requirement comes from our customer (not from me), and https://github.com/Samsung/ONE/issues/1833#issuecomment-638105806 is the only thing that I can currently say (unfortunately).

**Comment by AShedko** [comment]
I think a subgraph approach is better, even `TF` itself does not save `YUV_to_RGB` as a distinct op, instead saving it the same way `tflite` does.

**Comment by AShedko** [comment]
All PRs are merged. Closing
