### ISSUE TITLE
Compile FE: CUSTOM(MatMul) to FC+TRANSPOSE

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#1854]
Latest (TF 2.2) version TF lite converter converts `MatMul` Op to `FULLY_CONNECTED` + `TRANSPOSE`.
But, old version drops it as `CUSTOM(MatMul)`.

We may need to add a Pass to do this if our import reads this Op.

**Comment by seanshpark** [comment]
From #1675

**Comment by binarman** [comment]
@seanshpark 
> We may need to add a Pass to do this if our import reads this Op.

Do you mean `CUSTOM(MatMul)` to `FULLY_CONNECTED` conversion?
I also want to point, that latest TF is not able to convert all variants of `MatMul` operator.
For example, we still can get custom op for `tf.linalg.matmul(x, y, transpose_a=True, transpose_b=False)`

**Comment by seanshpark** [comment]
> Do you mean CUSTOM(MatMul) to FULLY_CONNECTED conversion?

Yes.. 

> I also want to point, that latest TF is not able to convert all variants of MatMul operator.

Yes, not all but it is good if we can convert any possible cases.

**Comment by kvochko** [comment]
@seanshpark is this task still available? If you don't mind, I'd like to take a crack at it

**Comment by seanshpark** [comment]
>  is this task still available? If you don't mind, I'd like to take a crack at it

Yes! it is available :) Please go ahead!

**Comment by seanshpark** [comment]
@kvochko, finished?

**Comment by kvochko** [comment]
Yes, it's all done!

**Comment by seanshpark** [comment]
Thank you!!!
