### ISSUE TITLE
Compiler FE: Enable Rank Operator

### ISSUE THREAD

**Issue by d-krylov** [Samsung/ONE#1957]
- [x] tflchef #2297 
- [x] luci.IR #2374 
- [x] luci.Import #2374 
- [x] luci.Export   #2374
- [x] luci.logex  #2374
- [x] luci.Service   #2374
- [x] res/TensorFlowPythonExamples #2365 
- [x] res/TensorFlowLiteRecipes  #2326 
- [x] tflite2circle #2312 
- [x] luci.tests  #2374
- [x] tfldump  nothing to do
- [x] circledump nothing to do

for #1606

draft #1918

**Comment by binarman** [comment]
All done, closing
