### ISSUE TITLE
Compiler FE: Enable SegmentSum Operator

### ISSUE THREAD

**Issue by d-krylov** [Samsung/ONE#1959]
- [x] tflchef #2323 
- [x] luci.IR #2375
- [x] luci.Import #2375
- [x] luci.Export  #2375
- [x] luci.logex #2375
- [x] luci.Service  #2375
- [x] res/TensorFlowPythonExamples #2361 
- [x] res/TensorFlowLiteRecipes  #2327 #2496
- [x] tflite2circle  #2324 
- [x] luci.tests #2375
- [x] tfldump  nothing to dump
- [x] circledump  nothing to dump

for #1606

draft #1717

**Comment by binarman** [comment]
everything is merged, closing
