### ISSUE TITLE
ONE logo design contest!

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#1970]
Let's make a logo for ONE.

Anyone can participate. Please make and upload your logos in your comments!

# ~~DUE for APPLICATION : 6/22 Mon 11:00 KST~~

# DUE for VOTING : 6/23 Tue 20:00 KST

VOTING RULES

- ANYONE CAN VOTE
- ONLY **THUMB-UP** 👍 s are counted
- You can vote as many candidates as you want

**Comment by kishcs** [comment]
Any Specifications? like size, font, color etc?
or its open time being?

**Comment by hyunsik-yoon** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/63768207/84008288-99525400-a9ac-11ea-978d-38520b261f80.png)

I don't like this but I posted just to encourage people. :-)
ONE pronunciation in Korean means "circle", which is a perfect object. So I tried to draw `1` with circle but it is not very satisfying. :-)

**Comment by kishcs** [comment]
Sorry, By Mistake `Close` button got pressed, due to mouse problem. :(

**Comment by kishcs** [comment]
I have made some, simple ones though :)
Have a look.

With White Background, White ONE with Black shadow
![ONE_3_1](https://user-images.githubusercontent.com/33931003/84064260-f74c5f00-a9df-11ea-88fd-38de32dffac6.png)
With No Background, White ONE with Black shadow
![ONE_3_2](https://user-images.githubusercontent.com/33931003/84064311-07643e80-a9e0-11ea-8d2a-cbc2c433102a.png)

With Black Background, Black ONE with White shadow
![ONE_4_1](https://user-images.githubusercontent.com/33931003/84064322-0b905c00-a9e0-11ea-8734-75a3c6609a4f.png)
With No Background, Black ONE with White shadow
![ONE_4_2](https://user-images.githubusercontent.com/33931003/84064334-0e8b4c80-a9e0-11ea-94a1-aaf12bbcaa3b.png)

**Comment by kishcs** [comment]
Some more ideas like... ONE in cube (Frontview: Hexagon shape)


![ONE_cube_1](https://user-images.githubusercontent.com/33931003/84100638-efb1a800-aa29-11ea-8388-a53ef86f9bb5.png)
![ONE_cube_2_GB](https://user-images.githubusercontent.com/33931003/84100656-f50ef280-aa29-11ea-9df1-61d5b4f5ab1a.png)
![ONE_cube_2](https://user-images.githubusercontent.com/33931003/84100725-18d23880-aa2a-11ea-9745-60abe851bf56.png)

Colors can be changed to any color we prefer :)

**Comment by mhs4670go** [comment]
![logo (1)](https://user-images.githubusercontent.com/24587354/84108224-a9287180-aa5a-11ea-83ea-d76ed4f1124e.png)

**Comment by seanshpark** [comment]
![image](https://user-images.githubusercontent.com/4616940/84109850-9879fa80-aa5e-11ea-8ef5-6476f8edeea9.png)

inspired by @mhs4670go

**Comment by seanshpark** [comment]
![image](https://user-images.githubusercontent.com/4616940/84110104-2c4bc680-aa5f-11ea-9cf4-d90fd4f74e39.png)

**Comment by dayo09** [comment]
![image](https://user-images.githubusercontent.com/17171963/84111473-fbb95c00-aa61-11ea-973e-ad7bf72a0611.png)

**Comment by kishcs** [comment]
Inspired by @dayo09 

![ONE_Refl](https://user-images.githubusercontent.com/33931003/84113750-ce13e900-aa48-11ea-8a51-69476ed34c7d.png)

**Comment by kishcs** [comment]
As Barcode
![ONE_barcode](https://user-images.githubusercontent.com/33931003/84113852-f69be300-aa48-11ea-877b-47550343fead.png)

![ONE_barcode_refl](https://user-images.githubusercontent.com/33931003/84113900-087d8600-aa49-11ea-8658-7c43a98abd87.png)

**Comment by chunseoklee** [comment]
![logo](https://user-images.githubusercontent.com/4862887/84131851-1ac6e680-aa80-11ea-9917-a958f1c6111f.png)

**Comment by hyunsik-yoon** [comment]
![image](https://user-images.githubusercontent.com/63768207/84133492-36cb8780-aa82-11ea-97be-61ae399160ee.png)

== [1] 
- as a engineer (not a mathematician) I am always confused.... can we replace length 1 vector with scalar? ;-)

**Comment by sun-sharma** [comment]
![one](https://user-images.githubusercontent.com/63772873/84144883-9c197b80-aa76-11ea-9369-bb2d3ec95412.png)

**Comment by kishcs** [comment]
We should try something like [this](https://2.bp.blogspot.com/-qRz-hnwUdY4/WulXSQ6Rv4I/AAAAAAAATvQ/shk7KsphA0c3E3nUMsDVASqYaH0PhLPNwCK4BGAYYCw/s1600/GoogleAI_logo_horizontal_color_rgb.png)

**Comment by kishcs** [comment]
![ONE_new](https://user-images.githubusercontent.com/33931003/84148319-75f6da00-aa7c-11ea-92b2-4b2975253a94.png)

**Comment by wateret** [comment]
![ONE2](https://user-images.githubusercontent.com/10582184/84157299-8c655b80-aaa5-11ea-8b2b-3944bb1a7244.png)

What about PIXEL ART?

**Comment by kishcs** [comment]
![ONE_variations](https://user-images.githubusercontent.com/33931003/84232779-a2f3cd00-ab0e-11ea-9b00-bfb760accbcc.png)

**Comment by kishcs** [comment]
On top, Samsung Logo can be placed. :)

![one_tower](https://user-images.githubusercontent.com/33931003/84234638-3c70ae00-ab12-11ea-8456-6c648b74f85e.png)

**Comment by nkoong** [comment]
### Option 1
![one logo-01](https://user-images.githubusercontent.com/66906198/84591920-108c5a00-ae7d-11ea-98c1-bc5e082cb502.jpg)

### Option 2
![one logo-02](https://user-images.githubusercontent.com/66906198/84591923-14b87780-ae7d-11ea-8486-d08ebcfce9f2.jpg)

### Option 3
![one logo-03](https://user-images.githubusercontent.com/66906198/84591925-15e9a480-ae7d-11ea-9c6f-a37691c2541e.jpg)

**Comment by kishcs** [comment]
All look good.
`Option 1` is **Elegant**

**Comment by dayo09** [comment]
@nkoong I vote for `Option 2` !! :-D

**Comment by Seo-Young** [comment]
@nkoong I vote for 'Option 2' !! :D

**Comment by DeveloperSamsung** [comment]
@nkoong I vote for 'Option 2' !! :-D

**Comment by DeveloperSamsung** [comment]
@nkoong I vote for 'Option 2' !! :-D

**Comment by hyunsik-yoon** [comment]
I vote for Option 2

**Comment by kishcs** [comment]
@nkoong I vote for Option 1. :)
Can you make Option 1 as different color for O, N and E - the first letter in each line ? Curious to see how it looks 👍

**Comment by lemmaa** [comment]
### 1. basic typeb

<img width="314" alt="Screen Shot 2020-06-18 at 9 05 39 AM" src="https://user-images.githubusercontent.com/1185333/84963138-8295c500-b143-11ea-8ca3-9a542f727a8b.png">

### 2. variation-1

<img width="334" alt="Screen Shot 2020-06-18 at 9 08 42 AM" src="https://user-images.githubusercontent.com/1185333/84963341-11a2dd00-b144-11ea-88be-4c4c985d814b.png">

Inspired from cross-word puzzle. Our journey towards AI is like solving a crossword puzzle. :)

Numbers from
- 1: stands for ONE
- 5, 22: The day we moved to open source. May 22nd.

Colors from
- Pantone color of the year 2020, when ONE birth: PANTONE 19-4052 Classic Blue
- Pantone color of the year 2019, when circle birth: PANTONE 16-1546 Living Coral

**Comment by kishcs** [comment]
1.
![one_nn_small](https://user-images.githubusercontent.com/33931003/85006592-f0f47a80-b177-11ea-9183-ae664103971d.png)

2.
![one_nn_2_small](https://user-images.githubusercontent.com/33931003/85006631-fe116980-b177-11ea-9d91-f76032edfb78.png)

**Comment by lemmaa** [comment]
<img width="225" alt="Screen Shot 2020-06-19 at 8 45 47 AM" src="https://user-images.githubusercontent.com/1185333/85082284-63fa0180-b209-11ea-90e6-24b19ce7098e.png">
<img width="235" alt="Screen Shot 2020-06-19 at 8 46 23 AM" src="https://user-images.githubusercontent.com/1185333/85082291-678d8880-b209-11ea-984f-9c469471c651.png">

**Comment by sun-sharma** [comment]
![one_sunchit](https://user-images.githubusercontent.com/63772873/85279257-c2421100-b4a3-11ea-94bf-ebedaed1f896.png)

**Comment by lemmaa** [comment]
@sun-sharma , how about this variation?

<img width="315" alt="Screen Shot 2020-06-22 at 10 30 07 PM" src="https://user-images.githubusercontent.com/1185333/85293232-09e29000-b4d8-11ea-8278-e4f42ed91cd7.png">

**Comment by sun-sharma** [comment]
It looks great :D

**Comment by wateret** [comment]
# DUE for VOTING : 6/23 Tue 20:00 KST

**Comment by intom** [comment]
Option 2

**Comment by kishcs** [comment]
![one_nn_4](https://user-images.githubusercontent.com/33931003/85372093-f4f51380-b54e-11ea-875f-0d971f43b951.png)

**Comment by kishcs** [comment]
Smaller Version
![one_nn_4_resized](https://user-images.githubusercontent.com/33931003/85372343-52896000-b54f-11ea-8456-c6bd0d487dde.png)

**Comment by kishcs** [comment]
![arrow](https://user-images.githubusercontent.com/33931003/85373096-641f3780-b550-11ea-9890-dcc9f26eb1f6.png)

**Comment by lemmaa** [comment]
Create an issue for final vote https://github.com/Samsung/ONE/issues/2546
