### ISSUE TITLE
 Compiler FE: Enable ReverseSequence Operator

### ISSUE THREAD

**Issue by d-krylov** [Samsung/ONE#1973]
- [x] tflchef #2007 
- [x] luci.IR #2311 
- [x] luci.Import #2311  
- [x] luci.Export   #2311 
- [x] luci.logex  #2311 
- [x] luci.Service   #2311 
- [x] res/TensorFlowPythonExamples #2497 
- [x] res/TensorFlowLiteRecipes  #2017 
- [x] tflite2circle #2009
- [x] luci.tests  #2311 
- [x] tfldump #2019 
- [x] circledump #2018

for #1606

draft #1977

**Comment by binarman** [comment]
@d-krylov 
Add python example, please

**Comment by binarman** [comment]
All done here, closing
