### ISSUE TITLE
 Compiler FE: Enable Where Operator  

### ISSUE THREAD

**Issue by d-krylov** [Samsung/ONE#2021]
- [x] tflchef #2330 
- [x] luci.IR #2545 
- [x] luci.Import  #2545 
- [x] luci.Export   #2545 
- [x] luci.logex  #2545 
- [x] luci.Service   #2545 
- [x] res/TensorFlowPythonExamples 
- [x] res/TensorFlowLiteRecipes  #2332 #2741 
- [x] tflite2circle  #2331 
- [x] luci.tests  #2545 
- [x] tfldump  nothing to do
- [x] circledump  nothing to do

for #1606

draft 1 #2060 
draft 2 #2741

**Comment by binarman** [comment]
Everything is done, closing
