### ISSUE TITLE
[onert] add shape inference for split.

### ISSUE THREAD

**Issue by Hyunjun85** [Samsung/ONE#2056]
add shape inference interface and its tc. for split.

**Comment by Hyunjun85** [comment]
PR: https://github.com/Samsung/ONE/pull/2082

**Comment by lemmaa** [comment]
> PR: #2082

@Hyunjun85 , You would be better linking this issue to PR. It provides UX to check the progress of PR at once in this issue. :)

**Comment by Hyunjun85** [comment]
@lemmaa  Thanks for inform.

**Comment by Hyunjun85** [comment]
The PR had been merged.
