### ISSUE TITLE
Update CMake version for compiler

### ISSUE THREAD

**Issue by s-barannikov** [Samsung/ONE#207]
CMake 3.1 which we currently use is a bit old (6 years). Is it possible to upgrade the version?
Ubuntu 18.04 LST comes with 3.10.2, which should be suitable for most developers.

BTW
Ubuntu 20.04 LTS is being released tomorrow (April 23).

@Samsung/nncc

**Comment by hseok-oh** [comment]
Minimum cmake version is updated to 3.10
