### ISSUE TITLE
Download proper TensorFlow dependencies

### ISSUE THREAD

**Issue by s-barannikov** [Samsung/ONE#208]
I would like to use TensorFlow Lite kernels in luci interpreter. I do not need to build TFLite (yet), as the kernels are contained in header files. But those header files depend on eigen and gemmlowp, so I need these dependencies.

TensorFlow needs exact versions of dependencies, otherwise it will most likely fail to compile.
The dependencies are listed in `tensorflow/workspase.bzl` as direct links to archives. For example:
```bazel
    tf_http_archive(
        name = "eigen_archive",
        build_file = clean_dep("//third_party:eigen.BUILD"),
        patch_file = clean_dep("//third_party/eigen3:gpu_packet_math.patch"),
        sha256 = "65d732985b593b553c20566e1f236f48dcc626730c418aed7b2aa1d0e3f1a0af",
        strip_prefix = "eigen-4e696901f873a2347f76d931cf2f701e31e15d05",
        urls = [
            "https://storage.googleapis.com/mirror.tensorflow.org/gitlab.com/libeigen/eigen/-/archive/4e696901f873a2347f76d931cf2f701e31e15d05/eigen-4e696901f873a2347f76d931cf2f701e31e15d05.tar.gz",
            "https://gitlab.com/libeigen/eigen/-/archive/4e696901f873a2347f76d931cf2f701e31e15d05/eigen-4e696901f873a2347f76d931cf2f701e31e15d05.tar.gz",
        ],
    )
```

It seems that the archives do not correspond to any release versions of the packages, they look more like snapshots (gemmlowp does not have releases at all).

How to properly download these dependencies? I was thinking about the following ways:
- Modify `TensorFlowSourceConfig.cmake` to execute `tensorflow/lite/tools/make/download_dependencies.sh`, which will put required dependencies in `tensorflow/lite/tools/make/downloads/` directory (easiest).
- Modify `TensorFlowSourceConfig.cmake` to download dependencies manually (don't see how it is better than the previous).
- Add `TensorFlowSourceDependenciesConfig.cmake` for needed TensorFlow version and make them download dependencies into `externals/TENSORFLOW-x.y-DEPENDENCIES` (better because some users of TensorFlow sources don't need those dependencies).
- Download dependencies locally in the components which require them (will put dependencies source code into `build` directory).
- Create `eigenSourceConfig-4e696901f873a2347f76d931cf2f701e31e15d05.cmake`, `gemmlowpSourceConfig-12fed0cd7cfcd9e169bf1925bc3a7a58725fdcc3.cmake` etc (arguably the best way, but I don't like the naming).

Which way is preferred? Or is there a better way?

@parjong Please help :)

**Comment by hseok-oh** [comment]
Resolved by #825
