### ISSUE TITLE
Test for post-training quantization

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#2088]
**Updated 2020/06/24**: The test framework now tests the end-to-end quantization steps (fake quantization, record minmax, quantization).

We are implementing post-training quantization (#696). This issue is about `quantization-value-test`, which tests the quantized values of a circle model.

![image](https://user-images.githubusercontent.com/5449554/85508474-19282180-b62f-11ea-84b4-b2f6b899f00d.png)

Above figure shows the overview of `quantization-value-test`. More details about the test process is described below.

**Step 1. Fake quantization**
Run `circle2circle` with `--quantize_dequantize_weights` option.
Dump the fake-quantized model with `circle-tensordump`.
Compare the dumped model with the expected output in "expected_outputs/<model_name>/fake_quantization/<tensor_name>"
The expected output should include
 (1) values of weights (for conv, transposed_conv, depthwise_conv, fc layers)

**Step 2. Record moving avg of min and moving avg of max for activations**
Run `record-minmax` with the fake-quantized model (input data is saved in "test_inputs/<model_name>/<record_number>")
Dump the minmax-recorded model with `circle-tensordump`.
Compare the dumped model with the expected output in "expected_outputs/<model_name>/record_minmax/<tensor_name>"
The expected output should include
 (1) min/max of activations

**Step 3. Quantization**
Run `circle2circle` with `--quantize_with_minmax` option.
Dump the quantized model with `circle-tensordump`.
Compare the dumped model with the expected output in "expected_outputs/<model_name>/quantization/<tensor_name>"
The expected output should include
 (1) scale, zero point of activations
 (2) scale, zero point, values of weights
 (3) scale, values (weights) of bias

**Comment by jinevening** [comment]
**Format of the tensor file (.h5)**

We use hdf5 file (.h5) to save tensors. Hierarchy of the file is as below.

```
Group "/"
  ㄴGroup <tensor_name>
      ㄴDataset "weights"
      ㄴDataset "zero_point" Shape (1, n)
      ㄴDataset "scale" Shape (1, n)
```
`tensor_name` : name of tensor (`/` is replaced with `_`)
`weights` : weights of the tensor
`zero_point` : zero points (shape: n = 1 for layer-wise quant, n = dimension of channel for channel-wise quant)
`scale` : scale (shape: same with zero_point)

Example: tensors related to a conv layer, channel-wise quant for filters and bias

```
Group "/"
  ㄴGroup "conv_filters"
      ㄴDataset "weights"
      ㄴDataset "zero_point" Shape (1,3)
      ㄴDataset "scale" Shape (1,3)
  ㄴGroup "conv_bias"
      ㄴDataset "weights"
      ㄴDataset "zero_point" Shape (1,3)
      ㄴDataset "scale" Shape (1,3)
  ㄴGroup "conv_input"
      ㄴDataset "weights"
      ㄴDataset "zero_point" Shape (1,1)
      ㄴDataset "scale" Shape (1,1)
       ...
```

Note that `zero_point` and `scale` of "conv_input" have shape (1,1), because quantization was applied per layer.

`zero_point` and `scale` of "conv_filters" and "conv_bias" have the shape (1,3), because quantization was applied per channel.

**Comment by meejeong** [comment]
@mhs4670go , @jinevening 

I think I can suppport to make golden set's format as below.
```
Group "/"
  ㄴGroup "conv_filters"
      ㄴDataset "weights" : type(uint8, int16)
      ㄴDataset "zero_point" Shape (1,3)
      ㄴDataset "scale" Shape (1,3)
  ㄴGroup "conv_bias"
      ㄴDataset "weights" : type(int32)
  ㄴGroup "conv_input"
      ㄴDataset "zero_point" Shape (1,1)
      ㄴDataset "scale" Shape (1,1)
  ㄴGroup "conv_output"
      ㄴDataset "zero_point" Shape (1,1)
      ㄴDataset "scale" Shape (1,1)
```
Furthermore, 
I think I gonna make golden set 2 things.
- ResNet-50 (layer-wise weight quant / layer-wise act quant ) 
- MobileNet-v1 (channel-wise weight quant / layer-wise act quant ) 

If you have some questions, let me know.

**Comment by mhs4670go** [comment]
@jinevening @meejeong 
I have a few questions about hdf5 layout. 
First, why do their shapes have one more extra rank? I mean, they have (1,n) shapes not (n). Is there any reasons?

Second, `conv_filters` got a `Dataset` whose name is "weights". But so does `conv_bias`. It seems natural `conv_filters` got it. but Is it okay to name it `weights` to bias? maybe this question came up because I'm not familiar with this field yet:)

Third, IIUC, quantization will be applied to only conv-siblings(?) and activation. `conv_input` and `conv_output` are activations, aren't they? I'm just confused as of its name:)

**Comment by jinevening** [comment]
> First, why do their shapes have one more extra rank? I mean, they have (1,n) shapes not (n). Is there any reasons?

I decided the shape format, but it seems that the extra rank is unnecessary. It would be better to use just rank 1. Thanks.

> Second, ... Is it okay to name it weights to bias? maybe this question came up because I'm not familiar with this field yet:)

It's a naming issue, which is one of the hardest problems :) We can use different names according to operators, but it will be more complicated. I just used the term 'weights' in general to call the buffer of constant tensors. If you have a better name, please suggest one. I'm ok with changing the name if @meejeong agrees.

> Third, IIUC, quantization will be applied to only conv-siblings(?) and activation. conv_input and conv_output are activations, aren't they?

Yes, they are activations. Quantization will be applied to all tensors except the outputs of some special Ops such as ArgMax.

**Comment by jinevening** [comment]
Format of the golden data

The golden data is saved in `expected_output/<recipe_name>/<granularity>/<quantized_type>/<test_name>/<tensor_name>.json`.

recipe_name : a recipe saved in `res/TensorFlowLiteRecipes`
granularity : layer (channel will be supported soon)
quantized_type : uint8 (int16 will be supported soon)
test_name : fake_quantization, record_minmax, quantization

Ex: The golden data of the activation named 'ifm' in the final quantized model is saved in `expected_output/Conv2D_004/layer/uint8/quantization/ifm.json`.

```json
{
  "scale": 0.09411764705882353, 
  "zero_point": 0.0
}
```

**Comment by jinevening** [comment]
**Format of the input data (.txt)**

The input data is saved in `test_inputs/<recipe_name>/<granularity>/<quantized_type>/<record_number>.txt`.

recipe_name : a recipe saved in res/TensorFlowLiteRecipes
granularity : layer (channel will be supported soon)
quantized_type : uint8 (int16 will be supported soon)
record_number : index of input record (starting from 0)

The input data is written in the txt file. If the test model has multiple inputs, each input should be saved in different lines.

Ex: The first input data of `Conv2D_004` is saved in `test_inputs/Conv2D_004/layer/uint8/0.txt`.

Contents of 0.txt
```
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24
```

**Comment by seanshpark** [comment]
> Format of the input data (.txt)

Is this input data format only for small input data or will it be also used for real images?

**Comment by jinevening** [comment]
> Is this input data format only for small input data or will it be also used for real images?

I didn't think about testing with real images, because this is a unittest for a small model (generated from hand-written recipes).

**Comment by jinevening** [comment]
Since our quantization algorithm has changed, the test data should be updated.

Changed parts.
1. Set the lowest scale value (1e-5)) #3480
2. Use percentile when clipping recorded min/max values #3047

**Comment by jinevening** [comment]
CIRCLE OP |  Status
-- | -- 
RELU | 
ADD | 
MUL |
MEAN | 
MAX_POOL_2D | 
AVERAGE_POOL_2D | 
(LWQ) CONV_2D | O
(LWQ) TRANSPOSE_CONV |
(LWQ) DEPTHWISE_CONV |  O
PRELU |

**Comment by jinevening** [comment]
I close this PR because all targets are covered.
