### ISSUE TITLE
nnpackage_run should support model with dynamic shape

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#2112]
nnpackage_run uses model's input shapes during inference. 
To test inference model with dynamic shape, nnpackag_run should provide a way to set various input shapes before inference. This can be done by using `nnfw_apply_tensorinfo` in nnpackage_run.

**Comment by chunseoklee** [comment]
cc @hyunsik-yoon

**Comment by hyunsik-yoon** [comment]
This is done with #2290.
