### ISSUE TITLE
How to reproduce ci failure on local pc. 

### ISSUE THREAD

**Issue by Hyunjun85** [Samsung/ONE#2141]
I want to know how to reproduce some CI failure on my pc.
The CI have been trying to verify the PR multiple time and cross platform. But in my case, one of that tryings was failure.
PR: https://github.com/Samsung/ONE/pull/1944

Could you please let me know how?

**Comment by hseok-oh** [comment]
You didn't update skiplist for acl-cl and acl-neon backend.
You need arm target machine for test.

**Comment by hseok-oh** [comment]
CI passed on cpu backend, but failed on acl-cl and acl-neon backend, and interpreter.
Please update skiplist `tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl`, `tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon`, `tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl`, `tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon`, `tests/nnapi/nnapi_gtest.skip.noarch.interp`

You can test on your arm target machine (ex. odroid-xu4) by 
```
$ BACKENDS=acl_cl ./Product/out/bin/nnapi_gtest --gtest_filter=one_hot_ex_dynamic_nnfw_1
```

**Comment by Hyunjun85** [comment]
@hseok-oh  Thanks. I will prepare any arm device. 
Above failure has a relation with op's implementation. So I have fixed it and raise again.

Thanks.
