### ISSUE TITLE
Compiler FE: change linux only header

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#2166]
For #2074, we need to build `tflchef` `circlechef` `circle-verify` etc. But, they include some header file that exists only in linux(e.g. `sys/mman.h`)

Let's change this header to something compatible with Windows.

**Comment by mhs4670go** [comment]
@seanshpark Above modules includes `sys/*` headers for loading `.tflite` or `.circle`. 

How about changing the way it loads to `ONE/compiler/tflite2circle/src/TFLModel.cpp` sytle?

It comes from [here](https://google.github.io/flatbuffers/flatbuffers_guide_use_cpp.html).

**Comment by seanshpark** [comment]
OK, let's try not to use `sys/mman.h` file
