### ISSUE TITLE
[luci] exports wrong output

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#2222]
I tried to optimize in-house model. But, there is an error that all the custom ops in the graph are replaced with the same custom ops.

### Before
![image](https://user-images.githubusercontent.com/24587354/84486331-3debd300-acd8-11ea-9596-655f3e01647d.png)

### After
![image](https://user-images.githubusercontent.com/24587354/84486217-0aa94400-acd8-11ea-9bd2-26acb41f4b58.png)

**Comment by seanshpark** [comment]
I don't understand what the problem is. Please explain this to me on-line or off-line.
