### ISSUE TITLE
[onert] Make nnfw_input_tensorinfo() work after calling nnfw_set_input_tensorinfo()

### ISSUE THREAD

**Issue by hyunsik-yoon** [Samsung/ONE#2293]
while working for [large_test.tflite](https://github.sec.samsung.net/STAR/nnfw/issues/11334#issuecomment-719756), I found the this issue.

The following sequence should work:

assuming that input tensor 0's shape is [1, 2] in tflite file, currently line 4 has error.

- `nnfw_load_model_from_file()`
- `nnfw_prepare()`
- `nnfw_set_input_tensorinfo(0, [2, 2])`
- `nnfw_input_tensorinfo(0)`       --> this still returns [1, 2]
- `nnfw_run()`

Anyone who's interested in this work, please assign yourself and start working!
Thanks!

**Comment by wateret** [comment]
As I worked on `nnfw_output_tensorinfo`, I will do this.
