### ISSUE TITLE
[nnpackage] How to load and use archive files more efficient?

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#2420]
This topic has been discussed at least a few times before, I suddenly recalled it so I leave a comment for that, as far as I remember.

FYI this requires almost none of ONE Compiler and Runtime knowledge.

## An archive file format?

We defined NNPackage as a ZIP file. See also - [10_packaging_and_manifest.md](https://github.com/Samsung/ONE/blob/500ad6eea910cdf8a574634b6f6b4d5f0dfcc7d3/nnpackage/spec/10_packaging_and_manifest.md)

And its internal structure is

```
nnpackage
├── custom_op
├── metadata
│   └── MANIFEST
└── mymodel.model
```

But NNFW API only accepts unarchived directories. Unzipping at runtime is not considered so far, as it will create a temporary files on the user's filesystem and it slows down. Are there any way to use the archived file efficiently?

## Things to consider

(JUST MY OPINION)

- Should not decompress or unarchive during runtime
    - So ZIP is probably not what we want
- Should not make any temp files to the devices' filesystem
- Should be almost same memory/performance with the directory version

Is there an archive format for NN Package **without side effects and any performance/memory regression**. Otherwise what would be the best alternative?

Any ideas are welcome. Even like "I don't see any advantages doing it", "it is not possible, because ..."

**Comment by mhs4670go** [comment]
If we store the metadata to circle schema, we can make nnpackage one file except custom_op. 

BTW, I don't know about custom_op. Is there any document or examples of this?

**Comment by wateret** [comment]
Good idea. That would be very simple solution. And here's my concerns.

- This is going to be NNPackage V2 which could be burdensome managing two versions
- Custom ops will contain `.so` files and say we embed it to circler. Can we directly load it? it is already `mmap`ed.

**Comment by wateret** [comment]
This may be related? https://developer.android.com/studio/command-line/zipalign

**Comment by glistening** [comment]
@wateret 

> We defined NNPackage as a directory. 

No. It was defined as zip archive format. See https://github.com/Samsung/ONE/blob/500ad6eea910cdf8a574634b6f6b4d5f0dfcc7d3/nnpackage/spec/10_packaging_and_manifest.md#2-packaging-structure.

However, as we don't want to have overhead of uncompressing before running the model. Our api assumes it is already decompressed.

> - Should not decompress during runtime
>   - So ZIP is probably not what we want

No. ZIP support zero compress mode as I mentioned in nnpackage specification. See https://github.com/Samsung/ONE/blob/500ad6eea910cdf8a574634b6f6b4d5f0dfcc7d3/nnpackage/spec/10_packaging_and_manifest.md#3-packaging-format.

> This may be related? https://developer.android.com/studio/command-line/zipalign

Someone and me investigated `zipalign` at early day of `nnpackage`. I searched our internal repo for finding history. I cannot find.

**Comment by wateret** [comment]
Oh I did not know NN Package was a ZIP format. NNFW API does not support ZIP file so it means NNFW API does not support NN Package.

> No. ZIP support zero compress mode as I mentioned in nnpackage specification. See https://github.com/Samsung/ONE/blob/500ad6eea910cdf8a574634b6f6b4d5f0dfcc7d3/nnpackage/spec/10_packaging_and_manifest.md#3-packaging-format.

It does not matter if it is actually compressed or not. I'll change that word to "archived". The thing is, if it can be easily used like it is already unarchived as a directory. Can "stored" zip file do that?

**Comment by seanshpark** [comment]
@wateret do you want something like, just store a directoy in a file without any compression?

**Comment by wateret** [comment]
@seanshpark Yes, I'm looking for something like that - treat a single file like a virtual filesystem.

% I'm totally OK with as-is(as a directory), but created this issue since we've discussed several times.

**Comment by seanshpark** [comment]
zip library and maybe others provide zero compression option, just store in one file.
can this be your solution?

**Comment by wateret** [comment]
Again, zero compression itself is not important. It should meet these conditions.

> - Should not decompress or unarchive during runtime
> - Should not make any temp files to the devices' filesystem
> - Should be almost same memory/performance with the directory version
> 
> Is there an archive format for NN Package **without side effects and any performance/memory regression**.

**Comment by lemmaa** [comment]
> - Should be almost same memory/performance with the directory version

I disagree. Why must this be? In some scenarios, initial startup time is not critical.

For example, if we are only measuring inference performance in every day development, it would be convenient to use one archive file format even with a little long loading time. :)

**Comment by glistening** [comment]
@wateret Could you please change the title? As I wrote, nnpackage is already `archive file format`. If you're going to provide `one api`, it may be better title. If you're going to redefine an archive file format for some reason, "Redefine archive format for nnpacakge` could be the title.

**Comment by wateret** [comment]
@glistening Sure, this title is misleading.

**Comment by wateret** [comment]
> > * Should be almost same memory/performance with the directory version
> 
> I disagree. Why must this be? In some scenarios, initial startup time is not critical.
> For example, if we are only measuring inference performance in every day development, it would be convenient to use one archive file format even with a little long loading time. :)

@lemmaa Then all these things that I have been considering are also not necessary.

> - Should not decompress or unarchive during runtime
> - Should not make any temp files to the devices' filesystem
> - Should be almost same memory/performance with the directory version

And using a normal ZIP(both compressed or stored) looks fine then. Then my question is #2735 , let's keep discussion there.
