### ISSUE TITLE
[onert] Determining on/off values for one-hot quant8

### ISSUE THREAD

**Issue by dr-venkman** [Samsung/ONE#2431]
The data types of `on_value` and `off_value` within `one-hot` are defined as `float` within onert. While this works for float32, how should it be handled for the case of quant8 asymm? There are two related questions I would like to know about, which are as follows:

1. Tfllite models the above values as tensors, and so can interpret them according to the type of computation (`float` or `uint8_t`). As onert defines them to be strictly `float`, should we typecast and clamp the values within (0, 255) range? 

For example, if we consider `float on_value = 300; float off_value = 0;` will they be converted to `uint8_t q_on_value = 255; uint8_t q_off_value = 0;`?

2. Will there be scale, offset parameters to consider for `on_value` and `off_value`? If yes, then, we will need additional parameters to be added under `runtime/onert/core/include/ir/operation/OneHot.h`.

Please let me know what approach works best.

**Comment by dayo09** [comment]
```c++
// ir/operation/onehot.h
class OneHot : public Operation
{
public:
  enum Input
  {
    INDICES = 0,
    DEPTH = 1,
    ON_VALUE = 2,
    OFF_VALUE = 3,
  };

  struct Param
  {
    int depth;       // comes from input tensor, not from OneHotOptions
    float on_value;  // comes from input tensor, not from OneHotOptions
    float off_value; // comes from input tensor, not from OneHotOptions
    int axis;
  };
```

- It seems that IR already has ON_VALUE and OFF_VALUE as Input Tensor.
- At base_loader.h, it converts ON_VALUE and OFF_VALUE from Input into Param.
- Therefore, you don't need to change IR, so there is no following concerns about other backends. Just changing base_loader will do. If it passes as Input Tensor instead of converting into param, I think it will work.

**Comment by dr-venkman** [comment]
Thanks for the explanation, I will get started with the implementation following this. Regarding the second question (about scale and offsets), I see that tflite does not convert between on/off tensor scales and output scales, so I can safely ignore that concern.

**Comment by glistening** [comment]
@dr-venkman I've just read this issue. I started to update `OneHot` yesterday. I will push it today or tomorrow.

**Comment by dr-venkman** [comment]
@glistening Thanks, I have just about completed quant8 support for comparison operators from last week. Please go ahead with one-hot, I will find other operations to work on shortly.

**Comment by hseok-oh** [comment]
#2759 is merged
