### ISSUE TITLE
Compiler FE: Enable Arg Max Operator

### ISSUE THREAD

**Issue by sun-sharma** [Samsung/ONE#2445]
- [ ] tflchef
- [ ]  luci.IR
- [ ]  luci.Import
- [ ]  luci.Export
- [ ]  luci.logex
- [ ]  luci.Service
- [ ]  res/TensorFlowPythonExamples
- [ ]  res/TensorFlowLiteRecipes
- [ ]  tflite2circle
- [ ]  luci.tests
- [ ]  tfldump
- [ ]  circledump

**Comment by seanshpark** [comment]
@sun-sharma , ArgMax seems to be working. Can you check this again?

**Comment by sun-sharma** [comment]
Sure, Thanks.
