### ISSUE TITLE
Comipler FE : Documentation

### ISSUE THREAD

**Issue by btheosam** [Samsung/ONE#2512]
This issue is to track all documentation regarding CFE (compiler FE). This issue is to be master issue listing all issues related to CFE documentation. 

a. Add README at compiler directory to mention what the directory is about. (Create a new issue)
b. write some compiler document #2514

**Comment by seanshpark** [comment]
> #1. Add
> #2. write

@btheosam , if you use `#number` in the comment it'll make a link to that issue that actully isn't related with this issue. this link can not be removed as I know.

**Comment by btheosam** [comment]
@seanshpark Thanks for the info. Fixed.

**Comment by btheosam** [comment]
Issue #2514 covers all the necessary documents. This issue duplicates that, hence closing this.
