### ISSUE TITLE
Resolve coverity defect on master

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#2522]
~~link : https://code.sec.samsung.net/ahub/service/analyses/128858~~
internal coverity analysis report : https://code.sec.samsung.net/ahub/service/analyses/130150

## Summary
update : 2020/06/24 12:31
21 defects 
| WID | resolved? | assignee | internal defect link |
| ----|    -----| ----| -- |
|    1140718     |      #2557             | @wateret | |
|    1140582     |         #2558          | @wateret | |
| 1140580 | Done - Intentional | @wateret | |
| 1140579 |#2559 | @wateret | |
| 1140578 | #2558 |@wateret | |
| 1140462 | #2561 |@wateret | |
| 1140458 | external (from TF) | @glistening | |
| 1140457 | Done | @glistening | |
| 1140307 | Done - False positive |@wateret | |
| 1140306 | #2563 | @glistening | |
| 1140305 | #2563 | @glistening | |
| 1139635 | Done | @glistening | |
| 1139634 | Done | @glistening | |
| 1134443 | Done | @glistening | |
| 1091162 | #2562 | @ragmani  | |
| 1091099 | #2562 | @ragmani  | |
| 1085213 | Done - False positive | @ragmani  | |
| 1045362 | #2560 | @ragmani  |  |
| 1045361 | #2560 | @ragmani |   |
| 839456 | #2556 | @ragmani  | |
|111659 | external | | |

**Comment by hseok-oh** [comment]
Many defects are related with test binaries

**Comment by chunseoklee** [comment]
cc @glistening @wateret @ragmani

**Comment by glistening** [comment]
@wateret, @ragmani I will start from 1/3 line (1140458) to bottom.

**Comment by wateret** [comment]
@periannath http://10.113.139.115:8081/reports.htm#v13368/p10494/fileInstanceId=259850887&defectInstanceId=92817200&mergedDefectId=1140580 Could you please take a look? This can be marked as false positive?

**Comment by wateret** [comment]
For 1085213 and 1140307

It had been marked as False Positive.

http://10.113.139.115:8081/reports.htm#v13368/p10180/fileInstanceId=209067200&defectInstanceId=75293460&mergedDefectId=1085213

**Comment by wateret** [comment]
Marked 1085213 and 1140307 as "False Positive".

Marked 1140580 as "Intentional".

**Comment by chunseoklee** [comment]
5 defects found on 9c2b5f15992b4b8a6400da15ea0e5045048454db : https://code.sec.samsung.net/ahub/service/analyses/130580

**Comment by chunseoklee** [comment]
update : https://code.sec.samsung.net/ahub/service/analyses/130861

**Comment by chunseoklee** [comment]
@ragmani PTAL http://10.113.139.115:8081/reports.htm#v13368/p10494/fileInstanceId=260098712&defectInstanceId=92895208&mergedDefectId=1140723

**Comment by ragmani** [comment]
@chunseoklee 
I classified it to `False positive`.

**Comment by chunseoklee** [comment]
link : https://code.sec.samsung.net/ahub/service/analyses/131324

critical, major defect 0 on 8876d6e356efda86c8ef8261b3f11f6f952f3950
