### ISSUE TITLE
Compiler FE: Enable ReverseV2 Operator 

### ISSUE THREAD

**Issue by d-krylov** [Samsung/ONE#2528]
- [x] tflchef  #2820 
- [x] luci.IR  #2913 
- [x] luci.Import  #2913 
- [x] luci.Export    #2913 
- [x] luci.logex  #2913 
- [x] luci.Service   #2913 
- [x] res/TensorFlowPythonExamples #2947
- [x] res/TensorFlowLiteRecipes  #2833
- [x] tflite2circle  #2822 
- [x] luci.tests  #2938 #2979 
- [x] tfldump nothing to do
- [x] circledump  nothing to do

for #1606

draft #2539

**Comment by binarman** [comment]
All done, closing
