### ISSUE TITLE
[nnfwapi] Design Asynchronous Run API

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#2541]
`nnfw_run` is blocking. We need an interface for asynchronous run.

Q. Do we need an interface for **multiple runs at the same time with a single session**?

**Comment by lemmaa** [comment]
> ... running multiple runs at the same time with a single session?

@wateret , could you explain it in more detail? I am not sure what this means exactly.

**Comment by wateret** [comment]
@lemmaa Sure 😃 

We have only one execution context so we can only run one by one. It is good for synchronous runs.

However we may want a single compiled(`nnfw_prepare`) session and run it with different inputs at the same time. → This is what I meant by that.

If we have to do that, this work may take a while since it probably requires a lot of changes in runtime core. If not, it may take only a couple of days since we don't need to change anything in runtime core.

**Comment by lemmaa** [comment]
> However we may want a single compiled(nnfw_prepare) session and run it with different inputs at the same time. → This is what I meant by that

@wateret , yes, I got it. This is a natural consideration to support asynchronous. Especially for runtime to serve as a daemon. But it would be nice to approach it step by step. 

Let's support single asynchronous first, assuming that only one session is used asynchronously but sequentially. After that, we can implement `multiple runs at the same time with a single session`. Until then, even if it was inefficient in terms of memory usage, we would be able to cope with that scenario by creating separate sessions with the same model.

**Comment by semun-lee** [comment]
If there is asynchronous nnfw_run(), I think we could optimize throughput of nnfw by software pipelining. 
https://en.wikipedia.org/wiki/Software_pipelining

For streaming data like voice or previews from camera, this could be helpful. While optimizing eASR, we separate enc module to enc1 and enc2 to gain the effect of software pipelinng, but I think it might be possible in onert in "layer" unit.

How do you think about this idea?

**Comment by hseok-oh** [comment]
To maximise throughput by asynchronous run, we should define API to set no. of thread per each inference for application developer. Our cpu backend already using multithread  (eigen, ruy). So If we don't support no. of thread setting API, asynchronous run may make additional overhead with small throughput gain.

**Comment by wateret** [comment]
@semun-lee 

> If there is asynchronous nnfw_run(), I think we could optimize throughput of nnfw by software pipelining.
> https://en.wikipedia.org/wiki/Software_pipelining

Yes and I think it is the user's(of NNFW API) responsibility doing pipelining. And limiting multithreads may be necessary as @hseok-oh mentioned. FYI multi-session management is not considered yet, actually I don't have much idea for that.

> For streaming data like voice or previews from camera, this could be helpful. While optimizing eASR, we separate enc module to enc1 and enc2 to gain the effect of software pipelinng, but I think it might be possible in onert in "layer" unit.

Can I ask what "onert in layer unit" means?

**Comment by semun-lee** [comment]
> Can I ask what "onert in layer unit" means?

I thought that "layer" could be a unit for pipelining because it has its own input/ouput spec. During eASR optimization, enc.tflite is separated to 1-layer model (enc1.tflite) and 5-layer model (enc2.tflite) manually. If onert could do that kind of optimization in runtime, it would be quite useful.

**Comment by wateret** [comment]
Thank you for clarification. Just to make sure we are on the same page,

> If onert could do that kind of optimization in runtime, it would be quite useful.

What do you mean by this exactly?

- User must slice the model and build their apps pipelined (Everything is the user's(of NNFW API) responsibility)
- User slices the model and onert runs it pipelined (half onert, half user)
- onert takes the whole model(`enc.tflite`) and slices properly and run it pipelined? (Everything is done by onert)
- Something else

**Comment by semun-lee** [comment]
> onert takes the whole model(enc.tflite) and slices properly and run it pipelined? (Everything is done by onert)

This is in my mind.

**Comment by wateret** [comment]
> Let's support single asynchronous first, assuming that only one session is used asynchronously but sequentially. 

I'm going to follow this way(#3087) since:

- With `nnfw_session`, it is not very convenient to invent new APIs that support multiple executions
    - NNAPI can generate multiple `Execution`s from a compilation but we have only one session
    - Possible API design (Introduce an integer ID which could be tricky for both users and developers)
```c
NNFW_STATUS nnfw_run_async(nnfw_session *session, int* async_id);
NNFW_STATUS nnfw_run_await(nnfw_session *session, int async_id);
```
- Even if we did, the runtime does not truly support multiple runs for a session yet
    - As `Execution` has only one memory space for one execution so even if multiple executions are running, they are running in sequence actually (There is a mutex)

So I'm thinking about supporting multiple executions for a session from NNFW API 2.0(more NNAPI-like, having multiple objects rather than the only session object, and possibly https://github.com/Samsung/ONE/issues/2541#issuecomment-651647053) which we may introduce someday.

cc: @hseok-oh @lemmaa

**Comment by wateret** [comment]
With #3243, "Let's support single asynchronous first, assuming that only one session is used asynchronously but sequentially." is done.
