### ISSUE TITLE
Final vote for ONE logo design

### ISSUE THREAD

**Issue by lemmaa** [Samsung/ONE#2546]
Parent issue : #1970

# Let's do the final vote!

It is not clear which one was recommended because several designs are included in one comment. So, I have selected the 6 designs with more than 5 votes and start final vote here.

Only 👍  will count. :)

### The vote ends on June 24th 23:59 KST. ###

/cc @Samsung/one , @Samsung/nnfw , @Samsung/nncc , @nkoong , @Seo-Young , @sos-masters

**Comment by lemmaa** [comment]
<img width="461" alt="Screen Shot 2020-06-23 at 9 40 39 PM" src="https://user-images.githubusercontent.com/1185333/85405311-2f849d80-b59b-11ea-996a-dbd26d1d64f6.png">

**Comment by lemmaa** [comment]
<img width="482" alt="Screen Shot 2020-06-23 at 9 40 52 PM" src="https://user-images.githubusercontent.com/1185333/85405436-5f33a580-b59b-11ea-92d6-7f3b3e0f0df7.png">

**Comment by lemmaa** [comment]
<img width="500" alt="Screen Shot 2020-06-23 at 9 41 11 PM" src="https://user-images.githubusercontent.com/1185333/85405564-8ee2ad80-b59b-11ea-8a8c-00d57989ca00.png">

**Comment by lemmaa** [comment]
<img width="500" alt="Screen Shot 2020-06-23 at 9 40 04 PM" src="https://user-images.githubusercontent.com/1185333/85405664-b89bd480-b59b-11ea-88fb-85014bd7b488.png">

**Comment by lemmaa** [comment]
<img width="417" alt="Screen Shot 2020-06-23 at 9 41 28 PM" src="https://user-images.githubusercontent.com/1185333/85405766-d9fcc080-b59b-11ea-9bf3-713cd957ddff.png">

**Comment by lemmaa** [comment]
<img width="500" alt="Screen Shot 2020-06-23 at 9 41 47 PM" src="https://user-images.githubusercontent.com/1185333/85405833-eda82700-b59b-11ea-9c50-31b53b83c3df.png">

**Comment by lemmaa** [comment]
For candidate 6, I hope the background of this is white, not current light yellow. :)

**Comment by sunchitsharma** [comment]
> For candidate 6, I hope the background of this is white, not current light yellow. :)

Yes, It is white.

**Comment by lemmaa** [comment]
# 🎉 Candidate 2 has been won. Congratulations!!! :confetti_ball:

**Comment by nkoong** [comment]
Thanks!!!

If something should be changed or if there is something I can help you for the logo, let me know I will help you!

**Comment by lemmaa** [comment]
> If something should be changed or if there is something I can help you for the logo, let me know I will help you!

@nkoong , It would be nice if there was an original `*.svg` format file for the selected design. Then we can use it by registering it in the repository. It is optional, but it would be nice if you had a guide document on the design philosophy or use of logo.

Thanks again!

**Comment by nkoong** [comment]
> > If something should be changed or if there is something I can help you for the logo, let me know I will help you!
> 
> @nkoong , It would be nice if there was an original `*.svg` format file for the selected design. Then we can use it by registering it in the repository. It is optional, but it would be nice if you had a guide document on the design philosophy or use of logo.
> 
> Thanks again!

Thanks :)  if it isn't needed quickly, Can I make and upload it in this weekend??

**Comment by lemmaa** [comment]
> Thanks :) if it isn't needed quickly, Can I make and upload it in this weekend??

Of course. Please use your time comfortably. :)
