### ISSUE TITLE
Compiler FE: Enable Unique Op

### ISSUE THREAD

**Issue by dr-venkman** [Samsung/ONE#2568]
Parent Issue : #1606 
Draft PR : #2829 

- [x] res/TensorFlowPythonExamples (#3252)
- [x] common-artifacts (#3255, #3450)
- [x] tflchef (#3274)
- [x] tflite2circle (#3267)
- [x] tfldump (#3295)
- [x] circledump (#3309)
- [x] res/TensorFlowLiteRecipes (#3410)
- [x] res/TensorFlowLiteRecipes (correction) (#3862)
- [x] luci.IR (#3573)
- [x] luci.Import (#3605)
- [x] luci.Export (#3640)
- [x] luci.logex (#3656)
- [x] luci.Service (#3687)
- [x] luci.Service (correction) (#3876)
- [x] luci.tests (#3919)

**Comment by hseok-oh** [comment]
Done
