### ISSUE TITLE
Changing seed value for nnapi_test

### ISSUE THREAD

**Issue by periannath** [Samsung/ONE#2606]
Currently, `nnapi_test` generate random inputs with seed value `0`. And CI is using that binary to validate runtime.

https://github.com/Samsung/ONE/blob/cb2c05a7354a2fd574ddd394c46cfcdebf793511/tests/tools/nnapi_test/src/nnapi_test.cc#L54

Even if the value is matched in CI, the kernel may produce wrong for other seed values.

How about changing seed value for `nnapi_test`?

/cc @hseok-oh

**Comment by glistening** [comment]
I prefer `0` since it gives deterministic result in CI. If someone would like to test with more, he/she can run `nnapi_test` with several input generated with different seed. It may be convenient for `nnapi_test` to get seed by an argument which defaults to `0`.

**Comment by periannath** [comment]
@glistening I think multiple tests with random seed are better. However, providing an option to set seed value is good middle ground considering CI. 

I've uploaded PR to set seed value for `nnapi_test`. #2622

**Comment by periannath** [comment]
I'm closing this issue since #2622 is merged.
If anyone is interested in changing seed value for `nnapi_test` including CI, feel free to reopen this issue or create another one.
