### ISSUE TITLE
Compiler FE: Enable MatrixDiag Op

### ISSUE THREAD

**Issue by d-krylov** [Samsung/ONE#2635]
Parent Issue : #1606 

Draft: #2649 

- [x] res/TensorFlowPythonExamples #2948 
- [x] tflchef #2812 
- [x] tflite2circle #2814 
- [x] tfldump nothing to do
- [x] circledump nothing to do
- [x] res/TensorFlowLiteRecipes #2830 
- [x] luci.IR #2914 
- [x] luci.Import #2914 
- [x] luci.Export #2914 
- [x] luci.logex #2914 
- [x] luci.Service #2914 
- [x] disable common artifacts #2977
- [x] luci.tests #2980

**Comment by binarman** [comment]
everything is done, closing
