### ISSUE TITLE
[info] Install flatbuffers rpm(libflatbuffers.so) when running on tizen devices

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#2647]
Since https://review.tizen.org/gerrit/gitweb?p=platform/upstream/tensorflow.git;a=commit;h=09c35c126558f655e1d4cc38c41e09683f38127a, install flatbuffer rpm to run onert on tizen.

**Comment by hseok-oh** [comment]
It is not valid guidance any more.
