### ISSUE TITLE
ONE Logo Guideline and SVG files

### ISSUE THREAD

**Issue by nkoong** [Samsung/ONE#2681]
Parent issue: #2546

Here is guideline for the logo and SVG files for the logo.

- [P_One_Guideline.pdf](https://github.com/Samsung/ONE/files/4842322/P_One_Guideline.pdf)
- [svg.zip](https://github.com/Samsung/ONE/files/4841989/svg.zip)

If English version guideline is also needed, I will make it too :)
Thank you.

### Updates
- 20200628 22:31 KST : typos in guideline file are fixed and uploaded updated file

**Comment by lemmaa** [comment]
> If English version guideline is also needed, I will make it too :)

@nkoong , It would be great if that would happen. :)

One more thing, it would be an honor if you PR these files,  directly to the `/logo` folder.
- ONE logo.svg
- ONE logo-black and white.png
- ONE logo guideline-KR.pdf
- ONE logo guideline-EN.pdf

**Comment by llFreetimell** [comment]
Because related PR is merged, close this issue!
