### ISSUE TITLE
Compiler FE: change test.lst

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#2690]
Our test modules have a list of tests named `test.lst`. But whenever a new resource comes into the repository, it needs to be added to this file, which is a burden I think.

So, how about changing it to exclude the test?

If so, we don't have to do anything when adding resources, we only need to add them when we need to exclude them(just like [this](https://github.com/Samsung/ONE/pull/2586/files?file-filters%5B%5D=.lst#diff-b368f8412a607e19cc3230798a141463)).

**Comment by seanshpark** [comment]
for luci test.lst, there are several modules to be work to enable the test and we cannot post all the codes at once. I'm not sure your suggestion works for this case.

**Comment by mhs4670go** [comment]
@seanshpark In the `CMakeLists.txt` of test module, it finds the resource(e.g. recipe) in repo and adds the test. I think if we post the recipe to the last, it will work.

**Comment by mhs4670go** [comment]
After offline meeting, we don't need to change every module. It would be good if the test-module maker decide the way it tests according to the characteristics or purpose of each module.
