### ISSUE TITLE
Compiler FE: Enable MatrixSetDiag Op

### ISSUE THREAD

**Issue by d-krylov** [Samsung/ONE#2732]
Parent Issue : #1606 

Draft: #2738 

- [x] res/TensorFlowPythonExamples #2949 
- [x] tflchef #2815 
- [x] tflite2circle #2817 
- [x] tfldump  nothing to do
- [x] circledump nothing to do
- [x] res/TensorFlowLiteRecipes #2831 
- [x] luci.IR #2950 
- [x] luci.Import #2950 
- [x] luci.Export #2950 
- [x] luci.logex #2950 
- [x] luci.Service #2950 
- [x] luci.tests #2981 
- [x] exclude interpreter test #2978

**Comment by binarman** [comment]
all done, closing
