### ISSUE TITLE
[nnfwapi] Support NNPackage(ZIP)?

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#2735]
Strictly speaking we can't say "NNFW API support NNPackage".

https://github.com/Samsung/ONE/blob/500ad6eea910cdf8a574634b6f6b4d5f0dfcc7d3/nnpackage/spec/10_packaging_and_manifest.md#2-packaging-structure

> nnpackage must be a ZIP archive.

`nnfw_load_model_from_file` loads an unarchived directory and it is the only function to load nnpackage.

**Comment by glistening** [comment]
> `nnfw_load_model_from_file` loads an unarchived directory and it is the only function to load nnpackage.

`nnfw_load_model_from_file` says:

```
@param[in] package_file_path Path to the nnpackage file or unzipped directory to be loaded
```

NNAPI has an API for loading nnpackage. However it has not been implemented till now since it is not necessary and inefficient.

**Comment by wateret** [comment]
It may be confusing because unzipped NNPackage is not official according to the definition of NNPackage.

**Comment by glistening** [comment]
@wateret So could you please let me know what is your suggestion? changing definition of NNPackage? providing an implementation for getting NNPackage?

**Comment by wateret** [comment]
I guess adding a description that says unarchived directory is also official is the easiest way. As we think unarchiving ZIP file at runtime is not worth it and #2420 does not have solution yet.

**Comment by wateret** [comment]
cc: @chunseoklee @lemmaa

**Comment by lemmaa** [comment]
@wateret , personally, even if it's not 100% satisfactory to all cases (as I commented https://github.com/Samsung/ONE/issues/2420#issuecomment-653003159 ), I wish we have support for the single archived file format. 

And `*.zip` is a good choice. :)

**Comment by wateret** [comment]
So about supporting normal ZIP file...

- Model load will take more time
- If we want to extract ZIP on the memory not to disk, it may increase memory peak during model loading which could be the peak
- nnfwapi will link with a ZIP library which may increase binary footprint.
