### ISSUE TITLE
Compiler FE: Common Intermediate Artifacts

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#2743]
In the middle of building our compiler module, we make several intermediate artifacts. But there are many overlapping processes because multiple modules make the same output(e.g. `.tflite`, `.circle`).

How about making an intermediate output beforehand and using it?

In this module(?), these will be created.
- recipe
- tensorflow lite
- circle
- nnpackage
- nnpackage test data(input.h5, expected.h5)

[This draft](https://github.com/Samsung/ONE/pull/2586) can be changed to this module I think.

**Comment by seanshpark** [comment]
@mhs4670go , can you describe in form of

AS-IS
- each source resides in `res/TensorFlowLiteRecipes` folder
- each modules in `compiler/` will make a copy of this recipe to it's build output folder
- each module will do it's conversion or call other module(s) to convert to intermediate file and do it's own conversion

TO-BE
- ...

**Comment by mhs4670go** [comment]
AS-IS

- each source resides in res/TensorFlowLiteRecipes folder
- each modules in compiler/ will make a copy of this recipe to it's build output folder
- each module will do it's conversion or call other module(s) to convert to intermediate file and do it's own conversion

TO-BE
- `common-artifacts` module will do conversion of all intermediate file to prevent duplication of copies
- each module will be able to get required resources from `common-artifacts` module.

I think copy of recipe is redundant as well but it seems to be okay with the concept of putting resources together.
