### ISSUE TITLE
[onert] Use ExternalData with mmaped pointer instead of CachedData

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE#2751]
Parent issue: https://github.com/Samsung/ONE/issues/2580

Use ExternalData with pointer by [mmap()](https://man7.org/linux/man-pages/man2/mmap.2.html) instead of CachedData from the beginning of ModelLoad phase.

**Comment by YongseopKim** [comment]
Points to consider more.

1. onert needs the base pointer of mmap() to do unmmap() partially
    - because of calculating the aligned memory address.
    - Please read `BaseLoader::deallocateMmappedArea()`
    - Just in case, unmmap() could be unnecessary?
1. which class has the base pointer of mmap()?
    - ExternalData can reach the class which has the base pointer of mmap()
    - subgraphs?
    - subgraphs.primary_subgraph()? it means Graph.
    - ~~an independent module. A class MMap as static class.~~
    - ExternalData has a partial pointer and also a base pointer of mmap.
        - I'm considering this.

**Comment by YongseopKim** [comment]
cc/ @Samsung/nnfw_committers

**Comment by wateret** [comment]
>    - ExternalData has a partial pointer and also a base pointer of mmap.

About implementation, probably it would be great to introduce a derived class(`MMapData` for the name maybe?) of `Data` rather than making changes on `ExternalData`, if possible.

**Comment by YongseopKim** [comment]
I choose @water's suggestion and upload pr https://github.com/Samsung/ONE/pull/2764

**Comment by YongseopKim** [comment]
Done via #2764
