### ISSUE TITLE
Compiler Frontend: Operators to enable

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#277]
Welcome to ONE compiler contribution!
Our Compiler frontend is supporting more operators day by day.
This issue is to share our next step Operstors to support and provide a guide how-to.

### steps to work

1. select an operator you want to work and create an issue
   - add a link to this issue by adding like "For #277"
   - use issue title like `Compiler FE: Enable ### Op`
1. someone(mostly I will) mark your ID in the table
1. work on a draft code following the modules one by one
1. post draft PR; parial codes of draft PR is OK
1. finish draft and update to PR
   - `luci_unit_readtest` and `luci_unit_writetest` should pass with adding to `luci/tests`
   - use `DRAFT Compiler FE` prefix in the title
   - add 3 labels `DRAFT, PR/NO MERGE, PR/NO TEST`
1. post separate PRs one by one with below steps
   1. TensorFlowPythonExamples
   1. tflite2circle , tflchef , tfldump , circledump : these can be posted in parallel
   1. TensorFlowLiteRecipes
   1. luci/lang
   1. luci/import , luci/service , luci/logex , luci/export : these can be posted in parallel
   1. luci/tests

### reference links

https://github.com/Samsung/ONE/issues?q=is%3Aissue++compiler+enable will show a list of issues used to track Operation support

https://github.com/Samsung/ONE/pulls?q=is%3Apr+DRAFT+Compiler+ will show a list of drafts that are related with Operation support.

**Comment by seanshpark** [comment]
All done for this issue.

**Comment by seanshpark** [comment]
Thanks for your hard work!!!

**Comment by binarman** [comment]
Yay, thank you!

**Comment by dr-venkman** [comment]
> Welcome to ONE compiler contribution!
> Our Compiler frontend is supporting more operators day by day.
> This issue is to share our next step Operstors to support and provide a guide how-to.
> 
> ### steps to work
> 1. select an operator you want to work and create an issue
>    
>    * add a link to this issue by adding like "For #277"
>    * use issue title like `Compiler FE: Enable ### Op`
> 2. someone(mostly I will) mark your ID in the table
> 3. work on a draft code following the modules one by one
> 4. post draft PR; parial codes of draft PR is OK
> 5. finish draft and update to PR
>    
>    * `luci_unit_readtest` and `luci_unit_writetest` should pass with adding to `luci/tests`
>    * use `DRAFT Compiler FE` prefix in the title
>    * add 3 labels `DRAFT, PR/NO MERGE, PR/NO TEST`
> 6. post separate PRs one by one with below steps
>    
>    1. TensorFlowPythonExamples
>    2. tflite2circle , tflchef , tfldump , circledump : these can be posted in parallel
>    3. TensorFlowLiteRecipes
>    4. luci/lang
>    5. luci/import , luci/service , luci/logex , luci/export : these can be posted in parallel
>    6. luci/tests
> 
> ### reference links
> https://github.com/Samsung/ONE/issues?q=is%3Aissue++compiler+enable will show a list of issues used to track Operation support
> 
> https://github.com/Samsung/ONE/pulls?q=is%3Apr+DRAFT+Compiler+ will show a list of drafts that are related with Operation support.

I think it would be a good idea to mention any additions to `common-artifacts` here. If an issue pertaining to it does exist, then maybe reference it, especially for point 6.iii. In my specific implementation, I have had to exclude recipes from circle optimization, in addition to generated testcases (please refer #3410 for the details).
