### ISSUE TITLE
U8 test input for luci-value-test is all zero

### ISSUE THREAD

**Issue by cgbahk** [Samsung/ONE#2771]
According to readme, `luci-value-test` is supposed to test with random input.
https://github.com/Samsung/ONE/blob/308753a8e25cd21237b9d13401e0dd684dc2f6dc/compiler/luci-value-test/README.md#L10-L11

But actually for U8 test, all input values seem zero.
```
$ hd build/compiler/luci-value-test/Add_U8_000.circle.input0

00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000030
```

All other U8 tests are same.

cc @parjong

**Comment by cgbahk** [comment]
Looks related to 
https://github.com/Samsung/ONE/blob/6c5e2872be12dcafcb03af11892688a686dfbeef/compiler/luci-value-test/luci_eval_verifier.py#L27-L34

**Comment by jinevening** [comment]
Thanks for the report. This results from the misuse of numpy API.

To generate random integers, `randint` should be used (instead of `random_sample`). I'll make a PR for this.
