### ISSUE TITLE
Compiler FE: execution environment setup

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#2777]
I'm not sure this title reflects what we need to do...
this is about setting environment to execute our compiler fontend as a user from a clean Linux machine with our [Releases](https://github.com/Samsung/ONE/releases)
- python virtual environment setup; 
   - users may not want this but we need this to run correctly
- prerequisite packages installation
   - I've found that `libhdf5` is needed (https://github.com/Samsung/ONE/issues/2550#issuecomment-652306595)
   - and also libboost_program_options.so.1.58.0
- TBA

**Comment by seanshpark** [comment]
CC @mhs4670go

**Comment by seanshpark** [comment]
In Ubuntu 16.04
```
sudo apt-get install libhdf5-cpp-11 libboost-program-options1.58.0
```

**Comment by seanshpark** [comment]
@jinevening , please resolve `record-minmax` dependency issue

**Comment by jinevening** [comment]
> @jinevening , please resolve record-minmax dependency issue

I'm trying to find a way to resolve the issue in #2809 .

**Comment by seanshpark** [comment]
all known resolved
