### ISSUE TITLE
Compiler FE reduce lines of code in class

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#2843]
One of our internal software analysis tool reports lines of codes are high.
- compiler/luci/export/src/CircleOperationExporter.cpp
- compiler/luci/service/src/CircleShapeInferenceRule.cpp
- compiler/luci/logex/src/FormattedGraph.cpp
- compiler/locomotiv/src/NodeExecution.h

Let's try to reduce these

**Comment by lemmaa** [comment]
FYI https://github.sec.samsung.net/RS7-Architectural-Refactoring/SAM-RefactoringGuide

**Comment by seanshpark** [comment]
I think we can remove asserts in each visit methods.

**Comment by seanshpark** [comment]
done this for now
