### ISSUE TITLE
luci-interpter with empty CircleConst

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#2968]
Current `Net_ZeroDim_001` is excluded in `common-artifacts` module with a problem in _luci_

problem:
> compiler/luci/lang/src/Nodes/CircleConst.cpp:42: const typename loco::DataTypeImpl<DT>::Type& luci::CircleConst::at(uint32_t) const [with loco::DataType DT = (loco::DataType)10; typename loco::DataTypeImpl<DT>::Type = float; uint32_t = unsigned int]: Assertion `n < size<DT>()' failed.

Let's fix this problem

**Comment by seanshpark** [comment]
this recipe has
```
operand {
  name: "perm"
  type: INT32
  shape {
    dim: 4
  }
  filler {
    tag: "explicit"
    arg: "0"
    arg: "2"
    arg: "1"
    arg: "3"
  }
}
```

**Comment by seanshpark** [comment]
To reproduce
```
cd build/debug/compiler/common-artifacts
./testDataGenerator Net_ZeroDim_001.circle
```

**Comment by seanshpark** [comment]
As `Net_ZeroDim_001` has operators that current _luci-interpreter_ does not support, simple Add would be better

This as `Add_001/test.recipe`
```
operand {
  name: "ifm1"
  type: FLOAT32
  shape { dim: 1 dim: 0 dim: 1 }
}
operand {
  name: "ifm2"
  type: FLOAT32
  shape { dim: 1 dim: 0 dim: 1}
  filler {
    tag: "explicit"
  }
}
operand {
  name: "ofm"
  type: FLOAT32
  shape { dim: 1 dim: 0 dim: 1 }
}
operation {
  type: "Add"
  input: "ifm1"
  input: "ifm2"
  output: "ofm"
  add_options {
    activation: NONE
  }
}
input: "ifm1"
output: "ofm"
```

**Comment by seanshpark** [comment]
@s-barannikov , can you please check with the draft #2971 ?
And possible, can you provide any guides to fix this? or it is OK if you fix this issue or point out it's another modules problem.

get draft and apply this change
```diff

index 4e7fab2..198f254 100644
--- a/compiler/common-artifacts/exclude.lst
+++ b/compiler/common-artifacts/exclude.lst
@@ -7,7 +7,7 @@ optimize(Where_001)

 # tcgenerate : Exclude from test data generation(TestDataGenerator)
 tcgenerate(Abs_000)
-tcgenerate(Add_001) # to fix luci-interpreter
+# tcgenerate(Add_001) # to fix luci-interpreter
 tcgenerate(AddN_000)
 tcgenerate(Add_U8_000)
 tcgenerate(All_000)
```

build compiler and you'll get the assert failure.

CC @jinevening

**Comment by seanshpark** [comment]
Update: I've revised Tensor.cpp in the draft PR so that there is no build error or test failures. But I'm not sure this is the OK or not.

**Comment by s-barannikov** [comment]
@seanshpark The draft looks good, although I would do it a bit differently. Please see the comments in the PR.

**Comment by seanshpark** [comment]
> The draft looks good, although I would do it a bit differently. Please see the comments in the PR.

Thanks for the comments, I'll try to revise the draft and let you know :)

**Comment by seanshpark** [comment]
done

**Comment by seanshpark** [comment]
Need to add `Add_001` test to `luci-value-test`
