### ISSUE TITLE
[onert] performance regression after #2894

### ISSUE THREAD

**Issue by glistening** [Samsung/ONE#2996]
I've found that my target model takes 2.5x time (0.55 ms →1.4 ms).

After several measuring with recent changes, I've found it is caused by #2894.

Before #2894, 0.52 ms
After #2894, 1.36 ms

@ragmani Could you please take a look?

cc @wateret, @hseok-oh

**Comment by ragmani** [comment]
@glistening 
Could you tell me what target model is?

**Comment by ragmani** [comment]
- After applying #3026

```bash
$ BACKENDS="cpu" ./Product/armv7l-linux.release/out/bin/nnpackage_run --nnpackage temp -d output.h5 -r10
===================================
MODEL_LOAD   takes 3.004 ms
PREPARE      takes 16.900 ms
EXECUTE      takes 0.876 ms
- MEAN     :  0.876 ms
- MAX      :  2.829 ms
- MIN      :  0.526 ms
- GEOMEAN  :  0.747 ms
===================================
```

**Comment by glistening** [comment]
@ragmani I confirmed that your patch works. Thanks.

With #3026 patch, it takes **0.56 ms** on my xu4 with `-w 1000 -r 3000`. It restored the previous execution time.
