### ISSUE TITLE
Frontend Quantization type limits

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#3016]
Current `str_to_dtype` in CircleOptimizerUtils.cpp accepts lots of data types but actually current implmentation in Quantization Pass works with UINT8 and INT16.
We need to limit this and do error handlings for unsupported data types.
- ~only convert data types in `str_to_dtype`~
- [x] error handling in `quantize()` method
- [x] unknown type handling in Quantization Pass

**Comment by seanshpark** [comment]
CC @jinevening @meejeong

**Comment by jinevening** [comment]
> We need to limit this and do error handlings for unsupported data types.

Is there a reason for changing `str_to_dtype` (e.g., SE)? I made `str_to_dtype` as a general utility function which can be used in other optimizations as well. 

IMHO, throwing an exception for unsupported types in `CircleOptimizer::quantize` would be enough for error handling.

**Comment by seanshpark** [comment]
> str_to_dtype 

Yes, reading the codes, `str_to_dtype` can be left as-is

> throwing an exception for unsupported types

this can be a solution. 

another though I have is, throw with message code will contain string message for the user. that is, the string message is one of the user interface things. IMHO, putting user inferface things in one place is sometimes better for code management: the driver.

**Comment by seanshpark** [comment]
done
