### ISSUE TITLE
Compile frontend drivers

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#3018]
WIP

Current frontend comamnds that are generated
- tf2tfliteV2.py
- tflite2circle
- circle2circle
- record-minmax
- circle-quantizer
- model2nnpkg.sh
- tf2nnpkg

User exposed commands to introduce
- one-import ( * -> circle)
   - one-import-tf
   - one-import-tflite
   - one-import-onnx (later)
- one-optimize (circle -> circle)
- one-quantize (circle -> circle)
- one-pack (circle -> nnpkg)
- one-codegen (circle -> binary)

User exposed commands to introduce for several steps at once
- one-compile : import - optimize - quantize
- one-build : import - optimzie - quantize - codegen
- one-build-pack : import - optimzie - quantize - pack
- one [command] 

one
- command driver to invoke commands
- command can be import, optimize, quantize, compile and build

one-import [model type] ...
- first argument
   - tf for TensorFlow model
   - tflite for TensorFlow lite model
- this will invoke tf2tflite.py, tflite2circle

one-optimize
- this will invoke circle2circle

one-quantize
- this will invoke record-minmax, circle-quantizer

one-compile
- this will invoke compiler backend

one-build
- this will call all above

**Comment by seanshpark** [comment]
CC @lemmaa , @parjong , @chunseoklee

**Comment by seanshpark** [comment]
In this month, July, as we have to freeze code in 20th, preparing three one-import, one-optimize and one-quantize seems possible.

**Comment by lemmaa** [comment]
@seanshpark , as we discussed off-line, I agree much with this. :)

**Comment by seanshpark** [comment]
@lemmaa , what about current `tf2nnpkg` ?

**Comment by seanshpark** [comment]
tf2tfliteV2.py needs to run in our TF 2.3.0rc0 (as of now) and to match this, we provide python virtual environment
- restricting user to run our tools in specific virtual environment for precondition doesn't seem to be good

it would be better to provide these commands tools with bash script

**Comment by lemmaa** [comment]
> @lemmaa , what about current `tf2nnpkg` ?

@seanshpark , how about `one build-pack` ? This is a complete replacement for `tf2nnpkg` which takes `tf` as input and creates `nnpackage` as output. Apart from this, we can have a `one pack` or `one pkg` that takes a `circle` as input and makes `nnpackage`.


```
$ dotnet --help
.NET Core SDK (3.1.301)
Usage: dotnet [runtime-options] [path-to-application] [arguments]

Execute a .NET Core application.

runtime-options:
  --additionalprobingpath <path>   Path containing probing policy and assemblies to probe for.
  --additional-deps <path>         Path to additional deps.json file.
  --fx-version <version>           Version of the installed Shared Framework to use to run the application.
  --roll-forward <setting>         Roll forward to framework version  (LatestPatch, Minor, LatestMinor, Major, LatestMajor, Disable).

path-to-application:
  The path to an application .dll file to execute.

Usage: dotnet [sdk-options] [command] [command-options] [arguments]

Execute a .NET Core SDK command.

sdk-options:
  -d|--diagnostics  Enable diagnostic output.
  -h|--help         Show command line help.
  --info            Display .NET Core information.
  --list-runtimes   Display the installed runtimes.
  --list-sdks       Display the installed SDKs.
  --version         Display .NET Core SDK version in use.

SDK commands:
  add               Add a package or reference to a .NET project.
  build             Build a .NET project.
  build-server      Interact with servers started by a build.
  clean             Clean build outputs of a .NET project.
  help              Show command line help.
  list              List project references of a .NET project.
  msbuild           Run Microsoft Build Engine (MSBuild) commands.
  new               Create a new .NET project or file.
  nuget             Provides additional NuGet commands.
  pack              Create a NuGet package.
  publish           Publish a .NET project for deployment.
  remove            Remove a package or reference from a .NET project.
  restore           Restore dependencies specified in a .NET project.
  run               Build and run a .NET project output.
  sln               Modify Visual Studio solution files.
  store             Store the specified assemblies in the runtime package store.
  test              Run unit tests using the test runner specified in a .NET project.
  tool              Install or manage tools that extend the .NET experience.
  vstest            Run Microsoft Test Engine (VSTest) commands.

Additional commands from bundled tools:
  dev-certs         Create and manage development certificates.
  fsi               Start F# Interactive / execute F# scripts.
  sql-cache         SQL Server cache command-line tools.
  user-secrets      Manage development user secrets.
  watch             Start a file watcher that runs a command when files change.

Run 'dotnet [command] --help' for more information on a command.
```

**Comment by lemmaa** [comment]
Here is little alternative if you don't mind. :)

- `one-import` : tf/tflite --> circle
- `one-optimize` : circle --> circle
- `one-quantize` : circle --> circle
- `one-compile` == `one-import` + `one-optimize` + `one-compile` in series : tf/tflite --> circle
- `one-codegen` : circle --> npu-code
- `one-pack` : circle --> nnpkg 
- `one-build` == `one-import` + `one-optimize` + `one-compile` + `one-codegen` in series : tf/tflite --> npu-code
- `one-build-pack` == `one-import` + `one-optimize` + `one-compile` + `one-pack` in series : tf/tflite --> nnpkg

**Comment by seanshpark** [comment]
`one-codegen` convention
- one-codegen backend [options]
- this will invoke `backend-compile` command

**Comment by seanshpark** [comment]
all landed.
