### ISSUE TITLE
[onert] Investigate ACL's WeightManager : how to share transformed weight between layers

### ISSUE THREAD

**Issue by dayo09** [Samsung/ONE#3074]
ONE supports operand sharing like this :
- One operand can be used by multiple operators by cpu, acl_cl, acl_neon backends
- Transformed operand cannot be used by multiple operators by cpu.
- Transformed operand can be used by multiple operators by acl_cl, acl_neon backends.
- (Not sure about different backend can share one operand in each other's operator. I assume it's unlikely.)

So I investigated how ACL's sharing transformed operand between different layers(a.k.a. operators, operations, kernels).
This is to share the concept.
Related issue : https://github.sec.samsung.net/STAR/nnfw/issues/11568

**Comment by dayo09** [comment]
#2727 ## Points
- IWeightsManager has map of <"pointer to the weight to be transformed","vector of ITransformWeights"
- ITransformWeights is not only contains a weight, but also has a transformation function. It runs only once while run(), called in Kernel Layer's prepare().


### 1. ITransformWeights is not a weight itself, it also has weight transform function.
```c++
/** Basic function to run @ref NEConvertFullyConnectedWeightsKernel. */
class NEConvertFullyConnectedWeightsManaged : public ITransformWeights
{
public:
    void run() override
    {
        _output.allocator()->allocate();
        _func.run();
        _reshape_run = true;
    }

    void release() override
    {
        _output.allocator()->free();
    }

    ITensor *get_weights() override
    {
        return &_output;
    }

    uint32_t uid() override
    {
        return _uid;
    }

    void configure(const ITensor *input, const TensorShape &original_input_shape, DataLayout data_layout)
    {
        _func.configure(input, &_output, original_input_shape, data_layout);
    }

private:
    static constexpr uint32_t      _uid = 0x4;
    Tensor                         _output{};
    NEConvertFullyConnectedWeights _func{};
};
```
- run : runs weight transformation and set _reshape_run true. Generated weight tensor is at _output.
- release : free _output's memory
- get_weights : get _output
- uid : Each weight transform class has unique uid.
- _func : weight transformation function

### 2. usage
#### Layer's configure
- _weights_manager->manage(weights) : register weights into the map
- _are_weights_reshaped : reshape is done once even if prepare is called multiple times
-  _reshape_weights_managed_function.configure(compile_context, weights); : weight is registered as _input here.
```c++
void CLFullyConnectedLayer::configure
...
    _original_weights      = weights;

    if(_weights_manager)
    {
        _weights_manager->manage(weights);
    }
...
    // Reshape weights if needed
    if(!_are_weights_reshaped)
    {
        if(_weights_manager && _weights_manager->are_weights_managed(weights))
        {
            _reshape_weights_managed_function.configure(compile_context, weights);
            weights_to_use = utils::cast::polymorphic_downcast<ICLTensor *>(_weights_manager->acquire(weights, &_reshape_weights_managed_function));
        }
```

#### Layer's prepare
- _weights_manager->run() :  if _weights_manager exists and weights is registered(managed).
 - returns transformed weight.
```c++

void CLFullyConnectedLayer::prepare()
...
    if(!_is_prepared)
    {
...
// Reshape of the weights if needed (happens only once)
        if(!_are_weights_reshaped)
        {
            if(_weights_manager && _weights_manager->are_weights_managed(_original_weights))
            {
                cur_weights = utils::cast::polymorphic_downcast<ICLTensor *>(_weights_manager->run(cur_weights, &_reshape_weights_managed_function));
            }
            else
            {
                // Run reshape weights kernel and mark weights as unused
                _reshape_weights_output.allocator()->allocate();
                _reshape_weights_function.run();

                cur_weights->mark_as_unused();
                cur_weights = &_reshape_weights_output;
            }
            _are_weights_reshaped = true;
```

#### WeightManager's run
- weights_transform : ITransformWieghts
- weights_transform->is_reshape_run() : check if function already run and made output tensor. Runs only once. 
- weights_transform->run() : performs transform
- 
```c++
    // Find if I have the same weights with weights transform. If I do, don't run the reshape
    auto     item = _managed_weights.find(weights);
    bool     perform_run{ true };
    ITensor *weights_tensor{ nullptr };

    // Check if I already have the requested transform and I have run the reshape function
    for(auto it : item->second)
    {
        if(it->is_reshape_run() && (it->uid() == weights_transform->uid()))
        {
            weights_tensor = it->get_weights();
            perform_run    = false;
            break;
        }
    }

    if(perform_run)
    {
        weights_transform->run();
        weights_tensor = weights_transform->get_weights();
    }
```

### 3. WeightManager map's second is vector of `ITransformWeights`.

- By acquire(const ITensor *weights, ITransformWeights *weights_transform), you can get the given weights_transform(in args)'s output.

#### WeightManager's run
```c++
//IWeightsManager::acquire
ITensor *IWeightsManager::acquire(const ITensor *weights, ITransformWeights *weights_transform)
{
    ARM_COMPUTE_ERROR_ON_MSG(!are_weights_managed(weights), "Cannot acquire weights. Weights are not managed");

    ITensor *transformed_weights{ nullptr };
    auto     item = _managed_weights.find(weights);

    // Check if I already have the requested transform. If I do,
    // increase the refcount of the transformed weights object and
    // reuse the tensor
    for(auto it : item->second)
    {
        if(it->uid() == weights_transform->uid())
        {
            transformed_weights = it->get_weights();
            it->increase_refcount();
            break;
        }
    }

    if(transformed_weights == nullptr)
    {
        transformed_weights = weights_transform->get_weights();
        weights_transform->increase_refcount();
        item->second.emplace_back(weights_transform);
    }

    // Manage the weights and store link to the parent node
    manage(transformed_weights, weights_transform);

    return transformed_weights;
}
```
```c++

//IWeightsManager::run
    // Check if we can release memory from parent
    auto parent_item = _managed_weights_parents.find(weights);
    if(parent_item != _managed_weights_parents.end())
    {
        int32_t refcount = parent_item->second->decrease_refcount();
        if(refcount == 0)
        {
            parent_item->second->release();
        }
    }

    // Check top level weights. If all the transformations are done
    // mark the weights as unused
    if(_managed_weights_parents.find(weights) == _managed_weights_parents.end())
    {
        auto item           = _managed_weights.find(weights);
        bool mark_as_unused = true;
        for(auto it : item->second)
        {
            if(!it->is_reshape_run())
            {
                mark_as_unused = false;
                break;
            }
        }

        if(mark_as_unused)
        {
            weights->mark_as_unused();
        }
    }

    return weights_tensor;
}
```

**Comment by dayo09** [comment]
### STUDY : ACL's IWeightsManager (2) Overall

#### Abbreviations
```
_wm : _weight_manager
_wtf : _weight_transform_function (IWeightTransform class's, specific member function)
w : weight
w' : transformed_weight
```

#### Functions
- Layer->configure
  -  _wm->manage(w)  // register weight as managed weight
  - _wtf->configure(w)  // configure wtf, input as weight
  - _wm->acquire(w, _wtf)  // get _output reference of _wtf with w, ref_count++ 

- Layer->prepare
  - _wm->run(w, _wtf) // run wtf function and generate transformed weight onto _output

- _wm->manage(w) // register original weight
  - _managed_weight[w]

- _wm->manage(w', _wtf) // register w' with _wtf as parent
  - _managed_weight[w]
  - _managed_weight_parent[w] = _wtf

- _wm->acquire(w, _wtf) 
  - ever been acquired : _wtf->ref_count++
  - never : _managed_weight[w]->second.emplace_back(_wtf) // register _wtf as w acquiring function
  - manage(w', _wtf) //register w' with _wtf as parent

_managed_weights : pair of <transformed_weight, vector<weight_transform_function>>
  - actually used as a set (??? to see)
  - check if the weights are managed or not

- _managed_weights_parents
  - pair of <transformed_weight, weight_transform_function>
  - map to find `from what function` `this weights` are transformed.

**Comment by dayo09** [comment]
### STUDY : ACL's IWeightsManager (3) WeightManager's scope

#### Where to make_shared<IWeightsManager>?
- There are 3 backends in ARMCOMPUTE - CL, GLES, NEON
- context has weights_management_ctx, which assigns WeightManager to each Target(Cl / GLES / NEON)
- CL, NEON uses WeightManager, GLES doesn't.

- summary : __each backends have unique wieghts manager in armcompute.__
```c++
// CLDeviceBackend.cpp
std::shared_ptr<arm_compute::IWeightsManager> CLDeviceBackend::create_weights_manager()
{
    auto weights_mgr = std::make_shared<IWeightsManager>();
    return weights_mgr;
}

//GCDeviceBackend.cpp
std::shared_ptr<arm_compute::IWeightsManager> GCDeviceBackend::create_weights_manager()
{
    return nullptr;
}
...
void CLDeviceBackend::setup_backend_context(GraphContext &ctx)
{
    // Create function level weights manager
    if(ctx.weights_management_ctx(Target::CL) == nullptr)
    {
        WeightsManagerContext wm_ctx;
        wm_ctx.target = Target::CL;
        wm_ctx.wm     = create_weights_manager();

        ctx.insert_weights_management_ctx(std::move(wm_ctx));
    }
// GraphContext.cpp
WeightsManagerContext *GraphContext::weights_management_ctx(Target target)
{
    return (_weights_managers.find(target) != std::end(_weights_managers)) ? &_weights_managers[target] : nullptr;
}

...

//NEDeviceBackend.cpp
std::shared_ptr<arm_compute::IWeightsManager> NEDeviceBackend::create_weights_manager()
{
    auto weights_mgr = std::make_shared<IWeightsManager>();
    return weights_mgr;
}
```

**Comment by dayo09** [comment]
## STUDY : ACL's IWeightsManager (4) Is it not sharing weights between layers?

```c++
ITensor *IWeightsManager::acquire(const ITensor *weights, ITransformWeights *weights_transform)
```
```c++
//void CLFullyConnectedLayer::configure
weights_to_use = utils::cast::polymorphic_downcast<ICLTensor *>(_weights_manager->acquire(weights, &_reshape_weights_managed_function));
...

```c++
//class CLFullyConnectedLayer
    weights_transformations::CLFullyConnectedLayerReshapeWeightsManaged _reshape_weights_managed_function;
```

If there are multiple `CLFullyConnectedLayer` instances, also are multiple `_reshape_weights_managed_function` members.
Address of them are different, so `acquire` with different `weights_transform` cannot obtain same 'transformed weight', even if the tensor is same.

So, ARMCOMPUTE's WeightsManager doesn't seem support sharing tensors between layers.

**Comment by ragmani** [comment]
> So, ARMCOMPUTE's WeightsManager doesn't seem support sharing tensors between layers.

Is this investigation finished? I think the consideration of sharing tensors is a good point in investigating a module of ACL. As far as I know, ACL doesn't consider sharing tensors at all, including `WeightsManager`. But onert supports sharing tensors. So I think we should consider how to handle sharing tensors, if we want to use a module of ACL that manages memory of tensors on onert.

In addition, some kernels(or layer) of ACL don't support weights as non-constant. But onert supports weights as non-constant. I think it would be more better to investigate `WeightsManager` with consideration of it.

**Comment by dayo09** [comment]
@ragmani Thanks for adding the point that ACL does't support weights as non-constant, whereas onert does. 
Hereby, as the motivation of this issue was to support weight sharing, I am about to closing the issue for now. :-)
