### ISSUE TITLE
Compiler FE: daily compiler coverage failed

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#3123]
http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-compiler-coverage/ fails

```
02:27:14  -- Configure TFLITE2CIRCLE-CONVERSION-TEST
02:27:14  CMake Error at /home/jenkins_slave_coverage/workspace/nnfw/master/daily-compiler-coverage/compiler/tflite2circle-conversion-test/CMakeLists.txt:41 (get_target_property):
02:27:14    get_target_property() called with non-existent target "testDataGenerator".
02:27:14  
02:27:14  
02:27:14  -- Configure TFLITE2CIRCLE-CONVERSION-TEST - Done
02:27:14  -- Configuring incomplete, errors occurred!
```

from recent no 31 : http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-compiler-coverage/31/console

**Comment by seanshpark** [comment]
@mhs4670go , do you know what may be the problem?

**Comment by seanshpark** [comment]
Seems `infra/scripts/configure_compiler_coverage.sh` needs update

**Comment by mhs4670go** [comment]
`tflite2circle-conversion-test` should be built after `common-artfacts` is built. So I think we should add `common-artifacts` to script.

**Comment by seanshpark** [comment]
need to add `arser` too

**Comment by seanshpark** [comment]
done
