### ISSUE TITLE
[record-minmax] running without arguments

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#3193]
If we run `record-minmax` without any arguments, it aborts with core dump.

```
$ ./record-minmax
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid argument. You must have missed some argument.
Aborted (core dumped)
```

It would be better to show help message.

**Comment by seanshpark** [comment]
@mhs4670go , @jinevening , PTAL

**Comment by jinevening** [comment]
@mhs4670go , Can `arser` automatically print help messages when invalid arguments are given ?

**Comment by mhs4670go** [comment]
I posted PR:)

**Comment by seanshpark** [comment]
fixed :)
