### ISSUE TITLE
[imgdata2hdf5] Python script to convert raw image data to hdf5

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#3213]
The input dataset for the argument of `record-minmax` has the form of hdf5. Users may have difficulty in making hdf5 file, so we will provide `imgdata2hdf5.py`, a Python script that converts raw data to hdf5 (only for image data for now)

![image](https://user-images.githubusercontent.com/5449554/87745755-b985f600-c829-11ea-82c0-a16e9fb133d8.png)

Input of `imgdata2hdf5.py` : data list (text file)
Output of `imgdata2hdf5.py` : hdf5 file which can be used by `record-minmax`

**Comment by jinevening** [comment]
## Example
```
python imgdata2hdf5.py \
> --input_path=tmp/imgdata/data
> --data_list=tmp/imgdata/datalist.txt
> --output_path=tmp/imgdata/imgdata.hdf5
```

## Arguments
```
  -h, --help            Show this help message and exit
  -i INPUT_PATH, --input_path INPUT_PATH
                        Path to the directory where the raw image data files are saved.
  -l DATA_LIST, --data_list DATA_LIST
                        Path to the text file which lists the raw image data files to be converted.
  -o OUTPUT_PATH, --output_path OUTPUT_PATH
                        Path to the output hdf5 file.
```

**Comment by seanshpark** [comment]
Just curious. if we gather all the image files in the `input_path`, then `data_list` is needless.
if some files are tobe exluced then not all files are used so list is needed. is this the reason of `data_list` file existance?
or if `data_list` all items has absolute path then `input_path` maybe needless.

**Comment by jinevening** [comment]
> if some files are tobe exluced then not all files are used so list is needed. is this the reason of data_list file existance?

Yes. data_list is for allowing users to exclude un-wanted files.

> just another thought, if data_list all items has absolute path then input_path maybe needless.

I agree with you.

> if there are hundreds or thousands images, preparing this data_list is a task.
I think not doing this task would help users...
or is there some simple way for this?

I agree that it can be a burden for some users. Using data_list is an idea from @lemma (AFAIK, SNPE quantization tool supports such an interface). @lemmaa what do you think of this issue?

**Comment by lemmaa** [comment]
@jinevening , @seanshpark , shouldn't we support both `--input_path` and `--data_list`? 
Both have their own advantages. `--input_path` eliminates the inconvenience of list creation, and `--data_list` supports selective test set configuration without moving the target file. (You can mix and use data from multiple directories) 

Basically, I expect to use one of them exclusively according to users choice.

If both are used, `--input_path` can be used to set the BASE_PATH, and --data_list can be used to select only the necessary data in the path. Of course, this is a problem that can be solved by writing two `--data_lists`, so we don't care to support this cae. :)

**Comment by lemmaa** [comment]
> AFAIK, SNPE quantization tool supports such an interface

@jinevening , FYI, SNPE supports only `--data_list`. :)

https://developer.qualcomm.com/docs/snpe/tools.html#tools_snpe-dlc-quantize

```
--input_list=<val>    Path to a file specifying the trial inputs. This file should be a plain text file,
                        containing one or more absolute file paths per line. These files will be taken to constitute
                        the trial set. Each path is expected to point to a binary file containing one trial input
                        in the 'raw' format, ready to be consumed by SNPE without any further modifications.
                        This is similar to how input is provided to snpe-net-run application.
```

**Comment by seanshpark** [comment]
@lemma, using only one looks good. from the example @jinevening provided didn't reflect this. from only with the option description, it is bit hard to understand. it would be better to provide examples so that users can choose.

**Comment by jinevening** [comment]
@seanshpark I've updated the example

**Comment by s-barannikov** [comment]
@jinevening What about preprocessing / uint8 support? Or is it planned for very limited uses?

**Comment by jinevening** [comment]
> @jinevening What about supporting:
- preprocessing
- network types other than image classification
- multiple inputs
Or is it planned for very limited uses?

`imgdata2hdf5` is a tool for image data (as its name implies). It would be good to make a general tool (raw data -> hdf5), but I have no plan for that now (this tool is for user convenience, so I made it as simple as possible).

Your Python interface looks very convenient (it looks similar to the Python interface of TFLite quantizer). If the Python interface is supported, we will not need translation (data -> hdf5) tools. I thought users can easily generate hdf5 file by just packaging raw data at the end of their pre-processing Python scripts. But everybody except me thinks that users will have difficulty on making the hdf5 file, so I'm ok to remove hdf5 in the tool chain (it will make the release process much easier as well).

**Comment by s-barannikov** [comment]
@jinevening 
I see, thanks.

**Comment by jinevening** [comment]
I close this issue because this job is done.

**Comment by jinevening** [comment]
I leave this comment to share example images.

[img_files.tar.gz](https://github.com/Samsung/ONE/files/5498415/img_files.tar.gz)
