### ISSUE TITLE
[cker/ruy] To enable dealloc cosnt backend tensors on cpu/ruy

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE#3225]
Current ruy kernel process
1. a thread a ruy context
1. the ruy context has PrepackedCache structure to cache tensors
1. after caching job, onert can deallocate const backend tensors if possible(reference is zero)

Current problems
- by nnapi, an execution a thread so that cached tensor on ruy is disappeared. However, onert assumed it was cached so that dealloc the existing const backend tensor https://github.com/Samsung/ONE/issues/2929
- on cker's fc, if input is zero vector, cker takes it by using just activation not by ruy kernel. However, onert assumed it was cached so that dealloc the existing const backend tensor
  - FullyConnected.h's FullyConnectedHybrid()'s `if (IsZeroVector())`
- fc hybrid's const tensors' use count can be more than 1 such as 2, 4, and 8. However, onert assumed it was 1 and so that  FullyConnectedLayer has `_is_weights_freed`. It should be replaced by something different and global.
  - it could be fixed by https://github.com/YongseopKim/ONE/tree/test/fix_ruy_kernel_decrease_ref

onert can enable deallocating const tensors when cached if the above problems are solved.

cc/ @chunseoklee @periannath @dhdh-oh

**Comment by wateret** [comment]
> - by nnapi, an execution a thread so that cached tensor on ruy is disappeared. However, onert assumed it was cached so that dealloc the existing const backend tensor https://github.com/Samsung/ONE/issues/2929

Does "nnapi" here mean the original Android NN API implementation?

Does "onert" here mean cpu backend implementation? Just to clarify if we are talking about onert core or cpu backend 😄

**Comment by YongseopKim** [comment]
> Does "nnapi" here mean the original Android NN API implementation?
> Does "onert" here mean cpu backend implementation? Just to clarify if we are talking about onert core or cpu backend

Oops, very poor explanation :( 

the exact meaning is 
- "nnapi" -> nnapi of our frontend(runtime/onert/frontend/nnapi) https://github.com/Samsung/ONE/issues/2929#issuecomment-658557868 . By our nnapi frontend, an execution does on a thread.
- "onert" -> cker's cpu fc op. `FullyConnectedLayer::fullyConnectedHybrid()`

**Comment by ragmani** [comment]
@YongseopKim 

> by nnapi, an execution a thread so that cached tensor on ruy is disappeared. However, onert assumed it was cached so that dealloc the existing const backend tensor #2929

From what I have heard, the problem that cached tensor on ruy is disappeared was caused by that `RuyContext` is thread_local. Now is this still a problem by onert's assumption?

> on cker's fc, if input is zero vector, cker takes it by using just activation not by ruy kernel. However, onert assumed it was cached so that dealloc the existing const backend tensor

I didn't understand it well. Do you mean that there is an unused input on the ruy kernel, but onert keeps the unused input? And what is const backend tensor?

**Comment by YongseopKim** [comment]
@ragmani In fact, I don't understand your point.

> the problem that cached tensor on ruy is disappeared was caused by that RuyContext is thread_local. Now is this still a problem by onert's assumption?

 Is it meaning that the problem was caused by RuyContext is thread_local and the problem is not resolved yet?
- If so, not resolved yet. It will be solved by https://github.com/Samsung/ONE/pull/3559

> there is an unused input on the ruy kernel, but onert keeps the unused input?

No. I meant the input could be a vector filled with zero. In the case, the input doesn't enter fc() function. You can see the code.
https://github.com/Samsung/ONE/blob/7c708f8a84e5ffb9866fb2a6aca63978fb9986aa/compute/cker/include/cker/operation/FullyConnected.h#L164-L168

> what is const backend tensor?

I meant the constant tensors which are managed by each backend.

**Comment by ragmani** [comment]
> If so, not resolved yet. It will be solved by #3559

I got it. I was curious if it was a problem not related to #3559. 

> No. I meant the input could be a vector filled with zero. In the case, the input doesn't enter fc() function. You can see the code.

I think there is no problem except unused input. What the problem there? Unused weights?

**Comment by YongseopKim** [comment]
@ragmani 

> I got it. I was curious if it was a problem not related to #3559.

thank you for your intereating :) 

> I think there is no problem except unused input. What the problem there? Unused weights?

Before answering your ask, I need to check one thing. Your `unused input` is `a vector filled with zero`? I'm actually confused why you use the word `unused`. 

If Your `unused input` is `a vector filled with zero`, no problem now but there was a problem. https://github.com/Samsung/ONE/pull/3446 fixed.

FYI, let me explain #3446 
- If Ruy kernel caches const tensors, onert deallocates the const tensors because Ruy kernel has already them(copied).
- Because Ruy kernel caches when execution(`fn->run()` not `fn->prepare()`), the first `fn->run()` caches and then run fc-hybrid.
- But sometime inputs are vectors filled with zero so that the flow didn't enter the step for Ruy kernel cache. (See my above comment.)
- Our rt assumed that the const tensors are already copied to ruy kernel so that deallocated them.
- And the second `fn->run()` runs with not input zero vector
- Ruy kernel tried cache and running fc-hybrid but const tensors are nullptr.

I hope you're satisfied.

**Comment by ragmani** [comment]
@YongseopKim 

> If Your unused input is a vector filled with zero, no problem now but there was a problem. #3446 fixed.

I see. Thanks for your explanation.
I didn't know it was already fixed. Sorry for asking unnecessary question.

**Comment by YongseopKim** [comment]
Resolved by #3318
