### ISSUE TITLE
[onert] Do we still need Interpreter?

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#3406]
As far as I remember, Interpreter(`interp` module) has been introduced to support models that cannot be compiled. And one big feature of the interpreter was supporting dynamic tensors. But now the compiler(onert module) supports it.

So now I wonder if it is worth maintaining the interpreter. Please let me know if I miss something.

cc: @hseok-oh

**Comment by hseok-oh** [comment]
@wateret 

>And one big feature of the interpreter was supporting dynamic tensors. But now the compiler(onert module) supports it.

You're right. The only things different with compilation is that interpreter is supporting asynchronous run.

**Comment by lemmaa** [comment]
@wateret , isn't that an important component in supporting your plan JIT? Assuming we of course extend it to adaptive JIT. :)

**Comment by wateret** [comment]
@lemmaa No, I don't have plans for adaptive JITC. What I was planning was just generating "a JIT compiled executor" rather than using the current executors to reduce indirect call costs.

Actually I would like to remove Interpreter if it is possible, to reduce maintenance cost for those code.
