### ISSUE TITLE
[nnfwapi] Introduce in-memory model loading API and model-building tool

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#3503]
NN API has model-building API, can we have (internal) API just like it?

```c
ANeuralNetworksModel_addOperand(ANeuralNetworksModel *model, const ANeuralNetworksOperandType *type);
ANeuralNetworksModel_addOperation(ANeuralNetworksModel *model, ANeuralNetworksOperationType type, uint32_t inputCount, const uint32_t *inputs, uint32_t outputCount, const uint32_t *outputs);
ANeuralNetworksModel_create(ANeuralNetworksModel **model);
ANeuralNetworksModel_finish(ANeuralNetworksModel *model);
ANeuralNetworksModel_free(ANeuralNetworksModel *model);
ANeuralNetworksModel_identifyInputsAndOutputs(ANeuralNetworksModel *model, uint32_t inputCount, const uint32_t *inputs, uint32_t outputCount, const uint32_t *outputs);
ANeuralNetworksModel_setOperandValue(ANeuralNetworksModel *model, int32_t index, const void *buffer, size_t length);
...
```

This API is useful especially when we make test cases. We have been struggling creating simple test cases as NNPackage(serialized). Even if it is so simple, it must be in the format of NNPackage directory. Plus it has to be uploaded on the server and downloaded before running the tests.

Some ideas for implementation

- Introduce one more state in `nnfw_api_internal.h` "MODEL_BUILDING"
- The usage example is almost something like `runtime/onert/test/core/exec/ExecInstance.cc` (but with C wrappers we are creating)
- Can we reuse `base_loader`'s operation generation? → This is the most important part IMO

**Comment by hseok-oh** [comment]
>This API is useful especially when we make test cases

👍

**Comment by wateret** [comment]
> Can we reuse `base_loader`'s operation generation?

We can't, as it is Flatbuffer generated code specific.

**Comment by wateret** [comment]
So operation generation(api to runtime in-memory structure) is very time-consuming.

**Comment by hseok-oh** [comment]
We need to introduce new frontend for test 
- NNAPI-like and simple API to make model graph 
- Use operation/operand IR directly if possible
- Simple API to set input, get output

**Comment by hyunsik-yoon** [comment]
> Use operation/operand IR directly if possible

I attached some code fragment from compiler just for reference:
```c++
  auto pull = make_node<loco::Pull>();  // Pull is input node
  {
    pull->dtype(loco::DataType::FLOAT32);
    pull->shape({1, 8, 8, 3});
  }
  auto relu6 = make_node<loco::ReLU6>();
  {
    relu6->input(pull);
  }
  auto push = make_node<loco::Push>();  // Push is output node
  {
    push->from(relu6);
  }

  auto input = graph()->inputs()->create();
  {
    input->name("input");
    loco::link(input, pull);
  }
  auto output = graph()->outputs()->create();
  {
    output->name("output");
    loco::link(output, push);
  }

  exo::TFLExporter::Impl exporter{graph()};
 ...
```

**Comment by wateret** [comment]
@hseok-oh @hyunsik-yoon 

> - Use operation/operand IR directly if possible

Thank you for the comments. IMHO they are C++ and there are too many headers to expose then. (even if it is just for `nnfw_internal.h`)

**Comment by wateret** [comment]
Things that has been considered

### Reusing NNAPI (X)

For adding operation, what about reusing OperationFactory?

However it will have dependency on NN API, and NN API does not have same semantics with TFLite/Circle.

### Reusing CircleLoader (X)

In order to do that, we need to expose `circle_schema_generated.h` and it does not make sense.

This is also not good in many ways.

**Comment by wateret** [comment]
### In-memory CIRCLE generation

As the main purpose of this is to make testing easier, so we can provide a CIRCLE file generator instead of providing model-building API. And i think it can be done by creating a wrapper for `circle_schema_generated.h` which is not dependent on nnfw API.

In this way, the only API that needs to be added is loading in-memory CIRCLE file.
