### ISSUE TITLE
Compiler FE: out of memory handling of tf2tfliteV2

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#3629]
Our _tf2tfliteV2.py_ is "killed" but the system when memory goes short.
It would be better to handle this to show some message not scary "killed".

Execution environment: Docker + Ubuntu XX + nncc 1.6.1

**Comment by seanshpark** [comment]
Experiment with release 1.6.1 (as our client used this version)
- Run with `tf2nnpkg` program
- Run inside virtual machine + Ubuntu16.04 server + 8G + 1G swap + tensorflow-cpu==2.3.0rc0
   - showed `MemoryError: std::bad_alloc` in `--v2` option and then conversion OK with `--v1` option

**Comment by lemmaa** [comment]
Just for the record, The cause of this problem was OOM at the time of compilation, and solved by using the official release version of Tensorflow 2.3.0.

**Comment by seanshpark** [comment]
closing as issue is now solved
