### ISSUE TITLE
Compiler FE: Introducing CircleFileExporter to reduce duplicate codes

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#3667]
When saving a luci module to a circle file, we use `CircleExporter`, which requires `CircleExporter::Contract` for its argument. For example,

```
  luci::CircleExporter exporter;
  CircleExpContract contract(module.get(), output_path);     // Implementation of CircleExporter::Contract
  if (!exporter.invoke(&contract))
  {
    std::cerr << "ERROR: Failed to export '" << output_path << "'" << std::endl;
    return 255;
  }
```

The problem is that `CircleExporter::Contract` needs to be implemented in each project, increasing duplicate codes. I found four modules have `CircleExpContract.h` and `CircleExpContract.cpp` which have the same implementation of `CircleExporter::Contract`.

```
hjj@hjj-ubuntu:~/ONE/compiler$ find . -name CircleExpContract*
./luci-value-test/tester/src/CircleExpContract.h
./luci-value-test/tester/src/CircleExpContract.cpp
./record-minmax/src/CircleExpContract.h
./record-minmax/src/CircleExpContract.cpp
./circle-quantizer/include/CircleExpContract.h
./circle-quantizer/src/CircleExpContract.cpp
./circle2circle/include/CircleExpContract.h
./circle2circle/src/CircleExpContract.cpp
```

I'd like to make `CircleFileExporter`, a class that exports a luci module to a circle file without need for implementing `CircleExporter::Contract`, to remove the duplicate codes.

One issue is to determine where to implement `CircleFileExporter` (making a separate module ? or under the `luci` directory?).

**Comment by seanshpark** [comment]
I think method to store to a file with filename parameter and others can be provided in `CircleExporter.h` file as inline function.

**Comment by jinevening** [comment]
> I think method to store to a file with filename parameter and others can be provided in CircleExporter.h file as inline function.

Making a method rather than a separate class would be simpler. I'll make `exportToFile` in `CircleExporter` class.

**Comment by jinevening** [comment]
I close this issue because all related PRs were merged.
