### ISSUE TITLE
[onert] Refactoring : Make Operand's Def operation as a single element

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#3719]
```cpp
class Operand
{
  OperandInfo _info;
  std::shared_ptr<Data> _data;

  OperationIndexSet _uses;
  OperationIndexSet _def; // size is 0 (constant) or 1 (from def operation)
};
```

As all the operands can be defined by just one operation, so having `_def` as `OperationIndexSet` could be confusing. Let's make it a more appropriate type. (If this change does not require the runtime structural changes)

**Comment by periannath** [comment]
I did a quick search and found that `NON_MAX_SUPPRESSION_V4` and  `NON_MAX_SUPPRESSION_V5` operation has multiple outputs. https://www.tensorflow.org/lite/guide/ops_compatibility
If we are going to support those operations later, it is better to maintain `_def` as `OperationINdexSet`.

**Comment by wateret** [comment]
Done by #3726
