### ISSUE TITLE
[luci-interpreter] Use Tensorflow version 2.3.0

### ISSUE THREAD

**Issue by struss** [Samsung/ONE#3785]
Current luci-value test use a TFlite version 2.3.0. 

So, update luci interpreter to use TFlite version 2.3.0.

**Comment by s-barannikov** [comment]
@struss Could you please post the linker error you've got in #3740?

**Comment by struss** [comment]
@s-barannikov sorry for late the main message is below
```
../luci-interpreter/src/libluci_interpreter.so: undefined reference to `tflite::QuantizeMultiplier(double, int*, int*)'
```
and this is comes from `Mean` kernel

**Comment by s-barannikov** [comment]
@struss Thank you. I found the code that causes the issue.
I support @mhs4670go's suggestion to add `quantization_util.cc` to the list of files.
Alternatively, you could switch to `reference_ops` for the `Mean` kernel. It may be simpler, but it has a side effect of decreased performance.

**Comment by struss** [comment]
TODO
1. Add Ruy and GEMMLowp Source on infra.
2. update Cmake file in `luci-interpreter/kernels`
3. update kernel function on leakyrelu, just add more optional values.
4. update mul to use optimized kernels
5. update TransposeConv...... -> TODO list is now preparing.

**Comment by struss** [comment]
Updated! and also fix TransposeConv for this version would real end!

**Comment by struss** [comment]
#3985 merged! Version up End! Thanks for all!
