### ISSUE TITLE
[nnpackage_run] Automatically get input shape/output size when load/dump options are given

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#3840]
I think these are possible and it would be nice to do them for our convenience.

- When a file is given for `--load`, we also know the input shape for `--shape_run`(or maybe `--shape_prepare`)
- When a file is given for `--dump`, we also know the output size for `--output-sizes`

**Comment by glistening** [comment]
@wateret Do you want to override the model's input and output shape using the shape of input or output hdf5 data when `--load` or `--dump` are given? It may cause somewhat unintended effect. At least for tflite model, it has `signature` whether it could be resized or not though we don't use `signature` at all for simplicity.

**Comment by wateret** [comment]
@glistening You're right. That must take into account.

**Comment by hyunsik-yoon** [comment]
@wateret I need this feature ASAP to test a model I am working on nowadays. Can I work on this?

**Comment by hyunsik-yoon** [comment]
1. regarding `shape_signature`
- I tried to get shape of input with unknown dim by calling `nnfw_input_tensorinfo(..)` but it returns `1` as its dim.
  - Our loader code also put `1` as a dim of unknown dim. https://github.com/Samsung/ONE/blob/master/runtime/onert/frontend/base_loader/include/base_loader.h#L317-L330
- To get `shape signature`, we may need to redesign `nnfw_input_tensorinfo(..)` but this is over the scope of this issue. So I will not consider `shape signature` with this issue.
2. for `--output-sizes`, when a model's output is dynamic tensor, I think that there is no way for onert to know the size before running the model. So I will not consider `--output-sizes` in this issue.

**Comment by glistening** [comment]
@hyunsik-yoon 

> Our loader code also put 1 as a dim of unknown dim. https://github.com/Samsung/ONE/blob/master/runtime/onert/frontend/base_loader/include/base_loader.h#L317-L330

I cannot find the code put `1` as dim of unknown dim. `base_loader` just seems to read the shape's dim of `.tflite`.
Do you have any model example that has unknown dim in input shape?

**Comment by hyunsik-yoon** [comment]
@glistening 
The big test model I am working on has known dim.
Also we have a model with unknown dim as one of nnfw API test. Please find `T(0:0)` in the following (screenshot of `tfldump` program of ONE compiler):

<details>

```

# unknown_dim_input_concat.zip (zipped nnpackage) is downloaded 
# when `./infra/scripts/test_ubuntu_runtime_mixed.sh` runs. 
# The file can also be found in the model server.

$ ./build/compiler/tfldump/tfldump ./Product/out/unittest_standalone/nnfw_api_gtest_models/unknown_dim_input_concat/unknown_dim_input_concat/unknown_dim_input_concat.tflite 
Dump: ./Product/out/unittest_standalone/nnfw_api_gtest_models/unknown_dim_input_concat/unknown_dim_input_concat/unknown_dim_input_concat.tflite

===================================================================
Model version: 3
 # sub graphs: 1

Operator Codes: [order] OpCodeName (OpCode Enum)
[0] CONCATENATION (code: 2, version: 1)

Buffers: B(index) (length) values, if any
B(0) (0) 
B(1) (0) 
B(2) (0) 
B(3) (0) 
B(4) (16) 0x31 0x2e 0x35 0x2e 0x30 00 00 00 00 00 00 00 00 00 00 00 ...

-------------------------------------------------------------------
Sub-Graph: #0 main

Operands: T(subgraph index : tensor index) TYPE (shape) (shape_signature) B(buffer index) OperandName
T(0:0) FLOAT32 (1, 1) (-1, -1) B(1) INPUT1
T(0:1) FLOAT32 (2, 3) B(2) INPUT2
T(0:2) FLOAT32 () B(3) CONCAT

Operators: O(subgraph index : operator index) OpCodeName 
    Option(values) ... <-- depending on OpCode
    I T(tensor index) OperandName <-- as input
    O T(tensor index) OperandName <-- as output
O(0:0) CONCATENATION 
    Activation(NONE) Axis(0)
    I T(0:0) INPUT1
    I T(0:1) INPUT2
    O T(0:2) CONCAT

Inputs/Outputs: I(input)/O(output) T(tensor index) OperandName
I T(0:0) INPUT1
I T(0:1) INPUT2
O T(0:2) CONCAT

===================================================================

```

</details>

AFAIK, tflite converter converts a TF tensor of shape `[None]` to a tflite tensor with `[1]` as shape, `[-1]` as shape signature.

**Comment by glistening** [comment]
@hyunsik-yoon Thank you. Your statement makes it clear.

> AFAIK, tflite converter converts a TF tensor of shape [None] to a tflite tensor with [1] as shape, [-1] as shape signature.

**Comment by wateret** [comment]
@hyunsik-yoon Please close this if it is done 😄

**Comment by hyunsik-yoon** [comment]
Thanks for noticing me. :-)
