### ISSUE TITLE
Tizen aarch64 error

### ISSUE THREAD

**Issue by kparichay** [Samsung/ONE#3846]
Using `one` (nnfw) runtime backend on `aarch64` with `acl_neon` backend results in `illegal instruction error`.

More details.
unittest file - tests/tizen_nnfw_runtime/unittest_nnfw_runtime_raw.cpp
unittest name - nnstreamer_nnfw_mlapi.invoke_single_00
Error details - on aarch64 architecture, this unittest fails with the call nnfw_prepare() with error qemu: uncaught target signal 4 (Illegal instruction) - core dumped. The backend set in this test is acl_neon and model file used is ./tests/test_models/models/add.tflite

Note that this same unittest with the described configuration runs successfully on armv7l.

More details on https://github.com/nnstreamer/nnstreamer/pull/2649

**Comment by hseok-oh** [comment]
@kparichay Did you run on qemu?

**Comment by kparichay** [comment]
Yes.

**Comment by hseok-oh** [comment]
We don't test on qemu environment, so we cannot be convinced that arm compute library backend work correctly on qemu environment.

**Comment by kparichay** [comment]
ok, I will disable using `acl_neon` backend on qemu environment.
Thanks for your response.
