### ISSUE TITLE
[luci] Introduce negative tests for the number of inputs of Circle nodes

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#39]
This issue is not urgent, but may be useful in the future.

A Circle node has constraints on the number of its inputs (e.g., ```CircleAbs``` must have only one input). Accessing inputs out of its range must be handled properly, e.g., throwing an exception. It would be worthwhile to introduce negative tests for these cases.

Example
```
TEST(CircleAbsTest, arity_NEG)
{
  luci::CircleAbs abs_node;
  // CircleAbs must have only one input
  ASSERT_NO_THROW(abs_node.arg(0));
  ASSERT_THROW(abs_node.arg(1), std::out_of_range);
}
```

**Comment by seanshpark** [comment]
This idea is applied :) Close?

**Comment by jinevening** [comment]
> This idea is applied :) Close?

Yes. I'll close the issue :)
