### ISSUE TITLE
[onert] Use MMapedData or CachedData?

### ISSUE THREAD

**Issue by periannath** [Samsung/ONE#3961]
On master, model is loaded as `MMapedData`. However, model is loaded as `CachedData` on release 1.8.0 since `MMapedData` produces performance degradation on some models. #3817 

Should we use `CachedData` on master branch the same as release 1.8.0?

Here is the comparison of `MMapedData` and `CachedData`

### MMapedData
- Using mmaped model file
- Pros
  - Fast model load time
  - Low memory usage at model load
- Cons
  - Overhead in inference

### CachedData
- Allocated memory using malloc
- Pros
  - Fast inference
- Cons
  - Slow model load time
  - High memory usage at model load

/cc @YongseopKim @chunseoklee

**Comment by chunseoklee** [comment]
IMHO, we should go for cached data since `Overhead in inference` is too risky.

**Comment by periannath** [comment]
I've uploaed #4007 to use `CachedData` instead of `MMapedData`.

**Comment by hyunsik-yoon** [comment]
Can I ask a question? I wonder why mmaped data has overhead in inference. Could you explain a bit? Thanks!

**Comment by YongseopKim** [comment]
> IMHO, we should go for cached data since Overhead in inference is too risky.
If so, what about introducing a build option which could choose one btw CachedData and MMapedData? TFLite also supports like that - `BUILD_WITH_MMAP`.

**Comment by periannath** [comment]
@hyunsik-yoon During the inference, runtime should read weight values from model file. When using `CachedData`, all the weight values are always resident on RAM.
However, `MMapedData` has page fault overhead since it should read weight values from disk if it is not exist in page cache. I'm not sure about the number of increment of page fault, but I suspect it cause increment in inference time.

**Comment by periannath** [comment]
@YongseopKim Thanks. It looks good to me. I'll upload the following PR after #4007 is merged.

**Comment by s-barannikov** [comment]
> If so, what about introducing a build option which could choose one btw CachedData and MMapedData?

I think it would be better to choose the behavior dynamically (environment variables or such), so that the user can choose what is best for them -- lower memory footprint or faster inference.

**Comment by periannath** [comment]
Closing this issue since `USE_MMAPED_DATA` option is added to used `MMapedData`.
