### ISSUE TITLE
Propagating quantization parameters of Concatenation Op

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#4004]
## In brief
We can remove rescaling in Concat Op by propagating the quantization parameters of the output of Concat Op to its inputs.

## Motivation

Let's assume inputs of Concat Op are quantized with different quantization parameters (scale, zp).

Concat Op not only just concatenates the input tensors but also rescales the values of the input tensors to make them have the same quantization parameters with the output tensor. Rescaling requires floating point division, multiplication and rouding ([link](https://github.com/Samsung/ONE/blob/master/compute/cker/include/cker/operation/Concatenation.h#L140-L146)), introducing computational overheads. Moreover, for the integer-based hardware such as npu, rescaling is approximated using shift and multiplication, which inevitably causes loss of precision.

![image](https://user-images.githubusercontent.com/5449554/91246426-bff18100-e78a-11ea-88c0-a9c17e139937.png)

For example, in the above graph (captured in Inception V3), Concat Op rescales the values of the input tensors (1)~(4) to have the same quantization parameters with the output tensor (5).

## Optimization chance

If we know the quantization parameters of the output tensor of the Concat Op before running the model (i.e., activations were statically quantized), we can avoid rescaling in Concat Op by overwriting the output tensor's quantization parameters to the input tensors.

## Issues

1. Subsequent concats.
  \- If an output of concat Op is given as an input of another concat Op, the quantization parameters of the later concat can be propagated to the upper concat. For example, in the below figure, quantparams of (5) can be propagated to (1), (2), (3), (4).

![image](https://user-images.githubusercontent.com/5449554/91371902-3ce52f00-e84d-11ea-910c-2acb923561ac.png)

 \- It seems that TFLite converter converts subsequent concats into one concat. (Subsequent concats in the pb file of InceptionV3 are replaced with one concat in tflite). Since ONE is using TFLite converter, **we will not consider subsequent concats for now**.

2. We should not propagate quantparams to an input tensor produced to other Ops.
 \- Overwriting quantparams to such an input tensor would affect the result of other Ops (e.g., concat in AI sound model).
 \- For example, in the below figure, if quantparams of (3) is propagated to (1) and (2), the result of `conv2` will be distorted as the quantparams of (1), i.e., the input of `conv2`, changes. Therefore we only overwrite (3) to (2) and leave (1) as-is.

![image](https://user-images.githubusercontent.com/5449554/91373402-45d7ff80-e851-11ea-9a57-cea9e03e945a.png)

**Comment by s-barannikov** [comment]
3. Some Concat inputs may not support the new quantization parameters. For instance, Softmax requires its output scale to be 1 / 256.
4. Changing quantization parameters of the network input tensors will change the computation results. Changing quantization parameters of constant tensors will require requantizing the constant data.

> Rescaling requires floating point division, multiplication and rouding (link), introducing computational overheads.

As long as TFLite is concerned, there will be no performance improvement. The data will still be rescaled (no-op), because it does not check whether the quantization parameters are the same or not.

**Comment by jinevening** [comment]
Thanks for the feedback.

> 3. Some Concat inputs may not support the new quantization parameters. For instance, Softmax requires its output scale to be 1 / 256.

Good point. TFLite restricts quantization parameters for some Ops. If we want to run the models with such Ops using TFLite kernels, we will need to follow the restrictions. But as far as I know, our target runtime does not have such restrictions so far. But I'll keep this issue in mind. 

> As long as TFLite is concerned, there will be no performance improvement. The data will still be rescaled (no-op), because it does not check whether the quantization parameters are the same or not.

I found the below code in `ConcatenationWithScaling` in TFLite source code. The code seems to check if the quantization parameters of input and output are the same.

```cpp
  for (int k = 0; k < outer_size; k++) {
    for (int i = 0; i < inputs_count; ++i) {
      const int copy_size = input_shapes[i]->Dims(axis) * base_inner_size;
      const uint8* input_ptr = input_data[i] + k * copy_size;
      if (input_zeropoint[i] == output_zeropoint &&
          input_scale[i] == output_scale) {
        memcpy(output_ptr, input_ptr, copy_size);
      } else {
        const float scale = input_scale[i] * inverse_output_scale;
        const float bias = -input_zeropoint[i] * scale;
        for (int j = 0; j < copy_size; ++j) {
          const int32_t value = static_cast<int32_t>(tflite::TfLiteRound(
                                    input_ptr[j] * scale + bias)) +
                                output_zeropoint;
          output_ptr[j] = static_cast<uint8_t>(
              std::max<int32_t>(std::min<int32_t>(255, value), 0));
        }
      }
      output_ptr += copy_size;
    }
```
