### ISSUE TITLE
Support gelu operator

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#4033]
Let's check new `gelu` operator in TF nightly (2.4.0-dev) version

**Comment by seanshpark** [comment]
tflite file from using `tf2tfliteV2.py` script: [gelu.tflite.zip](https://github.com/Samsung/ONE/files/5149413/gelu.tflite.zip)

**Comment by seanshpark** [comment]
CC @chunseoklee

**Comment by seanshpark** [comment]
Run in TF2.3.4 virtual env
```
    op_ = tf.nn.gelu(in_, approximate=True, name="Output")
AttributeError: module 'tensorflow._api.v2.nn' has no attribute 'gelu'
```

**Comment by chunseoklee** [comment]
> Run in TF2.3.0 virtual env. shows an error
> 
> ```
>     op_ = tf.nn.gelu(in_, approximate=True, name="Output")
> AttributeError: module 'tensorflow._api.v2.nn' has no attribute 'gelu'
> ```

This error is resolved by using TF-nightyly ?

**Comment by seanshpark** [comment]
> This error is resolved by using TF-nightyly ?

Yup :)

**Comment by seanshpark** [comment]
Added gelu.pbtxt file at https://github.com/Samsung/ONE/issues/4033#issuecomment-683660496

**Comment by seanshpark** [comment]
I think this can be closed
