### ISSUE TITLE
[onert][acl-cl] Enabling ARM_COMPUTE_ASSERTS

### ISSUE THREAD

**Issue by dr-venkman** [Samsung/ONE#4043]
I am implementing `SplitV` operation under `acl-cl` backend, and I find that the runtime fails when configured in debug mode (please refer #4011 for details).

The implementation for `SplitV` makes use of the `ARM_COMPUTE_ERROR...` macros defined at `externals/ARMCOMPUTE/arm_compute/core/Error.h`. So, conversely, when I comment out these calls, the tests pass successfully.

My issue is that I am currently unable to reproduce this problem on my working copy, despite the observation that in my `packaging/nnfw.spec` file, the `test_build` type is set to `Debug`.

I need to enable the macro `ARM_COMPUTE_ASSERTS_ENABLED`  in order to activate the macro calls, and reproduce the error. Could anyone please provide inputs on how to achieve this? Thanks in advance.

**Comment by hseok-oh** [comment]
>My issue is that I am currently unable to reproduce this problem on my working copy, despite the observation that in my packaging/nnfw.spec file, the test_build type is set to Debug.

Did you build by gbs with `--define 'test_build 1` --define 'build_type Debug' ?

**Comment by dr-venkman** [comment]
> > My issue is that I am currently unable to reproduce this problem on my working copy, despite the observation that in my packaging/nnfw.spec file, the test_build type is set to Debug.
> 
> Did you build by gbs with `--define 'test_build 1' --define 'build_type Debug'` ?

`--define 'test_build 1' - [x]
--define 'build_type Debug'` - No, I will enable this on my next build. Thanks for the information.
