### ISSUE TITLE
Compiler FE: Enable LOGICAL_AND Op

### ISSUE THREAD

**Issue by sun-sharma** [Samsung/ONE#406]
- [x]  res/TensorFlowPythonExamples
- [x]  res/TensorFlowLiteRecipes
- [x]  tflchef
- [x]  tfldump, circledump
- [x]  luci.IR
- [x]  luci.Import
- [x]  luci.Export
- [x]  luci.logex
- [x]  luci.Service
- [x]  tflite2circle
- [x]  luci.tests

For #277

**Comment by binarman** [comment]
@sun-sharma 
Is everything is done?

You can close this issue and draft if it is. =)

**Comment by seanshpark** [comment]
Seems done :) I can close but I'll let you, @sun-sharma, close :)
