### ISSUE TITLE
[onert] Copy elimination on subgraph calls 

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#4138]
Remove redundant copies between subgraph calls.

I'm thinking a way that making controlflow tensors can indirect another tensor. And when calling/returning just change the pointing tensor

**Comment by wateret** [comment]
This will take longer than I thought. I made a draft that works for some cases(not all, not uploaded yet). And I found out that I need to resolve other issues first.

**Comment by glistening** [comment]
@wateret I am happy to hear "copy elimination` and not not so happy because my model has only one subgraph.

`onert` has lots of redundant copies. Whenever I compare c++ native implementation and `onert` working`, I almost always find `onert` make redundant object (which requires allocations and copies). For example, `Reshape`, `StridedSlice` (when it is used like referencing index of array) ..., do you have plan to optimize those cases also?

**Comment by wateret** [comment]
> For example,Reshape, StridedSlice` (when it is used like referencing index of array) ..., do you have plan to optimize those cases also?

@glistening Sorry I don't get what you mean by that. Are you talking about compile-time copies or runtime copies? If it is the later, could you please elaborate the example? 😄

**Comment by glistening** [comment]
@wateret I meant the latter. For example, see ReshapeLayer.cc in cpu backend.

```c++
void ReshapeLayer::run() { reshapeGeneric(); }

void ReshapeLayer::reshapeGeneric()
{
  size_t count = _input->total_size();
  memcpy(_output->buffer(), _input->buffer(), count);
}
```

**Comment by wateret** [comment]
@glistening Thank you for your explanation. That is a very good point. For the Reshape case it looks like `onert` must support in-place operations, currently input and output must differ. StridedSlice looks trickier, but basically the same.

That one is present in my task list for 2021(in our secret repo),

> - Peephole Optimizations
>     - In-place calculation for supported operations (No need to allocate another tensor for outputs, the caluclation is done in the inputs)

I'm not saying I must be the one who works on it, though.

**Comment by wateret** [comment]
I just had second thoughts that Reshape and StridedSlice cases(and other in-place ops) can be handled from backend side, somewhat similar to Concat Elimination(acl backends).

**Comment by glistening** [comment]
@wateret In my target model, almost all `reshape`'s source is not used any longer. I would like to handle this case first in a few weeks. If you don't have plan, I will try.

**Comment by s-barannikov** [comment]
May be reuse the data pointed by a tensor instead of replacing the tensor? I.e. have two tensors (input and output of reshape) that share the same data. I thought concat elimination works this way.
Sorry if I misunderstood the issue.

**Comment by glistening** [comment]
> May be reuse the data pointed by a tensor instead of replacing the tensor? I.e. have two tensors (input and output of reshape) that share the same data. I thought concat elimination works this way.
> Sorry if I misunderstood the issue.

@s-barannikov I have the same idea. I will use `src`'s data pointer for `dst` data thought I don't know how `concat` works. 
I need to read memory allocator because it may break the assumption of our memory allocator.

**Comment by s-barannikov** [comment]
> I need to read memory allocator source

For me it is the most difficult part of the runtime >_<
Good luck! :)

**Comment by glistening** [comment]
> > I need to read memory allocator source
> 
> For me it is the most difficult part of the runtime.
> Tried to figure it out several times, but gave up >_<
> Good luck! :)

Totally agree. I hope I can this simple idea amidst complex memory allocator. I am sure I will fail to figure out it for multiple backend configuration. That is the reason I limited `cpu backcend` only and linear executor.

**Comment by wateret** [comment]
@s-barannikov

> May be reuse the data pointed by a tensor instead of replacing the tensor? I.e. have two tensors (input and output of reshape) that share the same data. I thought concat elimination works this way.

Exactly. The key is "pointer indirection"(not sure this is a correct word 😓 ). And for its implementation, we used ACL's Subtensor, which is a decorator that represents some sub-area of an actual tensor object(this one has actual allocation).

**Comment by wateret** [comment]
> @wateret In my target model, almost all `reshape`'s source is not used any longer after this reshape. I would like to handle this case first in a few weeks. If you don't have plan, I will try. I need to investigate how our memory allocator works. I will assume cpu backend only and linear executor and enable this optimization in this configuration due to lack of time. More general approach could be done in 2021 as you said.

@glistening Sounds great, please go on 😄

**Comment by glistening** [comment]
> In my target model, almost all reshape's source is not used any longer after this reshape. 

cc @YiHyunJin 

I've found that "almost" but not "all". Some `reshape` has multiple uses. We need to consider this case also.
