### ISSUE TITLE
Compiler FE: Enable EXPAND_DIMS Op

### ISSUE THREAD

**Issue by binarman** [Samsung/ONE#420]
- [x]  res/TensorFlowPythonExamples Done in #796 by hyunsik-yoon 
- [x]  res/TensorFlowLiteRecipes #1197
- [x]  tflchef #1201
- [x]  tfldump  (has no options)
- [x] circledump  (has no options)
- [x]  luci.IR #1198
- [x]  luci.Import #1199
- [x]  luci.Export #1200
- [x]  luci.logex #1195
- [x]  luci.Service #1194
- [x]  tflite2circle Done before me
- [x]  luci.tests #1196 #1332

For #277

**Comment by AShedko** [comment]
All done
