### ISSUE TITLE
Compiler FE: Enable FLOOR_DIV Op

### ISSUE THREAD

**Issue by d-krylov** [Samsung/ONE#432]
- [x]  res/TensorFlowPythonExamples (was done before)
- [x]  res/TensorFlowLiteRecipes #1283 
- [x]  tflchef (was done before)
- [x]  tfldump (nothing to do)
- [x] circledump (nothing to do)
- [x]  luci.IR #1280 
- [x]  luci.Import #1282 
- [x]  luci.Export #1285 
- [x]  luci.logex #1311 
- [x]  luci.Service #1284 
- [x]  tflite2circle #1281 #1310
- [x]  luci.tests #1286 

For #277

**Comment by binarman** [comment]
all done
