### ISSUE TITLE
Compiler FE: Enable REDUCE_MAX Op

### ISSUE THREAD

**Issue by d-krylov** [Samsung/ONE#433]
- [x]  res/TensorFlowPythonExamples #1427
- [x]  res/TensorFlowLiteRecipes #243 #1428
- [x]  tflchef #238 
- [x]  tfldump #1435 
- [x]  circledump #1436 
- [x]  luci.IR #1267
- [x]  luci.Import #1269 #1405 
- [x]  luci.Export #1279 #1425 
- [x]  luci.logex  #1276 #1410
- [x]  luci.Service #1274 #1409
- [x]  tflite2circle (this operator was supported when reducerOptions introduced)
- [x]  luci.tests #1437 

For #277

**Comment by binarman** [comment]
new draft: #1335

**Comment by binarman** [comment]
all done, closing
