### ISSUE TITLE
[nnpkg_run] nnpackage_run is version dependent

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#4330]
When onert and nnpackage_run were built with different codebase, it is very likely to crash.

I thought `nnpackage_run` only uses `nnfw.h` which is ABI compatible so it would work with any versions. But it turns out that it wouldn't.

How to regenerate: TBD

**Comment by wateret** [comment]
cc: @llFreetimell

**Comment by hseok-oh** [comment]
Now `onert_run` (`nnpackage_run`) is using nnfw API, not internal implementation.
