### ISSUE TITLE
[luci-interpreter] Support 16-bit int quantized operators

### ISSUE THREAD

**Issue by binarman** [Samsung/ONE#4339]
We need to start support of 16-bit quantization, this issue related to interpreter support

First priority operators are:

Operator | Status
--- | ---
ADD | #4569
AVERAGE_POOL_2D | #4541
CONV_2D | #4590
DEPTHWISE_CONV | #4591
MAX_POOL_2D | #4541
MEAN | #4571
MUL | #4568
PRELU | #4570
RELU | #4572
TRANSPOSE_CONV | #4593

+cc @s-barannikov @seanshpark @jinevening @lucenticus @parjong

**Comment by jinevening** [comment]
How are you going to support these operators? Are you going to manually implement them?

**Comment by s-barannikov** [comment]
Some of them can be implemented using function from TFLite, at least partially. Others will have to be impemented manually.

**Comment by binarman** [comment]
This task is done in the the form we planned it.

I know there were a discussion about channel-wise quantization support with @jinevening 
Do we have other issues we need to take into account?
What is the priority of related tasks (i.e. channel-wise quantization)?

**Comment by jinevening** [comment]
> What is the priority of related tasks (i.e. channel-wise quantization)?

The target model for testing int16 quantization is FSRCNN.

FSRCNN has depthwise_conv, conv, transpose_conv, so supporting CWQ kernels for them would be high priority.

After that, we may test if luci-interperter can run int16-quantized FSRCNN. :)

**Comment by binarman** [comment]
@jinevening I created separate issue for this activity, closing this one
