### ISSUE TITLE
Compiler FE: Support max_pool_with_argmax

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#4542]
Let's support `max_pool_with_argmax` Op in _luci_

Currently this is converted to `CUSTOM(MaxPoolWithArgMax)` in TF to TFlite.

DRAFT: #4646

- [x] tflchef: #4719
- [x] recipes: #4721

For #1928

**Comment by seanshpark** [comment]
@lemmaa , About circle schema, we need to add one for this. But the ID number may differ if TensorFlow adds this in TFlite schema and may result manual modifications. How should we do with this Op?

**Comment by seanshpark** [comment]
@lucenticus , please take this item

**Comment by lucenticus** [comment]
Okay, sure! @d-krylov is going to start implementation of this operation.

**Comment by d-krylov** [comment]
@seanshpark, I heard opinions Luci IR has too much operators (and we shouldn't add them without good reason). This operator requires adding in Luci IR, as I can see. Can i do it?

**Comment by seanshpark** [comment]
> I heard opinions Luci IR has too much operators (and we shouldn't add them without good reason).

Um? I wonder where that came from :)

> This operator requires adding in Luci IR, as I can see. Can i do it?

Yes, please go ahead!

**Comment by binarman** [comment]
@seanshpark 
> Um? I wonder where that came from :)

If I remember it right this concern was related to circle schema, like there are limited space for op codes.
But for now there are a lot of space for new operators, so I am not sure what it actually was about.

**Comment by binarman** [comment]
@seanshpark 
@glistening proposed to pass MaxPoolWithArgmax custom operator generated in tflite through Compiler as-is (https://github.com/Samsung/ONE/pull/4723#issuecomment-716238048 ) so we can avoid insertion of new opcode into circle.

I can not come up with any case when we need this operator as a separate entity so far, so maybe this proposal make sense.
Does this mean that we can consider this task completed if we merge tflchef, tests(receipts)?
What do you think?

**Comment by seanshpark** [comment]
> so we can avoid insertion of new opcode into circle.

Technically, I also think going with CustomOp is better than adding `MaxPoolWithArgmax` and get conflict in the future.

> I can not come up with any case when we need this operator as a separate entity so far, 

Me too :)

> Does this mean that we can consider this task completed if we merge tflchef, tests(receipts)? What do you think?

I think so. Had a short talk with @lemma and also agreed.

**Comment by binarman** [comment]
According our current design decision everything is done, closing.
Thank you!
