### ISSUE TITLE
[onert] Coverity warning by munmap in base_loader

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#4631]
http://10.113.139.115:8081/reports.htm#v13368/p10494/fileInstanceId=292815710&defectInstanceId=104472563&mergedDefectId=1153376

>A non-heap pointer is placed on the free list, likely causing a crash later.
>
>In onert::​base_loader::​BaseLoader<onert::​tflite_loader::​<unnamed>::​LoaderDomain>::​deallocateMmappedArea(unsigned char *, unsigned int): Free of an address-of expression, which can never be heap allocated (CWE-590)

CWE-590: http://cwe.mitre.org/data/definitions/590.html

https://github.com/Samsung/ONE/blob/e2e63858960770b0a63eb16873a01f959e9c3391/runtime/onert/frontend/base_loader/include/base_loader.h#L293-L301

This implementation is intrudeced by #4007

@periannath Could you resolve this issue before 1.10 release?

**Comment by periannath** [comment]
I'll check and fix it ASAP.

**Comment by hseok-oh** [comment]
Resolved
