### ISSUE TITLE
[onert] TEST CASE RULES

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#4672]
To **MEET RELEASE CRITERION CONSTANTLY** I define some rules about adding test cases.

The rules could be flexible depend on the situation. I kindly ask you to keep those in mind when you **work on tasks or review**.

1. When contributing to onert, please consider if your changes cover every control path,and if not, write test cases 
2. Relevant test cases should be in the same PR with the actual changes
3. **(IMPORTANT) When introducing positive TCs, you must also introduce equal or more number of negative TCs**
    - Otherwise the PR won't be accepted
    - If it is hard to make negative tests related to your PR, merge the PR and you can make some other negative TCs
    - This has been a rule since #41
    - (I'm afraid of this rule, but didn't find a better way)
4. GTest negative test names must be prefixed with `neg_` 
    - e.g.) `TEST_F(MyFixture, neg_TestName)`

Please also note these rules are for:

- verification
- test coverage (All the lines of code must be run at least once)
- "# of negative TC" > "# of positive test TC" is required by SE team
- **The rules can change by discussion**

cc: @Samsung/nnfw 

---

### What are negative test cases?

There is no solid definition from SE team.

From [Negative testing in Wikipedia](https://en.wikipedia.org/wiki/Negative_testing)

> Negative testing is a method of testing an application or system that ensures that the plot of the application is according to the requirements and can handle the unwanted input and user behavior.

For me, I would suggest things like:

- Make the control reach `throw` or returning an error code
- Take a look at the code coverage result and it is likely that the un-covered lines can be covered with some new negative tests
- For example, say we have a dictionary, find or remove a non-existing item
- Parameterize values so we can easily test with different values (this is good but doesn't count as separated tests)

### How is number of test cases counted?

We only count tests in this file - https://github.com/Samsung/ONE/blob/master/.ahub/tcchecker-tca/config.yaml (except nnapi tests, as they are imported tests mostly)

One GTest macro(`TEST`, `TEST_F` and so on) is counted as 1 test case. For parameterized tests, GTest seems like treat them as separate tests but TCM counts it as just 1, no matter how many instantiations there are.

### Is there a easy way to make some?

It is preferred to make negative test cases that is related to your commit. However sometimes it is not easy. Then you can make any negative tests. I usually make some tests with invalid operation parameters. You may refer to the folder `tests/nnfw_api/src/one_op_tests`.

**Comment by wateret** [comment]
@hasw7569 Please add 2 or more NEGATIVE test cases which weren't introduced from #4514  .

**Comment by wateret** [comment]
@dayo09 Please add 3 or more NEGATIVE test cases which weren't introduced from #4581 .

**Comment by wateret** [comment]
ping @hasw7569 @dayo09

**Comment by seanshpark** [comment]
> ping @hasw7569 @dayo09

I think who have merge ability should agree on the terms @wateret suggested. so that another `ping` won't happen.
@hseok-oh , @chunseoklee PTAL
For me, I agree :)

**Comment by chunseoklee** [comment]
I agree too

**Comment by hseok-oh** [comment]
I agree too.
