### ISSUE TITLE
[res] Add U8 recipe: MAXIMUM

### ISSUE THREAD

**Issue by underflow101** [Samsung/ONE#4703]
Parent Issue: #1880

Let's enable U8 recipe for Maximum_000 Op.

**Comment by seanshpark** [comment]
Just minor thing, it's not necessary to add `Signed-off-by` for issues :)

**Comment by underflow101** [comment]
> Just minor thing, it's not necessary to add `Signed-off-by` for issues :)

Thank you for your advice!
I edited issue!
