### ISSUE TITLE
[res] Add U8 recipe: GREATER

### ISSUE THREAD

**Issue by underflow101** [Samsung/ONE#4713]
Parent Issue: #1880

Let's enable U8 recipe for Greater_000 Op.

**Comment by jinevening** [comment]
I think you don't have to create an issue which is trivial and can be resolved with a single PR :)

**Comment by underflow101** [comment]
> I think you don't have to create an issue which is trivial and can be resolved with a single PR :)

Thank you for your advice, @jinevening :)

According to #1880 ,
```
Steps (not mandatory but usually this may happen)

- Create an issue with title like [res] Add U8 recipe: ADD for ADD Op, and some descriptions
- It would be nice if you work on one Op at a time to concentrate on the operator
- I'll update the table of this issue that others know you are working on like #1606 (I'll be notified by github from the new issue)
- create a PR and work on this topic; update PR with Work In Progress codes and this may help getting faster feedbacks
- get a review from guys working on this topic, like @jinevening
- apply feedback changes if any
- land the PR and done !
```
Although it tells me that these steps are not mandatory,
I thought I had to follow the guide for community's code of conduct :)

**Comment by jinevening** [comment]
> In order to register my commit lists to sos-masters, I need to create issue per PR

I didn't know that. If you need one issue per PR, then please go as is.

**Comment by underflow101** [comment]
> > In order to register my commit lists to sos-masters, I need to create issue per PR
> 
> I didn't know that. If you need one issue per PR, then please go as is.

Thank you for your understanding @jinevening :)
