### ISSUE TITLE
[Compiler] Discussion items in shape/dtype of luci

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE#4726]
## Background

While I was working in `luci/Service`, there were discussion items and technical debt but leaved it because of release schedule.
Now, it's time to discuss for such items!

---

## Discussion Items

Any thing in following items are not decided yet.
It is only for collecting discussion items and especially for offline discussion.

#### Current Status

Until now, we worked with assuming that model has always static shape.
However, the assumption was broken since some models with `shape_signature` is introduced.
Fortunately, as Runtime did not need the `shape_signature` information, it causes any problem but generated circle model is wrong because original `shape_signature` is removed.
(Specifically, `shape_signature` is alive until `tflite2circle` and dead after `circle2circle`)

#### Candidate solutions

This will be handled more detailed in #4372

#### Current Status

There are two methods to get shape or dtype of circle node in `luci/Pass`.
One is getting shape and dtype of Circle node and the other is getting shape and dtype of `loco::AnnotatedItem`
Which one is recommended?

#### Candidate Solution
- :arrow_right: By `loco::shape_get()` and `loco::dtype_get()`
    - During `ShapeInference` and `TypeInference`, shape and dtype are updated by `loco::AnnotatedItem`
- Refactoring to remove the redundancy
    - Redundancy between `loco::Shape` and `luci::Shape` is not desirable.
    - Refactoring can be fundamental solution for this issue but we don't know how dependent between `loco` and `circle`  for now.

#### Current Status

If shape or dtype of circle node is changed after each `luci/Pass`, should we change the shape or dtype in the `luci/Pass` or expect to be applied at next `ShapeInferencePass` or `TypeinferencePass` ?
This was happened in [FoldDequantizePass](https://github.com/Samsung/ONE/blob/9e86d44d24c110512251babb1e14560a783082f7/compiler/luci/pass/src/FoldDequantizePass.cpp#L111) and for now, dtype is changed in `FoldDequantizePass`.
This example is simple case, but what if more complicated passes are introduced? How should we handle it?

#### Candidate Solution

- :arrow_right: Run `ShapeInferencePass` and `TypeInferencePass` after every `luci/Pass`
- Change it in each `luci/Pass`
- :x: Leave it and expect to be applied at next `ShapeInferencePass` or `TypeInferencePass`
    - If another passes are influenced by it, the validity is broken.

**Comment by seanshpark** [comment]
It's a bit hard to understand the issue. What I know from your previous talk
- we need to add `shape_signature` in `CircleNode`
- we need some shape inference of `shape_signature` when nodes are altered in `Pass`

Can you please describe the problem first? This issue has mixed things and some things seem to be underneath that I can't see or I don't understand. For example, `CircleNode is impossible because of const keyword.`

**Comment by llFreetimell** [comment]
## Discussion Result

### 1. Supporting Dynamic Shape Inference

**:heavy_check_mark: Decided to support.**
This will be handled at #4372.

### 2. Getting shape/dtype in each luci/Pass

**:heavy_check_mark: Decided to remove a dependency between `loco` and `luci` by using `shape` and `dtype` of `CircleNode`.**
However, as it may takes some time, `loco::shape_get()` and `loco::dtype_get()` should be used until refactoring is finished.
This will be handled at another issue soon.

### 3. Validity of shape/dtype after luci/Pass is ended

:warning: **Decided to handle later.**
Most of problem is resolved by solution of issue 2. However, corner case still exist which is not resolved by it.
For resolving the issue perfectly, following works should be done.

- Add `ShapeInferencePass` and `TypeInferencePass` at the first in `CircleOptimizer`.
- Change `CircleOptimizer` strategy from `SATURATE` to `RESTART`

However, this is not needed right now so it will be done when this work is needed.

**Comment by llFreetimell** [comment]
Related discussion was ended, close :)
