### ISSUE TITLE
[res] Add U8 recipes

### ISSUE THREAD

**Issue by underflow101** [Samsung/ONE#4729]
Parent Issue: #1880

Let's enable U8 recipe for following:

- [x] GreaterEqual_U8_000
- [x] LessEqual_U8_000
- [x] NotEqual_U8_000

**Comment by seanshpark** [comment]
@underflow101 , it's OK to add separate issues for each Ops but I think it would be better to add a single issue for similar tasks with a list of Ops with a check box.,

**Comment by underflow101** [comment]
> @underflow101 , it's OK to add separate issues for each Ops but I think it would be better to add a single issue for similar tasks with a list of Ops with a check box.,

Ok! Editted as you guided, @seanshpark :)
I will close other issues.
