### ISSUE TITLE
[onert] Test : target independent optimizations on/off (both)

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#4745]
We have target independent optimizations (currently just one - `PermutationEliminationPass`) but we only run the tests with it on. Let's make it run with both cases.

1. [ ] Resolve bugs when PermutationEliminationPass is off #4693 
2. [ ] Add a compiler option for turning on/off target independent optimizations 
3. [ ] Run tests with the compiler option off (currently we run tests with it on)

% To clarify what is target independent/dependent optimization:

- Target independent optimization : optimizations that are not backend-specific, usually graph manipulations
- Target dependent optimization : optimizations from backends (`backend::IOptimizer`)

**Comment by chunseoklee** [comment]
postponed
