### ISSUE TITLE
Fuse pre-activation batchnorm

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#4773]
### Background

In inference models (tflite or circle), batchnorm is usually fused with the preceding CONV layer for better performance.

ResNet V2 has non-trivial structure called _pre-activation_ to improve model generalization. (<-> activation after CONV, i.e., post-activation). (paper link: https://arxiv.org/pdf/1603.05027v3.pdf)

![image](https://user-images.githubusercontent.com/5449554/97135420-8d1c3700-1793-11eb-9062-4eed6cb624a9.png)

In post-activation models (a), `tflite_convert` automatically fuses batchnorm into the preceding CONV layer (depicted as `weight`).

In pre-activation models (b), however, it is not simple to fuse batchnorm computations into nearby CONV layers.

### Goal

Introduce a new pass named `FusePreActivationBatchNormPass` that fuses batchnorm computations of pre-activations into nearby CONV layers. And finally remove all batchnorm computations in ResNet V2.

### Progress

- [x] Add `FusePreActivationBatchNormPass` in luci
- [x] Add test (luci)
- [x] Add test (dredd)
- [x] Add a pass to fuse remaining activation functions (`FuseActivationFunctionPass`) #4833
- [x] Add a pass to change negative values in gamma to positive (`MakeBatchNormGammaPositivePass`)
- [ ] Update one-build

CC @periannath

**Comment by periannath** [comment]
### Performance measurement

- Model : ResNet v2

#### Device : S20+ exynos

| Backend | Before fusion | After fusion |
|--|--|--|
| cpu | 478.5 | 469.0
| acl_cl | 143.1 | 134.8

#### Device : odroid-xu4

| Backend | Before fusion | After fusion |
|--|--|--|
| cpu | 1254.1 | 1224.4
| acl_cl | 662.4 | 651.4

**Comment by jinevening** [comment]
I close this issue as all tasks are done.

To sum up, we could successfully fuse 17 of 17 pre-activations in ResNet50 V2.

**Comment by seanshpark** [comment]
> I close this issue as all tasks are done.

last one is not checked :)

**Comment by jinevening** [comment]
> last one is not checked :)

I forgot to check the box. Thanks! :)

**Comment by periannath** [comment]
## Performance comparison of quantized model

- Model : ResNet v2
- CPU doesn't support RELU for uint8

#### Device : S20+ exynos

| Backend | Before fusion | After fusion | Speedup |
|--|--|--|--|
| acl_cl | 53.6 | 50.7 | 1.06

#### Device : odroid-xu4

| Backend | Before fusion | After fusion | Speedup |
|--|--|--|--|
| acl_cl | 1113.2 | 1092.8 | 1.02
