### ISSUE TITLE
format check regardless of extension

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#4886]
Recently, `one-cmds` is revised from bash script to python one. But the name didn't change for language-agnostic, which means that its interface won't change no matter what language it is written in.

It looks fine but, there is one problem, i.e., format checking.

Format checker as of now determines the file's language by its extension. Since `one-cmds` doesn't have `.py` extension, it is recognized as a bash script. So whenever my posting a PR, I manually run `yapf`, which is kind of burden.

To resolve this problem, there are two things that I come up with.

1. How about adding these files' path, i.e., no extension but not bash, to each lists;`FILES_TO_CHECK_PYTHON`, `FILES_TO_CHECK_CPP`, etc.?

2. Or we can just wrapping the script with bash.

Feel free to give some opinion about this.

**Comment by seanshpark** [comment]
Ping @hseok-oh

**Comment by hseok-oh** [comment]
Below patch will resolve exceptional case for `one-cmds`

```diff
--- a/infra/command/format
+++ b/infra/command/format
@@ -195,6 +195,15 @@ function check_python_files() {
     if [[ ${f} == *.py ]]; then
       FILES_TO_CHECK_PYTHON+=("${f}")
     fi
+
+    # Exceptional case: one-cmds don't have '.py' extension
+    if [[ ${f} == compiler/one-cmds/* ]]; then
+      # Ignore non-python source (cmake, etc)
+      # Ignore shell script: one-prepare-venv
+      if [[ ${f} != compiler/one-cmds/*.* ]] && [[ ${f} != compiler/one-cmds/one-prepare-venv ]]; then
+        FILES_TO_CHECK_PYTHON+=("${f}")
+      fi
+    fi
   done
   for s in ${DIRECTORIES_NOT_TO_BE_TESTED[@]}; do
     skip=${s#'.'/}/
```
