### ISSUE TITLE
Make ChromeTracing handle multiple subgraphs (executors)

### ISSUE THREAD

**Issue by hyunsik-yoon** [Samsung/ONE#4901]
Currently Chrome tracing does not show a model with multiple subgraphs (executors). 

Let's make ChromeTracing handle multiple subgraphs.

**Comment by hyunsik-yoon** [comment]
Draft: #4903 

Sample screen with the following model:

```
y=neg(0)
while less ( y, 100 )
  y = add (y, 10)
z = cos(y)
```

You can see 3 subgraphs: primary, while_condition, while_body
- purple bars: labeled `subgraph`
- orange op: `neg`
- pink op: `cos`
- green op: `comparison`
- blue op: `add`

![image](https://user-images.githubusercontent.com/63768207/97960783-698d6800-1df5-11eb-97c1-8a633c4f0397.png)

zoom in:
![image](https://user-images.githubusercontent.com/63768207/97961203-3ac3c180-1df6-11eb-8e54-515b22f0c098.png)

**Comment by wateret** [comment]
I hope we have a subgraph index rather than the object's pointer address, later on. I guess there is no way to get the subgraph index info for now.

**Comment by hyunsik-yoon** [comment]
Putting the exact subgraph index seems not easy 
- We don't want to put tflite subgraph index into `Graph` object
- So we need to have some mapping info class of IR->IR' (e.g., tflite subgraph ->graph pointer)

Maybe what we need is to _distinguish_ subgraphs in human readable way?
For now we could use something like `Subgraph A`, `Subgraph B`, etc.

**Comment by seanshpark** [comment]
> Maybe what we need is to distinguish subgraphs in human readable way?

FYI, Subgraphs in tflite and circle has human readable text name.

**Comment by hyunsik-yoon** [comment]
Now shape info was added.

When is this necessary?
- if you want to find an op whose input shape is [1, 2, 3], you can find it by typing "1 2 3" in _search bar_ now.
- Another format "[1, 2, 3]" would be better but Chrome browser's Json parser regards "[1, 2, 3]" as a list and it cannot be text-searchable.

![image](https://user-images.githubusercontent.com/63768207/98082785-a6706200-1ebc-11eb-9341-b3777020fcac.png)

**Comment by hyunsik-yoon** [comment]
All merged.

I'd like to leave how I have tested:

0. How to check the result (assuming that log name is `m.log`)
   - check manually `m.log`, `m.log.table.md` 
   - check manyally `m.log.chrome.json`
1. typical case: 1 session, 1 subgraph
- generate nnpackage from `tests/scripts/models/cache/mobilenet_v1_0.25_128_float_2017_11_08/mobilenet_v1_0.25_128.tflite`
```
$ TRACE_FILEPATH=../mobilenet.log OP_SEQ_MAX_NODE=1  ./Product/out/bin/nnpackage_run --nnpackage ../mobilenet_v1_0.25_128
```
2. 1 session, 1 subgraph, `OP_SEQ_MAX_NODE=5`
```
$ TRACE_FILEPATH=../mobilenet.log OP_SEQ_MAX_NODE=5  ./Product/out/bin/nnpackage_run --nnpackage ../mobilenet_v1_0.25_128
```
- In this case, op name in chrome tracer will have `(5)` as postfix
3. 1 session, multiple subgraphs
```
$ TRACE_FILEPATH=../OneOp_While_github_4783.log OP_SEQ_MAX_NODE=1  ./Product/out/unittest_standalone/nnfw_api_gtest --gtest_filter=*.OneOp_While_github_4783
```
4. 2 sessions, multiple subgraphs
```
$ TRACE_FILEPATH=../two_sessions_run_simple_While_model.log OP_SEQ_MAX_NODE=1  ./Product/out/unittest_standalone/nnfw_api_gtest --gtest_filter=ValidationTestTwoSessionsCreated.two_sessions_run_simple_While_model
```
