### ISSUE TITLE
[onert] Analysis current profiler and scheduler

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#4916]
This issue is posted for activity to understand current implementation of our Profiler and HEScheduler;
- add a link previous issues and describe how it works as a novice in this area
- list candidate items to enhance 
- let compiler frontend (maybe circle2circle) provide whatever information to onert from profile results

As of result
- link of previous issues
- description of current implementation
- enhancement candidates
- next activities to do

**Comment by seanshpark** [comment]
Profile related (tracking in progress)
- https://github.sec.samsung.net/STAR/nnfw/issues/4903
- https://github.sec.samsung.net/STAR/nnfw/pull/4925 > https://github.sec.samsung.net/STAR/nnfw/pull/5073
   - https://github.sec.samsung.net/STAR/nnfw/pull/5162
   - https://github.sec.samsung.net/STAR/nnfw/pull/5168
   - https://github.sec.samsung.net/STAR/nnfw/pull/5181
   - https://github.sec.samsung.net/STAR/nnfw/pull/5182
   - https://github.sec.samsung.net/STAR/nnfw/pull/5224
   - https://github.sec.samsung.net/STAR/nnfw/pull/5225
- https://github.sec.samsung.net/STAR/nnfw/issues/5115
- https://github.sec.samsung.net/STAR/nnfw/issues/5252
   - https://github.sec.samsung.net/STAR/nnfw/pull/5262
- https://github.sec.samsung.net/STAR/nnfw/pull/5365
- https://github.sec.samsung.net/STAR/nnfw/issues/6357
- https://github.sec.samsung.net/STAR/nnfw/issues/8885
   - https://github.sec.samsung.net/STAR/nnfw/pull/8995
- https://github.sec.samsung.net/STAR/nnfw/issues/8866
- https://github.sec.samsung.net/STAR/nnfw/pull/8943

Informations for HEScheduler
- https://en.wikipedia.org/wiki/Heterogeneous_Earliest_Finish_Time

**Comment by seanshpark** [comment]
Subjects talked before
- Op performance varies with input size, including weights, bias: maybe computation amount
   - Measurement identification: backend - op - input size - produce - chipset - processor
- Assign particular Op to particular backend (or kernel)

**Comment by seanshpark** [comment]
HSIP definitions
1. Actual Finish Time of DAG; AFT
2. Earlist Start Time of node on processor; EST
3. Earlist Finish Time of node on processor; EFT = EST + computation cost
4. Out-degree comminucation cost weight; OCCW

_The aim of the scheduling issue is to determine anassignment of the tasks in a given DAG to processors sothat the schedule length is reduced to a minimum_.

**Comment by seanshpark** [comment]
(WIP) OneRT scheduler problem
- We can measure computation duration
- Computation time differs also by inputs size; sometimes inputs size change
- There is communication cost between heterogeneous processors
- There is cost of transpose of tensors from channel first to/from channel last (HNWC <--> NCHW) depending on core
- Computation cores are shared resource and are not dedicated

**Comment by seanshpark** [comment]
(WIP)

Steps of task to do
1. Embed profile data to nnpackage
   - (runtime) do profile as-is --> nnpackage with profile data --> (runtime) run with profile data
1. partition and merge/scheule with simple partition algorithm
   - (compiler) partition model (?) --> (runtime) merge and alloc partition to backend/kernel --> (runtime) run
1. experiemnt partition/merge algorithms
   - (compiler) patition with profile data --> ...
1. ...

**Comment by dr-venkman** [comment]
@seanshpark , thank for the post with the detailed information. I wanted to share here our efforts at optimization and profiling for ML models running over onert. 

We are looking at the combined optimization of execution time and memory consumption. Therefore, our notion of optimality is not a single point, but rather a [pareto front](https://en.wikipedia.org/wiki/Pareto_efficiency#Pareto_frontier).

Estimating the pareto front from a objective space is a non-trivial problem, and there exists several works in literature ranging from deterministic to stochastic (evolutionary algorithms) that attempt to estimate it. Continuing along those works, we have developed a sampling-based pareto front estimator based on a neighborhood metric in decision space. We have compared and contrasted this algorithm with existing works, and the results look promising at present, so a detailed evaluation is being planned. Please let me know if this approach looks promising or of interest with the direction mentioned above. Thanks in advance.

**Comment by seanshpark** [comment]
@dr-venkman , What is your purpose or objective of what you doing? I've no information of that. May I ask who `we` are?

**Comment by seanshpark** [comment]
@dr-venkman , please post another issue for discussion with your task.

**Comment by seanshpark** [comment]
### How profile works

Condition
- let backend candidate be `cpu;acl_neon` and there is no `exec_time.json` file
- initial execution time for all nodes, for all backends is set to 1

First run
- `LoweredGraph::LoweredGraph()` will call `HEScheduler::schedule(const ir::Graph &graph)`
- In `HEScheduler::schedule()` will call `scheduleBranch` which wil call `HEScheduler::schedule()` for all operations
- which will set the backend `acl_neon` the `_backend_resolver` with first backend in `_all_backends` as all expected time is 1
- execution results with `acl_neon` will be saved to `exec_time.json`

Second run
- `ExecTime` will load the first result from `exec_time.json` and now `acl_neon` backend has real measurements that is bigger than 1
- so the smaller `cpu` will be chosen
- same as first run but with `cpu`, `exec_time.json` will now have both `acl_neon` and `cpu` measurements

Third run
- both `acl_neon` and `cpu` has real measurements data from `exec_time.json` 
- in `HEScheduler::schedule(const ir::Graph &graph)` , `all_nodes_are_profiled` is now true
- so `scheduleShufflingBackends()` is called to run with scheduling with both backends

**Comment by seanshpark** [comment]
Let's now look at executors...first `Dataflow` that is used with HEScheduler and then `Parallel`

**Comment by seanshpark** [comment]
Done for now
