### ISSUE TITLE
Upgrade ubuntu development and target machine 

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#4932]
#### Runtime target machine image

- Odroid-XU4
  - 18.04, 20.04: https://dn.odroid.com/5422/ODROID-XU3/Ubuntu/
- Odroid-N2
  - 18.04: https://dn.odroid.com/S922X/ODROID-N2/Ubuntu/
  - 20.04: http://odroid.in/ubuntu_20.04lts
- RPI4 
  - 20.04: https://ubuntu-mate.org/download/arm64/focal/

#### Developer docker image

Test image: https://hub.docker.com/layers/nnfw/nnas_test/focal/images/sha256-ffe57c3b793645f719191ac8953df2c01c0b3d79d10b2c0e3b32985d26f17fb3?context=explore

#### Release runtime package

- Decide runtime package release target version 
  - Release for all versions ? or selected version(s) ?
  - Current package release version
    - armv7l: 16.04
    - aarch64: 18.04
    - x86_64: 16.04 (until 1.10.0) -> 18.04 (1.11.0 nightly)

#### Compiler frontend issue

Lowest python3 version on ubuntu 20.04 is python 3.8, but cannot use TensorFlow 1.13.x (under 2.2) on python 3.8  

#### Format checker issue

clang-format 3.9 is not officially supported on ubuntu 20.04 (default clang-format version is 10)
Cannot make compatible style file for clang-format-10 without any change

## Upgrade to 18.04

No issue yet

**Comment by seanshpark** [comment]
From several issues, `18.04` seems OK

**Comment by hseok-oh** [comment]
Agree with @seanshpark

**Comment by hseok-oh** [comment]
I'm upgrading CI farm machine to 18.04

**Comment by hseok-oh** [comment]
Now all CI jobs for runtime uses ubuntu 18.04 (x86_64, armv7l, aarch64)
