### ISSUE TITLE
imgdata2hdf5: is this for image data only?

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#4939]
There is a question to this tool if this is for image data only? (maybe from name and/or experience from others)
I could see that this tool is just to pack input files to hdf5 format.
If so, using `img` prefix may mislead.
Can we change to name like `data2hdf5` or any other preferred ?

**Comment by seanshpark** [comment]
@jinevening PTAL

**Comment by jinevening** [comment]
> Can we change to name like data2hdf5 or any other preferred ?

Yes we can. I think `rawdata2hdf5` looks good as we talked offline.

**Comment by seanshpark** [comment]
Question solved :)
