### ISSUE TITLE
[onert] Refactor Backend API

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#5006]
There are several components that consist of a backend. The components are used during compilation, each has its own role and used in a fixed stage. For details, See [Runtime API](https://github.com/Samsung/ONE/blob/66014afd334f8a618e99aa7196524376fc08542a/docs/runtime/backend-api.md) document.

However we've faced limitation with this approach.

- The compiler workflow(how it uses backend components) looks unnatural, it is somewhat awkwardly specialized for the ACL backends
- We are going to introduce some more backends, but some of them do not fit the current workflow - need modification for backend workflow and API
- It limits backend implementation (e.g. limitation of optimization)

Let me illustrate the compilation workflow.

![BackendAPI (1)](https://user-images.githubusercontent.com/10582184/98778099-2d7d8700-2435-11eb-83d8-040cfd60c0db.png)

Please note:

- The left is as-is, the right is to-be
- BLUEs are the backend components that are used in each stage

**What I'm going to do is to merge 5 backend-dependent compilation tasks(the red box) into one single API.** And I expect it would make us more freely implement backends with a little code duplication.

I'm going to write a draft for this first, to find out if it is better than as-is and what might be obstacles for doing this. I also hope that the unified memory allocator(which @YongseopKim is going to work on) would make the backend API even simpler.

cc: @Samsung/nnfw

**Comment by wateret** [comment]
Issues

- Unified API design : unit of the interface - LoweredGraph vs. OpSequence
    - `(CodeMap, TensorRegistry) ICompiler::codegen(LoweredGraph);`
    - `(Code, TensorRegistry) ICompiler::codegen(OpSequence);`
- One single API seems not possible due to reusing tensors from other backends (migrant tensors)
    - All the tensor objects must be registered for all operands first, then backends can generate kerenels

> What I'm going to do is to merge 5 backend-dependent compilation tasks(the red square) into one single API

Looks like I need to change the plan. "one single API" → "Two API functions"(One for tensor object building and the other for the rest).

**Comment by YongseopKim** [comment]
> Unified API design : unit of the interface - LoweredGraph vs. OpSequence 

if it's possible not to need `LoweredInfo`, just `OpSequence` could be better.

**Comment by wateret** [comment]
#5255 has landed. Now we don't use `ITensorBuilder`, `IConstantInitializer`, `IKernelGenerator` and `IOptimizer`(Not removed yet though).

```cpp
class BackendContext {
  ...
  virtual ITensorRegistry *tensorGen(const std::vector<onert::ir::OpSequenceIndex> &, const ir::OpSequences &, const ir::LowerInfoMap &)
  virtual FunctionMap kernelGen(const std::vector<onert::ir::OpSequenceIndex> &, const ir::OpSequences &)
};
```

And now we use these two functions instead. However, these functions are not stable APIs.

- Having `OpSequenceIndex` list as a param is temporary - need to refactor it
    - Having two params - A partial graph(assigned for the given backend) AND which tensors are not managed by the backend(which are migrant tensors)
- Considering making these functions as C API (Having two C and C++ API(just like now) complicate things)

**Comment by wateret** [comment]
Done by #5926 !
