### ISSUE TITLE
[onert] Code coverage went down 86% → 71%

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#5020]
http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-arm-runtime-coverage/797/

Maybe #4986 caused some issue?

cc: @hseok-oh

**Comment by seanshpark** [comment]
Seems #5018 is to fix the problem

**Comment by hseok-oh** [comment]
85% coverage : http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-arm-runtime-coverage/798/

**Comment by hseok-oh** [comment]
86% -> 71% 

Class definition line is counted to zero when class uses implicit constructor and destructor

71% -> 85% 

Class definition line is ignored

### lcov 1.12-2 with gcc-6

![lcov-1 12-2](https://user-images.githubusercontent.com/18611688/98916806-f54a7700-250e-11eb-98b6-abb7bb14d186.png)

### lcov 1.13-4 with gcc-8

![lcov-1 13-4](https://user-images.githubusercontent.com/18611688/98916842-fed3df00-250e-11eb-90ee-ef0a2b016610.png)

### lcov 1.14-2 wotj gcc-8

![lcov-1 14-2](https://user-images.githubusercontent.com/18611688/98916864-06938380-250f-11eb-8441-f8e567fc07cf.png)

**Comment by wateret** [comment]
@hseok-oh Thanks for the info!
