### ISSUE TITLE
[onert] Use c++17 features 

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#5046]
We are using c++14 build option.
By previous task #4932, we can test c++17 features on CI

- Ubuntu: 18.04, gcc-8 toolchain
- Android: android-29 platform, ndk 20, clang 8.0.7 toolchain
- Tizen: gcc-9 toolchain

gcc-8 support c++17 feature without `exprimental`

Will we change build option to use c++17 ?

https://en.cppreference.com/w/cpp/compiler_support#cpp17

**Comment by chunseoklee** [comment]
>Will we change build option to use c++17 ?

1. tizen's toolchain is gcc-9
2. But, tizen have not suggest to use c++17 officially. I think tizen does not guarantee anything for c++17.

**Comment by chunseoklee** [comment]
Via offline discussion with tizen's toolchain guy, in his personal opinion, there will be no problem with c++17. But it is not official comment :)

**Comment by hseok-oh** [comment]
Pending issue: x86-64 target is reverted to ubuntu 16.04. So we cannot use gcc-8 toolchain.

**Comment by glistening** [comment]
I prefer c++14 yet.

- c++17 is not officially supported from Tizen.
- `c++17` is the default in GCC 11. See https://gcc.gnu.org/projects/cxx-status.html#cxx17.
- Tensorflow 2.3 uses GCC 7.3.1 as tested build configuration. See https://www.tensorflow.org/install/source#cpu. 
- Building tensorflow with c++17 had caused some errors. It seems `c++14` is officially tested configuration for tensorflow

**Comment by chunseoklee** [comment]
Let's discuss this later when at least TIZEN officially suggests to use c++17 feature.

**Comment by hseok-oh** [comment]
Will be handled later
