### ISSUE TITLE
[onert] xnnpack build failed on x64

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE#5087]
server's cmake cannot change macro rightly like
```cmake
SET_PROPERTY(SOURCE ${XNNPACK_MICROKERNEL_SRCS} APPEND_STRING PROPERTY COMPILE_FLAGS "$<$<NOT:$<CONFIG:Debug>>: /O2 >")
```

**Comment by YongseopKim** [comment]
To resolve this asap, I'll skip building xnnpack on x64.

**Comment by YongseopKim** [comment]
https://github.com/Samsung/ONE/pull/5021

**Comment by YongseopKim** [comment]
Something weird happens...
```
[  4%] Building C object externals/XNNPACK/CMakeFiles/XNNPACK.dir/src/operators/argmax-pooling-nhwc.c.o
In file included from /externals/XNNPACK/src/operators/argmax-pooling-nhwc.c:14:
/externals/XNNPACK/include/xnnpack.h:1:1: error: unknown type name 'u'
u/ Copyright (c) Facebook, Inc. and its affiliates.
^
/externals/XNNPACK/include/xnnpack.h:1:2: error: expected identifier or '('
u/ Copyright (c) Facebook, Inc. and its affiliates.
 ^
In file included from /externals/XNNPACK/src/operators/argmax-pooling-nhwc.c:14:
In file included from /externals/XNNPACK/include/xnnpack.h:16:
```
http://nnfw.mooo.com:8080/job/nnfw/job/master/job/pr-android-runtime-builder/1586/consoleText

**Comment by periannath** [comment]
@YongseopKim It was added by yesterday's test PR in #5085. It seems that source code at externals are affected by patch and not downloaded again.

**Comment by chunseoklee** [comment]
FYI. It turns out that 1)  #5085 modified build instance's external(in wrong way) without change of xnnpack's stamp file. 2) #5021 tried to build for x64 with the build instance. 
As a result, we'd better not use patch file to avoid these issues.
