### ISSUE TITLE
ONE Build failed with `externals/XNNPACK/CMakeLists.txt`

### ISSUE THREAD

**Issue by hyunsik-yoon** [Samsung/ONE#5177]
Recently building ONE failed in my environment.

```
$ rm -rf ./externals ./Product
$ ROOTFS_DIR=/home/eric/src/rootfs/arm-bionic ./infra/scripts/docker_build_cross_arm_runtime.sh
...
CMake Error at /home/eric/work/4/ONE/externals/XNNPACK/CMakeLists.txt:1989 (TARGET_COMPILE_DEFINITIONS):
  Error evaluating generator expression:

    $<IF:$<CONFIG:Debug>,5,0>

  Expression did not evaluate to a known generator expression
...

```

Anyone who already solved this problem, could you please help?

**Comment by hseok-oh** [comment]
Maybe you are using ubuntu 16.04 docker image & target. 

One solution is upgrade target and use 18.04 image. Other solution is install new cmake version in your custom docker image.

**Comment by periannath** [comment]
Same thing happened in #5087. As @hseok-oh explained, upgrading cmake version may solve this issue.

**Comment by hyunsik-yoon** [comment]
Could you let me know the recommended CMAKE version?

**Comment by hyunsik-yoon** [comment]
I tried local build (not docker) with cmake 3.10.2 and now it works.

**Comment by dayo09** [comment]
For those who may come here later...
I faced the same issue and I got the simple solution (from @periannath)
$ DOCKER_IMAGE_NAME="nnfw/one-devtools:bionic" ./infra/scripts/docker_build_cross_arm_runtime_release.sh
