### ISSUE TITLE
[onert] Revise tflite loader test tool

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#5213]
### Status

- TFLite loader test binary (tflite_loader_test_tool) compares onert and tensorflow lite inference result
- To get onert inference result, it uses onert internal header's API
- To get tensorflow inference result, it uses our tflite extension library (`runtime/lib/tflite`)

### TODO

- Use nnfw API for onert inference
- Use tensorflow lite's C API for tensorflow lite inference (or divide nnapi implementation from tflite extension library)

When we support and verify more operations with tensorflow lite model, `nnapi_test` requires additional implementation in tensorflow lite extension library for NNAPI and it hards to upgrade to tensorflow lite 2.x. By this, we may use this tools for tflite model inference verification instead of `nnapi_test` test binary.

**Comment by hseok-oh** [comment]
Additional issue: Rename test binary

https://github.com/Samsung/ONE/pull/5237#issuecomment-736878875

**Comment by hseok-oh** [comment]
We have 4 test tools (install on `bin/` directory)

- `tflite_run`
  - Run tflite
  - Input: tflite model
  - Use tflite interpreter / NNAPI (select by environment variable `USE_NNAPI`)
- `nnpackage_run`
  - Run onert
  - Input: nnpackage (optional: including golden input/output data)
  - Use `onert` by nnfw API
- `nnapi_test`
  - Compare tflite interpreter and `onert`
  - Input: tflite model
  - Use `onert` by NNAPI
- `tflite_loader_test_tool`
  - Compare tflite interpreter and `onert`
  - Input: tflite model
  - Use `onert` by nnfw API

Rename
- `nnpackage_run` -> `onert_run`
  - Same naming policy with `tflite_run`
- `nnapi_test` and `tflite_loader_test_tool`
  - `nnapi_test` -> ?
  - `tflite_loader_test_tool` -> ?

**Comment by glistening** [comment]
> Rename
> 
>* `nnpackage_run` -> `onert_run`
>   * Same naming policy with `tflite_run`

@hseok-oh

`nnpackage_run` was named with same naming policy with `tflite_run` in term of input format. `tflite_run` takes `tflite` file as input, `nnpackage_run` takes `nnpackage` as input. Naming with input format has two advantages:

1. At early days, people try to run `onert` by passing `tflite` directly. `nnpackage_run` says more clearly its input is `nnpackage`, not `tflite`. 

2. `onert` can run models through two ways: i) NNAPI ii) nnfw (now onert) API. 
`nnpackage_run` only covers the latter. `tflite_run` covers the latter with NNAPI=1.
Though last year, we'd mainly focused on onert API, I don't know how `onert` will go this year or later.

**Comment by hseok-oh** [comment]
>`tflite_run` takes `tflite` file as input, 

I thought `tflite_run` means that this binary run `tflite`, not `tflite model` (like `tflite_vanilla_run` run `tfilte v2.3` without `libneuralnetworks.so`). These namings made me confusion.

**Comment by glistening** [comment]
> > `tflite_run` takes `tflite` file as input,
> 
> I thought `tflite_run` means that this binary run `tflite`, not `tflite model` (like `tflite_vanilla_run` run `tfilte v2.3` without `libneuralnetworks.so`). These namings made me confusion.

`tflite_run` runs the given tflite model with `onert` engine (via NNAPI=1). Thus, `tflite_run` also makes me confused. :)

**Comment by hseok-oh** [comment]
TODO items are done.
