### ISSUE TITLE
[onert] Support operand data type inference?

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#5236]
Just like shape inference, do we need data type inference?

Should we support operand type inference? We have a param for that in NNFW API.

```c
NNFW_STATUS nnfw_set_input_tensorinfo(nnfw_session *session, uint32_t index,
                                      const nnfw_tensorinfo *tensor_info);
```

Data type is present in `nnfw_tensorinfo` but it is simply ignored for now.

NN API is the same. (Data type is present in `ANeuralNetworksOperandType `.) But I'm not sure it is really used in NN API.

```c
int ANeuralNetworksExecution_setInput(ANeuralNetworksExecution* execution, int32_t index,
                                      const ANeuralNetworksOperandType* type, const void* buffer,
                                      size_t length);
```

Do we need this? Or does this make sense in the first place?

cc: @Samsung/nnfw

**Comment by hseok-oh** [comment]
>Or does this make sense in the first place?

I also had same question.

Android runtime just check data type. NNAPI `setInput`'s `type` parameter is used to pass `shape`. On tensorflow lite, some operations just set operation output data type by input data type, but some operations check output data type and stop if fail.

IMO, we don't need data type inference (believe compiler/converter).

**Comment by hyunsik-yoon** [comment]
In case of shape, we need shape inference when the shape in tflite/circle can be changed at runtme.
For datatype, we haven't such requirement so far.

I tried the following with Tensorflow:
```
i = tf.constant(0, dtype=tf.int32)   # Input is tf.int32

def cond(i):
    return tf.constant(True, dtype=tf.bool)

def body(i):
  return tf.cast(tf.add(i, i), tf.int64)    # But this line changes data type to int64

result = tf.while_loop(cond, body, [i])

with tf.Session() as sess:
  print(sess.run(result))
```

and running fails with the message below:
```
InvalidArgumentError: Input 1 of node while/Merge was passed int64 from while/NextIteration:0 incompatible with expected int32.
```

**Comment by wateret** [comment]
In conclusion, we don't need it at least for now. Enough discussion for now, thank you!
