### ISSUE TITLE
[Doc] Missing Link

### ISSUE THREAD

**Issue by kishcs** [Samsung/ONE#526]
@chunseoklee
In [Cross build for Android](https://github.com/Samsung/ONE/blob/master/docs/nnfw/howto/CrossBuildForAndroid.md), `Note` section has a link for [howto.md](https://github.com/Samsung/ONE/blob/master/docs/nnfw/howto.md). It seems the file is missing.

**Comment by hseok-oh** [comment]
Resolved issue
