### ISSUE TITLE
Resolve coverity defect for ONE 1.12.0

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#5311]
parent : #5304 
~~report on master : https://analysishub.sec.samsung.net/service/v1/analyses/271482/pdf~~
new report : https://analysishub.sec.samsung.net/service/analyses/271617

We need patch for the following 3 defects : 

|    | Severity | WarningGroupID | Classification | CheckerName      | FilePath                                                                                                        |
|   ---| ----| ----| ---| -----| ---|
|  1 | Critical |        1217377 | Undecided      | UNINIT_CTOR      | /home/abuild/rpmbuild/BUILD/nnfw-1.12.0/runtime/onert/core/src/util/EventCollector.h:54                         |
|  5 | Critical |        1217309 | Undecided      | FORWARD_NULL     | /home/abuild/rpmbuild/BUILD/nnfw-1.12.0/compute/cker/include/cker/operation/DepthwiseConv.h:177                 |
|  7 | Critical |        1217265 | Undecided      | useless call   |  /home/abuild/rpmbuild/BUILD/nnfw-1.12.0/compute/ruy/include/ruy/Utils.h:145   |

Others will be resolved by identifying as external dep(or false alarm)

**Comment by hseok-oh** [comment]
1217267 -> 1217265 ?

**Comment by hseok-oh** [comment]
1217309 is false positive - if `ruy_context` is null, `thread_count` become 1, then it will not reach to line 177

**Comment by chunseoklee** [comment]
> 1217309 is false positive - if `ruy_context` is null, `thread_count` become 1, then it will not reach to line 177

updated on server as false positive. 2 defects remain.

**Comment by chunseoklee** [comment]
I classify 1217265 as intentional. Now, only 1217377 remains.

**Comment by chunseoklee** [comment]
@hyunsik-yoon There is no side effect after the following variables are initialized with arbitrary values(-1) ?

```
   Event(Edge a_edge, const std::string &a_backend, const std::string &a_label)
        : edge(a_edge), backend(a_backend), label(a_label)
    { /* empty */
2. uninit_member: Non-static class member session_index is not initialized in this constructor nor in any functions that it calls.
4. uninit_member: Non-static class member subg_index is not initialized in this constructor nor in any functions that it calls.
6. uninit_member: Non-static class member op_index is not initialized in this constructor nor in any functions that it calls.
CID 1217377 (#1 of 1): Uninitialized scalar field (UNINIT_CTOR)
8. uninit_member: Non-static class member op_seq_size is not initialized in this constructor nor in any functions that it calls.
```

**Comment by hyunsik-yoon** [comment]
@chunseoklee  `op_seq_size` is not used yet, so any value will be fine. (The PR that use the var will be pushed later)

**Comment by chunseoklee** [comment]
#5316 for 1217377

**Comment by chunseoklee** [comment]
final report : https://analysishub.sec.samsung.net/service/analyses/271702
