### ISSUE TITLE
Compiler FE: add one-build test

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#5375]
## What
Let's add more `one-build` test

## Why
There are `one-build` test but it is too insufficient to cover bunch of usecases.

There are seven `one-cmds` drivers and it should be test with variety of combination.

e.g.
one-import-tf -> one-codegen
one-import-tflite -> one-optimize -> one-codgen
one-import-tf -> one-optimize -> one-quantize -> one-codegen
one-import-tf -> one-optimize -> one-quantize -> one-pack

**Comment by mhs4670go** [comment]
@seanshpark 
From https://github.com/Samsung/ONE/pull/5436#issuecomment-749995953, is it okay to revise one tests like below?

- Remove dependency between tests : Some test(e.g. `one-quantize_001.test`) doesn't create test material from scratch, which might occur problem sometimes.
- Create working directory : this is a bit similar with the second one. [create `working_dir` -> pushd `working_dir` -> test -> popd `working_dir`] process will make the tests more clear(?) and repeatable. Test output will be just a log file.

**Comment by seanshpark** [comment]
> Remove dependency between tests : Some test(e.g. one-quantize_001.test) doesn't create test material from scratch, which might occur problem sometimes.

@jinevening , please give your opinion

**Comment by seanshpark** [comment]
> Create working directory : this is a bit similar with the second one. [create working_dir -> pushd working_dir -> test -> popd working_dir] process will make the tests more clear(?) and repeatable. Test output will be just a log file.

Seems OK, but please check when jump to error handler.

**Comment by jinevening** [comment]
> Remove dependency between tests : Some test(e.g. one-quantize_001.test) doesn't create test material from scratch, which might occur problem sometimes.

> @jinevening , please give your opinion
It is OK with me if you revise to use commands, not tests.

I agree with you. It would be better to call `one-import` command instead of running `one-import_001.test`.

**Comment by mhs4670go** [comment]
> using commands is like "we assume this command has no problem".

I will download all the required material in `prepare_test_materials` steps. e.g., `.tflite`

**Comment by jinevening** [comment]
> I will download all the required material in prepare_test_materials steps rather than running other commands. e.g., .tflite

This seems to be a perfect solution if network/storage resources for one-build tests are not too limited.
