### ISSUE TITLE
"Hall of Fame"(Sourcerer.io) in README.md does not work

### ISSUE THREAD

**Issue by wateret** [Samsung/ONE#5417]
Hall of Fame section in the top-level README.md have been broken since a few weeks ago.

I can't connect to https://sourcerer.io . Looks like there is some security issues.

cc: @lemmaa

**Comment by seanshpark** [comment]
It think it's certificate has expired...

**Comment by lemmaa** [comment]
<img width="486" alt="Screen Shot 2020-12-17 at 5 28 26 PM" src="https://user-images.githubusercontent.com/1185333/102462587-507f0480-408d-11eb-954e-9623a082a530.png">

**Comment by wateret** [comment]
😅

**Comment by wateret** [comment]
Just for who are interested - https://github.com/sourcerer-io/sourcerer-app/issues/632

TL;DR; Sourcerer is sold by another organization, not sure if it is going to work again or not.
