### ISSUE TITLE
[luci] Use DataFormat in circle schema

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#5487]
## What

Support DataFormat in circle schema.

## Why

Currently luci does not correctly read/write DataFormat field in circle schema.

## ToDo

To be added

- [ ] luci/import
- [ ] luci/export
- [ ] Add data_format field in Module #5492
- [ ] circlechef
- [ ] circle recipes
- [ ] ConvertNCHWToNHWCPass
- [ ] tflite2circle
- circledump (already supported)
...
---
Related to: https://github.com/Samsung/ONE/issues/5401

**Comment by binarman** [comment]
AFAIK luci-interpreter does not support channels-first layout also.
Should we add luci-interpreter as an item in this list or track it in separate issue?

**Comment by jinevening** [comment]
> Should we add luci-interpreter as an item in this list or track it in separate issue?

I don't think so. The main purpose of this issue is to identify (and set) the data format of a circle model before/after NCHW->NHWC conversion (#5454). Currently luci-interpreter is used only for quantization, so it may not need NCHW support.

**Comment by seanshpark** [comment]
Before landing #5492, have you verified (by some draft code) the logic you are thinking of?
We may have these situations...
- circle file with out dataformat
- circle file with dataformat channel last
- circle file with dataformat channel first

for each files, user wants to read as channel first using #5401

**Comment by jinevening** [comment]
> Before landing #5492, have you verified (by some draft code) the logic you are thinking of?
We may have these situations...

#5492 only has some unit tests (I thought that's enough because the change is simple).

I'll upload full draft that tests the cases you've mentioned. It may take some time because we need test models (circle recipes) and update in circlechef to generate them (if someone knows a simpler solution for verification, please let me know:slightly_smiling_face:).

**Comment by seanshpark** [comment]
> It may take some time because we need test models

Yes, please take your time :)

**Comment by jinevening** [comment]
> Should we add luci-interpreter as an item in this list or track it in separate issue?

> We may need a guard code that prevents luci-interpreter from running NCHW model. Thanks.

At first glance, I thought that I can easily handle luci-interpreter in this issue by preventing luci-interpreter from running NCHW model. But in fact luci-interpreter can run NCHW model if the model only has "data-format-independent" operators, e.g., element-wise computations such as ADD or MUL. So, we should add guard codes only in the "data-format-dependent" operators (e.g., CONV) to prevent execution when the input of the operator is NCHW.

The problem is that it is not simple to get the data format of the input of each operator. According to the comment in `circle_schema.fbs`, data_format field only describes the format of the input/output of each subgraph. So the data format of each operator's input needs to be inferred (not retrieved). I think further discussion had better be done in a separate issue. I'll remove luci-interpreter in the TODO list.

**Comment by jinevening** [comment]
> According to the comment in circle_schema.fbs, data_format field only describes the format of the input/output of each subgraph.

This was my misunderstanding. data_format of each subgraph indicates data format of all operators in the subgraph.
(Related issue: https://github.sec.samsung.net/STAR/nnfw/issues/5503)

The current schema assumes that all operators in the subgraph have the same layout. But tflite models from onnx-tf have both NCHW/NHWC operators in the same subgraph. More specifically, when translated from onnx (NCHW) to tflite (NHWC), most NCHW operators remain as-is by default while some Ops, such as CONV, are changed to NHWC (Transpose Ops are inserted before/after those special Ops). I have no idea how to handle such models in the current schema.

**Comment by seanshpark** [comment]
> I have no idea how to handle such models in the current schema.

Hmmmmm.....

**Comment by jinevening** [comment]
I'll close this issue until the limitation of circle schema is resolved.
