### ISSUE TITLE
Compiler FE: Support constant folding for SparseToDense, AddV2 and Cast

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#5598]
## What

Let's support constant folding for the below operators.

1. SparseToDense @jinevening 
If the size of sparse_indices is 0 and the rest of inputs are constant -> Fold to constant

2. AddV2 @jinevening 
If all inputs are constant -> Fold to constant

3. Cast @jinevening 
If input is constant -> Fold to constant

## Why

onnx-tf generates the above patterns for Reshape Op. They can be removed by constant folding, but tf2tfliteV2 does not handle those patterns.

onnx model
![reshape_onnx](https://user-images.githubusercontent.com/5449554/104256881-726a7c00-54bf-11eb-8453-755e19d1b8ae.png)

tflite model (generated by onnx-tf)
![reshape_circle](https://user-images.githubusercontent.com/5449554/104256886-74ccd600-54bf-11eb-9c2d-5f2fdf963599.png)

**Comment by jinevening** [comment]
I'm working on the first operator (SparseToDense). Any help is welcome.

**Comment by jinevening** [comment]
Interim result. SparseToDense was folded. I'm working on AddV2.
```
circle2circle --fold_sparse_to_dense test.circle test.folded_stod.circle
```

![image](https://user-images.githubusercontent.com/5449554/104431311-1a20a080-55cb-11eb-9093-c920d467159c.png)

**Comment by seanshpark** [comment]
I missed something for #5687

There's a pass `ResolveCustomOpAddPass` and I think it would be better not to work with `CircleCustom` but with `CircleAdd`,
What do you think about this?

**Comment by seanshpark** [comment]
If would could rework on `CircleAddV2` then, (1) undo #5687, (2) add constant folding for `CircleAdd`, ...

**Comment by jinevening** [comment]
> What do you think about this?

CircleCustom may be less stable, so working with CircleAdd looks good.

But for now, I think we had better go with AddV2. In the target pattern, inputs of AddV2 are int64. Add in TFLite does not support int64 (it is not runnable on TFLite interpreter). That's why AddV2 was generated by TFLite converter in the target pattern.

**Comment by seanshpark** [comment]
> inputs of AddV2 are int64

OK, this is a good reason to continue with CustomOp AddV2

> We had better insert some code in ResolveCustomOpAddPass not to convert AddV2 to Add when the inputs are unsupported types.

I'll add an todo issue for this

**Comment by jinevening** [comment]
All done. Final result.

```
circle2circle test.circle --fold_sparse_to_dense --fold_add_v2 --fold_cast test.opt.circle
```

![image](https://user-images.githubusercontent.com/5449554/104858922-d41a6280-5965-11eb-8b23-bd02022c93c9.png)

If there is no more issue, I'll close this tomorrow.
