### ISSUE TITLE
Compiler FE: Transform minimum-maximum pattern to Relu6

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#5599]
## What

Let's transform max(min(input, 6), 0) to Relu6

![image](https://user-images.githubusercontent.com/5449554/103969788-11cefc80-51aa-11eb-82ea-ba12d223e038.png)

## Why

onnx-tf generates the above pattern for Relu6. We can transform it to a single operator Relu6.
Additionally, this transformation gives a chance for FuseActivationFunctionPass to fuse Relu6 with a preceding operator such as Conv.

**Comment by seanshpark** [comment]
close?

**Comment by jinevening** [comment]
> close?

@mhs4670go did all the jobs for this issue. @mhs4670go  Can you please close this if everything is done?
