### ISSUE TITLE
Compiler FE: TF 2.4 version upgrade

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#5688]
TensorFlow has release 2.4.0 last month.
Let's find out if there are any problems to upgrade to TF 2.4.0

Points to check
- Tool upgrade issue
- circle format compatibility issue

Why?
- TF released this new version
- onnx-tensorflow (latest 1.8) uses 2.4.0

**Comment by llFreetimell** [comment]
As I said before, there is a big issue in TF 2.4.0 related with scehma.

- `enum BuiltinOperator : byte` --> `enum BuiltinOperator : int32`
  - https://github.com/tensorflow/tensorflow/blob/df05368807dc600d75f71dd3b82b59041df69741/tensorflow/lite/schema/schema.fbs#L220
- `builtin_code:BuiltinOperator` --> `deprecated_builtin_code:byte`. 
  - https://github.com/tensorflow/tensorflow/blob/df05368807dc600d75f71dd3b82b59041df69741/tensorflow/lite/schema/schema.fbs#L991-L1009
- `builtin_code:BuiltinOperator` is newly introduced
  - https://github.com/tensorflow/tensorflow/blob/df05368807dc600d75f71dd3b82b59041df69741/tensorflow/lite/schema/schema.fbs#L1008

As a result, we should investigate how much our current codes should be modified.

**Comment by seanshpark** [comment]
@llFreetimell , thanks for reminding about schema change :)

Can we do like this?
- Use TF2.4 to read TF files
- Use TF2.4 tflite converter to write converted tflite files
- tflite2circle as-is: still tflite file written with 2.4 will have backward compatibility

There can be loses but may work for now...

**Comment by llFreetimell** [comment]
@seanshpark 

Until tflite operator reached at 252(currently, top value is 128(CUMSUM)), I think it may works without any loss :)
What we need to do is just adding new operators and changing function name.

However, if tflite operator becomes larger than 251, circle schema must be changed..!

**Comment by seanshpark** [comment]
> What we need to do is just adding new operators and changing function name.

I think we should do this (I assume `new operators` is our circle native ops) after frontend and runtime migrate to new schema...

> However, if tflite operator becomes larger than 251, circle schema must be changed..!

Certainly!

**Comment by llFreetimell** [comment]
## Python Support

Until Tensorflow 2.3, python 3.5 was supported.
However, as python 3.5 is EOF(End of life), Tensorflow dropped supporting python 3.5.
As a result, python 3.5 is not supported from Tensorflow 2.4.0, which means we cannot find TensorFlow 2.4.0 install package in python 3.5.

If users who use Ubuntu higher than 3.5 have no problem, but we may need to check whether there is dependent thing with Python 3.5.

**Comment by llFreetimell** [comment]
This is passed to #7616. Close!
