### ISSUE TITLE
Compiler FE: Use v2 for saved_model and keras model

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#5746]
Current `tf2tfliteV2` command option is generated with `--v1` option for saved_model or keras model.
As these formats are used mostly in 2.x version it would be better to use `--v2`.

Should we change default to `--v2` or let it as-is?

Related options in `one-cmds/utils.py`
```py
    # model_format
    if _is_valid_attr(args, 'model_format_cmd'):
        cmd.append(getattr(args, 'model_format_cmd'))
    elif _is_valid_attr(args, 'model_format'):
        cmd.append('--' + getattr(args, 'model_format'))
    else:
        cmd.append('--graph_def')  # default value
    # converter version
    if _is_valid_attr(args, 'converter_version_cmd'):
        cmd.append(getattr(args, 'converter_version_cmd'))
    elif _is_valid_attr(args, 'converter_version'):
        cmd.append('--' + getattr(args, 'converter_version'))
    else:
        cmd.append('--v1')  # default value
```

**Comment by seanshpark** [comment]
Related https://github.com/Samsung/ONE/issues/5706#issuecomment-762682012

@mhs4670go , could you please take a look at this?

**Comment by mhs4670go** [comment]
@seanshpark Current `tf2tfliteV2` converter version has no default value as well as other options except input format. And as https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/keras and https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/saved_model, there are saved_model and keras_model related APIs in 1.X tensorflow. Isn't it okay to let users choose the version?

**Comment by seanshpark** [comment]
I missed one thing... I used `one-build` so the options are generated from `_make_tf2tfliteV2_cmd` in `utils.py`
I think 
```py
    # model_format
    if _is_valid_attr(args, 'model_format_cmd'):
        cmd.append(getattr(args, 'model_format_cmd'))
    elif _is_valid_attr(args, 'model_format'):
        cmd.append('--' + getattr(args, 'model_format'))
    else:
        cmd.append('--graph_def')  # default value
    # converter version
    if _is_valid_attr(args, 'converter_version_cmd'):
        cmd.append(getattr(args, 'converter_version_cmd'))
    elif _is_valid_attr(args, 'converter_version'):
        cmd.append('--' + getattr(args, 'converter_version'))
    else:
        cmd.append('--v1')  # default value
``` 
code block is related.

**Comment by seanshpark** [comment]
There is `converter_version=v2` but I missed to use this...

**Comment by seanshpark** [comment]
I think we can change this option when 2.x is widely used by our customers...

Still then, I'll leave this issue open.

**Comment by seanshpark** [comment]
Major is now 2.x
