### ISSUE TITLE
[Compiler][luci] Implementation of more efficient luci/pass

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE#5777]
## What?

Let's re-implement some of passes to be more fast!

## Why?

Some of passes are implemented like following logic, which always break if pass is applied once.
```cpp
bool RemoveRedundantTransposePass::run(loco::Graph *g)
{
  bool changed = false;
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    auto circle_node = loco::must_cast<luci::CircleNode *>(node);
    if (remove_consecutive_transpose_function(circle_node))
    {
      changed = true;
      break;
    }
  }
  return changed;
}
```
If there are N nodes to apply such kind of passes, we should execute above pass at least N times.
This makes compiler slow for big models.

## How?

Let's enable following implementations.
(Some passes may changed core logic to do so)

```cpp
bool RemoveRedundantTransposePass::run(loco::Graph *g)
{
  bool changed = false;
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    if (auto transpose = dynamic_cast<luci::CircleTranspose *>(node))
    {
      if (remove_consecutive_transpose_function(transpose))
        changed = true;
    }
  }
  return changed;
}
```

## To-do

Re-implement following passes. If re-implementation is impossible, remove it from following list.

- [x] ConvertNCHWToNHWCPass #5822
- [x] PropagateQuantParamPass #5817
- [x] RemoveRedundantTransposePass #5815
- [x] ReplaceMulAddWithDepthwiseConvPass #5816

**Comment by seanshpark** [comment]
```cxx
    auto circle_node = loco::must_cast<luci::CircleNode *>(node);
    if (remove_consecutive_transpose_function(circle_node))
      changed = true;
```
would be better be
```cxx
    if (specific_node = dynamic_cast<luci::CircleSomeSpecificNode*>(node))
    {
      if (some_specif_function(specific_node ))
        changed = true;
    }
```
You shouldn't use `must_cast` here.

**Comment by llFreetimell** [comment]
That can be handled together :)

**Comment by llFreetimell** [comment]
Done!
