### ISSUE TITLE
Compiler FE: Remove optimization "--all"

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#5780]
The `--all` option was first introduced to enable all the optimization options but currently it didn't turned out that way.
To add new option to the `all` maybe risky in terms of stability.
As of result, `all` misleads that one may expect it will do all optimizations but actually it doesn't.

I think it would be better to remove this `all` option and provide some more specific group of options as an alias.

I'd like to know if there are any problems before just removing this option.
If there is no comments about a week, I'll go on removing them.

**Comment by seanshpark** [comment]
CC @samsung/ONE

**Comment by lemmaa** [comment]
As a suggestion, what if we provide the `-O1`, `-O2`, and `-O3` options like c compiler? 

As you might expect, it's kind of a group of optimization options. Probably the most stable optimizations are reflected in `-O1`, the slightly challenging ones in `-O2`, and the risky, perhaps current `--all` items are reflected through `-O3`. Of course, the configuration of the options in this group can be changed at any time at our discretion, so users can use it without confusion. The long format of this option would be around `--optimization-level={1,2,3}`. 

In addition, options such as `-O4` or `--experimental` could be added.

**Comment by seanshpark** [comment]
> As a suggestion, what if we provide the -O1, -O2, and -O3 options like c compiler?

Thanks! I'll add another issue for this, as this issue is  just about removing `--all` option.

**Comment by seanshpark** [comment]
Where `--all` is used, for testing
- compiler/common-artifacts/CMakeLists.txt
```cmake
  if(NOT DEFINED NO_OPTIMIZE_${RECIPE})
    # Generate optimized .circle
    add_custom_command(OUTPUT ${OPT_CIRCLE_OUTPUT_PATH}
      COMMAND $<TARGET_FILE:circle2circle> --all ${CIRCLE_OUTPUT_PATH} ${OPT_CIRCLE_OUTPUT_PATH}
      DEPENDS $<TARGET_FILE:circle2circle>  ${CIRCLE_OUTPUT_PATH}
      COMMENT "Generate ${OPT_CIRCLE_FILE}"
    )
    set(OPT_FORMAT ".opt")
    list(APPEND TEST_DEPS ${OPT_CIRCLE_OUTPUT_PATH})
  endif()
```
- docs/compiler/compiler/common-artifacts/CMakeLists.txt
```cmake
  if(NOT DEFINED NO_OPTIMIZE_${RECIPE})
    # Generate optimized .circle
    add_custom_command(OUTPUT ${OPT_CIRCLE_OUTPUT_PATH}
      COMMAND $<TARGET_FILE:circle2circle> --all ${CIRCLE_OUTPUT_PATH} ${OPT_CIRCLE_OUTPUT_PATH}
      DEPENDS $<TARGET_FILE:circle2circle>  ${CIRCLE_OUTPUT_PATH}
      COMMENT "Generate ${OPT_CIRCLE_FILE}"
    )
    set(OPT_FORMAT ".opt")
    list(APPEND TEST_DEPS ${OPT_CIRCLE_OUTPUT_PATH})
  endif()
```
- and compiler/one-cmds/tests/one-optimize_001.test and several `one-optimize` tests

**Comment by seanshpark** [comment]
Current `--all` options
```cxx
  if (arser.get<bool>("--all"))
  {
    options->enable(Algorithms::FuseBCQ);
    options->enable(Algorithms::FuseInstanceNorm);
    options->enable(Algorithms::ResolveCustomOpAdd);
    options->enable(Algorithms::ResolveCustomOpBatchMatMul);
    options->enable(Algorithms::ResolveCustomOpMatMul);
    options->enable(Algorithms::RemoveRedundantTranspose);
    options->enable(Algorithms::SubstitutePackToReshape);
  }
```

**Comment by mhs4670go** [comment]
@seanshpark How about renaming `--all` with the name from #5784?(maybe O1?) I mean decide #5784 first and then apply it to this issue.

**Comment by seanshpark** [comment]
> How about renaming --all with the name from #5784?(maybe O1?) I mean decide #5784 first and then apply it to this issue.

That is one good suggestion.
One strange thing about current `--all` is that I can't explain why these options are grouped to `--all` or `-O1`.
Only I could say is "it's... historical reason..."

**Comment by seanshpark** [comment]
I can't find any good name for current `--all`.
As suggestion, I'll use `--experimental` for it.

**Comment by seanshpark** [comment]
done
