### ISSUE TITLE
Compiler FE: Revise resolve_customop_add

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#5786]
We need to revise `resolve_customop_add` option not to work with `int64` inputs.

Refer: https://github.com/Samsung/ONE/issues/5781#issuecomment-765049842

**Comment by mhs4670go** [comment]
@seanshpark I am not sure but `Const(Int64) - CustomOp(AddV2) - Cast(to int32)` will convert to `Const(Int64) - Add - Cast(to int32)` with `resolve_customop_add`. It is not supposed to do so?

**Comment by seanshpark** [comment]
As-is: doesn not check int64 or int32.
-> Problem: converting to int64 may cause loss
-> To-be: don't convert from CustomOp(AddV2) to CircleAdd

New problem ???: There will be `CustomOp(AddV2)` in circle model.

**Comment by mhs4670go** [comment]
For more detail, since `CircleAdd` input should be `int32`, `int64` shouldn't be its input. If you are not doing this job yet, I'll revise this code.

**Comment by seanshpark** [comment]
> If you are not doing this job yet, I'll revise this code.

That will be nice :)

**Comment by seanshpark** [comment]
From #5819,

@mhs4670go , can you explain a bit why `BroadcastTo` is introduced?

**Comment by mhs4670go** [comment]
@seanshpark https://github.com/Samsung/ONE/blob/721dfa4798086868289d6ddad36992a5098a91b9/compiler/luci/pass/src/ResolveCustomOpAddPass.cpp#L45-L59

Originally `ResolveCustomOpAddPass` was introduced for above pattern. And to make up for insufficient tests, I'll add related network recipe. And to generate test artifacts, `BroadcastTo` should be introduced.
