### ISSUE TITLE
Compiler FE: ONNX file with Channel 1 Conv2D

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#5808]
Let's try with this model where channel is 1 for Conv2D.

```py
import torch


class TestModel(torch.nn.Module):
  def __init__(self):
    super(TestModel, self).__init__()

    self.conv1 = torch.nn.Conv2d(1, 1, 3, padding=(1, 1))
    self.relu1 = torch.nn.ReLU()
    self.conv2 = torch.nn.Conv2d(1, 8, 3, padding=(1, 1))
    self.relu2 = torch.nn.ReLU()

  def forward(self, input):
    output = input
    output = self.conv1(input)
    output = self.relu1(output)
    output = self.conv2(output)
    output = self.relu2(output)
    return output


model = TestModel()
torch.save(model, "model.pth")

input = torch.randn(1, 1, 16, 16)
torch.onnx.export(model, input, "onnx_conv2d_conv2d-11.onnx", verbose=False,
                  input_names=["input"],
                  output_names=["output"])
```

**Comment by seanshpark** [comment]
ONNX model
<img src='https://user-images.githubusercontent.com/4616940/105679292-943d1780-5f31-11eb-8879-b16c1d58561a.png' width=150px>

RAW circle model from tflite2circle
![image](https://user-images.githubusercontent.com/4616940/105679407-bcc51180-5f31-11eb-9495-b4bcb10b0df3.png)

**Comment by seanshpark** [comment]
For channel 1, `Reshape` is used instead of `Transpose` may be because `Reshape` is cheap (in terms of calculation...)

**Comment by seanshpark** [comment]
With 
```
convert_nchw_to_nhwc=True
remove_redundant_transpose=True
```
options, the first Conv2D is surrounded by `Transpose` - `Reshape`, `Reshape` - `Transpose` pattern

![image](https://user-images.githubusercontent.com/4616940/105682839-48d93800-5f36-11eb-964d-eb180380eab8.png)

**Comment by seanshpark** [comment]
As we have `remove_redundant_transpose` option that will eliminate `Transpose` - `Transpose` with some conditions, we can substitute `Reshape` to `Transpose` if conditions are met.

Condition
- `Transpose`-`Reshape` sequence of 1xHxWx1 to 1x1xHxW and back to 1xHxWx1
- `Reshape`-`Transpose` sequence of 1xHxWx1 to 1x1xHxW and back to 1xHxWx1

**Comment by jinevening** [comment]
As you said above, Reshape is cheaper than Transpose. IMHO, it would be better to substitute Transpose to Reshape (@struss has made a pass for this) and use `remove_redundant_reshape` pass (@struss has made this too).

**Comment by seanshpark** [comment]
These options are what I used
```
convert_nchw_to_nhwc=True
substitute_transpose_to_reshape=True
remove_redundant_reshape=True
remove_unnecessary_reshape=True
remove_redundant_transpose=True
```
problem is that this doesn't work.  if you think I missed something, please add some comments.

**Comment by seanshpark** [comment]
> As you said above, Reshape is cheaper than Transpose

Eventually Reshape and the Transpose both will be removed so it doesn't care.

**Comment by seanshpark** [comment]
`remove_redundant_reshape` was now added :)
`remove_redundant_reshape` is still WIP

with
```
convert_nchw_to_nhwc=True
substitute_transpose_to_reshape=True
remove_redundant_reshape=True
remove_unnecessary_reshape=True
```
network looks like this
![image](https://user-images.githubusercontent.com/4616940/105796561-6bb92a00-5fd2-11eb-829f-ea1248851fbe.png)

**Comment by jinevening** [comment]
> substitute_transpose_to_reshape was now added :)

This was the reason :)  I expect Reshape ops in the figure will be removed by applying `remove_redundant_reshape` and `remove_unnecessary_reshape`.

**Comment by seanshpark** [comment]
Related PRs landed and now works OK :)

Used options
```
convert_nchw_to_nhwc=True
remove_redundant_transpose=True
remove_redundant_reshape=True
remove_unnecessary_reshape=True
substitute_transpose_to_reshape=True
```
