### ISSUE TITLE
luci_interpreter: Support CircleNeg

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#5857]
From #5848, we need to support CircleNeg in _luci_interpreter_.

**Comment by seanshpark** [comment]
TensorFlow lite does not support quantized values...
@jinevening , do you know anything about how to support quantized Neg?

**Comment by jinevening** [comment]
>  do you know anything about how to support quantized Neg?

Do we have to support quantized Neg? or just float32 Neg is ok?

If we only need float32 Neg, we can port the existing one from TFLite. If we need uint8 Neg, we'll have to implement the kernel by hand (TFLite supports Neg only for int32, int64, float32).

**Comment by seanshpark** [comment]
> Do we have to support quantized Neg? or just float32 Neg is ok?

For me, float32 is OK and I'm currently working on this.
But if we need to make a quantized model including `Neg` op with record-minmax, then won't we need Q8?

**Comment by jinevening** [comment]
> won't we need Q8?

F32 kernel is enough for quantization.

**Comment by seanshpark** [comment]
Draft prepared in #5854

**Comment by seanshpark** [comment]
done
