### ISSUE TITLE
Compiler FE: Remove test codes from metric score

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#6058]
Out DuplicateCode analysis (SAM) result shows lots of `*.test.cpp` codes are included in `luci-interpreter`
I think we don't have to include these test files as analysis target.

**Comment by seanshpark** [comment]
@cgbahk , is it possible to do this?
If there is no file filter then we can think of moving the files into `test` folder.

**Comment by cgbahk** [comment]
I guess luci-interpreter may not configured to exclude test by setting
```
-DENABLE_TEST=OFF
```

**Comment by seanshpark** [comment]
@cgbahk thanks!

it turns our that `compiler/luci-interpreter/src/kernels/CMakeLists.txt` doesn't check `ENABLE_TEST` option :)

**Comment by seanshpark** [comment]
This came from #6053

**Comment by seanshpark** [comment]
Done
