### ISSUE TITLE
[circle-quantizer] Unsupported SPLIT Op

### ISSUE THREAD

**Issue by a-zh** [Samsung/ONE#6161]
**How to reproduce:**

Run the command: 
```
$ ./build/arch/circle-quantizer/circle-quantizer --quantize_with_minmax float32 uint8 channel /tmp/1/model.minmax_recorded.circle /tmp/1/model.q.circle
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unsupported Op for const inputs
Aborted
```

Please, find `model.minmax_recorded.circle` in archive: [model.minmax_recorded.zip](https://github.com/Samsung/ONE/files/6049037/model.minmax_recorded.zip)

**Comment by a-zh** [comment]
@hj1-jeong @seanshpark

**Comment by jinevening** [comment]
Hi, I'm hj1-jeong.

circle-quantizer does not support quantization of SPLIT Op yet. I can make it for you next Tuesday~Wednesday (Monday is our national holiday). 

I think SPLIT does not require  a special logic. If you need quantized SPLIT model, you can try to compile circle-quantizer with the below change.

**Comment by jinevening** [comment]
The above code is not tested. Please leave a comment if the above code does not work.

**Comment by a-zh** [comment]
> circle-quantizer does not support quantization of SPLIT Op yet. I can make it for you next Tuesday~Wednesday (Monday is our national holiday).

This would be very helpful to me. Thank you.

**Comment by a-zh** [comment]
> Add two lines in QuantizeWithMinMaxPass.cpp (Line number 955).

This workaround works as expected. But we still need to implement quantizing?

**Comment by jinevening** [comment]
> But we still need to implement quantizing?

The workaround does not work if an input tensor is const. I'll soon upload the PRs for quantizing SPLIT.

**Comment by jinevening** [comment]
@a-zh I close this issue as circle-quantizer now supports SPLIT Op.
