### ISSUE TITLE
Compiler FE: Model partitioning

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#6230]
As we support several backends and we can think of this in the frontend,
- one of the backend maybe need off-line code generation 
- we can assign specific operator to specific backend
- we can literally split the model into several sub models for the backends

Currently I'm not clear of this task. Let's do some prototyping and see...

**Comment by seanshpark** [comment]
Let's begin with a simple Model
- Source Model: Input - Sin - Cos - Output
- Target Model: (1) Input - Sin - Output , (2) Input - Cos - Output

With this, I could prepare/build-up necessary methods for basic tasks.

**Comment by seanshpark** [comment]
For the first step, lets assume model has only one subgraph with above `Input - Sqrt- Rsqrt- Output` network.
Then we can use `IF` or `WHILE` for multiple subgraphs.

**Comment by seanshpark** [comment]
https://github.com/Samsung/ONE/pull/6231#issuecomment-799037972 commit stores to two circle files like
![image](https://user-images.githubusercontent.com/4616940/111093883-5053af80-857d-11eb-818e-8f017e0825d9.png)

**Comment by seanshpark** [comment]
Let's now try to group graphs with same kind of group(backend).

Cases of source circle model graph 
- graph input: single or multiple
- graph output: single or multiple
- node output: used or unused

**Comment by seanshpark** [comment]
Things to do from 10,000 feet
- [ ] save connection information file
- [ ] check with a model that may produce recursive situation
- [ ] test framework with running the source model vs produced models
- [ ] check for repetitive things (per Op) and find alternative way

**Comment by seanshpark** [comment]
> check with a model that may produce recursive situation

- `Rsqrt` - `Rsqrt` sequnce should have one input and two outputs: one from first `Rsqrt` and another from second `Rsqrt`
- need to fix this

**Comment by seanshpark** [comment]
> todo : Remove unused outputs

Let's think this with `save connection information file` together...

**Comment by seanshpark** [comment]
@hseok-oh wrote https://github.com/Samsung/ONE/pull/6231#issuecomment-800762497

My draft based on partitioned model: `MANIFEST` and `Net_Sqrt_Rsqrt_001.part.config `(json)

`MANIFEST`
```json
{ 
  "major-version" : "1",
  "minor-version" : "1",
  "patch-version" : "0",
  "models"      : [ "Net_Sqrt_Rsqrt_001.part.00001_acl_cl.circle" , "Net_Sqrt_Rsqrt_001.part.00002_cpu.circle" ],
  "partition"   : "Net_Sqrt_Rsqrt_001.part.config",
  "model-types" : [ "circle", "circle" ]
}
```

`Net_Sqrt_Rsqrt_001.part.config`
```json
{ 
  "source" : {
    "file" : "Net_Sqrt_Rsqrt_001.circle",
    "inputs" : [ "ifm" ],
    "outputs" : [ "sqrt", "rsqrt", "ofm" ]
  },
  "parts" : [
    {  
      "file" : "Net_Sqrt_Rsqrt_001.part.00001_acl_cl.circle",
      "inputs" : [ "ifm" ],
      "outputs" : [ "sqrt2", "sqrt" ],
    },
    {
      "file" : "Net_Sqrt_Rsqrt_001.part.00002_cpu.circle",
      "inputs" : [ "sqrt2" ],
      "outputs" : [ "ofm", "rsqrt"]
    }
  ]
}
```

**Comment by seanshpark** [comment]
This (`Net_Sqrt_Rsqrt_Add_002`) fails with `SQRT` assigned to different group(backend)
![image](https://user-images.githubusercontent.com/4616940/111574112-2f929080-87ef-11eb-8c27-14e83d1b4a36.png)

**Comment by seanshpark** [comment]
This (`Net_Sqrt_Rsqrt_Add_003`) should produce only one but three
![image](https://user-images.githubusercontent.com/4616940/111580969-cc5b2b00-87fb-11eb-9ffd-ffd4d9907268.png)

**Comment by seanshpark** [comment]
This (`Net_Add_Sub_000`) (Sub differ) doesn't work
![image](https://user-images.githubusercontent.com/4616940/111585379-8c4b7680-8802-11eb-8a00-60fb7fe9ac37.png)

**Comment by seanshpark** [comment]
Rename `Net_` to `Part_` for testing partitioning...

**Comment by seanshpark** [comment]
Need to find a model that needs to cleanup for there are unused input...

**Comment by seanshpark** [comment]
Started posting PRs that seems stable.

**Comment by seanshpark** [comment]
- how to do with `CircleConst` ?
   - related: `Net_InstanceNorm_003`

**Comment by seanshpark** [comment]
To verify `Net_InstanceNorm_003` network, need to add `SquaredDifference` in luci_interpreter

**Comment by seanshpark** [comment]
Let's add `model validation: all nodes must have a name, all names must be unique`

**Comment by seanshpark** [comment]
About terms...
- partition file:  `.part` : describes how to partition the circle model
- connection file: `.conn` : describes how to connect partitioned circle models
- partition configuration: file to store partition file or connection file based on `ini` or `json` file format

**Comment by seanshpark** [comment]
`circle-part-eval` generated connection file seems needs some touch
- source circle path is written in full absolute path: doesn't seem to fit with nnpackage

Let's revise `circle-partitioner` working path and arguments
- `partition` file is madatory: let's use positional like circle input file
- use third argument (folder) as work folder where input circle, part file exist and outputs are generated
- this way files in the connection file have only filename, no path
- nnpackage can be freely organize source and partitioned circle files

**Comment by hseok-oh** [comment]
I've confirmed that model partitioning test results are generated in `${NNCC_WORKSPACE}/compiler/circle-part-eval`. I'll use this for runtime loading draft #6274. Thanks.

**Comment by seanshpark** [comment]
How to manage `CircleConst`
- previous comment : https://github.com/Samsung/ONE/issues/6230#issuecomment-809802813

Current issue
- https://github.com/Samsung/ONE/issues/7185#issuecomment-876012498

As for now, let's try with this change
- if `CircleConst` is used by only one node, let that `CircleConst` follow that node
- i `CircleConst` is shared by two or more nodes, let's make clones so that one `CircleConst` is used for one node.

**Comment by seanshpark** [comment]
To be sure this change and any other change is working correclty, we need some validation method in test process...

How to validate?
- number of output circle files ?
- each circle file having input nodes with names bla bla bla and output nodes with names bla bla bla...

For first step, number of output circle files can be used for our `CircleConst` issue.

**Comment by seanshpark** [comment]
Working on #8005 and strange code is changed
```diff
diff --git a/compiler/luci/partition/src/PartitionMerge.cpp b/compiler/luci/partition/src/PartitionMerge.cpp
index c517bf93f..67a7d1680 100644
--- a/compiler/luci/partition/src/PartitionMerge.cpp
+++ b/compiler/luci/partition/src/PartitionMerge.cpp
@@ -87,7 +87,9 @@ bool is_input_same(const luci::PGroup *pgroup, const luci::PGroups *pgroups)
         input_pgroup = pgroup_input;
       else
       {
-        if (input_pgroup != pgroup_input)
+        // if (input_pgroup != pgroup_input)
+        //  return false;
+        if (input_pgroup->group != pgroup_input->group)
           return false;
       }
     }
```
Out internal model is now partitioned as expected but two unit tests fails.

**Comment by seanshpark** [comment]
Part_Sqrt_Rsqrt_Add_002

![image](https://user-images.githubusercontent.com/4616940/141880983-45c569b4-1bd4-4a5e-8b94-f7e4d2070b1c.png)

**Comment by seanshpark** [comment]
Multi-output nodes partitioning is a bit tricky when merging to the host(?).
So, I think it would be better to prepare PGroup with nodes that should be merged for virtul nodes, in the first place.
- like CircleFullyConnected with CircleOutputExclude for empty bias
- CircleXXX + CircleXXXOut

**Comment by seanshpark** [comment]
done for now
