### ISSUE TITLE
[onert] Rename namespace "cpu_common" to "common"

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#6284]
`onert::backend::cpu_common` is introduced in `onert/core/` (not `onert/backend`) and classes in `cpu_common` are used on many backend implementations. By renaming,

- Remove restriction from name 
- Reduce namespace word length

@Samsung/nnfw Please share your opinions.

**Comment by wateret** [comment]
I like renaming to `common`. Also I would like a name without `cpu_`. Here's more candidates.

- generic
- basic

**Comment by hseok-oh** [comment]
>Here's more candidates.

`basic` looks good to me.

**Comment by hseok-oh** [comment]
TODO

- [ ] Rename directory
- [ ] Update namespace
- [ ] Update header guard

**Comment by hseok-oh** [comment]
Done
