### ISSUE TITLE
[luci-interpreter] Integrate build configurator of luci interpreter for cortex-m4 microcontrollers

### ISSUE THREAD

**Issue by SlavikMIPT** [Samsung/ONE#6302]
In continuation of https://github.com/Samsung/ONE/issues/5080

## Goal
Integrate build configurator of luci interpreter for cortex-m4 microconrollers into the mainstream.

## Rationale
During investigation I found that luci interpreter as-is does not fit into flash memory of MCU.

In offline discussion with SRR members we came up with three solutions:
- Static set of kernels: like in tflite micro, code contains fixed subset of tflite kernels.
- Dynamic set of kernels: compile all kernels in form of dynamic library, store this library in large external storage (for example SD card) and load them from interpreter on demand.
- Build time configurable set of kernels: during luci interpreter build time we can choose which kernels to use.

**Static set**

pros:
- This is the easiest approach to implement

cons:
- Can not run arbitrary NNs, because this approach restricts set of available kernels, even if they are available in "big" luci-interpreter. It requires some engineering effort from user to add more kernels
- Could be inefficient in terms of used memory if target NN does not use all kernels presented in interpreter

**Dynamic set**

pros:
- Can run arbitrary NN
- Can update working NN at any time, even after MCU is flashed, for example download NN from internet

cons:
- Additional hardware is needed (like SD card for storing all code and structures)
- Need a lot of engineering effort to implement dynamic code loading on target MCU

**Build time configurable set**

There are ways to configure build:
- By set of target layers
- By set of target models

pros:
- No need for additional hardware to support arbitrary NNs
- Saves resources, because this solution uses only needed code
- Can apply additional optimizations on kernels/runtime based on target models

cons:
- Can not update NN that is flashed on device
- Need to rebuild interpreter for every target model/set of layers

## Conclusion

For now we decided to try **Build time configurable** approach, because:
- "Static" approach is not flexible and effective
- "Dynamic" approach is flexible and effective, but hard to implement and requires additional hardware.
- "Build time" approach is flexible, and provides more optimization opportunities

## Plan

1. Add support of arm-none-eabi toolchain to cmake build script(to load third-party dependencies such as tensorflow, mbed-os e.t.c)
2. Write a python script which configures libraries and generates code (supporting required kernels to run the .tflite/.circle models provided in input parameters) which is ready to build using mbed-cli.
3. Run python script from cmake

**Comment by SlavikMIPT** [comment]
I continue to work on the issue, at the moment I have written cmakes to build the luci-interpreter with arm-none-eabi toolchain and writing a demo benchmark to run on a cortex microcontrollers

**Comment by binarman** [comment]
Today we had a meeting about MCU support in luci-micro.

This task gives us several challenges:
- Make MCU build developer friendly. For now build of luci-micro requires a lot of manual actions, like toolchain downloading, project configuration, etc.
- Make it possible to build luci-interpreter for different platforms in one repo without interference between them: enabling of one platform **should not degrade features/performance** of other supported platforms. Currently if we want to build interpreter for bare metal we need to switch to slower kernels for all platforms.
- Require as little RAM as possible for interpreter itself. For now there are no convenient mechanism to build only part of the kernels (described as a **Build time configurable** approach mentioned above).

To achieve goals above   we came up with several steps:

- Refactor `KernelBuilder`, to make it possible to configure set of supported operators during build.
  - Current design contains multiple `KernelBuilders` and make it hard to generate code, configure it with some macros defines, etc..
- Enable partial interpreter build from list of operators.
- Implement HAL(maybe PAL, we need to decide terminology) to abstract from available OS resources, like threads.
- Build integration of luci-interpteter-micro into main build system, to simplify it for developers.

**Comment by binarman** [comment]
This issue is now part of #7288
Let's continue there, closing this one.
