### ISSUE TITLE
[one-quantize] Quantize with exact min/max for specified layers

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#6303]
## What

Add a new option to quantize the weights of some layers to include the exact min/max values

## Why

Nudging shifts the zero point, making the quantization range not include the exact min/max values. But for some layers, it is important to keep the exact values to reduce quantization errors. We will provide an option to specify the layers that need to include the exact min/max values when quantized.

CC @meejeong

**Comment by jinevening** [comment]
I've listed the changes for the modules related to quantization.

### one-quantize
- Add an option to specify the layers.
- Example: `--exact_minmax=layer1,layer2` (layer1, layer 2 are the names of layers)
- If a user gives the option, `one-quantize` should call `circle-quantizer` with proper options

### circle-quantizer (called with --quantize_dequantize_weights)
- Add an option to specify the layers.
- Example: `--exact_minmax=layer1,layer2` (layer1, layer 2 are the names of layers)
- The specified layers should not be fake-quantized (to keep the original min/max values).

### record-minmax
- No need to change

### circle-quantizer (called with --quantize_with_minmax)
- Add an option to specify the layers.
- Example: `--exact_minmax=layer1,layer2` (layer1, layer 2 are the names of layers)
- The specified layers should be quantized with a new nudging algorithm where the quantization range includes the exact min/max values.

**Comment by seanshpark** [comment]
@jinevening , we may need to revise `one-build` options too.

CC @mhs4670go

**Comment by jinevening** [comment]
We don't need this functionality anymore. So I'll close this issue. Let's reopen when necessary.
