### ISSUE TITLE
Compiler FE: rename PGraph, PGraphs

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#6326]
Current `PGraph` and `PGraphs` name in luci partition misleads it's nature.

Let's find appropriate name for these.

**Comment by seanshpark** [comment]
From https://github.com/Samsung/ONE/pull/6325#issuecomment-805677940

**Comment by seanshpark** [comment]
With offline talk with @llFreetimell and help from @parjong ,

- `PGraph` -> `GroupNodes`
- `PGraphs` -> `GroupNodesCollection`

`GroupNodesCollection` : `GroupNodesCol` for short

`GroupNodes` -> `PGroupNodes` as it's used for `Partition` or `PartGrpNodes` ...

**Comment by seanshpark** [comment]
@llFreetimell , @mhs4670go , any comments?

**Comment by llFreetimell** [comment]
From `PNode`, `PGraph`, `PGraphs` to...

- `MockNode`, `MockGraph`, `MockGraphs`
- `PNode`, `PNodeBox`, `PNodeBoxes` --> 1st preference for me :smiley_cat: 
- `PGroupNode`, `PGroupNodeBox`, `PGroupNodeBoxes`

**Comment by seanshpark** [comment]
> PNode, PNodeBox, PNodeBoxes

I think this is nice :)
One thing bothers me is that there is a member `group` that is used for the grouping same nodes.
This `group` and `box` doesn't seem to fit.

1) PNode, PNodeGroup(+group), PNodeGroups 
2) PNode, PNodeBox(+box), PNodeBoxes

for 2), chaning `group` variable to `box` is somewhat strange to me... 

We can use word `key` instead of `group`... hmm...

Need more thougts... :)

**Comment by seanshpark** [comment]
How about `PNode`, `PNodeGroup`, `PNodeGroups` ?

**Comment by mhs4670go** [comment]
@seanshpark Then, how about changing their attribute name `std::string group` to `name` or `backend`?
```
PGroup->name;
PGroup->backend;
```

**Comment by seanshpark** [comment]
>  how about changing their attribute name std::string group to name or backend?

I think `backend` is specific to some purpose. we can partition by other aspects, not only by the backend.
`name` of `PGroup` seems OK, but there is member in `PartitionTable` and `PartitionTable` which has `group` variable.
They exist for same purpose and I think using same name would be better for understanding.

**Comment by seanshpark** [comment]
done
