### ISSUE TITLE
[circle-quantizer] Support SplitV quantization

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#6331]
## What

Support SplitV quantization

## Why

To increase model coverage

**Comment by jinevening** [comment]
CircleSplitV has three inputs

`input`, `size_splits`, `split_dim`

`size_splits` and `split_dim` should not be quantized.

**Comment by m-bronnikov** [comment]
I tried to quantize following model with `SplitV` locally:

![image](https://user-images.githubusercontent.com/43731397/133281591-c7e51619-cd34-4c2b-8340-b73ade72cf9d.png)

Quantization with random data to different types works looks good:

**Q16:**
![image](https://user-images.githubusercontent.com/43731397/133283373-6ae61005-b0ea-491d-a75d-eb176d21e862.png)

**Q8:**
![image](https://user-images.githubusercontent.com/43731397/133283607-37f87d81-888e-450f-8c5b-104a48489f84.png)

I think this issue could be closed! =)

**Comment by jinevening** [comment]
@m-bronnikov Thanks for the work!
