### ISSUE TITLE
common-artifacts unnecessary build actions

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#6530]
After some fixes, unnecessary build actions are almost reduced

Now I could see lots of
```
Generate XXX nnpackage directory
```
lines :)

**Comment by seanshpark** [comment]
CC @mhs4670go

**Comment by mhs4670go** [comment]
@seanshpark Could you give it a try one more time after removing `build/compiler/common-artifacts` and `build/CMakeCache.txt`?

**Comment by seanshpark** [comment]
delete them and now it is clean build :)
thanks!
