### ISSUE TITLE
QuantizedModelVerifierTest: GTEST.NO_ASSERTION

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#6571]
Current `QuantizedModelVerifierTest` shows lots of `GTEST.NO_ASSERTION` issue from our TCM.

How to reproduce in local:
- follow and run `infra/scripts/build-tcm.sh`
- latest package is `tca-standalone-1.0.0.jar`

**Comment by seanshpark** [comment]
CC @jinevening

**Comment by jinevening** [comment]
> You may add SUCCEED(); at each test to resolve this issue.

Now all tests have `SUCCEED` or `EXPECT_ANY_THROW`. I think we can close this issue.

**Comment by seanshpark** [comment]
Thanks! I'll check the report tomorrow :)

**Comment by seanshpark** [comment]
Fixed :)
