### ISSUE TITLE
Bump up ONE to 1.15.0 on review.tizen.org

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#6610]
## Background 

In https://github.com/Samsung/ONE/pull/6241, Compute Library bump to v21.02. To enable this on public tizen obs, we need to update both ONE(https://review.tizen.org/gerrit/#/admin/projects/platform/core/ml/nnfw) and Compute Library(https://review.tizen.org/gerrit/#/admin/projects/platform/upstream/armcl). 

## Issue

- https://github.com/Samsung/ONE/pull/6241 is merged into development branch(master) of version 1.15.0
- To enable obs build, upstream branch must contains proper version commit(1.15.0) : 

![image](https://user-images.githubusercontent.com/4862887/114678016-ce0a0700-9d45-11eb-8c9f-452443d73306.png)

but 1.15.0 should be keep until 1.15.0 is released. 

- We have two options : 
    1) push dc18d30228b4a with `1.15.0` into upstream branch and push patches into tizen branch until ONE 1.15.0 released  : no ONE 1.15.0 tag commit will be pushed into review.tizen.org
    2) push dc18d30228b4a with `1.15.0pre` into upstream branch and push ONE 1.15.0 into upstream branch on dc18d3022 : ONE 1.15.0 tag commit will be pushed into review.tizen.org

## TODO
- Let's go for 1)

**Comment by hseok-oh** [comment]
@chunseoklee Can we close this issue?

**Comment by chunseoklee** [comment]
> @chunseoklee Can we close this issue?

Ok I will
