### ISSUE TITLE
[circle-quantizer] Support quantization of LRN (Local Response Norm)

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#6704]
## What

Let's quantize LRN op.

**Comment by seanshpark** [comment]
@jinevening , I've made weekly `SPRINT` as we work on `agile` style. Would you like to join it?
There is not much to do. Split tasks that can be done within a week and set sprint in `milestone`.
If a task exceeds a week that is OK. Add another issue for the left over tasks and set to next sprint.
Add a comment and link in old task to new task and close it.

**Comment by jinevening** [comment]
> Would you like to join it?

Sure :) This issue is a small job, so it would be appropriate for a weekly `SPRINT`.
