### ISSUE TITLE
Compiler FE: Partition enable with IF Op

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#6708]
Lets' enable partitioning with IF and WHILE Op.

These two has linked sub-graph to clone; which can be a bit more complicated than other ops.

**Comment by seanshpark** [comment]
For #6230

**Comment by seanshpark** [comment]
Start with `IF`
- from a simplest one `IF` model, let's see how the partitioned result graph should look like.

**Comment by seanshpark** [comment]
Refresh for `IF` node
- `THEN` and `ELSE` branch in file is index of subgraph --> order of subgraph is important
- there is `post_import_graph()` step in `import` that will make a link FROM index TO  graph pointer

**Comment by seanshpark** [comment]
In the steps of partitioning, preparation for `IF` is now ready in draft.
Last big thing left is to attach subgraphs to `IF` node: in `produce_pmodules()` method.

**Comment by seanshpark** [comment]
Test of `circle-partition`
```
cd circle-partitioner-test

LUCI_LOG=1 \
../circle-partitioner/circle_partitioner \
Net_InstanceNorm_003.part \
Net_InstanceNorm_003.circle \
Net_InstanceNorm_003
```

Test of `circle-part-value-test`
```
cd circle-part-value-test/Net_If_Add_Sub_000.001

LUCI_LOG=1 \
../../circle-part-driver/circle_part_driver \
Net_If_Add_Sub_000.001.conn.ini \
3 \
Net_If_Add_Sub_000.001.circle.input \
Net_If_Add_Sub_000.001.circle.output
```

**Comment by seanshpark** [comment]
Testing another IF graph inside IF-THEN graph...

_luci-interpreter_ has this condition.
```cxx
graph->getInputTensors().size() == getInputTensors().size() - 1
```

**Comment by seanshpark** [comment]
> graph->getInputTensors().size() == getInputTensors().size() - 1
> 
> This condition doesn't seem to be correct.

@jinevening , do you know why this condition is needed? or if you don't know, can you give your opinion on this condition?

**Comment by seanshpark** [comment]
`circle-part-value-test` with `Part_If_Add_Sub_001` graph + `Part_If_Add_Sub_001.001.part`
--> _luci_interpreter_ needs more updates

> RuntimeError: tensorflow/lite/kernels/if.cc:77 num_inputs != subgraph->inputs().size() (2 != 3)Node number 2 (IF) failed to prepare.

**Comment by jinevening** [comment]
> do you know why this condition is needed? or if you don't know, can you give your opinion on this condition?

It seems that the above condition (`graph->getInputTensors().size() == getInputTensors().size() - 1`) checks if `then_graph` and `else_graph` have the same number of inputs with IF statement excluding `cond`, which is the first input of IF statement.

I think that the recipe used for the test should be updated to meet the requirement.

**Comment by seanshpark** [comment]
@jinevening , thanks for the comment, I've found this condition came from tflite kernel source.

`getInputTensors().size() - 1` : this is number of inputs of `IF` node. (excluding `cond` input)
`graph->getInputTensors().size()` this is number of inputs for the graph

From this, we cannot give condition from graph input...

**Comment by seanshpark** [comment]
Need to test
- run generated `tflite` file with tflite interpreter

**Comment by seanshpark** [comment]
IF done.
