### ISSUE TITLE
Compiler FE: Install circle-tensordump

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#6760]
There are some problems when `circle-tensordump` is installed. `circle-tensordump` needs hdf5 library, which makes it hard to install the `circle-tensordump`. 

As of now, `circle-tensordump` is installed but can't be run.
```bash
$ ./circle-tensordump
./circle-tensordump: error while loading shared libraries: libhdf5_cpp.so.10.1.0: cannot open shared object file: No such file or directory
```

It is because when the one compiler is built, we use the specific version of hdf5 package that is built from cmake rather than the one of system's. I can't come up with proper solution abut this. We should have more discussion. 

Until then, `circle-tensordump` shouldn't be installed. I'll remove the install command.

Anyway, these are things that I came up with as of now.

- Get build directory of hdf5 package and manually copy the library files to the install directory.
  - Looks bad to me..
- Make hdf5 package be pre-requisite of one compiler
  - Version problem might be occurred..

**Comment by seanshpark** [comment]
> Get build directory of hdf5 package and manually copy the library files to the install directory.
Looks bad to me..

Um?... what is bad?

**Comment by mhs4670go** [comment]
@seanshpark I think it would be hard to keep maintaining hdf5 library in our release package list. The reason why I said "looks bad" is from that point. And, plus, hdf5 package is not our package.

> Get build directory of hdf5 package and manually copy the library files to the install directory.

Say I choose this option.
```bash
$ ls build/overlay/lib/*hdf5*       
build/overlay/lib/libhdf5.a                 build/overlay/lib/libhdf5_hl.so.10.1.0
build/overlay/lib/libhdf5_cpp.a             build/overlay/lib/libhdf5_hl.so.1.8.16
build/overlay/lib/libhdf5_cpp.so            build/overlay/lib/libhdf5.settings
build/overlay/lib/libhdf5_cpp.so.10.1.0     build/overlay/lib/libhdf5.so
build/overlay/lib/libhdf5_cpp.so.1.8.16     build/overlay/lib/libhdf5.so.10.1.0
build/overlay/lib/libhdf5_hl.a              build/overlay/lib/libhdf5.so.1.8.16
build/overlay/lib/libhdf5_hl_cpp.a          build/overlay/lib/libhdf5_tools.a
build/overlay/lib/libhdf5_hl_cpp.so         build/overlay/lib/libhdf5_tools.so
build/overlay/lib/libhdf5_hl_cpp.so.10.1.0  build/overlay/lib/libhdf5_tools.so.10.1.0
build/overlay/lib/libhdf5_hl_cpp.so.1.8.16  build/overlay/lib/libhdf5_tools.so.1.8.16
build/overlay/lib/libhdf5_hl.so

```
These are the list of hdf5 library as of now whose version is 1.8.16. Technically, some of them aren't actually needed but the number is still a lot. Of course sometimes we can use regex pattern when we get the list of them in cmake, but sometimes we can't when, for instance, we build a `one-compiler-dev` debian package.

I'm not sure but its script would be like this.
```bash
$ cat debian/one-compiler-dev.install 
# {FILES_TO_INSTALL} {DEST_DIR}
# bin
usr/bin/circledump opt/one_compiler/bin/
# lib
usr/lib/libhdf5_cpp.so opt/one_compiler/lib/
usr/lib/libhdf5_cpp.so.10.1.0 opt/one_compiler/lib/
usr/lib/libhdf5_cpp.so.1.8.16 opt/one_compiler/lib/
usr/lib/libhdf5.settings opt/one_compiler/lib/
usr/lib/libhdf5.so opt/one_compiler/lib/
usr/lib/libhdf5.so.10.1.0 opt/one_compiler/lib/
usr/lib/libhdf5.so.1.8.16 opt/one_compiler/lib/
# include
usr/include/* opt/one_compiler/include/
```
And, maybe there might still be other places to keep its version. Then, when we want to change the version in the future, it would be a burden I think.

Plus, from the point of debian view, making hdf5 library be another package and letting `one-compiler-dev` have a dependency of it is more natural than installing `one-compiler-dev`'s dependencies by itself.
