### ISSUE TITLE
[one-cmds] Fix arser bool with 'False'

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#6842]
```cxx
if (arser.get<bool>("--someoption"))
```
doesn't seem to work (return `False`) when cfg file has
```
someoption=False
```

that is `if (arser.get<bool>("--option"))` seems to be always true.

**Comment by seanshpark** [comment]
Found this while working with #6832

**Comment by seanshpark** [comment]
CC @mhs4670go

**Comment by mhs4670go** [comment]
@seanshpark I think that `someoption` has 0 nargs. It means, there is no need to give value to that option.

```bash
$ ./driver --someoption // arser.get<bool>("--someoption") == true
$ ./driver                      // arser.get<bool>("--someoption") == false
```

**Comment by mhs4670go** [comment]
Hmm.. To make this more intuitive, the point where cfg is evaluated should be changed. I'm gonna check that out.

**Comment by seanshpark** [comment]
Fixed! thank you!
