### ISSUE TITLE
[one-cmds] Make parser case-sensitive

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#6854]
## What

Let's make configparser preserve the case.

## Why

Actually, the keys in sections of configparser are case-insensitive. But I've missed `--O1` case. I think it would be better to make the configparser preserve the case rather than changing `O1` to `o1`.

**Comment by seanshpark** [comment]
@mhs4670go , we now have `2021...` in `Projects`. Please use them instead of old `2020 ... `

**Comment by mhs4670go** [comment]
@seanshpark Oh, sorry. I didn't know 2021 exists as it always show me `Recent` tap. I'll keep it in mind.
