### ISSUE TITLE
[one-cmds] The way one-codegen finds backends

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#6884]
## What

Let's extends the point where `one-codegen` finds backends.

## Why

As of now, `one-codegen` finds its backends only in its directory folder. But, we can make this coverage broader to give users more convenient experience.

Here's the path I'm going to add.

```bash
$ ls one_package_dir
backends  bin  doc  include  lib  test
```

Note `backends` folder is added. If users install their backends on below `backends` folder, `codegen` would automatically find its binary.

**Comment by mhs4670go** [comment]
Because @6885 is merged, `codegen` finds its backend in `../backends` folder. It will be extended to `$PATH` later when it is needed.

**Comment by seanshpark** [comment]
Maybe #6885  ?
