### ISSUE TITLE
[vconone] Version with debian package build number(string)

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#6895]
Current version uses form of `major.minor.patch`.
Our debian package may have addition strings, currently `YYMMDDHH` for nightly builds.
Resulting, something like `1.16.0-21052710` may exist.

As our command lines show the version through _vconone_ , lets' find a way to print debian package version string.

Related things tochange
- cmake to accept debian package  version string from build
- new APIs to support debian package version string

Limitations
- existing version number/string will be as-is as debian version string is free form including alphabets

Current version
```
$ circle2circle --version
circle2circle version 1.16.0
```
Expected version
```
$ circle2circle --version
circle2circle version 1.16.0 (1.16.0-21052710)
```

**Comment by seanshpark** [comment]
CC @mhs4670go

**Comment by mhs4670go** [comment]
Hmmm.. First thing that came to me is to use `dpkg-parsechangelog` command in `vconone`.
```bash
$ pwd
ONE
$ dpkg-parsechangelog --show-field Version
1.16.0

$ pwd
ONE/compiler/vconone
$ dpkg-parsechangelog --file ../../debian/changelog  --show-field Version          
1.16.0
```

And, use this result at cmake.

**Comment by mhs4670go** [comment]
@seanshpark If this issue is resolved, `debian/changelog` would be the only place to have version info? Or `vconone`'d still have its version info?

**Comment by seanshpark** [comment]
> debian/changelog would be the only place to have version info? Or vconone'd still have its version info?

Ah, there will be both. `vconone` will contain it's own version and this will be the default.
CMake is to override the version and do something by manual.
I havn't a concrete case for this usage. It's to prepare when we may need someday.

**Comment by mhs4670go** [comment]
@seanshpark In versioning(?) meeting, we've decided to print just `major.minor.patch` without build number. So, things are fine the way they are:)
