### ISSUE TITLE
[one-cmds] Do not symlink to virtual env python

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#6902]
## What

Let's remove the `ln` command in `one-prepare-venv` that symlinks virtual env's python to `${PACKAGE_PATH}/bin/python`.

## Why

https://github.com/Samsung/ONE/blob/7e6742dd0cd96a75e3eb882ba0b0ea6f732facb5/compiler/one-cmds/one-prepare-venv#L80-L82

As of now, virtual env's python binary is symlinked. But turns out it does not what we thought it does. I mean, we thought that symlinked binary would do what `venv/bin/python` does but it doesn't.

Python executable itself isn't any difference with other python executables. It's their directory location that matters. When Python is starting up, it looks at the path of its binary. Then, the path is used for locating the `site-packages` directory by searching the relative path `lib/pythonX.X/site-packags/`, where X.X is the version of Python you're using.

So, `${PACKAGE_PATH}/bin/python` is useless unless there's `site-package` in `${PACKAGE_PATH}/lib/pythonX.X/`.

### reference

https://realpython.com/python-virtual-environments-a-primer/#how-does-a-virtual-environment-work

**Comment by seanshpark** [comment]
@hseok-oh , as I recall, you added the symbolic link but I don't remember the reason. Could you please describe it in short?

**Comment by seanshpark** [comment]
Can we close this issue?
