### ISSUE TITLE
[circle2circle] Change output node

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#6974]
Some in-house models have `CAST` at the end of the model, which our _luci-interpreter_ doesn't support yet.

To go around this situation,
if we could change the output node to the one before the `CAST`,
then we could at least test the model with the sub network.

And with this new feature, we can test the model without cutting the model with other tools.

**Comment by mhs4670go** [comment]
@seanshpark Codes look fine to me. I just wonder it can be introduced to `circle2circle` which uses for circle graph optimization. IMHO, this might be introduced to another tool that modify the graph.

**Comment by seanshpark** [comment]
>  I just wonder it can be introduced to circle2circle which uses for circle graph optimization.

it will be introduced in `circle2circle`, you can see in DRAFT code.

**Comment by seanshpark** [comment]
Done for now
