### ISSUE TITLE
Introduce tool to slice parts of a circle model

### ISSUE THREAD

**Issue by periannath** [Samsung/ONE#6996]
While developing runtime optimization, the developer only needs to run the bottlenecks of the model instead of the entire model.

AFAIK, ONE has tool to slice `tflite` file. (`./tools/tflitefile_tool/select_operator.py`)

```bash
$ echo 9 > op_list
$ python3 tools/tflitefile_tool/select_operator.py  mv1.tflite  op_list  mv1_slice.tflite
```

It would be better if ONE provides tool to slice `circle` model.

**Comment by llFreetimell** [comment]
This issue will be handled at #6648!
Would you close this? :)

**Comment by periannath** [comment]
This issue will be handled in #6648.
