### ISSUE TITLE
Resolve Svace/Coverity Defect(21/06/29)

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#7111]
Due to PR #7003, several defects are introduced. Let's resolve them. 

svace link : ~~https://analysishub.sec.samsung.net/service/analyses/641305~~ (resolved at 07/05/2021)
coverity link : ~~https://analysishub.sec.samsung.net/service/analyses/641529~~

**Comment by chunseoklee** [comment]
@YiHyunJin PTAL

**Comment by YiHyunJin** [comment]
|  |
-- | -- |
DeviceInfo.h:130 | UNINIT.CTOR.MANY |
Tensor.cc:511 | NO_CAST.INTEGER_OVERFLOW |
StorageTypeUtil.cc:40 | NO_CAST.INTEGER_OVERFLOW |
GpuObject.h:154 | UNINIT.CTOR |
GpuObject.h:151 | UNINIT.CTOR |
ClKernel.h:50 | UNINIT.CTOR |
add | O |

**Comment by YiHyunJin** [comment]
|  |
-- | -- |
DeviceInfo.h:130 | UNINIT.CTOR.MANY |
Tensor.cc:511 | NO_CAST.INTEGER_OVERFLOW |
StorageTypeUtil.cc:40 | NO_CAST.INTEGER_OVERFLOW |
GpuObject.h:154 | UNINIT.CTOR |
GpuObject.h:151 | UNINIT.CTOR |
ClKernel.h:50 | UNINIT.CTOR |
Buffer.h:64 | UNINIT.CTOR |
Tensor.cc:513 |  NO_CAST.INTEGER_OVERFLOW |
Shape.h:391 |  INVARIANT_RESULT.OP_ZERO |
Shape.h:418 | NO_EFFECT |
StorageTypeUtil.cc:40 | SIGNED_TO_BIGGER_UNSIGNED | 
Shape.h:391 | NO_EFFECT |

**Comment by YiHyunJin** [comment]
StorageTypeUtil.cc:40

`const uint64_t flt4_size = 4 * (descriptor.data_type == DataType::FLOAT32 ? 4 : 2);`

so flt4_size is only 8 or 16.

**Comment by chunseoklee** [comment]
New svace result : https://analysishub.sec.samsung.net/service/analyses/655979

@YiHyunJin PTAL 
1 (relevant) remaining defect : [link](https://analysishub.sec.samsung.net/dm/tizen/sb2/main/review#PRJID=501&WGID=464229)

**Comment by chunseoklee** [comment]
New coverity report : https://analysishub.sec.samsung.net/service/analyses/656033

@YiHyunJin unfortunately, many coverity defects found. PTAL

**Comment by chunseoklee** [comment]
@YiHyunJin Now, two defects may remain after merging #7150. 

Here is the recent result with the latest master : [link](https://analysishub.sec.samsung.net/service/analyses/662916)

**Comment by chunseoklee** [comment]
#7150 merged. Here is a new coverity result : [link](https://analysishub.sec.samsung.net/service/analyses/664749)
