### ISSUE TITLE
[onert] Test coverage under 80%

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#7123]
Current status

- Line coverage: 74% (release criteria: 80%)
- Method coverage: 68% (release criteria: 80%)

**Comment by chunseoklee** [comment]
This is very strange. It seems like ADD test case is not run with gpu_cl backend.

@YiHyunJin PTAL [internal coverage link](http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-arm-runtime-coverage/52/cobertura/)

**Comment by seanshpark** [comment]
http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-arm-runtime-coverage/52/cobertura/runtime_onert_backend_gpu_cl_open_cl/
Most of the codes are not test.

**Comment by YiHyunJin** [comment]
I think... the current gpu_cl is not working.
so 
https://github.com/Samsung/ONE/pull/7137,
https://github.com/Samsung/ONE/pull/7138,
and https://github.com/Samsung/ONE/pull/7139
are merged, then I will check.

**Comment by chunseoklee** [comment]
With several fix, mixed test now runs and we have 77% line coverage : [link](http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-arm-runtime-coverage/55/cobertura/)

@YiHyunJin PTAL. line coverage of `gpu_cl` backend is too low. Especially, `runtime.onert.backend.gpu_cl.open_cl` shows 30% and  `runtime.onert.backend.gpu_cl.open_cl.kernels` shows 22%

**Comment by YiHyunJin** [comment]
Removed unused and unnecessary codes. - https://github.com/Samsung/ONE/pull/7167

But buffer is about to be implemented soon.

**Comment by chunseoklee** [comment]
> Removed unused and unnecessary codes. - #7167
> 
> But buffer is about to be implemented soon.

I will check coverage with this PR on my local. I will share it soon.

**Comment by chunseoklee** [comment]
With #7167, line coverage is now 78% ( increased by 1%). Need to add tests or remove code more.

**Comment by hseok-oh** [comment]
After a5c85dcc67bed2a45b7edda6d55c508b7c14309c

```
02:28:18  Overall coverage rate:
02:28:18    lines......: 82.4% (29457 of 35767 lines)
02:28:18    functions..: 78.5% (4597 of 5853 functions)
```

Today

```
02:30:15  Overall coverage rate:
02:30:15    lines......: 83.2% (29354 of 35298 lines)
02:30:15    functions..: 78.9% (4560 of 5779 functions)
```

**Comment by hseok-oh** [comment]
Today
```
02:27:38  Overall coverage rate:
02:27:38    lines......: 83.2% (29619 of 35605 lines)
02:27:38    functions..: 78.1% (4667 of 5976 functions)
```
