### ISSUE TITLE
[luci] General Constant Folding Pass

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE#7129]
## What?

Let's introduce `CircleConstantFoldingPass` in `luci`.
And integrate current `Fold*Pass` to `CircleConstantFoldingPass`.

## Why?

For now, we should introduce new constant folding pass for each operations whenever we need to introduce new pass.
It has some cons.
- If users want to fold 10 operations
  - We should introduce 10 passes
  - Users should turn on 10 options
- If we want to use similar logic in other modules/passes, we are hard to re-use it.

## How?

- Introduce `CircleNodeCalculator.h` (name can be changed) in `luci/service`
  - Implement constant folding logic in each nodes' file
- Introduce `CircleConstantFoldingPass.h` in `luci/pass`.
- Introduce `--constant_folding` option in `circle2circle`
- Move current logic of `Fold*Pass` to `CircleNodeCalculator`
- (After checking whether each are used or not) Deprecate `Fold*Pass`

**I tried to use `luci-interpreter` for this, but it is impossible for now because `luci-interpreter` requires `luci`. (cyclic dependency)**

### Draft

TBD

**Comment by seanshpark** [comment]
> Users should turn on 10 options

I don'k know why this is a problem. We can provide an meta like option to turn on other options. like current `--O1`
And on the contrary that can be a case where user wants to turn on 8 cases but not with others.

> Introduce CircleNodeCalculator.h

Please do not use `Circle` as prefix for a Pass name. All the things are `Circle`.
I also like to remove existing `Circle---Pass` too.

**Comment by llFreetimell** [comment]
> I don'k know why this is a problem. We can provide an meta like option to turn on other options. like current --O1

For users of `circle2circle`, you are absolutely right.
What I wanted to say was when we want to use the pass itself(e.g. internal module). We should add each passes to phase.

---

After I heard your opinion, it would be better to re-open when this issue is really needed :)
Close for now!
