### ISSUE TITLE
[record-minmax] Accept raw data as a representative dataset

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#7132]
## What

Let's enable record-minmax to accept raw data as a representative dataset.

## Why

For someone who is not familiar with hdf5.

CC @lemmaa

**Comment by jinevening** [comment]
`record-minmax --input_data <input_data>`

If <input_data> is an .h5 file (~~.h5), record-minmax will run as before.

Else, <input_data> is assumed to be a text file which specifies the representative data. The text file should contain absolute file path per line. The pointed file should be a binary file containing one representative input, ready to be consumed by the input circle model without any modification (i.e., pre-processed raw data).

**Comment by jinevening** [comment]
Future work may be to support some pre-precessing functionalities.

**Comment by seanshpark** [comment]
> Else, <input_data> is assumed to be a text file which specifies the representative data.

This makes codes complicated. I don't think this is a good approach. It would be better to introduce new option.

**Comment by jinevening** [comment]
I'm afraid adding a new option may confuse users. For example, if there are two options (e.g., --input_data (we should keep this option for backward compatibility), --raw_input_list), users can misuse the option (using with a wrong file type or using both options, etc).

**Comment by seanshpark** [comment]
> using with a wrong file type 

All the options have to solve this problem. Even you go with one option: h5 or not.

> using both options

We also have this cases. I think this is natural. We have this situation on _one-import_tf_ where input model be one of saved model, keras or just graph_def.

1) to support by option
- `--input_data` or  `--raw_input_list` or ...
- `--input_data` for input file and addition option `--data-type`  (default is `h5` and there are others, `list` for text format list)
- we only check for the type, if failed it is a failure.  codes and testing will be simple.

2) automatic type detection
- we must first try with existing supported type. how? using extension can be dangerous.
- we may try with error handling. h5 throws. this is ok. for text of list.. well...
- when we try to support other types... it happens to be a text with a list but format is different...
- code itself should handle all the cases with `if, elseif, elseif,....`

anyway, there can be lots of bad cases that we can think of and lots of good things we only wany to think of..
there can be many complicated and error prone for also (1) but here we want to make it simple for both use interface and code.

**Comment by jinevening** [comment]
@seanshpark  I understand your concern.

Then, there are two options.
1. --input_data, --raw_input_list, ..
2.  --input_data, --input_data_format (input_data_format can be `h5`/`hdf5` (default) and `list`)

I'd like to go with the second option because it is simpler.

**Comment by jinevening** [comment]
TODO
- [ ] Update record-minmax
- [ ] Update one-build, one-quantize interface
- [ ] Add tests (one-cmds)

**Comment by jinevening** [comment]
All done
