### ISSUE TITLE
[circle-inspect] Input and output info

### ISSUE THREAD

**Issue by Bronnikoff** [Samsung/ONE#7200]
## What? 

How about to add an option to `circle-inspect`, which gives pretty information about input and output nodes of the model?

## Why?

Information about input and output nodes of model required for any usage of model. For tflite model this info can be easily obtained using python:
```python
import tensorflow as tf

with open('model.tflite', 'rb') as f:
  interp = tf.lite.Interpreter(model_content=f.read())

print(interp.get_input_details())
print(interp.get_output_details())
``` 

 It would be nice to have tool, which can give this info for circle models.

**Comment by Bronnikoff** [comment]
PR: #7201

**Comment by seanshpark** [comment]
@Bronnikoff , `circle-inspect` is used for dredd test to check operators type, cound and stuff.
Are you planning to revise dredd test? if not please do not add new features to _circle-inspect_
This is the purpose of this tool and I do not want to add features that are not used by the tool.

You may add a new tool for your purpose with a name that tells the purpose.

**Comment by Bronnikoff** [comment]
> Are you planning to revise dredd test? if not please do not add new features to _circle-inspect_

Ahh, I just took a look to README description of the tool and made a decisiion to extend this tool for my purposes:

```
circle-inspect allows users to retrieve various information from a Circle model file
```

So, I don't planning to revise dredd tests, let's close this issue.
