### ISSUE TITLE
[common-artifacts] Check enable If_000

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#7224]
Let's check if we can enable `If_000` for `tcgenerate(If_000)`

**Comment by seanshpark** [comment]
From #7222

**Comment by seanshpark** [comment]
> Generate build/debug/compiler/common-artifacts/If_000.opt/metadata/tc/input.h5 and build/debug/compiler/common-artifacts/If_000.opt/metadata/tc/expected.h5
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Invalid data size.
Aborted (core dumped)

**Comment by seanshpark** [comment]
In compiler/common-artifacts/src/TestDataGenerator.cpp

```diff
@@ -166,7 +178,8 @@ int entry(int argc, char **argv)

   std::random_device rd; // used to obtain a seed for the random number engine
   uint32_t input_index = 0;
-  for (uint32_t g = 0; g < circle_model->subgraphs()->size(); g++)
+  // for (uint32_t g = 0; g < circle_model->subgraphs()->size(); g++)
+  uint32_t g = 0;
   {
     const auto input_nodes = loco::input_no
```

seems to make `If_000` and `IF_001` pass...

**Comment by mhs4670go** [comment]
@seanshpark IIUC, since subgraphs except first one don't receive inputs from user, above change seems okay:)

**Comment by seanshpark** [comment]
`If` test is now enabled.
