### ISSUE TITLE
[luci] MaxPoolWithArgmax resolving pass

### ISSUE THREAD

**Issue by Bronnikoff** [Samsung/ONE#7229]
### What? 

Let's introduce resolving pass to lower MaxPoolWithArgmax custom op to subgraph with currently supported Circle node's.

### Why?

Circle schema and luci doesn't has `MaxPoolWithArgmax`. So we can't quantize and execute models with this custom op now.

**Comment by Bronnikoff** [comment]
Models with MaxPoolWithArgmax can be obtained from TF models with tf.nn.max_pool_with_argmax operation using conversion `tf --> tflite --> circle`.

**Comment by Bronnikoff** [comment]
DRAFT: #7236

**Comment by binarman** [comment]
This issue depends on #7306

**Comment by binarman** [comment]
Everything is merged, closing
