### ISSUE TITLE
Compiler FE: Convert StridedSlice to Reshape

### ISSUE THREAD

**Issue by hyunsik-yoon** [Samsung/ONE#7232]
**WHAT**

StridedSlice can be converted into Reshape, e.g.,

```
A = input of shape [1, 1, 1, 32]
B = StridedSlice(A, begin =[0,0,0,0], end=[1,1,1,32], shrinkAxisMask=0b0001) 
```

is same with
```
A = input of shape [1, 1, 1, 32]
C = Reshape(A, [1,1,32])
```

**WHY**

In backend, implementation of Reshape is generally simpler than that of strided_slice.

Therefore, converting strided_slice to reshape in this case could generally improve performance.

**Comment by hyunsik-yoon** [comment]
**Condition**

With a op below,
- A = input
- B = StridedSlice(A, ...)

If all conditions below are true

- begin[i] == 0
- end[i] = A.dim[i]
- shrinkAxisMask[s] == 1 (s'th bit is 1)
- end[s] = 1

Convert strided_slice to the following `Reshape`

- Reshape(A, new_shape)
   - d = 0
   -  for 0 <= x < A.shape.rank()
       - if x == s, continue
       - else new_shape[d++] = A.shape.dim[x]

**Comment by hyunsik-yoon** [comment]
**Where to implement**

I found 

https://github.com/Samsung/ONE/blob/2dc8f730a5184f96a59b0cf57833d0228f8e1741/compiler/circle2circle/src/Circle2Circle.cpp#L198-L202

Likewise, can I make the following option?

```
  arser.add_argument("--substitute_strided_slice_to_reshape")

```

**Comment by seanshpark** [comment]
@hyunsik-yoon , please add a test in `circle2circle-dredd-recipe-test` to check it's working.

**Comment by hyunsik-yoon** [comment]
all done.
