### ISSUE TITLE
Compiler FE: Fold consecutive CircleMean nodes

### ISSUE THREAD

**Issue by kvochko** [Samsung/ONE#7335]
An optimization that can be applied to some networks is like this:
* when two CircleMean operations are applied one by one, we can fold them into one operation and merge reduction indices. For example, the following network can be optimized:

![image](https://user-images.githubusercontent.com/2308830/127152773-096b1b5b-8a33-448a-95d0-5a43c57a7fb4.png)

to this:

![image](https://user-images.githubusercontent.com/2308830/127153068-282803f1-d8d7-483c-8138-b5e75660683f.png)

**Comment by kvochko** [comment]
@jinevening I just noticed that ConvertNCHWToNHWC pass now runs before all other passes (#7376), and prevents this optimization from working. Do you think it would be safe to add another phase before ConvertNCHWToNHWC with just FuseMeanWithMean?

**Comment by seanshpark** [comment]
Hum.... we need this feature for our internal model...

I don't think special treatment for `FuseMeanWithMean` is a good idea... we may end up in a dish of spaghetti.
We're heading to a complex situation and we need to find a good way...

**Comment by seanshpark** [comment]
Need to prepare Mean-Mean network regression test like #7367

**Comment by jinevening** [comment]
> Do you think it would be safe to add another phase before ConvertNCHWToNHWC with just FuseMeanWithMean?

I agree with @seanshpark . Adding a new phase just for this case will make things complicated.

I can think of two solutions

1. Run one-optimize twice.
  - First, run one-optimize w/ FuseMeanWithMean
  - Second, run one-optimize w/ ConvertNCHWToNHWC
  - one-build cannot be used in this case

2. Implement passes that can fuse Mean-Transpose-Mean
  - I think this can be done with two passes
    - Fuse Transpose-Mean
    - Fuse Mean-Mean

**Comment by kvochko** [comment]
I like the idea of  fusing Transpose with Mean, I think it's the way to go, thank you!

**Comment by ai-moiseev** [comment]
@kvochko got sick recently, I would like to continue this task during his absence.

**Comment by jinevening** [comment]
> @kvochko got sick recently, I would like to continue this task during his absence.

Hope he gets well soon :pray:

**Comment by seanshpark** [comment]
@ai-moiseev , thanks for working on this item.

If you are done with supporting this, you can check if it's working with #7394 `compiler/circle2circle-dredd-recipe-test/test.lst` change.

**Comment by binarman** [comment]
Ooops, missed this conversation.
@ai-moiseev FYI I've created PR with simple cases.

**Comment by kvochko** [comment]
All done, let's close this issue.
