### ISSUE TITLE
[luci-interpreter] Move tensor memory management to separate class

### ISSUE THREAD

**Issue by binarman** [Samsung/ONE#7355]
### Goal

Introduce tensor memory manager class.
Role or this manager is to assign and free tensor memory.

Proposed interface looks like this:
```c++
class MManager
{
public:
  virtual void allocate_memory(luci_interpreter Tensor *tensor);
  virtual void release_memory(luci_interpreter Tensor *tensor);
};
```

Manager is passed to interpreter at it's(Interpreter) construction time.
For example:
``` c++
  AdvancedMManager mm;
  luci_interpreter::Interpreter interpreter(module.get(), mm);
```

`allocate_memory` and `release_memory` methods should be called in `RuntimeGraph::TensorAllocPlan::allocate(size_t)` and `RuntimeGraph::TensorAllocPlan::deallocate(size_t)` methods instead of `Tensor::allocate`/`Tensor::deallocate`.

### Rationale

Currently we can not control memory allocations, proposed design could enable static memory planning (for specific model) and different strategies specific for neural networks.

**Comment by binarman** [comment]
+cc @BalyshevArtem

**Comment by BalyshevArtem** [comment]
Result of tracking allocations and releases memory (with help of overloading operators new[] and delete[]) in inception_v3, mobilenet_v1_224 and mobilenet_v2_224.
Attach two variants for each network of tracing new[] / delete[] with memoryManager and without:

[mobilenet_v2_224_without_mm.txt](https://github.com/Samsung/ONE/files/7098199/mobilenet_v2_224_without_mm.txt)
[mobilenet_v2_224_with_mm.txt](https://github.com/Samsung/ONE/files/7098200/mobilenet_v2_224_with_mm.txt)
[mobilenet_v1_224_without_mm.txt](https://github.com/Samsung/ONE/files/7098201/mobilenet_v1_224_without_mm.txt)
[mobilenet_v1_224_with_mm.txt](https://github.com/Samsung/ONE/files/7098202/mobilenet_v1_224_with_mm.txt)
[inception_v3_without_mm.txt](https://github.com/Samsung/ONE/files/7098203/inception_v3_without_mm.txt)
[inception_v3_with_mm.txt](https://github.com/Samsung/ONE/files/7098204/inception_v3_with_mm.txt)

**Comment by binarman** [comment]
Everything is merged, closing!
