### ISSUE TITLE
[Question] Master branch versioning 

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#7421]
---

BTW, I remember we decided to maintain master branch's version as next release version. So current master branch's version should 1.17.0. Did we abandon this rule?

_Originally posted by @hseok-oh in https://github.com/Samsung/ONE/issues/7386#issuecomment-894038643_

---

It is related with nightly build package version. Because of this, we still use `1.16.0` for nightly build on compiler and runtime nightly build because

- Runtime & compiler version is not updated to `1.17.0` after `release/1.16.0` branch out
- Nightly build package tool uses runtime version for compiler package generation because it assume that compiler & runtime uses same version

**Comment by hseok-oh** [comment]
@chunseoklee @mhs4670go

**Comment by chunseoklee** [comment]
> Did we abandon this rule?

Yes. It is abandoned (due to issue of debian package and CI) since 1.15.0.

**Comment by mhs4670go** [comment]
As @chunseoklee said, it is abandoned. 

When the nightly version is built, there was a version problem.

Since the debian package nightly version is `version-{nightly-version}`, if we follow the old rule, it should be `{next release version}-{nightly-version}`. Which looks like the version after `{next release version}`. To prevent such confusion, the rules were changed.

**Comment by hseok-oh** [comment]
>if we follow the old rule, it should be `{next release version}-{nightly-version}`. Which looks like the version after `{next release version}`

Is it confusion? IMO, it's natural to use next version on nightly build.

**Comment by chunseoklee** [comment]
> it's natural to use next version on nightly build, because it is nightly, not official (or beta) release.

Briefly looking around tensorflow and pytorch packages, this seems natural. 
However, note that they use postfix `dev+{DATE}` for nightly package. 

> Since the debian package nightly version is version-{nightly-version}

@mhs4670go Considering the whole worlflow(e.g. release process, CI and etc), what is the critical issue if we follows the old rule ?

**Comment by hseok-oh** [comment]
I briefly investigate some examples

#### Chrome

- https://www.google.com/intl/ko/chrome/canary/
- Support windows nightly only

#### Firefox

- Nightly build tar file release
  - https://ftp.mozilla.org/pub/firefox/nightly/
- Unofficial nightly build release
  - https://launchpad.net/~ubuntu-mozilla-daily/+archive/ubuntu/ppa
  - Different package name: `firefox-trunk`

#### VSCode

- https://packages.microsoft.com/repos/code/pool/main/c/
  - `code-insider`: nightty build
  - `code`: official release
  - `code-exploration`: ?
- Different package name for nightly (`code-insider`)
- Timestamp postfix: `date '+%s'

#### Jenkins

- Stable (LTS) / Regular (Weekly)
  - Stable: https://pkg.jenkins.io/debian-stable
  - Regular: https://pkg.jenkins.io/debian
- Same package name: `jenkins`


All examples uses upper version on nightly build than release build.

**Comment by lemmaa** [comment]
@hseok-oh , The problem is to deploy the nightly build through the _apt-get_ channel. Does the examples do that? If so, we can learn how. :)

**Comment by hseok-oh** [comment]
@lemmaa `vscode-insider` is nightly build, and we can get this by `apt-get install vscode-insider`. Our issue comes that our nightly build uses same package name with official release build. 

One selectable option is add timestamp on official release build (same with nightly build). I don't know reason, but `vscode` official build package (`vscode`) also have timestamp like nightly build.

**Comment by lemmaa** [comment]
> One selectable option is adding timestamp as debian revision on official release build (same with nightly build). I don't know reason, but `vscode` official build package (`vscode`) also have timestamp like nightly build.

@jyoungyun , what do you think about this?

**Comment by jyoungyun** [comment]
I'm sorry for late response.

I agree that the nightly build will be versioned with the next version.

However, the versioning in apt system is slightly different. (See the Chapter 7.3 in [here](https://www.debian.org/doc/manuals/debian-faq/pkg-basics.en.html))
The debian package name follows `<foo>_<VersionNumber>-<DebianRevisionNumber>_<DebianArchitecture>.deb` convention. Because the DebianRevisionNumber is added after VersionNumber, DebianRevisionNumber is recognized as a higher version than VersionNumber alone. For example, `1.0.0-210818` is recognized as a higher version than `1.0.0`.

From my understanding, in the apt system behavior, it seems more appropriate from the debian pkg to release 1.0 and then increase the revision number of 1.0 and then release 2.0.

However, apart from this content, as I remember, we decided the one-compiler always has a timestamp in its debian name even though it is an official release version. Am I wrong? /cc @mhs4670go

**Comment by mhs4670go** [comment]
> However, apart from this content, as I remember, we decided the one-compiler always has a timestamp in its debian name even though it is an official release version. Um, am I wrong..?

It applies only to nightly build version. Current versioning is like this.
```
1.16.1 release
1.16.1-210414 nightly build
1.16.1-210415 nightly build
1.16.1-210416 nightly build
..
1.17.0 release
1.17.0-210514 nightly build
```

And, @hseok-oh suggested like this.
```
1.16.1 release
1.17.0-210414 nightly build
1.17.0-210415 nightly build
1.17.0-210416 nightly build
..
1.17.0 release
1.18.0-210514 nightly build
```

But, as @jyoungyun said, debian package versioning regards `1.17.0-210416` as higher one than `1.17.0`.
```
1.16.1 < 1.17.0 < 1.17.0-210414 < 1.17.0-210416 < 1.18.0 < 1.18.0-210514
```
If we want to do right, we could use tilda(`~`).
```
1.16.1 release
1.17.0~210414 nightly build
1.17.0~210415 nightly build
1.17.0~210416 nightly build
..
1.17.0 release
1.18.0~210514 nightly build
```
```
1.16.1 < 1.17.0~210414 < 1.17.0~210416 < 1.17.0 < 1.18.0~210514 < 1.18.0
```

**Comment by lemmaa** [comment]
> One selectable option is adding timestamp as debian revision on official release build (same with nightly build). I don't know reason, but `vscode` official build package (`vscode`) also have timestamp like nightly build.

of https://github.com/Samsung/ONE/issues/7421#issuecomment-898076376 and

> And, @hseok-oh suggested like this.
> 
> ```
> 1.16.1 release
> 1.17.0-210414 nightly build
> 1.17.0-210415 nightly build
> 1.17.0-210416 nightly build
> ..
> 1.17.0 release
> 1.18.0-210514 nightly build
> ```

IIUC, @hseok-oh said

```
1.16.1-210413 release
1.17.0-210414 nightly build
1.17.0-210415 nightly build
1.17.0-210416 nightly build
..
1.17.0-210513 release
1.18.0-210514 nightly build

**Comment by mhs4670go** [comment]
I see. Then, there's no problem:)

**Comment by chunseoklee** [comment]
Here is the artifact examples just after 1.17.0 release : 

- Release(release branch 1.17.0)
   + debian pkg : nncc-1.17.0-20210819.deb ( no onert deb now )
   + publish job's zip file : onert-1.17.0-linux-armv7l.tar.gz, nncc-1.17.0.tar.gz

- Nightly(master branch)
   + debian pkg :  nncc-1.18.0-20210819.deb ( no onert deb now )
   + publich job's zip : onert-1.18.0-nightly-linux-armv7l.tar.gz, nncc-1.18.0-nightly.tar.gz

@lemmaa @chunseoklee @jyoungyun @hseok-oh @mhs4670go PTAL

**Comment by lemmaa** [comment]
> - debian pkg : nncc-1.17.0-20210819.deb ( no onert deb now )
> - publish job's zip file : onert-1.17.0-linux-armv7l.tar.gz, nncc-1.17.0.tar.gz

In `*-1.17.0-20210819` for `*.deb` vs `*-1.17.0` for `*.tar.gz` 
Any reason to use postfix differently?

**Comment by mhs4670go** [comment]
@lemmaa 
I'm a bit confused. If the date is added to version suffix, is it applied to release name(tag) as well?

**Comment by chunseoklee** [comment]
> I'm a bit confused. If the date is added to version suffix, is it applied to release name(tag) as well?

Aside from this. 

release's binary(onert-1.17.0.tar.gz) is downloaded during nnstreamer's nnfw plugin building process.  I will check the issue if we change the binary name.

**Comment by chunseoklee** [comment]
> release's binary(onert-1.17.0.tar.gz) is downloaded during nnstreamer's nnfw plugin building process.(https://github.com/nnstreamer/api/blob/3e953862301ec7c5f8fe74461f895f43c430ba01/java/build-nnstreamer-android.sh#L398-L400) I will check the issue if we change the binary name.

via offline discussion with nnstreamer member, little update resolves this issue. Thus, no problem on it.

**Comment by chunseoklee** [comment]
IMHO, date postfix on release binary seems awkward. Thus, I'd like to remove date postfix from debian(nncc) package, either.

**Comment by lemmaa** [comment]
> @lemmaa
> I'm a bit confused. If the date is added to version suffix, is it applied to release name(tag) as well?

I don't think so. :) As we call Windows 10-build1234 just Windows 10.

**Comment by mhs4670go** [comment]
@lemmaa 
> Any reason to use postfix differently?

In offline meeting, we wanted to use no postfix with release version. But, for resolving debian versioning priority, they versioned differently.

But, I think there should be no difference between tar and debian version. How about using tilda(~)?

Then, 
- Before release
   + debian pkg :  nncc-1.17.0~20210719.deb ( no onert deb now )
   + publich job's zip : onert-1.17.0~20210719-linux-armv7l.tar.gz, nncc-1.17.0~20210719.tar.gz
- Release(release branch 1.17.0)
   + debian pkg : nncc-1.17.0.deb ( no onert deb now )
   + publish job's zip file : onert-1.17.0-linux-armv7l.tar.gz, nncc-1.17.0.tar.gz

- Nightly(master branch)
   + debian pkg :  nncc-1.18.0~20210819.deb ( no onert deb now )
   + publich job's zip : onert-1.18.0~20210819-linux-armv7l.tar.gz, nncc-1.18.0~20210819.tar.gz

**Comment by jyoungyun** [comment]
@lemmaa Do you plan to apply the above changed rules to our other projects?

**Comment by lemmaa** [comment]
> @lemmaa Do you plan to apply the above changed rules to our other projects?

@jyoungyun , if everyone agrees that this option is the best, there seems to be no reason not to apply. However, such unification of the all other project is not a prerequisite for this release. :)

**Comment by hseok-oh** [comment]
Close this issue because question is resolved and versioning is updated.
