### ISSUE TITLE
[one-cmds] Each module displays its name for its messages

### ISSUE THREAD

**Issue by glistening** [Samsung/ONE#7422]
From #7418, `onecc` prints the driver name of callee (`one-xxx`).

However, @lemmaa suggested

> Wouldn't it be nice to let `one-import-tf` display its own name?

from https://github.com/Samsung/ONE/pull/7418#issuecomment-894039739

Maybe, it is not applicable for all modules since several modules (e.g. `tflite_convert`, `onnx_tf` and some future tools) are out of our control.

**Comment by glistening** [comment]
@lemmaa As I understand, you want each module to display its own name for only (self) message. 

That is, suppose that user invoke `onecc -C ...`, then

```
onecc -> one-import-tf -> tf2tfliteV2 -> tflite_converter
```

`one-import-tf` will put `one-import-tf: ` for its own message, (not for child's message).
For message from `tf2tfliteV2`, it will have `tf2tfliteV2: `.
For message from `tflite_converter`, it will have no prefix.

You want to identify the message generator as much as possible by letting each module to add prefix.

Please correct me if my understanding is wrong.

**Comment by glistening** [comment]
@lemmaa I am modifying sources as you've requested. It requires several changes around several sources from several repositories.

Please find #7423, which is a bit of changes.

I am trying `circle-quantizer`. However, I am in trouble because `circle-quantizer`'s error message are generated all around the source. Several runtime_exceptions are thrown from several places. Some of them (e.g, `foder::FileLoader`) are caught in `SafeMain`, unfortunately, which is library used throughout a lot of tools within this repo.

from `safemain/SafeMain.cpp`

```c++
int main(int argc, char **argv)
{
  try
  {
    return entry(argc, argv);
  }
  catch (const std::exception &e)
  {
    std::cerr << "ERROR: " << e.what() << std::endl;
  }

  return 255;
}
```

Changing existing callee (existing modules)'s behavior requires much labor and hard to maintain, and may break something.

@lemmaa As I understand, you already know this limitation and want to apply this change for some applicable ones (perhaps python implementation) only. Could you confirm me to whether continue this change or not?

**Comment by lemmaa** [comment]
Right

Under our rule, we can guess that unnamed logs are theirs. Of course, if such a relationship is repeated over 2 levels, it will be difficult to distinguish. But this is also true in other cases.

In that case, if it is absolutely necessary, you can make the module caller print it out.

The subtle differences between the two are:

1. In the case that the error occurred module displays the name of the error module by default.
2. In the case that the module that called the module displays the name of the module in which the error occurred by default

In case 1, there are two points that we can easily control.
In case 2, there is only one point that we can easily control. It is not easy to handle the case where another module calls our module.

**Comment by lemmaa** [comment]
> @lemmaa As I understand, you already know this limitation and want to apply this change for some applicable ones (perhaps python implementation) only. Could you confirm me to whether continue this change or not?

@glistening , I'm just commenting on the basic direction. It is impossible for me to know the implementation state of all modules in detail. We want to refactor in the desired direction. A `circle-quantizer` or whatever, isn't that just something to improve on? If it is implemented that is not easy to modify, I think it is only a problem in itself. :)

**Comment by glistening** [comment]
> @glistening , I'm just commenting on the basic direction. It is impossible for me to know the implementation state of all modules in detail.

0. I also don't know the detail. I also just guess and read the code. : )

> We want to refactor in the desired direction. A `circle-quantizer` or whatever, isn't that just something to improve on? If it is implemented that is not easy to modify, I think it is only a problem in itself. :)

1. different point of view

Maybe it is the different view for this approach. I think the way of handling error in `circle-quantizer` and so on has no problem. I believe it is the natural way of error handling — throwing error and catching in appropriate location — either in C++ or Python. Thus, I don't think see the problem in current implementation.

> A circle-quantizer or whatever, isn't that just something to improve on?

2. `safe-main`

I think we need to modify (in my term, not improve) `safemain` library to override the error message `ERROR: ...`.
However, I see at least 2 problems to solve.

(1) `safemain` is a library, it does not know the app name.

(2) `safemain` is used around several sources within `ONE`, and maybe out of `ONE`.
Is it okay to change `safemain`?

We may require to introduce another library or use its own exception handler in each App's `main()`.

3. out of `safe-main`

In addition, several error messages are printed directly by

```c++
std::cerr << "ERROR: ..."
```

I need to change all occurrences of this kind of statements in all app code. Also, as we mentioned in **0.**, there may be several changes required.

I don't see the benefit from `callee` print its own message considering the required changes and labors.
The caller knows callee's name, and it is more likely `caller` is in our control, it requires less modification.
It can catch almost all errors because it already has all error messages from `Popen`.

> Under our rule, we can guess that unnamed logs are theirs. Of course, if such a relationship is repeated over 2 levels, it will be difficult to distinguish. But this is also true in other cases.

Practically, we just requires one line change for most errors in the way of #7418, though it requires to distinguish `stdout` and `stderr` as you pointed out in messenger.

```
# run backend driver
with subprocess.Popen(
        codegen_cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        bufsize=1) as p:
    for line in p.stdout:
        sys.stdout.buffer.write(line)  ## Change here, and do right thing for STDOUT and STDERR
        sys.stdout.buffer.flush()
if p.returncode != 0:
    sys.exit(p.returncode)
```

**Comment by glistening** [comment]
@lemmaa I've made another draft in #7427. It does better than #7418, since it shows its name `one-xxx` executed directly, and it also shows internal names `{backend}-compile` and `circle-quantizer` and so on which requires much changes.

Here are example runs with various errors:

```
$ ./onecc codegen -b tv2 --input_path=12321 -o=123
one-codegen: FileNotFoundError: tv2-compile not found

$ ./onecc codegen -b tv2 --input_path=12321 -o=123
tv2-compile: ERROR: not supported tv2

$ ./build/install/bin/onecc quantize --put_path=12321 -o=123
usage: one-quantize [-h] [-v] [-V] [-C CONFIG] [-i INPUT_PATH] [-d INPUT_DATA]
                    [-f INPUT_DATA_FORMAT] [-o OUTPUT_PATH] [-p]
                    [--input_dtype INPUT_DTYPE]
                    [--quantized_dtype QUANTIZED_DTYPE]
                    [--granularity GRANULARITY]
                    [--min_percentile MIN_PERCENTILE]
                    [--max_percentile MAX_PERCENTILE] [--mode MODE]
one-quantize: error: unrecognized arguments: --put_path=12321

$ ./build/install/bin/onecc quantize --input_path=12321 -o=123
circle_quantizer: ERROR: Failed to open file: 12321

$ build/install/bin/one-import-tf -C build/install/bin/one-import-tf.cfg
tf2tfliteV2.py: OSError: File './../compiler/one-cmds/tests/inception_v3.pb' does not exist.

$ build/install/bin/one-import-tf -C build/install/bin/one-import-tf.cfg
tf2tfliteV2.py: ValueError: Invalid tensors 'inputs' were found.
```
