### ISSUE TITLE
LUCI_LOG disabled

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#7521]
```cxx
  if (arser.get<bool>("--verbose"))
    setenv("LUCI_LOG", "100", true);
  else
    setenv("LUCI_LOG", "0", true);
```

Now that setting `LUCI_LOG=1` in command line is DISBLED!!!!!!!!

PLEASE DO NOT ALTER WHAT WAS WORKING TO DIFFERENT BEHAVIOUR!!!!!

**Comment by seanshpark** [comment]
CC @lemmaa 

@jyoungyun PLEASE FIX THIS!!!!!

**Comment by seanshpark** [comment]
`setenv("LUCI_LOG", "100", true);` IS BAD USAGE FOR `LUCI_LOG`

**Comment by jyoungyun** [comment]
I was guided by @mhs4670go to use `100`. I will talk to him.

**Comment by lemmaa** [comment]
> I was guided by @mhs4670go to use `100`. I will talk to him.

Apart from that, it seems that it was necessary to first check whether a value is set in LUCI_LOG. :)

**Comment by jyoungyun** [comment]
When I checked this value in this project, test already use 100 and @mhs4670go suggests me to use 100 too.
https://github.com/Samsung/ONE/blob/8241bc459ee82b2727b285852562eb750f37f378/compiler/luci/tests/readverify.sh#L11
And when I tested this value as 1, 2, 3 and 100, the 100 is that most detailed log output. So I chose it.

**Comment by lemmaa** [comment]
Another problem seems to be the lack of documentation about the currently implemented feature and usage, and the lack of design discussion about applying `--vesbose`. (Of course, in both cases, maybe it's just something I didn't find.)

It is also our mistake that occurred due to the urgent schedule.

I think it will be a good lesson for us. :)

**Comment by seanshpark** [comment]
(1) The problem I think is
```cxx
  else
    setenv("LUCI_LOG", "0", true);
```
This should not be added. This will eatup given from command line.

(2) `setenv("LUCI_LOG", "100", true); ` is bad usage
I mean, this is not wrong, setting to `100` maybe a way to work as `verbose`
The `BAD` in my viewpoint is we can use (or add if not present) by an interface
not by calling `setenv` cause the code that reads `LUCI_LOG` is by `getenv` or something.

I understand there is short time slot to implement things talked in UX T/F so happend.

**Comment by jyoungyun** [comment]
There are some wrong points in my code. :(

> (1) The problem I think is
> ```cxx
>   else
>     setenv("LUCI_LOG", "0", true);
> ```
> This should not be added. This will eatup given from command line.

Yes, you're right. Because of this part, the value set by the user who want to sue `LUCI_LOG` directly is completely ignored..... 

> (2) `setenv("LUCI_LOG", "100", true); ` is bad usage
> I mean, this is not wrong, setting to `100` maybe a way to work as `verbose`
> The `BAD` in my viewpoint is we can use (or add if not present) by an interface
> not by calling `setenv` cause the code that reads `LUCI_LOG` is by `getenv` or something.

Also, even if there is a `--verbose` option, if there is a value set by the user, the value should have higher priority than source codes. I will check the value using `getenv` first, and if there is a value in this environment, I will use it.

I'm sorry for merging this PRs without maintainer's review. I will create a PR soon.

**Comment by seanshpark** [comment]
FYI

https://github.com/Samsung/ONE/blob/8241bc459ee82b2727b285852562eb750f37f378/compiler/luci/tests/readverify.sh#L11

This script is used in our code test coverage report in our CI.
`LUCI_LOG=100` is used to enable test codes only when LOG is enabled, coverage has dropped as now disabled.

![image](https://user-images.githubusercontent.com/4616940/130004695-0fd40315-ce35-4a30-a63e-92a615b7d857.png)
- the yellow line or the redline, not sure which...

**Comment by jyoungyun** [comment]
I close this issue because all PRs were merged.

**Comment by seanshpark** [comment]
@jyoungyun , about closing an issue... this is what I learned about an issue working from several teams
- issue creator owns then issue; owning in our case is not that important
- issue creator can assign to someone; we don't do this as a culture with hope of volunteer 
- when the issue is resolved, it is marked as resolve; we don't have this status but we know
- issue creator checks the 'claim of resolve' and closes if resolved, or add more comments
- issue can be managed; count and push the engineers; we also don't do this
- and so on...

Here, it would be polite to ask the creator to check the problem again; he/she maybe checking at the moment or maybe busy doing other stuffs.

For this case, I have another urgent task, but had a problem with remote desktop and had to reboot the system so had to prepar e the environment again to check this but did not and now I'm writing this...

You don't have to reopen this issue.
Above actions are not agreed among us but I wanted to write down how others may think about an issue.

**Comment by seanshpark** [comment]
Confirm this issue is now resolved.

Code coverage did not rise with related changes. Seems from other one... -_-;

![image](https://user-images.githubusercontent.com/4616940/130165238-631a96b3-23bb-41d3-b407-28ce9d55cfd1.png)
