### ISSUE TITLE
[one-import-onnx] Investigate output index changes on TF 2.6.0

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#7592]
Lets' investigate about output index changes when importing ONNX models on TF 2.6.0.

First, let's create a simple model that shows this result.

**Comment by seanshpark** [comment]
ONNX model
![image](https://user-images.githubusercontent.com/4616940/131460722-29b00152-9c65-4cd1-9b28-2a6d6da70e9b.png)

tflite model
![image](https://user-images.githubusercontent.com/4616940/131460905-4f8c1636-331e-4431-b226-408a3ec86e11.png)

Two models: [output.zip](https://github.com/Samsung/ONE/files/7082020/output.zip)

**Comment by seanshpark** [comment]
tflite model on TF2.3.0
![image](https://user-images.githubusercontent.com/4616940/131463356-88c8bd82-62e1-4552-aaa3-14ea49273539.png)

**Comment by seanshpark** [comment]
Experiment: Convert TF to tflite
- TF model from TF 2.6.0 --> convert with TF 2.3.0 --> tflite : OK
- TF model from TF 2.3.0 --> convert with TF 2.6.0 --> tflite : NOK

**Comment by seanshpark** [comment]
Next step: Try create a model NOT from onnx but from TensorFlow 2.3.0 / 2.6.0 and convert to tflite

**Comment by seanshpark** [comment]
Steps #7593 
1. prepare TF2.3.0 venv and TF2.6.0 venv
2. within TF2.3.0 run `savedmodel_1.py`, output as `test_saved_model.tf230`
3. within TF2.6.0 run `savedmodel_1.py`, output as `test_saved_model.tf260`
4. within TF2.3.0 run `savedmode_2.py` with `test_saved_model.tf230`, save it as `test_saved_model.tf230-tf230.tflite`
5. within TF2.3.0 run `savedmode_2.py` with `test_saved_model.tf260`, save it as `test_saved_model.tf230-tf260.tflite`
6. within TF2.6.0 run `savedmode_2.py` with `test_saved_model.tf230`, save it as `test_saved_model.tf260-tf230.tflite`
7. within TF2.6.0 run `savedmode_2.py` with `test_saved_model.tf260`, save it as `test_saved_model.tf260-tf260.tflite`

[test_saved_model.tflite.zip](https://github.com/Samsung/ONE/files/7118296/test_saved_model.tflite.zip)

`test_saved_model.tf230-tf230.tflite`
![image](https://user-images.githubusercontent.com/4616940/132270636-fdff902f-c468-4006-abd8-58a58f0df919.png)

`test_saved_model.tf230-tf260.tflite`
![image](https://user-images.githubusercontent.com/4616940/132270684-b337f2fd-b3e5-4e1d-9f1c-a6079494d433.png)

`test_saved_model.tf260-tf230.tflite`
![image](https://user-images.githubusercontent.com/4616940/132270736-d165dd4b-a7cf-4084-8b8f-6580e78defca.png)

`test_saved_model.tf260-tf260.tflite`
![image](https://user-images.githubusercontent.com/4616940/132270784-01d0bfcf-c036-4cd9-9cd7-98eea93fd075.png)

**Comment by seanshpark** [comment]
TF2.6.0 has problem with altering output index

**Comment by seanshpark** [comment]
Posted https://github.com/tensorflow/tensorflow/issues/51858

**Comment by chunseoklee** [comment]
@seanshpark In short, `TF model from TF 2.3.0 --> convert with TF 2.6.0` is only the problematic case ?

**Comment by seanshpark** [comment]
> is only the problematic case ?

Um? I can't catch the question...

**Comment by chunseoklee** [comment]
> > is only the problematic case ?
> 
> Um? I can't catch the question...

index altering issue happens only with `TF model from TF 2.3.0 --> convert with TF 2.6.0` (not happened on other case)

**Comment by seanshpark** [comment]
Index altering issue happens when using TF 2.4.x (or maybe TF 2.5.x ?) and above to convert TF to TFlite,
That is this issue is tflite converter issue.
TF version that made the model doesn't seem to be related.

**Comment by seanshpark** [comment]
Conclusion
- it's not ONNX issue
- we need to use `SignatureDef` inside tflite file
- that is we need to upgrade to TF 2.6.0
- #7593 has changes to just upgrade to TF 2.6.0 and local test is all OK (need to wait for CI test)
- need to find if gradual way of changes with multiple modules
