### ISSUE TITLE
[luci/pass] Pass quantparam in SubstituteSqueezeToReshape

### ISSUE THREAD

**Issue by Bronnikoff** [Samsung/ONE#7594]
### What?

Let's pass quantization param of `CircleSqueeze` to `CircleReshape` node in *SubstituteSqueezeToReshapePass*!

### Why?

It could make possible to apply this optimization for quantized models.

**Comment by seanshpark** [comment]
@Bronnikoff , could you please share in which case (or model) this is valid?

**Comment by seanshpark** [comment]
CC @jinevening

**Comment by jinevening** [comment]
Hmm.. It seems that many other passes have the same issue. Qparam is not copied to the newly created node.

```
SubstitutePackToReshape
SubstituteStridedSliceToReshapePass
SubstituteTransposeToReshapePass
...
```

I think we should copy qparam in those passes or insert a guard code to make the pass be applied only when the dtype of the target Op is fp32.

**Comment by Bronnikoff** [comment]
> @Bronnikoff , could you please share in which case (or model) this is valid?

Personally, I would like to apply this pass to quantized to Q8 MobileNetV1, which includes Squeeze at the tail of model. Currently, pass produce invalid graph with not quantized Reshape node.

**Comment by Bronnikoff** [comment]
#7595 merged, so, I think this issue can be closed =)
