### ISSUE TITLE
Q) luci-interpreter adding new kernels

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#7626]
I'd like to know when adding new kernels to enable new ops,
do we must enable all available backends at once or selectable?

**Comment by seanshpark** [comment]
CC @binarman

**Comment by binarman** [comment]
> do we must enable all available backends at once or selectable?

This is not mandatory, but desirable =)

However I think `linux` target is a "must have" and should be supported as a first priority, because it is used in other tools, like quantizer.

**Comment by seanshpark** [comment]
> This is not mandatory, but desirable =) 

Um? which one is not mandatory? should develop all backends at once OR selectable?

**Comment by binarman** [comment]
> should develop all backends at once OR selectable?

Uh, sorry, I misunderstood the point of question =_=

I think **selectable** is preferred method, because in some cases we need to introduce helper functions that would be easier to review separately.

P.s. I assume that "backend" is a target platform, like `linux` or `mcu`.

**Comment by seanshpark** [comment]
> P.s. I assume that "backend" is a target platform, like linux or mcu.

Yes :)

**Comment by seanshpark** [comment]
Closing as question is resolved :)
