### ISSUE TITLE
[Circle_OpSelector] [select_operator] How should I test While or If subgraphs

### ISSUE THREAD

**Issue by kevin622** [Samsung/ONE#7630]
We are team COSMOS working on the **Circle_OpSelector** project. (#7596)

As you can see in our previous Issue(#7606), we are currently developing a test process that can test whether the Circle_OpSelector is working properly by comparing it to [`select_operator.py`](https://github.com/Samsung/ONE/blob/master/tools/tflitefile_tool/select_operator.py). The detail of our test is explained [here](https://github.com/Samsung/ONE/issues/7606#issuecomment-913984405).

We faced a problem when trying to select `while` or `if` operators. Since these operators may create multiple outputs, a proper output can't be defined.

For example, if we select node 2 and 3 of [`if_dynamic.tflite`](https://github.com/Samsung/ONE/blob/master/nnpackage/examples/v1.0.0/if_dynamic/if_dynamic.tflite) using `select_operator.py`, we get the result below. Visualization is done using [netron](https://netron.app/).

![image](https://user-images.githubusercontent.com/46149751/132612658-b48a9450-62e1-4091-b10a-3627081afd57.png)

 It's visible that the output of this subgraph can't be defined as one output file unless more operations are applied.(such as concatenation?)

Thus we are leaning toward concluding that if operations such as above are on either(or both) the input or the output of the subgraph, the comparison between the `tflite` subgraph and the`circle` subgraph should not be done by `onert-test` but should be done **only visaully**.

Another option we are considering is to use `luci-test`. As @m-bronnikov mentioned [here](https://github.com/Samsung/ONE/issues/7606#issuecomment-915303952), it seems that the `circle-eval-driver` can process multiple inputs and multiple outputs for a `circle` model, which may solve our problem. If we choose this option as our test procedure, we would need to find a way to process multiple inputs and outputs for a `tflite` model as well.
(Edit) We saw that `./build/compiler/luci-eval-driver/luci_eval_driver` also works on `tflite` model!
(Edit2) When applying `luci-eval-driver` to `while_dynamic`, we get the following error.
```shell
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Unsupported operator: 85 sequential/lambda/rnn_2/TensorArrayV2Stack/TensorListStack
중지됨 (core dumped)
```
Since we saw other `tflite` files having no trouble, we are guessing this Error is due to the __while__ operator.

We'd like to know if we are on the right track. We thank you in advance for your suggestions or opinions.

**Comment by chunseoklee** [comment]
>  the comparison between the tflite subgraph and thecircle subgraph should not be done by onert-test but should be done only visaully.

@kevin622 AFAIK, onert-test(especially, gen_golden tool) seems to supports multiple output comparison.  

@glistening gen_golden supports multiple output ?

**Comment by kevin622** [comment]
Thanks for your sharing, @chunseoklee ! We've just checked that `onert-test` supports multiple output comparison.

We found that we were misunderstanding the problem. The problem of the errors were not caused by multiple outputs, but rather by the `If` node.(And the `While` node as well) 

We are currently seeking a way to compare models whose last node is an `If` node or `While` node.

**Comment by m-bronnikov** [comment]
> (Edit) We saw that `./build/compiler/luci-eval-driver/luci_eval_driver` also works on `tflite` model!
> (Edit2) When applying `luci-eval-driver` to `while_dynamic`, we get the following error.
> 
> ```shell
> terminate called after throwing an instance of 'std::invalid_argument'
>   what():  Unsupported operator: 85 sequential/lambda/rnn_2/TensorArrayV2Stack/TensorListStack
> 중지됨 (core dumped)
> ```
> 
> Since we saw other `tflite` files having no trouble, we are guessing this Error is due to the **while** operator.

AFAIK, `luci-eval-driver` expects circle models as input and not expects to meet tflite models:
https://github.com/Samsung/ONE/blob/b1e81c34e94c7b89c6a48fc7594dd1777823c22f/compiler/luci-eval-driver/src/EvalDriver.cpp#L59

I think your luck could be explained by similarity of tflite and circle schema, but, nevertheless, they are different. So, I think use of `luci-eval-driver` for tflite models execution is not a good idea.
 
> If we choose this option as our test procedure, we would need to find a way to process multiple inputs and outputs for a `tflite` model as well.

Personally, I prefer following way to infer `tflite` models using python:

```python
import tensorflow as tf
import numpy as np

model_path = "./model.tflite"

with open(model_path, 'rb') as binf:
    interp = tf.lite.Interpreter(model_content=binf.read())

interp.allocate_tensors()

for idx, detail in enumerate(interp.get_input_details()):
    tensor_idx = detail['index']
    # generate random data
    tensor_data = np.random.randn(*detail['shape']).astype(detail['dtype'])
    # dump to file (if needed)
    np.save("input" + str(idx) + ".npy", tensor_data)
    # set data to interpreter
    interp.set_tensor(tensor_idx, tensor_data)

# execute model
interp.invoke()

# collect outputs to list
ouptuts = []
for idx, detail in enumerate(interp.get_output_details()):
    tensor_idx = detail['index']
    tensor_data = interp.get_tensor(tensor_idx)
    ouptuts.append(tensor_data)
    # dump to file (if needed)
    np.save("output" + str(idx) + ".npy", tensor_data)
```
