### ISSUE TITLE
[Circle-OpSelector] How to 'include' header file, CircleImportMetadata.h?

### ISSUE THREAD

**Issue by dongyooncho** [Samsung/ONE#7662]
I'm wondering what would be the best way to include the header file `import/src/CircleImportMetadata.h`.

Currently I am using it like this.
```
#include <luci/../../src/CircleImportMetadata.h>
```

It work for me but, I think it's pretty weird. It doesn't seem to be common sentence. Is there any other way to include this module?

**Comment by glistening** [comment]
`CircleImportMetadata.h` seems not be public header. It means it is not supposed to be included out of `import`. Why do you need this header? Maybe, at first, you need to find some public interface that provides what you want. I've found `metadata()` in `CircleReader.h`

**Comment by dongyooncho** [comment]
I need it because I couldn’t get `circle::Model` ‘s metadata

I'm working on selecting some nodes now.

I 'm trying to change Graph at `luci::Module`, and I found similar function in `Importer.cpp`;
```
convert_graph(const luci::GraphBuilderSource, luci::CircleReader, loco::Graph)
```
It seems to read `circle::Model` data by `CircleReader` and convert it to `loco::Graph`.
But, this is a little different from our final goal.
It doesn't support specific node selection. So I create a new function like this;
```
select_nodes(const luci::GraphBuilderSource, luci::CircleReader, loco::Graph, Map<op_id, op_name>)
```
In this function, I use data like this;
```
const auto &operators = reader.operators();
const auto &tensors = reader.tensors();
auto tensors_ptr = reader.tensors_ptr();
assert(tensors_ptr != nullptr);
```
but I couldn't use it's metadata.
```
auto circle_metadata = std::make_unique<luci::CircleImportMetadata>(reader); // error. need it's header.
```

So I need to include this header.

**Comment by mhs4670go** [comment]
@dongyooncho 

> It work for me but, I think it's pretty weird. It doesn't seem to be common sentence. Is there any other way to include this module?

First, You're right. It shouldn't be included that way.
```cmake
# cat compiler/luci/import/CMakeLists.txt
..
target_include_directories(luci_import PRIVATE src) # NOTE here
target_include_directories(luci_import PUBLIC include)
```

`src` directory is only for private use. If some headers or classes turn out to be acceptable as well for public use, it can be moved to the public one, which I think is not the case for this. 

> So I need to include this header.

I think you don't have to use this header. `CircleImportMetadata` class literally imports `Metadata` of circle schema. It has nothing to do with the operator information you are looking for. FYI, we are using this for internal use.
```flatbuffers
table Metadata {
  // A human readable string to uniquely identify a Metadata.
  name:string;
  // An index to the buffers table.
  buffer:uint;
}
```

All you should do is just look at the imported module(graphs) and create a new graph based on that information. Actually, imported module has all the information you want. For example, `name` is already included in `CircleNode` class, which can be accessed by `name` method. `index` can be accessed by `get_node_id` method(@llFreetimell This is the only way to get the id, isn't it?).

**Comment by dongyooncho** [comment]
I need it because I couldn't use `circle::Model`'s metadata.

I'm working on selecting some nodes now.

I 'm trying to change graph at `luci::Module`, and I found similar function in `Importer.cpp`;
```
convert_graph(const luci::GraphBuilderSource, luci::CircleReader, loco::Graph)
```
It seems to read `circle::Model` data by `CircleReader` and convert it to `loco::Graph`. But, this is a little different from our final goal. It doesn't support specific node selection. So I create a new function like this;
```
select_nodes(const luci::GraphBuilderSource, luci::CircleReader, loco::Graph, Map<op_id, op_name>)
```
In this function, I use data like this;
```
const auto &operators = reader.operators();
const auto &tensors = reader.tensors();
auto tensors_ptr = reader.tensors_ptr();
assert(tensors_ptr != nullptr);
```
but I couldn't use it's metadata.
```
auto circle_metadata = std::make_unique<luci::CircleImportMetadata>(reader); // error. need it's header.
```

So I need to include this header.

**Comment by glistening** [comment]
@dongyooncho If you access metadata with flatbuffer APIs only, you may refer to the the following:

https://github.com/Samsung/ONE/blob/bfe626fc37bc385f53c4361e29164ea5446be200/compiler/circledump/src/Dump.cpp#L401-L416

I've found the code above ( `circledump` ) by searching with `metadata()` in `ONE` source.
I think you may find this code also.

I think @mhs4670go explains how the metadata can be accessed from imported `loco::Graph`. 
If you think `loco::Graph` provides several APIs that is helpful to selecting and manipulating the graph, you can choose `loco::Graph`. I don't know much about `loco::Graph`.

**Comment by dongyooncho** [comment]
@mhs4670go
> CircleImportMetadata class literally imports Metadata of circle schema.

Oh, if then.. it might has no need to use this..! Thank you for your comment.

@glistening If I need to use this module, I will check this code first! Thank you :D

**Comment by glistening** [comment]
> @mhs4670go
> 
> > CircleImportMetadata class literally imports Metadata of circle schema.
> 
> Oh, if then.. it might has no need to use this..! Thank you for your comment.

I think the selected `circle` must keep all information from original graph including `metadata` if any.
