### ISSUE TITLE
[circle-quantizer] Support manual writing of quantization parameters

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#7682]
## What

Let's enable a new feature that manually writes quantization parameters (scale, zerop) to specified tensors.

Target tensors and scale/zerop are specified as `--force_quantparam <tensor_name> <scale> <zerop>`. Multiple tensors can be updated by repeating the interface. 

For example,

input model: input.circle
output model: output.circle 

Write scale = 1.0, zerop = 0 to the tensor named Input
```
circle-quantizer --force_quantparam Input 1.0 0 input.circle output.circle
```

Write scale = 1.0, zerop = 0 to the tensor named Input and scale = 2.0, zerop = 1 to the tensor named Input2
```
circle-quantizer --force_quantparam Input 1.0 0 --force_quantparam Input2 2.0 1 input.circle output.circle
```

CC @lemmaa

**Comment by jinevening** [comment]
This feature will only support writing per-tensor qparams (not per-channel).

**Comment by seanshpark** [comment]
@jinevening , tensorname may include `;` character... have to tested with this?

**Comment by jinevening** [comment]
> @jinevening , tensorname may include ; character... have to tested with this?

I used `;` as a delimiter in the draft, but now `tensor_name` is saved in a vector, so it is ok for `tensor_name` to have `;`.

**Comment by jinevening** [comment]
All done.
