### ISSUE TITLE
[Circle-OpSelector] How to import tflite(or circle) file in javascript

### ISSUE THREAD

**Issue by kevin622** [Samsung/ONE#7692]
I am trying to develop a GUI tool for `Circle-OpSelector`(#7596) using `Javascript`, whose UI would be similar to [`Netron`](https://github.com/lutzroeder/netron).

While developing this tool, I'm having a problem importing `tflite` model in `javascript`. Here are some tryouts I've tried.

## 1. Use `tfjs-tflite` 

I found that [tfjs(Tensorflow for Javascript)](https://www.tensorflow.org/js/) was being developed, so I tried to use the [`tfjs-tflite`](https://github.com/tensorflow/tfjs/tree/tfjs-tflite-v0.0.1-alpha.4/tfjs-tflite) api of this library. Since using a node-based app was required, I created a Vue2 project(`nodejs` and [`vue/cli`](https://cli.vuejs.org/) is required for the code below) and installed `tfjs`.

```shell
$ vue --version # version of Vue CLI
@vue/cli 4.5.13

$ vue create netron_self # name of the project is netron_self
$ cd netron_self
$ npm install @tensorflow/tfjs
```

 However, `tfjs-tflite` was not included in the installation process, so I had to install this package manually.

```shell
$ npm install @tensorflow/tfjs-tflite
```

The file structure is as such;

```shell
$ tree node_modules/@tensorflow -L 1
node_modules/@tensorflow
    ├── tfjs
    ├── tfjs-backend-cpu
    ├── tfjs-backend-webgl
    ├── tfjs-converter
    ├── tfjs-core
    ├── tfjs-data
    ├── tfjs-layers
    └── tfjs-tflite
```

The problem occured when I try to use this `tfjs-tflite`. If I import this module, an error is printed in the browser developer tool console.

```
Uncaught (in promise) TypeError: A[(d.tfliteWebApiName + "_ModuleFactory")] is not a function
```

When I try to use the `loadTFLiteModel` function of this module, I get the same error and can't import my model.

```javascript
console.log(tflite.loadTFLiteModel(PATH_TO_MODEL))
> Promise { <state>: "pending" }
<state>: "rejected"
<reason>: TypeError: A[(d.tfliteWebApiName + "_ModuleFactory")] is not a function
```

Is there anyone who succeeded in using this module?

## 2. Use `flatbuffers`

Since `circle` uses flatbuffers schema(`.fbs`), and noticing that Netron uses flatbuffers(there is a `flatbuffers.js` file [here](https://github.com/lutzroeder/netron/blob/main/source/flatbuffers.js)), I thought using this option might be a trick.

However, I have trouble figuring out how this works. 

The [tutorials of flatbuffers](https://google.github.io/flatbuffers/flatbuffers_guide_tutorial.html) using `javascript` indicates that flatbuffers doesn't directly support `javascript` but supports `typescript` and transpilation is needed. I think this caused the problem that I'm currently facing, because I'm getting the following errors when trying to import the files made during the tutorial(to the `Vue` app I created earlier).

```vue
<!-- the vue file -->
<script>
const flatbuffers = require("../../flatbuffers/js/flatbuffers")
const monster = require("../../flatbuffers/samples/monster")
...
</script>
```

![image-20210915152035590](https://user-images.githubusercontent.com/46149751/133381453-085555da-740f-410b-8692-e7cc517ec178.png)

Can anyone recommend me a fine way to access a `tflite` model via `javascript`?

**Comment by mhs4670go** [comment]
@kevin622 Try like below.

```bash
$ flatc --ts circle_schema.fbs
$ tsc circle_schema.ts circle/*.ts
$ cat sample.js

var Model = require('./circle/model').Model
var flatbuffers = require('flatbuffers')
var fs = require('fs');

var bytes = new Uint8Array(fs.readFileSync('./Abs_000.circle'));
var buf = new flatbuffers.ByteBuffer(bytes);

var model = Model.getRootAsModel(buf);

console.log(model);

$ node sample.js
Model {
  bb: ByteBuffer {
    bytes_: Uint8Array(368) [
       24,   0,   0,   0,  67,  73,  82,  48,   0,   0,  14,   0,
       20,   0,   0,   0,  12,   0,   8,   0,  16,   0,   4,   0,
       14,   0,   0,   0,  16,   0,   0,   0,  40,   0,   0,   0,
       36,   1,   0,   0,  56,   1,   0,   0,   3,   0,   0,   0,
       20,   0,   0,   0,  12,   0,   0,   0,   4,   0,   0,   0,
      140, 255, 255, 255, 144, 255, 255, 255, 148, 255, 255, 255,
        1,   0,   0,   0,  20,   0,   0,   0,   0,   0,  14,   0,
       24,   0,  20,   0,  16,   0,  12,   0,   8,   0,   4,   0,
       14,   0,   0,   0,
      ... 268 more items
    ],
    position_: 0
  },
  bb_pos: 24
}
```

**Comment by glistening** [comment]
- `netron` itself can be an example using flatbuffers JS APIs. You man refer to `tflite.js` in netron source.
- `ONE-VSCode` develops in TypeScript. I think https://github.com/Samsung/ONE-vscode/issues/46 may help.

**Comment by kevin622** [comment]
@mhs4670go Thank you for your interest. I followed your suggestion and it worked! I thought though some line-by-line specification would be helpful for someone who might read this issue.



> `$ flatc --ts circle_schema.fbs`

In order to try run this code, I've copied the `circle_schema.fbs` at `ONE/nnpackage/schema/circle_schema.fbs` file to `flatbuffers/` folder, which is the folder I've cloned from [flatbuffers github](https://github.com/google/flatbuffers).
Then, I ran the code as below, at `flatbuffers/`. The code below requires the flatbuffers to be [built](https://google.github.io/flatbuffers/flatbuffers_guide_building.html).

```bash
$ ./flatc --ts circle_schema.fbs
```

This created `circle` folder and `circle_schema.ts` file at my current directory (`flatbuffers/` folder) as expected.

```bash
$ ls | grep circle
circle
circle_schema.fbs
circle_schema.ts
```



> ```shell
> tsc circle_schema.ts circle/*.ts
> ```

Here I experienced some problems, since most  `ts` files in `flatbuffers/circle/` folder includes an `import flatbuffers from 'flatbuffers'` statement, and the 'flatbuffers' module couldn't be found.

So I changed all the `import` statements via `shell script` and copied the `flatbuffers.ts` file in `flatbuffers/ts/` to `flatbuffers/circle/`.

_before_

```typescript
import * as flatbuffers from 'flatbuffers'
```

_typed command in terminal_

```shell
$ sed "s/'flatbuffers'/'.\/flatbuffers'/" -i circle/*.ts
```

_after_

```typescript
import * as flatbuffers from './flatbuffers'
```



After all the `import` statements were modified, I've ran the command below.

```shell
$ tsc circle_schema.ts circle/*.ts
```

Then some `javascript` files were created in the `flatbuffers/circle/` folder, though some errors were printed.

```shell
ts/builder.ts(27,26): error TS2304: Cannot find name 'Map'.
ts/builder.ts(508,32): error TS2304: Cannot find name 'Map'.
ts/byte-buffer.ts(315,51): error TS2304: Cannot find name 'unknown'.
ts/byte-buffer.ts(332,48): error TS2304: Cannot find name 'unknown'.
```





Lastly, to I made the `sample.js` file.

> ```shell
> $ cat sample.js
> 
> var Model = require('./circle/model').Model
> var flatbuffers = require('flatbuffers')
> var fs = require('fs');
> 
> var bytes = new Uint8Array(fs.readFileSync('./Abs_000.circle'));
> var buf = new flatbuffers.ByteBuffer(bytes);
> 
> var model = Model.getRootAsModel(buf);
> 
> console.log(model);
> ```

_the file that I used_(I used the inception_v3 file, created via `tflite2circle`)

```js
var Model = require('./circle/model').Model
var circleFlatbuffers = require('./circle/flatbuffers')
var fs = require('fs');

var bytes = new Uint8Array(fs.readFileSync('./inception_v3.circle'));
var buf = new circleFlatbuffers.ByteBuffer(bytes);

var model = Model.getRootAsModel(buf);


console.log(model);
```

And I got the result that I wanted.

```shell
$ node sample.js
Model {
  bb: ByteBuffer {
    bytes_: Uint8Array(95324716) [
       24,   0,   0, 0,  67,  73,  82, 48,   0,   0,  14, 0,
       20,   0,   0, 0,  12,   0,   8,  0,  16,   0,   4, 0,
       14,   0,   0, 0,  16,   0,   0,  0,  44, 226, 173, 5,
      164, 137, 174, 5, 244, 137, 174,  5,  63,   1,   0, 0,
       24, 226, 173, 5,   0, 226, 173,  5,  76, 210, 173, 5,
       60, 207, 173, 5,  44, 201, 173,  5,  28, 195, 173, 5,
       12, 189, 173, 5, 252, 181, 173,  5, 236, 175, 173, 5,
      220, 169, 173, 5, 204, 164, 173,  5, 188, 161, 173, 5,
      172, 155, 173, 5,
      ... 95324616 more items
    ],
    position_: 0
  },
  bb_pos: 24
}
```

**Comment by kevin622** [comment]
However, I'm still having a problem, regarding `Vue`.

In my `vue` project, I'm trying to import the `flatbuffers` file created, so that I can open `circle` models. 

Sadly, I'm receiving tons of warnings when I run the `Vue` server. 

Here is my `App.vue` code

```vue
<template>
  <div>
    <button @click="onClick">button</button>
  </div>
</template>

<script>
/* eslint-disable */
import * as circleFlatbuffers from '../../flatbuffers/circle/flatbuffers.ts'
import * as fs from 'fs'
const bytes = new Uint8Array(fs.readFileSync('../../flatbuffers/inception_v3.circle'));
const buf = new circleFlatbuffers.ByteBuffer(bytes);
const Model = require('../../flatbuffers/circle/model').Model
const model = Model.getRootAsModel(buf);
export default {
  name: 'App',
  components: {
    
  },
  methods: {
    onClick () {
      console.log(circleFlatbuffers)
      console.log(model)
      }
  }
}
</script>

<style>
</style>

```

Not only are warnings printed in my terminal, but errors are printed as well in the browser console.

Here is the error on my broweser console. With this error, nothing is rendered as a webpage.

```
Uncaught TypeError: fs__WEBPACK_IMPORTED_MODULE_26__.readFileSync is not a function
```

Currently I'm searching for a way to solve the `fs.readFileSync` error.

**Comment by glistening** [comment]
@kevin622 Before you dive into `vue` more, I would like to ask whether `vue` app can be integrated with VSCode? For example, the tool (profile result viewer) uses `react` and integrated in `VSCode`. Please see https://github.com/Samsung/ONE-vscode/pull/52.

**Comment by llFreetimell** [comment]
I wonder why this issue is needed for circle-opselector, but https://github.com/Samsung/ONE-vscode/issues/46 maybe useful :D
We are working on this because we are developing https://github.com/Samsung/ONE-vscode/issues/66!

**Comment by glistening** [comment]
> I wonder why this issue is needed for circle-opselector, but [Samsung/ONE-vscode#46](https://github.com/Samsung/ONE-vscode/issues/46) maybe useful :D
> We are working on this because we are developing [Samsung/ONE-vscode#66](https://github.com/Samsung/ONE-vscode/issues/66)!

@llFreetimell I think the first line of this issue explains:

kevin622 wrote:
> I am trying to develop a GUI tool for Circle-OpSelector(#7596) using Javascript, whose UI would be similar to Netron.

**Comment by kevin622** [comment]
Since I'm developing a browser based app, I decided to use `input` tag for reading files. That helped me figure out some problems, so I'll close this issue.
