### ISSUE TITLE
[Circle-OpSelector] How can I read nodes of a circle model via JS?

### ISSUE THREAD

**Issue by kevin622** [Samsung/ONE#7745]
Hi! I'm 국현 from team COSMOS. We are currently developing a tool which would be named Circle-OpSelector. (#7596 is our main issue)

I'm trying to develop a tool that can __visualize__ the operation(the Circle-OpSelector), so I'm using `Vue` to create an browser based app. Here, I'm having a problem reading information of a Circle model.

Below is `App.vue`, created to check whether the model was read properly.

```vue
<template>
  <div>
    <input type="file" ref="files" @change="fileInputChange">
  </div>
</template>

<script>
/* eslint-disable */
import * as circleFlatbuffers from '../../flatbuffers/circle/flatbuffers.ts'

export default {
  name: 'App',
  methods: {
    async fileInputChange () {
      // file input (circle)
      const file = this.$refs.files.files[0]

      // change the input file to arrayBuffer
      const arrayBuffer = await file.arrayBuffer()

      // change the arrayBuffer to Uint8Array
      const bytes = new Uint8Array(arrayBuffer)

      // change the Uint8Array to flatbuffers
      const buf = new circleFlatbuffers.ByteBuffer(bytes);

      // Import the Model Class
      const Model = require('../../flatbuffers/circle/model').Model

      // Create a Model instance
      const model = Model.getRootAsModel(buf);

      // Check the operators of the model
      for(let i=0; i < model.operatorCodesLength(); i++) {
        console.log(`#${i} operator code;`, model.operatorCodes(i).builtinCode())
      }

      // Check the description of the model
      console.log('description;', model.description())

      // Check the buffers(?) of the model
      console.log('buffersLength;', model.buffersLength()) 
      for(let i=0; i < model.buffersLength(); i++) {
        const buffers = model.buffers(i)
        console.log('buffers; ', buffers.dataArray())  
      }
      
    },
  }
}
</script>

<style>
</style>

```

Here I want to access the __nodes__(such as `Conv2d`, `Add`, _etc_), but I'm not sure how to. I'm guessing that the `buffers` contain all information regarding each node, but I don't know how to interpret it.
Can anyone inform me of the way to read the __node information__ of a model?

I appreciate your help in advance. 🙇 

_ps. The reason why I'm developing from scratch and not using the codes in [Netron](https://github.com/lutzroeder/netron) is because since we are developing a new operation(Circle-OpSelector), I wanted to make sure I'm aware of all the codes in the visualization app, so I know where to apply the operation code._

**Comment by seanshpark** [comment]
@kevin622 , I think you're the first one using JS to accessing circle schema.

Besides JS, please refer `Dump.cpp` and `Read.cpp` in `compiler/tfldump/src/` how to understand data.
- for `buffers`, these are usually constant values such as weights of Conv2D.

**Comment by glistening** [comment]
@kevin622 Please find https://github.com/Samsung/ONE/issues/7692#issuecomment-919805172. 

> - `ONE-VSCode` develops in TypeScript. I think https://github.com/Samsung/ONE-vscode/issues/46 may help.

Here is some code from above link for how to access flatbuffer schema members.

```js
let bytes = new Uint8Array(fs.readFileSync(path.resolve(__dirname, "./{path}/{circlefile_name}.circle")));

let buf = new flatbuffers.ByteBuffer(bytes);

// get Model
let myModel = circle.Model.getRootAsModel(buf);

// information of circle
let metadataBuffer = myModel.metadataBuffer;
let description = myModel.description();
```

and please read `circle_schema.fbs`.

For example, you can access the operator via:

```
model -> subgraphs -> operators -> ...
```

**Comment by seanshpark** [comment]
> I'm trying to develop a tool that can visualize the operation(the Circle-OpSelector), so I'm using Vue to create an browser based app. Here, I'm having a problem reading information of a Circle model.

For better understanding, as far as I know `circle-opselector` is a console program that reads a circle file and splits to several (or one?) new circle model.

You are asking about visualization program that shows graph of a circle model.

My questions (if these don't make sense, please point it out) 
- What are the relations of this console program an visualizer program?
- What are the user scenario, that is, how do you expect the user would use the programs?

**Comment by kevin622** [comment]
@seanshpark 
> Besides JS, please refer Dump.cpp and Read.cpp in compiler/tfldump/src/ how to understand data.

I'll check these files to get help!

@glistening 
> For example, you can access the operator via:
> 
> ```
> model -> subgraphs -> operators -> ...
> ```
> 
> https://miro.com/app/board/o9J_kuaY2Mk=/ from #3468 may help you understand.

This seems to be the code I've been searching for! I was trying to access the `tensor` variable, without knowing the chained relations.. Thank you 🙇 🙇 

@seanshpark 
> My questions (if these don't make sense, please point it out)
>
> - What are the relations of this console program an visualizer program?
> - What are the user scenario, that is, how do you expect the user would use the programs?

I apologize for not making clear what I'm trying to develop. I'll make another issue to elaborate(what, why, how) the tool I'm working on.

**Comment by kevin622** [comment]
In #7760 I wrote some details about the tool I'm developing. I'll close this issue as I said before.
