### ISSUE TITLE
[Circle-OpSelector] How to compare tflite files and circle files?

### ISSUE THREAD

**Issue by Simji-sw** [Samsung/ONE#7766]
Hi! I'm 지영 from team COSMOS. 

As you can see in our Pull Request(#7765), we created new draft about **circle-opselector-test**. 
We'd like to know the best way to compare tflite files and circle files.

We are going to proceed with the circle-opselector-test in the following way.

1) We will write `test.lst` in the form `addeval(CIRCLE_ORIGIN CIRCLE_SELECTED NODES)`.
2) Prepare the `original Recipe file` and the Recipe file that is the expected result when selected, 
and convert them into a circle file and a tflite file.
(AFAIK, if we place the Recipe file in `res/TensorFlowLiteRecipes`, `common-artifact` will automatically generate the TFLite file when the compiler module is built.)

3) And `Select` the circle file made with the original `Recipe` using `circle-opselector`.

4) Compare it with the tflite file created by the `expected Recipe`.

I'd like to know how to compare the tflite files and circle files, which is the process of 4).

Previously, I tried to compare files with the file comparison command `cmp`, but I thought using this command was not the right way to do it.

So, as @mhs4670go said before, we refer to luci-value-test. 
After generating random input data, the 'selected' circle file runs `luci-interpreter` and 'expected' tflite file runs `tflite interpreter` to compare the two results.

Is it okay to proceed like this?
Any comments would be appreciated.

**Comment by glistening** [comment]
@Simji-sw I think @mhs4670go guided in https://github.com/Samsung/ONE/issues/7671#issuecomment-917965490 for value test (= run each models and compare the values) between `tflite` and `circle`. Do you want more information about value test? Or do you want to introduce another way to compare `tflite` and `circle` w/o running the models?
