### ISSUE TITLE
[luci] Revise 'LIBRARY_TYPE' to 'LUCI_LIBRARY_TYPE'

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#7834]
How about renaming `LIBRARY_TYPE` to `LUCI_LIBRARY_TYPE` as this seems to set luci library type: shared or static.
If this is used for other modules, I think it would be better to introduce another for that too.

**Comment by seanshpark** [comment]
Related #7830

**Comment by binarman** [comment]
> could you please consider this change? If you don't agree, could you share your thoughts ?

As 7830 showed, this change will improve interface robustness, when integrating luci in other build systems, so I don't have any arguments against this =)

**Comment by seanshpark** [comment]
done :)
