### ISSUE TITLE
[luci/importer] Support importing without models UnPack

### ISSUE THREAD

**Issue by m-bronnikov** [Samsung/ONE#7886]
### What?

Current importer's implementation uses flatbuffer's `ModelT` obtained with UnPack of the `Model`:

https://github.com/Samsung/ONE/blob/2c0ab2d0ec92487138a281604b08c7c4f92a514c/compiler/luci/import/src/CircleReader.cpp#L322-L332

Let's import `luci::Module` from `circle::Model`directly!

### Why?

Internally, `UnPack()` provides `circle::ModelT` via full copying of the model:

```cpp
inline ModelT *Model::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = new ModelT();
  UnPackTo(_o, _resolver);
  return _o;
}

inline void Model::UnPackTo(ModelT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = version(); _o->version = _e; };
  { auto _e = operator_codes(); if (_e) { _o->operator_codes.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->operator_codes[_i] = std::unique_ptr<OperatorCodeT>(_e->Get(_i)->UnPack(_resolver)); } } };
  { auto _e = subgraphs(); if (_e) { _o->subgraphs.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->subgraphs[_i] = std::unique_ptr<SubGraphT>(_e->Get(_i)->UnPack(_resolver)); } } };
  { auto _e = description(); if (_e) _o->description = _e->str(); };
  { auto _e = buffers(); if (_e) { _o->buffers.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->buffers[_i] = std::unique_ptr<BufferT>(_e->Get(_i)->UnPack(_resolver)); } } };
  { auto _e = metadata_buffer(); if (_e) { _o->metadata_buffer.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->metadata_buffer[_i] = _e->Get(_i); } } };
  { auto _e = metadata(); if (_e) { _o->metadata.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->metadata[_i] = std::unique_ptr<MetadataT>(_e->Get(_i)->UnPack(_resolver)); } } };
}
```

This design produces extra memory usage, whcih might be critical for usage of  luci on devices like MCU. (details: https://github.com/Samsung/ONE/pull/7857#issuecomment-946591994)

Howeever, it's possible to refactor importer to import models directly by usage of referneces to the data from source models buffer in order to minimize amount of copiyng and allocations during import.

**Comment by seanshpark** [comment]
@m-bronnikov , thanks for preparing a draft. I don't fully accepy the changes. I've left some comments.
And there are changes that doens't seem to be related what you wanted to do. Those changes disturbs understand the change it self. I hope you remove them for better discussion.

**Comment by m-bronnikov** [comment]
@seanshpark With #8007 and #8008 main changes to importer is done and UnPack API is unused! Next step: remove Unpack methods from CircleReader and rename native methods: `native_method` --> `method`. 

But I would like to know your opinion about this step first. May be better to leave both API in CircleReader for now?

Personally, I'm happy with any decision.

**Comment by seanshpark** [comment]
> But I would like to know your opinion about this step first. May be better to leave both API in CircleReader for now?

As I know, there was `method` and then `native_method` was introduced for some reason and
now as `method` is not used, you want to replace `native_method` to `method`.
If this is correct, I think there is no reason not to do so...
If you have something that bothers you, please share :)

**Comment by m-bronnikov** [comment]
> > But I would like to know your opinion about this step first. May be better to leave both API in CircleReader for now?
> 
> If this is correct, I think there is no reason not to do so...

I think so, let's do that!

**Comment by m-bronnikov** [comment]
Work on this issue is done. Let's close.

@seanshpark Thank you for your reviews!
