### ISSUE TITLE
[luci] LUCI_LOG doesn't follow its verbose level

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#7893]
It seems that `LUCI_LOG` doesn't follow its verbose level.

For example, see below commands.
```bash
$ LUCI_LOG=1 ./one-build -C ../test/one-build_014.cfg -OONE-BUILD_014 > log
$ cat log | grep -i pass
Before luci::CircleShapeInferencePass
After luci::CircleShapeInferencePass (changed: Y)
Before luci::CircleShapeInferencePass
After luci::CircleShapeInferencePass (changed: N)
Before luci::CircleTypeInferencePass
After luci::CircleTypeInferencePass (changed: N)
Before RemoveDeadNodeWithQueryPass
After RemoveDeadNodeWithQueryPass (changed: N)
Before luci::CircleShapeInferencePass
After luci::CircleShapeInferencePass (changed: N)
Before luci::CircleTypeInferencePass
After luci::CircleTypeInferencePass (changed: N)
Before luci::MakeBatchNormGammaPositivePass
After luci::MakeBatchNormGammaPositivePass (changed: N)
Before luci::CircleShapeInferencePass
After luci::CircleShapeInferencePass (changed: N)
Before luci::CircleTypeInferencePass
After luci::CircleTypeInferencePass (changed: N)
```
Since, `ProgressReporter` sets its verbose level to 4, `LUCI_LOG` should be 5 to print related logs. But, as you can see above, just level 1 prints those logs.

```cxx
void ProgressReporter::notify(const logo::PhaseEventInfo<logo::PhaseEvent::PassBegin> *info)
{
  LOGGER(l);

  VERBOSE(l, 4) << "--------------------------------------------------------------";
  VERBOSE(l, 4) << "Before " << logo::pass_name(info->pass());
}

void ProgressReporter::notify(const logo::PhaseEventInfo<logo::PhaseEvent::PassEnd> *info)
{
  LOGGER(l);

  VERBOSE(l, 4) << "After " << logo::pass_name(info->pass())
                << " (changed: " << to_char(info->changed()) << ")";
  VERBOSE(l, 4) << fmt(graph());
}
```

**Comment by binarman** [comment]
@mhs4670go Hi!

This is twisted :slightly_smiling_face: 

We have two `luci::ProgressReporter` classes in luci:
- One in `luci/export/src/ProgressReport.cpp`
- Second in `luci/pass/src/ProgressReporter.cpp`

I think you are getting messages from `pass` version (it uses INFO instead of VERBOSE). Could you check if this is the problem?

P.s. We should get rid of one vesion (or rename it), because this situation is a **one definition rule violation** and very confusing =_=

**Comment by seanshpark** [comment]
> P.s. We should get rid of one vesion (or rename it),

Thanks finding this out!
One from me and one from @llFreetimell  :)
We usually copied codes from start and then refactor, move them to common...
Maybe time to do that...

**Comment by mhs4670go** [comment]
@binarman Thank you for your information. Actually, this issue is from #7891.

As you know, `ProgressReporter` in `pass` is used with `INFO` that is printed when the log level is above 4. 
```cxx
  INFO = 3,
```

But, in ubuntu 18.04, even if the log level is 1, `pass` related logs are printed. So, when I wrote `one-build_014.test`, I just set the log level to 1 in my local PC whose ubuntu version is 18.04 and the test had been passed.

**Comment by mhs4670go** [comment]
I found the problem.
```cxx
$ cat compiler/luci/log/src/Log.cpp
LoggerConfig::LoggerConfig()
{
  auto settings = luci::UserSettings::settings();

  _show_warn = !settings->get(luci::UserSettings::Key::MuteWarnings);

  // Turn on info logging if LUCI_LOG is set as non-zero value
  _show_info = safecast<bool>(std::getenv("LUCI_LOG"), false); // NOTE HERE

  // Turn on verbose logging if LUCI_LOG is set to some level
  // VERBOSE(l, 1) will be visible with LUCI_LOG=2 and VERBOSE(l, 2) with LUCI_LOG=3 and so on
  _show_verbose = safecast<int>(std::getenv("LUCI_LOG"), 0);
}
..
void LoggerConfig::configure(const Logger *, hermes::Source::Setting &setting) const
{
  setting.filter(hermes::SeverityCategory::FATAL).reject_all();
  setting.filter(hermes::SeverityCategory::ERROR).reject_all();
  setting.filter(hermes::SeverityCategory::WARN).reject_all();
  setting.filter(hermes::SeverityCategory::INFO).reject_all();
  setting.filter(hermes::SeverityCategory::VERBOSE).reject_all();

  // TODO enable FATAL and ERROR
  if (_show_warn)
  {
    setting.filter(hermes::SeverityCategory::WARN).accept_all();
  }
  if (_show_info)
  {
    setting.filter(hermes::SeverityCategory::INFO).accept_all();
  }
  if (_show_verbose)
  {
    setting.filter(hermes::SeverityCategory::VERBOSE).accept_upto(_show_verbose);
  }
}

```
Since `INFO` is checked with boolean value, just setting `LUCI_LOG` to 1 will print the logs. To resolve this problem, I'm going to remove other attributes except `_show_verbose`.

**Comment by binarman** [comment]
> Since INFO is checked with boolean value, just setting LUCI_LOG to 1 will print the logs. To resolve this problem, I'm going to remove other attributes except _show_verbose.

I thought this behavior was added intentionally :open_mouth:

P.s. I didn't know we have tests based on logs! This could be useful =)

**Comment by seanshpark** [comment]
> P.s. I didn't know we have tests based on logs! This could be useful =)

Well... just to survive... -_-;
and we also have test with logs on to check the LOG relalated codes in code test coverage -_-;
