### ISSUE TITLE
[tflchef] How to generate tflite model with -1(optional) tensor in FC ? 

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#7911]
Here is a part of tfldump result with my local model : 

```
O(0:2) FULLY_CONNECTED
    WeightFormat(DEFAULT) Activation(NONE)
    I T(0:4) Tanh
    I T(0:2) MatMul
    I T(0:-1)
    O T(0:5) MatMul2
```

I'd like to make such tflite file with tflchef. But, it seems that tflchef does not support optional tensor with -1 index, yet.

**Comment by seanshpark** [comment]
I've found `FullyConnected_002` in `res/TensorFlowLiteRecipes` is the test recipe for this kind

```
$ cd build/debug/compiler/common-artifacts
$ tfldump FullyConnected_002.tflite

...
O(0:0) FULLY_CONNECTED
    WeightFormat(DEFAULT) Activation(NONE)
    I T(0:0) in
    I T(0:1) weight
    I T(0:-1)
    O T(0:2) out
...
```

Let's move on to the next step with partitioning :)

**Comment by seanshpark** [comment]
I'll check with `Conv2D` too

**Comment by chunseoklee** [comment]
I have confirmed that tflchef supports -1 indexed tensor in FC layer.

**Comment by chunseoklee** [comment]
@seanshpark Is it ok to close this issue ? or keep it open to track other ops(e.g. Conv2D)'s status ?

**Comment by seanshpark** [comment]
It's OK to close this issue :)

**Comment by chunseoklee** [comment]
close since resolved.
