### ISSUE TITLE
[circle-partitioner] Can't partition Unpack-Tanh model

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#7928]
### Issue

circle-partitioner can't partition model with Unpack-Tanh sequence

### Reproduce Step 

recipe :  #7927 

partition file 

```
[partition]
backends=cpu,npu
default=npu
comply=opcode

[OPCODE]
UNPACK=cpu
```

Note that it doe snot happen if no partition occur. Also it succeed with https://github.com/Samsung/ONE/blob/master/res/TensorFlowLiteRecipes/Unpack_001/test.recipe (single unpack model)

**Comment by seanshpark** [comment]
Existing `Net_UnpackAdd_001` seems to fail. I'll work on with this model.

**Comment by seanshpark** [comment]
Multi-output nodes like `Unpack` was not handled in current partitioner.
That is, the feature was not developed yet. I need some time to think how to implement this...

**Comment by seanshpark** [comment]
@chunseoklee , are there any other nodes that have multiple outputs like UNPACK?

**Comment by seanshpark** [comment]
@chunseoklee , could you please check with #7929 ?

**Comment by chunseoklee** [comment]
(Maybe)split operation ?

**Comment by seanshpark** [comment]
> (Maybe)split operation ?

OK, I'll work on this Op too

**Comment by seanshpark** [comment]
SPLIT added to #7929

**Comment by chunseoklee** [comment]
> @chunseoklee , could you please check with #7929 ?

This patch seems to resolve the multi-output issue of Unpack.(But, during partition, new error occurs. I will post new issue after analysis)

**Comment by seanshpark** [comment]
> This patch seems to resolve the multi-output issue of Unpac

If the draft code for Unpack and others work, do you think it is OK to post PRs for them?

**Comment by chunseoklee** [comment]
> > This patch seems to resolve the multi-output issue of Unpac
> 
> If the draft code for Unpack and others work, do you think it is OK to post PRs for them?

Yes. 

> during partition, new error occurs. I will post new issue after analysis

Still WIP(hard to figure out).

**Comment by chunseoklee** [comment]
closed by resolved
