### ISSUE TITLE
Check support TF 2.7.0

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#7942]
TF 2.7.0 was released a few days ago.
Let's check support new verison is OK.
- This needs python 3.7 and above

~Still 2.6.0 support is not finised yet...~

**Comment by seanshpark** [comment]
`This needs python 3.7 and above` ... how do we solve this issue with Ubuntu 18.04 (default is 3.6)
- ...

**Comment by seanshpark** [comment]
Our internal setup works fine with TF 2.7.0 execution environment.
Now, let's test our unit tests. (looks like order is in backwards...)

**Comment by seanshpark** [comment]
> Now, let's check with our unit tests. 

Issues
- Ubuntu 18.04 does not have Python 3.8.0 --> User(developer) must manually have to install and set as default
- ...

**Comment by lemmaa** [comment]
> ... there is no need to go through TF2.7.0 now.

@seanshpark , the only thing I can think of right now is, Tizen 7.0 is yet to officially support TF2.7.0. This may eventually be changed to TF2.8.0, but it would be good to support TF2.7.0 for now from a ONE runtime's point of view. 

Is there any reason we need to upgrade onnx-tf to a version that requires 2.8.0 soon? If so, we may have to reconsider this issue.

Sorry for the confusion.

**Comment by seanshpark** [comment]
Thanks for sharing your thoughts :)
I have no actual requirements to upgrade to use TF2.7.0 nor TF2.8.0 as of now; also in considering onnx-tf. Situation is like, packages used to import the models are upgrading so we may need to upgrade them one day.
The problem is that our main version of Ubuntu is 18.04 which does not support TF2.7.x nor TF2.8.x. (without upgrading manually to Python3.7 or higher)
So when we need to upgrade to TF2.7.x or TF2.8.x, we may have to migrate to Ubuntu 20.04 (or maybe 22.04?)(I think you already know this situation)
So my current question is like; should we move to 20.04 for development? if not when would be a good time?

**Comment by mhs4670go** [comment]
I think if we don't have to use latest version of `onnx-tf`, we could got different `one-prepare-venv` for each ubuntu version. Say there'd be `one-prepare-venv-bionic` and `one-prepare-venv-focal` and install them as `one-prepare-venv`. If user whose ubuntu version is 18.04 wants to use latest version of `onnx-tf`, we could provide a guide for upgrading python and its version.

**Comment by chunseoklee** [comment]
backlinking to https://github.com/Samsung/ONE/issues/8569 since tf-2.7. also relate to the issue.

**Comment by ragmani** [comment]
> So when we need to upgrade to TF2.7.x or TF2.8.x, we may have to migrate to Ubuntu 20.04 (or maybe 22.04?)(I think you already know this situation)

This link is system requirements to install tensorflow with pip.
https://www.tensorflow.org/install/pip#system-requirements
I think there may be a similar problem in ubuntu 22.04 if python version is 3.10 by default on ubuntu 22.04.

**Comment by seanshpark** [comment]
Closing as we'll go to TF2.8.0
