### ISSUE TITLE
How to execute model exynos NPU?

### ISSUE THREAD

**Issue by ARKAD97** [Samsung/ONE#8017]
Hi. Readme mentions NPU, but doesn't tell how to execute model on Android NPU and lots of docfiles are empty.

Does com.samsung.onert-1.19.0-release.aar support NPU execution?
As far as I understand I have to convert **tflite** model to **circle**, but what is next?

**Comment by chunseoklee** [comment]
@ARKAD97 Thank you for attention. 

> Does com.samsung.onert-1.19.0-release.aar support NPU execution?

Unfortunately, No. ONE does not support Exynos NPU.
