### ISSUE TITLE
[luci] Remove constants duplication from circle to luci

### ISSUE THREAD

**Issue by m-bronnikov** [Samsung/ONE#8042]
### What?

Let's avoid constants duplication between circle and luci IR. 

### Why?

Constant duplication is significant overheap for low-end devices, especially for MCU. 

### How?

It's possible to use constants directly from model's buffer!

-----------------

This issue is part of #7604.

**Comment by m-bronnikov** [comment]
I described in draft #8043 what changes I would like to introduce. This approach leads to extension of luci IR and Importer interface, so, I would like to discuss this changes first.

Also, approach implemented in #8043 requires that model's buffer must be alive longer than imported IR. I don't know how to declare this restriction in the best way and draft not gives answer to this question =(

So, I would like to hear any suggestions for this issue and any comments about draft #8043.

-----------------------

+cc @binarman @seanshpark @BalyshevArtem

**Comment by seanshpark** [comment]
There are features in _luci_ where CircleConst are duplicated when there are identical contents.
Have you check with these kind of models?

**Comment by m-bronnikov** [comment]
> There are features in _luci_ where CircleConst are duplicated when there are identical contents. Have you checked with these kind of models?

No, I didn't check, I'll make it soon, thank you.

**Comment by m-bronnikov** [comment]
Issue is resolved. Value test for feature: #8344. Let's close!
