### ISSUE TITLE
[Compiler] Introduce utils for reading TFLite file

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE#8050]
### What?

Let's introduce utils for reading TFLite files.
(e.g. Getting builtin code, checking custom, etc)

### Why?

Currently, we have some difficulties such as following.

- Some modules have duplicated codes to read TFLite file
- When TFLite schema is updated, we should update all of the codes
- When we need to fix something, we should modify all of the codes

By introducing common utility functions by wrapping TFLite flatbuffer functions, we may expect following things.

- Reduce duplicated codes
- When can provide utility functions according to each version of TFLite
- When TFLite schema is updated or when we need to fix something, we may modify codes only once.

### PRs

- [x] Introduce helper functions
  - #8082 
  - #8091
- [x] Replace helper functions in `tflchef`
  - #8095
- [x] Replace helper functions in `tfldump`
  - #8093
- [x] Replace helper functions in `tfl-inspect`
  - #8092
- [x] Replace helper functions in `tflite2circle`
  - #8094

#### Draft

- #8051

**Comment by llFreetimell** [comment]
This will be rebased/updated after TF 2.7.0 is applied

**Comment by seanshpark** [comment]
> This will be rebased/updated after TF 2.7.0 is applied

We will go with TF 2.6.0 for a while. Please ask @lemmaa for background.
And TF2.7.0 cannot run on Ubuntu 18.04 by default. This requires >= python 3.7.

**Comment by llFreetimell** [comment]
> We will go with TF 2.6.0 for a while

Oh, thanks for notification. Then I shall proceed with current draft :)

**Comment by lemmaa** [comment]
> We will go with TF 2.6.0 for a while. Please ask @lemmaa for background.

In a nutshell, just as we followed ACLs one version back, TensorFlow support intends to do the same. :)

**Comment by llFreetimell** [comment]
Done!
