### ISSUE TITLE
[circle-quantizer] Support TF-style MaxPool quantization

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#8055]
## What

Let's support TF-style MaxPool quantization.

## Why

Our quantizer allows MaxPool to have different input/output qparams for model accuracy. However, some applications require MaxPool to have the same input/output qparams (based on TF implementation).

We provide an option to quantize MaxPool Op in TF-style.

```
onecc quantize --quantized_dtype uint8 \
--TF-style_maxpool \
--input_path ./sample.circle \
--output_path ./sample.q8.circle
```

NOTE: This feature can degrade accuracy in some models.

TODO
- [x] Update QuantizeWithMinMaxPass
- [x] Update circle-quantizer
- [x] Update one-quantize

@lemmaa We've talked about `copy_qparam` feature, but after some thoughts, I guess that it would be not easy for users to find the name of a proper tensor using netron-circle and write the name in GUI. TF-style option (e.g., `TF-style_maxpool`) would be much easier for users because it can be applied during quantization (no post-modification).

**Comment by lemmaa** [comment]
> @lemmaa ... TF-style option (e.g., `TF-style_maxpool`) would be much easier for users because it can be applied during quantization (no post-modification).

@jinevening , although the simplest way, this method was not preferred because it affects all MaxPool operations of the model. Let's think about a little more. :)

**Comment by jinevening** [comment]
> @jinevening , although the simplest way, this method was not preferred because it affects all MaxPool operations of the model. Let's think about a little more. :)

Before I make this issue, I've checked that this option only affects the tensor what we want in our target model. Other MaxPool Ops appear after `Conv2D+Relu` Ops. Relu before MaxPool makes MaxPool Ops have the same input/output qparam.

I agree that copying qparam is a more powerful (general) option. My suggestion is to support TF-style MaxPool for our target model (for ease of integration with our GUI tool and better UX), and also support the copy feature for future usage.

**Comment by lemmaa** [comment]
> My suggestion is to support TF-style MaxPool for our target model (for ease of integration with our GUI tool and better UX), and also support the copy feature for future usage.

I have no objection here. If there is no difficulty in maintenance, I think it is a good choice when considering compatibility with TF models. Let's proceed with this. :)

**Comment by jinevening** [comment]
All done. Let's proceed with the copy feature in #8079.
