### ISSUE TITLE
[circle-quantizer] Support OneHot's quantization

### ISSUE THREAD

**Issue by m-bronnikov** [Samsung/ONE#8065]
### What?

Let's support qunatization of OneHot and qunatize following model:

![image](https://user-images.githubusercontent.com/43731397/143946965-84453edc-209e-4fba-a0d4-8da9a8536af2.png)

<details>
<summary> Code to obtain model </summary>

```python
import tensorflow as tf
import numpy as np

depth=100

with tf.Graph().as_default() as graph:
    # create model
    input_shape = (4, )
    ifm = tf.compat.v1.placeholder(tf.int32, shape = input_shape)
    ofm = tf.one_hot(ifm, depth=depth)

    # save to tflite
    with tf.compat.v1.Session() as sess:
        sess.run(tf.compat.v1.global_variables_initializer())
        converter = tf.compat.v1.lite.TFLiteConverter.from_session(sess, [ifm], [ofm])
        converter.allow_custom_ops = True
        content = converter.convert()
        with open("one_hot.tflite", 'wb') as binf:
            binf.write(content)
```

</details>

### Why?

To increase models coverage which could be quantized using *circle-quantizer*.

**Comment by m-bronnikov** [comment]
To support qunatization of OneHot in *circle-quantizer* we need to resolve #8064 first.

**Comment by m-bronnikov** [comment]
+cc @jinevening

**Comment by m-bronnikov** [comment]
@jinevening I would like to ask your suggestion!

OneHot op expects int32 non-constant input. How we could quantize this input?
AFAIK `record-minmax` expects float32 input and `circle-quantizer` also not allowed to handle these dtype of input. =(

**Comment by jinevening** [comment]
> OneHot op expects int32 (or int64) non-constant input. How we could quantize this input?

Such an input is an index, so it should not be quantized. For example, we do not quantize ArgMax as its output is index.

> AFAIK record-minmax expects float32 input and circle-quantizer also not allowed to handle these dtype of input. =(

As to record-minmax, we may have to support non-float type input. I think MinMaxObserver should be changed as below.

MinMaxObserver.cpp
```cpp
  // Only support recording of float32 values
  if (tensor->element_type() != DataType::FLOAT32)
  {
    // Exceptions that should be processed in backends
    switch (node->opcode())
    {
      case luci::CircleOpcode::ARG_MAX:
        // Output of arg_max is the index of the largest value across axes of a tensor.
        // It always has integer type.
      case luci::CircleOpcode::CAST:
        // Cast is quantized only if it converts <type> -> float.
        // Other cases should be processed in backends.
      case luci::CircleOpcode::RESHAPE:
        // Reshape changes only shape of input tensor, efficiently is it a no-op.
      case luci::CircleOpcode::CIRCLEINPUT:
        // Non-float type input is not quantized
        return;
      default:
        throw std::runtime_error("Tensor's data type is not float");
    }
  }
```

Plus, if you want to quantize without representative dataset, random data generator for int32 or int64 type should be implemented. PTAL `profileDataWithRandomInputs` in RecordMinMax.cpp. Currenlty only fp32 and bool types are supported.

```cpp
      // TODO Support more input data types
      assert(input_node->dtype() == loco::DataType::FLOAT32 ||
             input_node->dtype() == loco::DataType::BOOL);
```

As to circle-quantizer, if record-minmax does not record min/max of qparam of int32 input, the input will not be quantized.

**Comment by m-bronnikov** [comment]
Kernel for `OneHot` supported (https://github.com/Samsung/ONE/issues/8064#issuecomment-989314162), this issue can be started!

**Comment by m-bronnikov** [comment]
Let's check  status of issue with `master`(https://github.com/Samsung/ONE/commit/ca70469ea88923f5c3e2d74ea01405a6f335552d).

Steps:
1. Invoke script from "What" section and obtain tflite model.
2. Convert tflite to circle
3. Record minmax with random data
4. Quantize with minmax.

Log:

```bash
$ python3 onehot_invoker.py 2> /dev/null Enter axis:
-1
$ ./build/compiler/tflite2circle/tflite2circle one_hot.tflite one_hot.circle
$ ./build/compiler/record-minmax/record-minmax --output_model one_hot.m.circle  --input_model one_hot.circle 
Recording 0'th data
Recording 1'th data
Recording 2'th data
Recording finished. Number of recorded data: 3
$ ./build/compiler/circle-quantizer/circle-quantizer --quantize_with_minmax float32 uint8 layer one_hot.m.circle one_hot.q.circle 
```

There is no any fails. Quantized model seems okay:

![image](https://user-images.githubusercontent.com/43731397/146154380-88860f47-8f4c-4622-95e3-708972be6670.png)

So, "What" section seems achieved. Let's close this issue.
