### ISSUE TITLE
[format] Q. Which version is yapf's?

### ISSUE THREAD

**Issue by YongseopKim** [Samsung/ONE#8102]
I ran `format`.

```
~/Works/ONE(master ✔) bash infra/command/format
...
        modified:   tools/tensorflow_model_freezer/sample/TOPK_gen.py
        modified:   tools/tensorflow_model_freezer/sample/UNSTACK_gen.py
        modified:   tools/tflkit/summarize_pb.py
...
```

The only py files have been reformatted. On my local PC(ubuntu 20.04), something different is there. I guess `ypaf` is it.

```
~/Works/ONE(master ✔) pip3 list | grep yapf
yapf                   0.31.0
```

So, which version is valid version of ypaf?

**Comment by lemmaa** [comment]
PTAL, https://github.com/Samsung/ONE/blob/master/infra/docker/bionic/Dockerfile#L46

**Comment by YongseopKim** [comment]
Thanks @lemmaa ! Resolved!

**Comment by YongseopKim** [comment]
FYI, `yapf==0.22.0`
