### ISSUE TITLE
[one-cmds] one-import-onnx fails without onnx_legalizer

### ISSUE THREAD

**Issue by m-bronnikov** [Samsung/ONE#8152]
### What?

I tried to use one-import-onnx tool with latest debian package and obtain fail because onnx_legalizer is missed.

### Why?

`onnx_legalizer` excluded from debian package.

**Comment by m-bronnikov** [comment]
I think we need to add onnx_legalizer to https://github.com/Samsung/ONE/blob/master/infra/debian/compiler/one-compiler.install

+cc @mhs4670go @seanshpark @binarman

**Comment by seanshpark** [comment]
Maybe remove `onnx_leaglizer.py` from default usage.
I'm not sure it's ready to put in the debian package.

**Comment by m-bronnikov** [comment]
I think this one can be closed with #8153.
