### ISSUE TITLE
[luci/export] Refactoring MultiOutputDetector

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE#8192]
### What?

Let's refactor `MultiOutputDetector` class in `luci/export`!

### Why?

- `MultiOutputDetector` has multiple responsibility
  - Detecting multiple output nodes
  - Storing multiple output nodes
- Redundant if-else statement is used because of multiple responsibility 
https://github.com/Samsung/ONE/blob/fba84c5bf5fe0c4ed1e9e60a9c72fbb4838b80b1/compiler/luci/export/src/CircleTensorExporter.cpp#L287-L294

### How?

- Rename class name with single responsibility
- Integrate related functions into the class
- Remove if-else statement

----

#### Draft

- #8193

#### Related PRs

TBA

**Comment by seanshpark** [comment]
There's a comment 
```
  // TODO revise this when loco supports multiple outputs
  // NOTE this will store all virtual output tensors and skip for the real node
  if (auto circle_node = dynamic_cast<luci::CircleNode *>(node))
  {
    MultiOutputDetector d(ctx);
    if (circle_node->accept(&d))
      return;
  }
```
Which is why there is an `if` and I don't know this is really related with _multiple responsibility._

**Comment by seanshpark** [comment]
Can you explain about `Storing multiple output nodes`?

**Comment by llFreetimell** [comment]
> Can you explain about Storing multiple output nodes?

Currently, `MultiOutputDetector` have following `visit` functions.

https://github.com/Samsung/ONE/blob/fba84c5bf5fe0c4ed1e9e60a9c72fbb4838b80b1/compiler/luci/export/src/CircleTensorExporter.cpp#L222-L226

It **store**s multiple output nodes by `store_outputs` function.

> Which is why there is an if and I don't know this is really related with multiple responsibility.

If we refactor the class to have only one responsibility, we can remove if-else and make the codes like following.

https://github.com/Samsung/ONE/blob/449f636eaea631a69d15104ae627cfef2b9722dc/compiler/luci/export/src/CircleTensorExporter.cpp#L240

**Comment by llFreetimell** [comment]
FYI, I was to remove "detecting multiple output" because allocating tensor info can be done without it

### Before

```cpp
  if (auto circle_node = dynamic_cast<luci::CircleNode *>(node))
  {
    MultiOutputDetector d(ctx);
    if (circle_node->accept(&d))
      return;
  }

  allocateCircleTensorInfo(node, ctx);
```

### After

```cpp
  CircleTensorInfoAllocationRule tensor_info_allocation_rule(ctx);
  node->accept(&tensor_info_allocation_rule); // allocate tensor info
```

**Comment by seanshpark** [comment]
I am not sure but I think I got what you want to do and why I disgree on this change.
It's about the comment I mentioned 
>   // TODO revise this when loco supports multiple outputs
  // NOTE this will store all virtual output tensors and skip for the real node

which is why there is an `if` but I don not want to remove this `if`.
I'm not sure when _loco_ can support multiple outputs and this workaround may be removed but until then I want to leave it as is.

**Comment by llFreetimell** [comment]
> but I do not want to remove this if.

Can I ask you why? :)

I thought that it is not that big change because
- Core logic is exactly same (implementations are not changed)
- The comments will not be removed

So I wonder what would be cons of this change :)

**Comment by seanshpark** [comment]
> Can I ask you why? :)

As I wrote above, "I'm not sure when loco can support multiple outputs and this workaround may be removed but until then I want to leave it as is."
When _loco_ support multiple outputs, the `if` is not needed and the the multiple detection too.

> The comments will not be removed

```
  // TODO revise this when loco supports multiple outputs
  // NOTE this will store all virtual output tensors and skip for the real node
  CircleTensorInfoAllocationRule tensor_info_allocation_rule(ctx);
  node->accept(&tensor_info_allocation_rule);
```
As I see, this will exist. And I don't know how this code should be changed after `loco supports multiple outputs`. The comment should be moved to someplace else or deleted.

**Comment by llFreetimell** [comment]
> this workaround may be removed but until then I want to leave it as is.

Hmm... my draft is not removing current workaround, but just making original intention more clear.
(As implementation is not changed at all, current workaround is still alive)

---

I am little bit difficult to understand why this is related with `loco` and what would be cons of this change, but as this is not that urgent/important issue, I will close this issue for now :)

**Comment by seanshpark** [comment]
> why this is related with loco 

#101 may help understanding why locl is involved. if you already know this, I've nothing to say more.
