### ISSUE TITLE
[luci/export] Refactoring Circle Operation Exporter

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE#8198]
### What?

Currently, we applied following workarounds to avoid large LoC.

- Separating `visit` functions with alphabet grouping
https://github.com/Samsung/ONE/blob/638a1e64b417a6ff9fe243b402e95eac2b449b2e/compiler/luci/export/src/CircleOperationExporter.cpp#L956-L964
- Just moving implementation to another function
https://github.com/Samsung/ONE/blob/638a1e64b417a6ff9fe243b402e95eac2b449b2e/compiler/luci/export/src/CircleOperationExporter.cpp#L982

Let's try to remove the workarounds!

### How?

I will apply following things
- Remove duplicated code
- Integrate separated operations
- Create separate Visitor classes

Then I expect following result :)

#### Before

![before](https://user-images.githubusercontent.com/24720192/146870634-38c94305-be3e-43fb-b691-aeea6b01e906.png)

#### After

![after](https://user-images.githubusercontent.com/24720192/146870668-237ce114-a126-4cba-a110-6e9ee78c6144.png)

---

#### Related PRs

- Draft : #8199
- [x] Introduce BuiltinTypesMappingRule
  - #8205
- [x] Introduce BuiltinOptionsExtractor
  - #8209
- [x] Util functions update
  - #8206
  - #8211
- [x] Introduce OperationExporterRule
  - #8218
- [x] Apply refactored class
  - #8220
- [x] Remove unused codes
  - #8225

**Comment by seanshpark** [comment]
@llFreetimell , please share LoC value (URL would be better through our internal github) from our static analyzer of your draft :)

**Comment by llFreetimell** [comment]
@seanshpark Please refer to internal PR#13154, LoC value is same with current :D

**Comment by seanshpark** [comment]
FYI #8203 was for new Op. I am curious of how new Ops can be added without and problems for latest refactorings of mine and yours :)

**Comment by llFreetimell** [comment]
> I am curious of how new Ops can be added without any problems for latest refactorings of mine and yours

Plus my additional (but not that critical) concern is.. LoC score would be 4.99 not 5.0 after `CircleSVDF` is added ^.T

**Comment by seanshpark** [comment]
> LoC score would be 4.99 not 5.0 after CircleSVDF is added ^.T

Well, this was my concern as all the lines for all the nodes in a class adds up and that sometimes exceeded the tipping point ... -_-; I think this was why I splitted to multiple classes.

I'll leave the decision to you for this; go or no-go.

**Comment by llFreetimell** [comment]
@seanshpark 

FYI, there is one solution, which I was planning to apply this at `luci/logex NodeSummaryBuilder` and `luci/service CloneNode` :)
(only needed thing is my labor..!)
If we apply the design of `luci/import GraphBuilderRegistry`, the LoC problem can be resolved. (Unless circle operation exceed 500 operations :D)
How about applying this solution? :)

**Comment by seanshpark** [comment]
> For me, score 4.90~5.00 can be accepted

Me too, I think we can go with this.
We can later refactor when you(or someone else) have some time for "labor" :)

**Comment by llFreetimell** [comment]
Done!
