### ISSUE TITLE
[Question] Does ONE support sparse inference like XNNPack?

### ISSUE THREAD

**Issue by TigerVersusT** [Samsung/ONE#8226]
Hi, I find this project in [XNNPack](https://github.com/google/xnnpack)'s main page, since it declared to support sparse inference(  for example, model obtained by unstructured pruning ) and mentioned ONE in the [ecosystem](https://github.com/google/xnnpack#ecosystem), I'm wondering whether ONE has the same support. 

Thanks for you help.

**Comment by chunseoklee** [comment]
@TigerVersusT Thank you for attention.

ONE supports sparsity for FC for now. Here, the sparsity means Tensorflow Lite's own sparsity definition. Please refer to 
https://github.com/Samsung/ONE/issues/3597 for details. 

cc @glistening

**Comment by TigerVersusT** [comment]
Thanks for your replay

**Comment by glistening** [comment]
@chunseoklee You're right. `ONE` supports sparsity based on tensorflow lite's schema. We've tried several sparsity kernel implementations (including `xnnpack`) on `arm64` (as I remember it was the main target architecture at that time) and `x86_64`.
