### ISSUE TITLE
[one-cmds] torch package sometimes fail to install in in-house CI

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#8234]
```
# Install PyTorch and ONNX related
${VENV_PYTHON} -m pip ${PIP_OPTIONS} install torch==1.10.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
```
`torch` installation sometimes fail to install in our in-house CI.

let's check and provide a way to overcome this problem.

**Comment by jyoungyun** [comment]
Detailed error log:

```
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa37493def0>: Failed to establish a new connection: [Errno 110] Connection timed out',)': /whl/torch_stable.html
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa374949400>: Failed to establish a new connection: [Errno 110] Connection timed out',)': /whl/torch_stable.html
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa374949160>: Failed to establish a new connection: [Errno 110] Connection timed out',)': /whl/torch_stable.html
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa374949f28>: Failed to establish a new connection: [Errno 110] Connection timed out',)': /whl/torch_stable.html
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa3749680b8>: Failed to establish a new connection: [Errno 110] Connection timed out',)': /whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.10.0+cpu (from versions: 0.3.1, 0.4.0, 0.4.1, 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1)
ERROR: No matching distribution found for torch==1.10.0+cpu
```

The related issue is [here](https://github.com/pytorch/pytorch/issues/51723).
However when I try to reproduce this issue, it did not happened again.

**Comment by seanshpark** [comment]
bump up to 1.10.0+cpu was from #8060

@binarman, do we need this package?

I'm thinking of (1) remove this package as it's not used (yet) (2) revise this so that URL can be overridden.

**Comment by seanshpark** [comment]
> (1) remove this package as it's not used (yet)

All test passes without torch. (internal CI also)
I now realize that `torch` is not needed as current flow begins from ONNX but at the time code was added, it wasn't sure.

**Comment by binarman** [comment]
@seanshpark 
> do we need this package?

As you mentioned, this package is not used in CI tests.

P.s. There are additional tests in `one-cmds/tests/onnx-operations` and `one-cmds/tests/pytorch-operations` that require this package. They are not executed on a regular basis and used only for verification of one of last year goals =)

**Comment by seanshpark** [comment]
> As you mentioned, this package is not used in CI tests.
P.s. There are additional tests in ...

As there are tests using these and I think it would be better to leave them but to solve this isuse, I've posted #8237. Could you PTAL at the PR?

**Comment by seanshpark** [comment]
done for this repo.
