### ISSUE TITLE
[CFE] determine `is_variable` of tensor and it's influence

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#8272]
From SVDF Op, there is `is_variable` and I need to investigate/understand and it's influence to existing codes.

**Comment by seanshpark** [comment]
From  #8231

**Comment by seanshpark** [comment]
How does `is_variable` work in tflite?

**Comment by seanshpark** [comment]
In tflite schema, these last two are related
```cxx
// An operator takes tensors as inputs and outputs. The type of operation being
// performed is determined by an index into the list of valid OperatorCodes,
// while the specifics of each operations is configured using builtin_options
// or custom_options.
table Operator {
...
  // A list of booleans indicating the input tensors which are being mutated by
  // this operator.(e.g. used by RNN and LSTM).
  // For example, if the "inputs" array refers to 5 tensors and the second and
  // fifth are mutable variables, then this list will contain
  // [false, true, false, false, true].
  //
  // If the list is empty, no variable is mutated in this operator.
  // The list either has the same length as `inputs`, or is empty.
  mutating_variable_inputs:[bool];

  // A list of indices to the subgraph's "tensors" that are internal to an Op.
  // Internal tensors are those that do not flow in or out of the operation,
  // but instead are part of internal computation. As such, the operation's
  // implementation may manage its memory more efficiently. They are needed
  // however (i.e. not just an implementation detail) since they are part of the
  // computation, which may require relevant metadata such as quantization
  // parameters.
  intermediates:[int];
}
```

**Comment by seanshpark** [comment]
dump of KWS model from #8203
```
[2] SVDF (code: 27, dep_code: 27, version: 3)

T(0:4) INT16 (1, 512) B(0) (noname)
    Quantization: scale(0.00437017) zeropt(0) quantized_dimension(0)

T(0:5) INT8 (1, 64) B(0) (noname)
    Quantization: min(0) max(60.2268) scale(0.236183) zeropt(-128) quantized_dimension(0

O(0:1) SVDF
    I T(0:0) (noname)
    I T(0:1) (noname)
    I T(0:2) (noname)
    I T(0:3) (noname)
    I T(0:4) (noname)
    O T(0:5) (noname)
```

**Comment by binarman** [comment]
Design from #8279  looks reasonable and sufficient for KWS, and probably for other models.

However I am not sure if tflite guarantee that variable tensor is used in only one operation.
If we want to support reuse of one variable tensor values in one inference we probably need to separate explicit read and write of variable tensor:

Current #8279 design | Explicit accesses
--- | ---
![svdf_implicit](https://user-images.githubusercontent.com/3631351/149517847-779cdd7e-4a33-4aa5-9868-f80850e7c0a7.png) | ![svdf_explicit](https://user-images.githubusercontent.com/3631351/149517866-c70c0054-d9a8-49ca-abb7-0642b09e949b.png)

* **bold** lines shows where variable tensors are used

Using variable tensor in multiple operations could look like this:
![svdf_stacked](https://user-images.githubusercontent.com/3631351/149518187-fdc130fc-0927-480d-8086-0b72c0a90e5c.png)

**Comment by binarman** [comment]
Overall, I think current design it is good, but I think we need to add some checker in importer that verifies that variable tensors are used in only one operation

**Comment by seanshpark** [comment]
> If we want to support reuse of one variable tensor values in one inference we probably need to separate explicit read and write of variable tensor:

Thanks for the comment. I also think this is possible.
But I think it would be better to leave this to future work when we meet actual model and add some assert checks to catch this as you wrote like;

> add some checker in importer that verifies that variable tensors are used in only one operation

**Comment by seanshpark** [comment]
I think we can now close this issue.
