### ISSUE TITLE
[circle-quantizer] Support quantization of BatchMatMul

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#8325]
## What

Let's support quantization of BatchMatMul Op.

- [x] draft
- [x] luci-interpereter
- [x] luci/pass
- [x] common-artifacts (remove BMM from exclude.lst)

**Comment by m-bronnikov** [comment]
@jinevening Do you work on this issue or can I take this issue if nobody minds?

**Comment by jinevening** [comment]
> @jinevening Do you work on this issue or can I take this issue if nobody minds?

I'm working on this :)

**Comment by jinevening** [comment]
All done.
