### ISSUE TITLE
[luci-micro] Warning message

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#8337]
Current ONE compiler cmake configure step shows
```
-- Configure LUCI-MICRO
CMake Warning at /home/maxwell/ml/ss/one/compiler/luci-micro/CMakeLists.txt:9 (message):
  ARM compiler is NOT FOUND, skipping luci-micro build


-- Configure LUCI-MICRO - Done
```
when `arm-none-eabi-` compiler does not exist.

I'm not sure showing as `warning` is appropriate.

**Comment by seanshpark** [comment]
@binarman , I would like to remove this warning as not having `arm-none-eabi-` is normal.
Please share your thoughts.

**Comment by seanshpark** [comment]
@binarman , ping

**Comment by binarman** [comment]
Sorry for long delay

You are right, warning is probably too bold mode for this message.
What do you think about `STATUS` instead of `WARNING`, like in other places?

**Comment by seanshpark** [comment]
Yes `STATUS` will be nice :)
