### ISSUE TITLE
[circle-quantizer] Fix bias quantization

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#8385]
## What

Fix bias quantization
- Reorder quantization steps
- Add tests to prevent such cases

## Why

Currently, input activation can be overwritten after bias is quantized. This causes mismatch between input scale and bias scale. To prevent this, we should reorder quantization steps.

Current quantization flow

Quantize activation -> Quantize weights -> Quantize bias -> Propagate concat param (backward) -> Quantize const input -> Set input/output dtype -> Propagate activation qparam (forward)

Changed flow

Quantize activation -> Propagate concat param (backward) -> Quantize const input -> Propagate activation qparam (forward) -> Quantize weights -> Quantize bias -> Set input/output dtype

Activation qparam should not be changed after bias is quantized.

**Comment by jinevening** [comment]
All done. Refactoring (https://github.com/Samsung/ONE/pull/8388#issuecomment-1032214650) will be done after #8393 is done.

**Comment by seanshpark** [comment]
@jinevening , what about `TF_style_maxpool getter/setter` ?

**Comment by jinevening** [comment]
As mentioned in https://github.com/Samsung/ONE/pull/8388#issuecomment-1032214650, I think that it would be better to introduce `Context` struct, which contains all arguments including `TF_style_maxpool`.

Introducing `Context` is not directly related to this issue, so I plan to do it after #8393 is done.

**Comment by seanshpark** [comment]
> Please tell me if you have a different view.

I also think `Context` is good so don't have different view.

> so I plan to do it after https://github.com/Samsung/ONE/issues/8393 is done.

OK :) thanks!
