### ISSUE TITLE
[luci/pass] Separate quantizer from optimizer

### ISSUE THREAD

**Issue by llFreetimell** [Samsung/ONE#8393]
### What?

Let's separate `quantize(loco::Graph *)` from `CircleOptimizer` and introduce `CircleQuantizer`!

### Why?

- Quantization is not related with optimization. (`quantize(g)` and `optimize(g)` have never been used together)
  - Violation of SRP
  - Violation of OCP
  - Low cohesion
-  LoC of `CircleOptimizer` is little bit large

---

#### Related PR/Issue

- Draft : #8394

#### Todo

- [x] Introduce `CircleQuantizer` #8404
- [x] Replace `CircleOptimizer` in `circle-quantizer` with `CircleQuantizer` #8427
- [x] Remove quantization in `CircleOptimizer` #8428

**Comment by llFreetimell** [comment]
@jinevening  FYI :D

**Comment by jinevening** [comment]
Please go ahead. #8385 is closed.

**Comment by llFreetimell** [comment]
Done!
