### ISSUE TITLE
[one-quantize] Support mixed-precision quantization

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#8398]
## What

Let's support manual mixed-precision quantization. 'Manual' indicates that quantization configuration file is manually written by users.

![image](https://user-images.githubusercontent.com/5449554/153107541-65946412-efbd-43dc-b52c-dadfd0c51b62.png)

- [x] Quantization configuration file #8399
- [x] Update quantizer
  - [x] FakeQuant
  - [x] ~RecordMinMax~ Nothing to update
  - [x] QuantizeWithMinMax
  - [x] one-quantize

NOTE: In this issue, we'll assume that the output model will not contain any fp32 layer.

**Comment by seanshpark** [comment]
> Quantization configuration file

Have you decided which format to use?

**Comment by jinevening** [comment]
> Have you decided which format to use? and which library?

JSON looks good to me due to the following reasons
    - Widely used, MIT licensed parser: jsoncpp (https://github.com/open-source-parsers/jsoncpp)
    - More concise than XML
    - Allow array

I've made https://github.com/Samsung/ONE/issues/8399 for quantization configuration file. Let's discuss there :)

**Comment by jinevening** [comment]
Manual mixed-precision quantization is now working.
