### ISSUE TITLE
[luci] Create a new const when quantizing const inputs

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#8406]
## What 

Let's create new const nodes when quantizing const inputs

## Why

Currently cont inputs are in-place quantized. (in `quantize_const_inputs`)

It was for ease of implementation, and did not cause any problem before quant steps are reordered (https://github.com/Samsung/ONE/issues/8385).

But now it becomes a problem when the const input is used both as an activation and a bias.

**Comment by seanshpark** [comment]
> But now it becomes a problem when the const input is used both as an activation and a bias.

You mean, when constant is shared, quantization should be appliced differntly?

**Comment by jinevening** [comment]
> You mean, when constant is shared, quantization should be applied for each case?

Exactly :)

For example, let's assume there is a zero constant used as the input of ADD and the bias of CONV.

They should be quantized in a different way, so we need to create separate consts.

**Comment by jinevening** [comment]
All done.
