### ISSUE TITLE
[infra] Adjust python file filter in format script

### ISSUE THREAD

**Issue by binarman** [Samsung/ONE#8448]
## What?

Need to refactor file path filtering in infra/command/format script.
Format script should check scripts `onecc`, `one-import-tflite` and other scripts without extensions and '.py' files.

## Why?

#8221 introduced [these lines](https://github.com/Samsung/ONE/pull/8221/files#diff-f26ca7df49b7cc7c3f32f3769aa92113e722738d77a5f2458a5850dde86b352dR181-R182) which disables checking for one-cmds

This code filtered out files like `compiler/one-cmds/onecc`, `compiler/one-cmds/one-codegen`, etc.
Original code filtered out only files with extensions.

**Comment by hseok-oh** [comment]
Done: https://github.com/Samsung/ONE/blob/master/infra/command/format#L158-L163
