### ISSUE TITLE
[luci] Remove redundant Quantize operators

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#8526]
## What

Let's implement a pass to remove redundant Quantize Ops

![image](https://user-images.githubusercontent.com/5449554/155666120-537b471a-2429-46d0-8cb5-c3a385e449de.png)

For subsequent Quantize Ops, only the last Quantize Op is valid, so we can remove the rest of the Quantize Op (the first Quantize Op in the figure).

We can also remove the last Quantize Op if the following conditions are met.
1. dtype0 == dtype2
2. s0 == s2 AND zp0 == zp2

## Why

To remove redudant Quantize Ops generated during mixed-precision quantization (for more details: https://github.com/Samsung/ONE/issues/8512#issue-1148776330).

**Comment by BalyshevArtem** [comment]
I would like to work on this issue, can I? :)

**Comment by jinevening** [comment]
Sure :)

**Comment by BalyshevArtem** [comment]
> Q) do we have any test models from `tflchef` recipes?

I think we don't have it. I can add new `tflchef` recipes if needed.

**Comment by seanshpark** [comment]
@BalyshevArtem , please add options to `one-cmds` too

**Comment by BalyshevArtem** [comment]
I think everything is merged and we can close this issue :)
