### ISSUE TITLE
Nominating Hyukjin Jeong (@jinevening) to become a ONE committer 

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#8541]
I'd like to become a ONE committer because I have non-trivial patches on quantization issues, which can be viewed here:
https://github.com/Samsung/ONE/pulls?q=is%3Apr+is%3Aclosed+author%3Ajinevening+label%3Aarea%2Fquant

I'll only merge commits related to quantization issues with one or more approvals.

Could you give an opinion? @lemmaa  @seanshpark  @Samsung/one_quantizer

**Comment by llFreetimell** [comment]
I already agreed with 👍 :D

**Comment by lemmaa** [comment]
From the number of thumbs up, it was possible to confirm the consent of members. Now @jinevening will contribute as a committer of the quantizer domain. Congratulations!!!

**Comment by jinevening** [comment]
Thanks :)
