### ISSUE TITLE
[circle-partitioner] Include in one-cmds (onecc)

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#8570]
There are some more features to develop this year(2022) like partition by node name,
I think it is time to include `circle-partitioner` in `onecc` command.

**Comment by seanshpark** [comment]
Had a short off-line meeting with @chunseoklee and @hyunsik-yoon today.
First question is about when to partithion the model?
- current procedure of `onecc` is like import -> optimize -> quntize -> package

What we agreeded as of now is to run partition after quantize and before package like
- import -> optimize -> quantize -> partition -> package

I'd like to open this topic for a while before actually implementhing this.
Any thoughts are welcome :)

Note: we can discussion about flexible procedure in another issue.

**Comment by seanshpark** [comment]
I'll work on this topic as `import -> optimize -> quantize -> partition -> package`

**Comment by seanshpark** [comment]
In the `README.md` of _circle-partitioner_ , 
```
Why does input files be placed in `work` folder too?
- this is still work in progress condition
- use cases are still ambigious
- original `input` model file can be used by the backend, so `.conn` file links it as `source`
- to make things simple for the backend, it would be better not to use relative path for the files
```

Now, it's time to fix this...

**Comment by seanshpark** [comment]
@mhs4670go , can positional argument (the last one) be optional?

**Comment by lemmaa** [comment]
> I'll work on this topic as `import -> optimize -> quantize -> partition -> package`

@seanshpark , oops, I was totally missing out on this issue. I'm sorry. :(
One point I would like to make is that partitions can happen anywhere.

1. `partition -> optimize -> quantize`
    - I'm not sure what the advantages of this are clearly. But I think it's a possible scenario.
2. `optimize -> partition -> quantize`
   - Required when targeting backends that use different quantization schemes. For example, when using CPU/GPU and NPU at the same time
3. `optimize -> quantize -> partition`
   - May be useful for multiple backends using the same quantization scheme. For example multi-core .

Perhaps @chunseoklee first considered case 3. It is expected that the case 2 will be next. :)

**Comment by seanshpark** [comment]
>  oops, I was totally missing out on this issue. I'm sorry. :(

Case 3 was consisdered first, cause when performing quantize after the partition,
we can't provide reference data (real data) for quantization (as of now).

**Comment by mhs4670go** [comment]
> @mhs4670go , can positional argument (the last one) be optional?

No,, it can't.

**Comment by seanshpark** [comment]
@lemmaa , current `onecc` or `one-build` is fixed in execution order.

**Comment by lemmaa** [comment]
> @lemmaa , current onecc or one-build is fixed in execution order.

Yes. For case 1 and case 2, we will need an extension of onecc in near future. One way is, what if the execution order is processed in the order in which key(=property) is described in the [onecc] section? If recognizing the order of keys is complicated, simply adding a new key such as `execution-order` is a way. (The former is more intuitive and convenient.)

In the future, we will also need workflow management features something like follows. :)

```
m -> [partition] --> m.p1 -> [quantize] -> m.p1.q -> [codegen] -> m.p1.q.o --> [pack] -> m.pkg --> [infer]
                 |-> m.p2 -------------------------------------------------|                   |
                 +-> m.p3 -> [quantize] -> m.p3.q -------------------------+                   +-> [profile]
```

/cc @Samsung/one-vscode

**Comment by seanshpark** [comment]
@mhs4670go , I'm adding `one-partiton` section in `.cfg` and `one-partition` tool requries three positional arguments but I'm not sure how to make this work...
```ini
[one-partition]
partition=Net_InstanceNorm_003.part
input=Net_InstanceNorm_003.circle
work=.
```
Can you please take a look at the draft #9074 ? please check with `one-build` not `onecc`

**Comment by mhs4670go** [comment]
@seanshpark Which error did you meet? I think you could meet an error because positional arguments are not given. Umm.. how about make them optional and verify some condition like this?
```python
def _verify_arg(parser, args):
    """verify given arguments"""
    # check if required arguments is given
    missing = []
    if not _utils._is_valid_attr(args, 'input_path'):
        missing.append('-i/--input_path')
    if not _utils._is_valid_attr(args, 'output_path'):
        missing.append('-o/--output_path')
    if len(missing):
        parser.error('the following arguments are required: ' + ' '.join(missing))
```

**Comment by seanshpark** [comment]
> I think you could meet an error because positional arguments are not given

Yes, I think this is the problem and we cannot use positional arguments in `one-xxx` tool...

**Comment by seanshpark** [comment]
As there are limitaton of positional arguments and difference from other `one-` commands tools, 
I think it would be better to revise `circle-partition` command argument style.

**Comment by mhs4670go** [comment]
I think we don't need to match interface between `circle-partition` and `one-` command tools. Just `one-cmds` using optional arguments seems enough because it can call `circle-partition` internally with customized commands.

**Comment by seanshpark** [comment]
Yes, we don't need to but will make confusion...
as current _circle-partitioner_ is not used officially so I think it would be better to change this when we can.

**Comment by seanshpark** [comment]
Let's add some tests for _one-cmds_

**Comment by seanshpark** [comment]
Test material
- [Net_InstanceNorm_003.zip](https://github.com/Samsung/ONE/files/8608844/Net_InstanceNorm_003.zip)

**Comment by seanshpark** [comment]
done for now.
