### ISSUE TITLE
[quantizer] Introduce input model checker

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#8580]
## What

Let's introduce a checker to verify the input model has the form acceptable by quantizer.

For example,
quantizer only accepts const weights and const bias for Conv2D.

## Why

I think that it should be implemented as a new pass or visitor. I'll check it in another PR.

_Originally posted by @jinevening in https://github.com/Samsung/ONE/pull/8579#discussion_r820368924_

**Comment by BalyshevArtem** [comment]
Could I work on this issue? :)

**Comment by jinevening** [comment]
> Could I work on this issue? :)

Sure. I know you can do this task with your experiences in luci, but I'd like to give a rough guide to reduce unnecessary revisions :)

Let's say the class name of the checker is `QuantizationPreChecker` (you can use a more appropriate name).

1. `QuantizationPreChecker` will accept `loco::Graph` and raise an exception when it detects a model has an unacceptable condition. For now, it will be called before `QuantizedWithMinMaxPass` runs ([CircleQuantizer.cpp](https://github.com/Samsung/ONE/blob/master/compiler/luci/pass/src/CircleQuantizer.cpp#L312)), but it can be used in another source in the future.

2. `QuantizationPreChecker` will work in a blocklist manner (<-> allowlist). That is, it passes a model by default but raises an exception only when the model has unacceptable conditions.

3. There will be many conditions (maybe applied based on opcode), so it should be possible to easily add new conditions.
