### ISSUE TITLE
[circle-eval-diff] Introduce a module to compare results of inference

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#8634]
**Update: I've renamed `luci-eval-diff` to `circle-eval-diff`.**

## What

Let's introduce a new module (`circle-eval-diff`) that compares inference results of two circle models.

![image](https://user-images.githubusercontent.com/5449554/158323377-65de12c9-a470-4b2a-bfd1-156729114e90.png)

`circle-eval-diff` will be useful to evaluate the accuracy of quantized model. We may use the module as follows.

```
./circle-eval-diff --first_model <circle> --second_model <circle> --first_input_data <h5/directory> --second_input_data <h5/directory> --metric <metric>
```

NOTES
- It would be possible to implement circle-eval-diff in different ways (C++ or Python)
- Input models can have different dtypes (e.g., A is fp32 and B is uint8). Comparison code should recognize the dtype of output.
- Possible metrics would be MAE, MSE, PEIR ..

CC @Samsung/one_quantizer

**Comment by jinevening** [comment]
Format of `input_data` would be `h5` and `directory`, which is the same with that of `record-minmax`.

**Comment by seanshpark** [comment]
Q) can we use random data if `<input_data>` is not given?

**Comment by jinevening** [comment]
> Q) can we use random data if <input_data> is not given?

I think that would be a convenient option (although not very accurate way to evaluate accuracy).

**Comment by jinevening** [comment]
I've renamed the tool to `circle-eval-diff`.

**Comment by jinevening** [comment]
HDF5 format of input_data

```
/first
/first/<data_num>/<input_num>
/second
/second/<data_num>/<input_num>
```

**Comment by jinevening** [comment]
Now draft has merged.

## Test results

Same model, same data (MAE = 0)
```
$ build/debug/compiler/circle-eval-diff/circle-eval-diff --first_model /home/hjj/TRIV2_Model_Zoo/VD-MODIFIED/AI_ZOOM/centernet_1216/centernet_1216.circle --second_model /home/hjj/TRIV2_Model_Zoo/VD-MODIFIED/AI_ZOOM/centernet_1216/centernet_1216.circle --first_input_data /home/hjj/TRIV2_Data_Zoo/VD/centernet_1216.input.1.h5 --second_input_data /home/hjj/TRIV2_Data_Zoo/VD/centernet_1216.input.1.h5
Evaluating 0'th data
Evaluation finished. Number of data: 1
Mean Absolute Error (MAE)
MAE for conf is 0
MAE for conf_pool is 0
MAE for boxes is 0
```

Same model, different data (non-zero MAE)
```
build/debug/compiler/circle-eval-diff/circle-eval-diff --first_model /home/hjj/TRIV2_Model_Zoo/VD-MODIFIED/AI_ZOOM/centernet_1216/centernet_1216.circle --second_model /home/hjj/TRIV2_Model_Zoo/VD-MODIFIED/AI_ZOOM/centernet_1216/centernet_1216.circle --first_input_data /home/hjj/TRIV2_Data_Zoo/VD/centernet_1216.input.1.h5 --second_input_data /home/hjj/TRIV2_Data_Zoo/VD/centernet_1216.input.2.h5
Evaluating 0'th data
Evaluation finished. Number of data: 1
Mean Absolute Error (MAE)
MAE for conf is 0.0251598
MAE for conf_pool is 0.0466728
MAE for boxes is 13.6235
```

**Comment by jinevening** [comment]
Default behavior is implemented.

## TODO lists
- More metrics
- More data format
- Better API (Is it necessary to support different metrics for different outputs?)
