### ISSUE TITLE
Compiler FE : Speed up CI build and test time

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#865]
CI builds and tests `nncc` every PR. But it makes us spends too much time building and testing. So, it is better to do a long test(e.g. `tf2tfliteV2` test takes like 5 minutes), not every PR, just periodically.

There are a few options I think.

1. Reduce build time
We can make a white list which is created by gathering frequently used(need to discusstion) or necessary to releases.
then,
every PR build - build with white list
push build - build all module

2. Reduce test time
We can add command to `./nncc test` like below.
`./nncc test -E ".*_remote_test|tf2tfliteV2_.*"`
then,
every PR build - test with above command
push build - test all module

Second option looks good to me but first option looks a little bit optional.

Please give your opinion:)

**Comment by hseok-oh** [comment]
@mhs4670go I think it is done by #11814
