### ISSUE TITLE
[quantizer] Support mixed-precision in Ops with multiple outputs

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#8654]
## What

Let's support mixed-precision quantization in Ops with multiple outputs.

## Why

For now, Ops with multiple outputs are disabled (https://github.com/Samsung/ONE/pull/8595). Supporting Ops w/ multiple outputs can be a future task.

_Originally posted by @jinevening in https://github.com/Samsung/ONE/pull/8640#discussion_r827526608_

**Comment by jinevening** [comment]
There is a naming issue in multi-out Ops.

For example, for Split Op with num_split = 2, three circle nodes are generated.
1. CircleSplit (name: "split0") <- name is copied from the first SplitOut
2. CircleSplitOut (index: 0, name: "split0")
3. CircleSplitOut (index: 1, name: "split1")

If quantization config file designates precision of "split0", Quantize Ops will be inserted before/after of both 1 and 2, which is not intended.

**Comment by BalyshevArtem** [comment]
I would like to work on this issue, can I? :)

**Comment by jinevening** [comment]
> I would like to work on this issue, can I? :)

Sure :)

**Comment by jinevening** [comment]
I'm closing this issue as @BalyshevArtem has finished this job :)
