### ISSUE TITLE
tv2-compile: ERROR: Something goes wrong during compilation

### ISSUE THREAD

**Issue by lstomy** [Samsung/ONE#8685]
Hi,

I am trying to convert my own model using onecc tool for tv2 beckend (onecc version 1.19.0).
At [one-codegen] step I got the error: "tv2-compile: ERROR: Something goes wrong during compilation", which actually doesn't give any helpful info for me to originate what's exactly wrong with the model (e.g. may be some layers/ops are not supported or other reason).

So, are there any guides how I can debug such cases with more details?

My config file `frozen_model.cfg`:
```
[onecc]
one-import-tf=True
one-import-tflite=False
one-import-bcq=False
one-import-onnx=False
one-optimize=True
one-quantize=True
one-pack=False
one-codegen=True

[one-import-tf]
input_path=./frozen_model.pb
output_path=frozen_model.circle
input_arrays=input
input_shapes=1,128,128,3
output_arrays=MNet/outputs/flatten/Reshape
converter_version=v1
model_format=graph_def

[one-optimize]
input_path=frozen_model.circle
output_path=frozen_model.opt.circle
generate_profile_data=False

[one-quantize]
input_path=frozen_model.opt.circle
output_path=frozen_model.quantized.circle
input_data=./../images_ds.h5

[one-codegen]
backend=tv2
command=-o frozen_model.tvn --DSP-quota 64k ./frozen_model.quantized.circle
```

And run command:
`onecc -C frozen_model.cfg`

that outputs:

```
Recording 0'th data
Recording 1'th data
...
Recording 98'th data
Recording 99'th data
Recording finished. Number of recorded data: 100
tv2-compile: ERROR: Something goes wrong during compilation
```

**Comment by lemmaa** [comment]
@lstomy , tv2 backend is not publicly available. In other words, it is not open source. Please inquire through the relevant internal repo. :)

**Comment by lstomy** [comment]
@lemmaa , Oh, okay I will follow your guideline. Thanks ^^)
