### ISSUE TITLE
[luci] Port ConnectNode visitor to service module

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#8724]
## What

Let's port `ConnectNode` visitor to `service` module.

## Why

I'm working on #8170 and the logic that clones and connects nodes is needed. Cloning nodes can be done with `service` logic but there is no logic that connects them, which is in `partition` module. That seems good to be ported to `service`.

Related: #8170

**Comment by mhs4670go** [comment]
@seanshpark Do you think it is feasible?

**Comment by seanshpark** [comment]
is there any problem using `luci/partition` as-is ?

**Comment by mhs4670go** [comment]
@seanshpark No, I just thought `service` module is for general usage. Maybe we proceed as it is first, and if a similar situation repeats, then port it to `service`?

**Comment by seanshpark** [comment]
OK, please proceed with current modules. I'll investigate migration of `ConnectNode` to service module.
Please leave comments here if you have any difficulties.

**Comment by mhs4670go** [comment]
@seanshpark As of now, I can't use current `ConnectNode` because it isn't public..

**Comment by seanshpark** [comment]
Please go with 1 as of now.
