### ISSUE TITLE
Compiler FE: Upgrade packages

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#8732]
To use latest packages with model import, we have to upgrade our execution environments
- [x] python 3.8 (or higher for using Tensorflow 2.7.0 or higher) for Ubuntu 18.04

And the packages
- [x] TensorFlow 2.8.0
- [x] ONNX-TF 1.10.0
- [x] ONNX 1.11.0
- [x] ONNERUNTIME 1.11.0

And some module(s)
- [x] introduce `mio-tflite280` and revise to use this

**Comment by seanshpark** [comment]
From https://github.com/Samsung/ONE/issues/7942#issuecomment-1056682307

**Comment by seanshpark** [comment]
Current onnx-tensorflow version of 1.10.0
```
tensorflow==2.8.0
onnx==1.10.2
```

**Comment by seanshpark** [comment]
## Upgrade to use python 3.8

### For Ubuntu 18.04

- explicit install of python3.8 is required
- need to use `python3.8`
- `common-artifacts` venv preparation needs update
- `infra/docker/bionic/Dockerfile` needs update
- CI needs update with Docker image
- ...

**Comment by seanshpark** [comment]
local PRESET build test fails a lot -_-;

```
one-build_003.test FAILED
one-build_006.test FAILED
one-build_007.test FAILED
one-build_008.test FAILED
one-build_009.test FAILED
one-build_011.test FAILED
one-build_012.test FAILED
one-build_013.test FAILED
one-build_neg_006.test FAILED
one-import-onnx_001.test FAILED
one-import_005.test FAILED
one-import_006.test FAILED
one-quantize_001.test FAILED
one-quantize_003.test FAILED
one-quantize_004.test FAILED
one-quantize_neg_004.test FAILED
one-quantize_neg_009.test FAILED
one-quantize_neg_010.test FAILED
one-quantize_neg_011.test FAILED
one-quantize_neg_012.test FAILED
one-quantize_neg_014.test FAILED
onecc_003.test FAILED
onecc_006.test FAILED
onecc_007.test FAILED
onecc_008.test FAILED
onecc_009.test FAILED
onecc_011.test FAILED
onecc_012.test FAILED
onecc_016.test FAILED
onecc_018.test FAILED
onecc_019.test FAILED
onecc_neg_006.test FAILED
rawdata2hdf5_001.test FAILED
33 TESTS FAILED
```

**Comment by seanshpark** [comment]
```
$ one-quantize -C one-build_003.cfg
record_minmax: ERROR: The input data file does not contain any record.
```
um?

**Comment by seanshpark** [comment]
Another test
- run `prepare_test_materials.sh` with python3.6
- update to python3.8
- run test
```
one-build_011.test FAILED
one-build_neg_006.test FAILED
one-import-onnx_001.test FAILED
one-import_005.test FAILED
one-import_006.test FAILED
onecc_008.test FAILED
onecc_011.test FAILED
onecc_016.test FAILED
onecc_neg_006.test FAILED
9 TESTS FAILED
```

**Comment by seanshpark** [comment]
> check internal CI is working OK with python 3.8; need to see new with new release

--> check internal CI after #8825 lands

**Comment by hseok-oh** [comment]
I've fixed title's typo. (Comiler -> Compiler)

**Comment by seanshpark** [comment]
done for now
