### ISSUE TITLE
[Compiler FE] Convert dynamic batch to single batch

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#8739]
## What

Let's implement an option to convert a model with a dynamic batch size to a model with a single batch.

For example,

```
onecc optimize --dynamic_batch_to_single_batch -i dynamic.circle -o single.circle
```

## Why

The option will

1. enable quantization of the model
2. allow the model to be run on backends that do not support dynamic shapes

**Comment by seanshpark** [comment]
`dynamic batch size`:  where shape of input is like `(-1, 224, 244, 3)` where -1 is unknown(dynamic) batch size.

**Comment by jinevening** [comment]
More specifically, `shape_signature` is like (-1, 224, 224, 3). The below case is possible

shape: (1, 224, 224, 3)
shape_signature: (-1, 224, 224, 3)

**Comment by jinevening** [comment]
Hmm.. there exist consistent needs for this feature from our customers.. I think it's time to support it.

**Comment by jinevening** [comment]
This enables quantization of edgetpu MV1 model in MLPerf.

https://github.com/Samsung/ONE/pull/10974#issuecomment-1619517461

**Comment by jinevening** [comment]
All done.
