### ISSUE TITLE
[onert] Introduce IR for prebuilt binary

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#8759]
### What?

Let's introduce runtime internal IR for binary and related information.

### Why?

As a first step to load prebuilt binary, we can introduce IR. Then we can split work item as `loader` and `backend`.

Draft: #7501

@chunseoklee @glistening

**Comment by glistening** [comment]
@hseok-oh, @chunseoklee Do you want to introduce a somewhat generic binary format? I was thinking of some npu architecture specific prebuilt binary like `.tvn`. If it is going to support various type of prebuilt binary? How will you identify the binary is for what architecture?

**Comment by glistening** [comment]
@hseok-oh, @chunseoklee May I assume the draft code in #7501 is a candidate for tizen m1 release? Or will we design something different in #7501? Could you please provide more details what the below sentence means?

> As a first step to load prebuilt binary, we can introduce IR. Then we can split work item as loader and backend.

**Comment by hseok-oh** [comment]
I don't think #7501 's loader is final candidate, but IR sepc is usable anyway. #7501 don't have backend, and loader is not called on runtime frontend (it looks just prototype implementation).

**Comment by hseok-oh** [comment]
Handled on #8795
