### ISSUE TITLE
Compiler FE: deprecate common_artifacts venv_1_13_2

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#8772]
As we can use `venv_2_6_0` for existing modules using `venv_1_13_2` we can upgrade and deprecate `venv_1_13_2`

**Comment by seanshpark** [comment]
From #8767

**Comment by seanshpark** [comment]
@mhs4670go , any comments?

**Comment by mhs4670go** [comment]
@seanshpark I'm not sure but I removed `venv_1_13_2` and tested it. It passed successfully. I think it is okay to do that.

**Comment by seanshpark** [comment]
done
