### ISSUE TITLE
[luci-interpreter] Support ExpandDims op

### ISSUE THREAD

**Issue by BalyshevArtem** [Samsung/ONE#8781]
## What

Let's support ExpandDims operation in luci-interpreter.

## Why

From https://github.com/Samsung/ONE/issues/7598#issuecomment-1082535327 there are some models with ExpandDims op. To measure the result we need this op in luci interpreter.

**Comment by seanshpark** [comment]
@BalyshevArtem , I've reopened this issue to inform you that we can test luci-interpreter kernel by this change.
```diff
diff --git a/compiler/common-artifacts/exclude.lst b/compiler/common-artifacts/exclude.lst
index 9046e3610..1c4015631 100644
--- a/compiler/common-artifacts/exclude.lst
+++ b/compiler/common-artifacts/exclude.lst
@@ -38,11 +38,6 @@ tcgenerate(Cos_000)
 tcgenerate(DepthwiseConv2D_001) # runtime doesn't support dilation
 tcgenerate(DepthwiseConv2D_003) # runtime doesn't support dilation
 tcgenerate(DepthwiseConv2D_U8_001)  # luci-interpreter doesn't support channel-wise quantization yet
-tcgenerate(ExpandDims_000)
-tcgenerate(ExpandDims_001)
-tcgenerate(ExpandDims_002)
-tcgenerate(ExpandDims_003)
-tcgenerate(ExpandDims_004)
 tcgenerate(FakeQuant_000) # runtime and luci-interpreter doesn't support yet
 tcgenerate(Fill_000)
 tcgenerate(Fill_001)
```
I think not all unit test models pass. Can you check this?

**Comment by seanshpark** [comment]
> I am actually don't understand why there is no shapes and how we can handle with it. Is it okay, or maybe we should add shapes here?

Thanks for checking :)
I'll look on history why the models are like as is and I think there was some reason for this.

**Comment by seanshpark** [comment]
#1564 is the PR for `ExpandDims_001` and `ExpandDims_002`
Related issue was #1561 and #1562

**Comment by seanshpark** [comment]
@BalyshevArtem , I'm not sure but there was some internal or public model that gave us this strange circle model. If you're not sure for this then we can leave `001` and `002` exist in exclude list.

**Comment by BalyshevArtem** [comment]
Let's leave `001` and `002` in exclude list :)

**Comment by seanshpark** [comment]
Closing as PR is posted. I'm sorry if you planned to post the change.
