### ISSUE TITLE
[onert] Prepare nnpackage for trix-engine backend

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#8784]
### What?

Let's define nnpackage spec for trix-engine binary and example package: MobileNet.

### Why?

We need to decide nnpackage spec for loader implementation. And we need example package for test.

**Comment by hseok-oh** [comment]
Please give comment about below example

```
{
  "major-version" : "1",
  "minor-version" : "2",
  "patch-version" : "0",
  "configs"     : [ "config.cfg" ],
  "models"      : [ "example.ext" ],
  "model-types" : [ "trix" ]
}
```

- Version update: 1.2.0 (need version up?)
- Add model-type: "trix" (or different name? general binary?)

@chunseoklee @glistening

**Comment by glistening** [comment]
- For what `config.cfg` is necessary?
- `models`
  - I thought `example.tvn`.
- `model-types`
  - I thought `tvn` since I don't have experience except for `tvn`. But I think the name of `trix-engine` implies it supports all trix (including tvn). Thus, it may be okay to use `trix` for model-type name.
- I think 1.2.0 would be good since it now support one more [`model-types`](https://github.com/Samsung/ONE/blob/master/nnpackage/spec/10_packaging_and_manifest.md#model-types).

**Comment by chunseoklee** [comment]
> For what config.cfg is necessary?

config.cfg is used to provide user-specified config. For example, user provides backend  assignment via config.cfg.

**Comment by hseok-oh** [comment]
`configs` field is introduced on version 1.1.0.

**Comment by hseok-oh** [comment]
>I thought tvn since I don't have experience except for tvn. But I think the name of trix-engine implies it supports all trix (including tvn)

In fact, I prefer to naming `tvn`, not `trix` for `model-type` field.

**Comment by glistening** [comment]
> `configs` field is introduced on version 1.1.0.

I know. I am asking what information from `config.cfg` is necessary for `trix`.

**Comment by glistening** [comment]
> > For what config.cfg is necessary?
> 
> config.cfg is used to provide user-specified config. For example, user provides backend assignment via config.cfg.

Ah, I understood. If we use `.tvn`, we would not require `config.cfg` to specify backend.

**Comment by chunseoklee** [comment]
> If we use .tvn, we would not require config.cfg to specify backend

For single tvn file, yes for now.

**Comment by glistening** [comment]
> > If we use .tvn, we would not require config.cfg to specify backend
> 
> For single tvn file, no(not require) for now.

Yes, I mentioned on the assumption of a single tvn.

**Comment by hseok-oh** [comment]
Daily test uses nnpackage for trix backend.
