### ISSUE TITLE
[onert] Backend for Trix 

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#8788]
Let's implement trix backend on onert.

Here is a example PR when we introduce ruy backend : https://github.com/Samsung/ONE/pull/5067

**Comment by chunseoklee** [comment]
cc @glistening, @chunseoklee, @dayo09

**Comment by jyoungyun** [comment]
### References

* [Backend API guideline](https://github.com/Samsung/ONE/blob/master/docs/runtime/backend-api.md)

### ToDo
[x] Introduce TRIX Engine(#8788)
[ ] Add "Trix" directory for trix backend
...
???

**Comment by chunseoklee** [comment]
Closed by done
