### ISSUE TITLE
[onert] Increase function coverage

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#8935]
### What?

Let's increases function coverage

### Why?

Function coverage is 78%. We need function coverage over 80%.

From https://github.com/Samsung/ONE/issues/8775#issuecomment-1098956890

- Hit/Total: 4672/5920 - 78%
  - Need more 120 hit
  - Major miss directory: `compute/cker/include/cker/operation`
    - 370/604 61.3% (line coverage: 3105/3582 86.7%)
    - `Comparison.h`
      - Line coverage 100% (79/79), Function coverage 47.6% (80/168)
      - Maybe `template` 's type issue

**Comment by hseok-oh** [comment]
Today function coverage `compute/cker/include/cker/operation/Comparison.h`

47.6% (80/168) -> 56% (94/168) by #8901

We need more comparision OP tests like #8901

- [ ] `NotEqual`
- [ ] `Less`
- [ ] `LessEqual`
- [ ] `Greater`
- [ ] `GreaterEqual`

**Comment by hseok-oh** [comment]
cc/ @glistening

**Comment by glistening** [comment]
@hseok-oh https://github.com/Samsung/ONE/pull/8901#issuecomment-1099901074

**Comment by chunseoklee** [comment]
cc @jyoungyun since this issue related to TEM

**Comment by glistening** [comment]
I will do `Less`, `LessEqual` ,... If anyone is interested in this task, please start from bottom line (e.g. `GreaterEqual`), and let me know.

**Comment by chunseoklee** [comment]
At the time of writing, we have 78.4% function coverage (4,719/6,019).
To achieve 80% function coverage, 4816(6019*0.8)-4719 = 97 more functions should be covered.

**Comment by glistening** [comment]
I will add more test in `tests/nnfw_api/src/one_op_tests/Cast.cc`.

**Comment by glistening** [comment]
As of 1:38 PM in KST, fn coverage is 4752/6019 (79%). Let's see after #8954 and `Cast`.

**Comment by glistening** [comment]
We may copy `compiler/angkor/src/ADT/tensor/IndexEnumerator.test.cpp`  to cover some of `runtime.libs.misc.include.misc.tensor`. (e.g. `IndexEnumerator.h` (_**0 of 20**_) and `Shape.h` (**_0 of 5_**)). This is basically same structure to make use of tensorflow lite's tensor structure.

**Comment by chunseoklee** [comment]
with 0c1a1f6c6952baf863a27220f89418bda2d30401, Func coverage finally reach to 80% !

**Comment by hseok-oh** [comment]
Today function coverage: 79.8%

```
02:28:59  Writing directory view page.
02:28:59  Overall coverage rate:
02:28:59    lines......: 83.3% (29251 of 35134 lines)
02:28:59    functions..: 79.8% (4864 of 6097 functions)
```

**Comment by glistening** [comment]
> Today function coverage: 79.8%
> ...
> 02:28:59    functions..: 79.8% (4864 of 6097 functions)

Yes, I also checked the number is same with https://github.com/Samsung/ONE/issues/8935#issuecomment-1102419991. We need about 15 functions more. I am waiting for score after #8971 and #8972.

**Comment by hseok-oh** [comment]
#8963 merged

```
10:34:20  Overall coverage rate:
10:34:20    lines......: 83.3% (29254 of 35136 lines)
10:34:20    functions..: 79.8% (4866 of 6097 functions)
```

**Comment by hseok-oh** [comment]
Now 81.2%

```
11:53:38  Overall coverage rate:
11:53:38    lines......: 83.4% (29332 of 35151 lines)
11:53:38    functions..: 81.2% (4991 of 6144 functions)
```

**Comment by hseok-oh** [comment]
https://github.com/Samsung/ONE/pull/8972#discussion_r853100805

We need to build gtest binary with coverage build option to cover header-implemented code (ex. template)

cc/ @seanshpark

**Comment by hseok-oh** [comment]
Done
