### ISSUE TITLE
Refactor: circledump and circle-tensordump

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#8997]
_circledump_ and _circletensordump_ have common looking codes, where our analysis tool warns with ducplicate codes.

let's refactor this... what can be possible;

(1) make a common library `libcircledump` as a seperate module
(2) make a common library `libcircledump` inside  `circledump` and let `circle-tensordump` use it
(3) merge `circle-tensordump` into `circle-dump` but with two executables

I think start with (2) seems nice, then goto (1) later.

**Comment by seanshpark** [comment]
related #8870

CC @mhs4670go

**Comment by mhs4670go** [comment]
@seanshpark Well, seems to me that there are not that things to be a common,, =ㅁ= If they can be, what you think is a good option I think.

**Comment by seanshpark** [comment]
> seems to me that there are not that things to be a common

Reader.cpp and Reader.cpp have common things :)

**Comment by seanshpark** [comment]
I think can introduce `mio::circle::Reader` in `mio-circle04` for this.

**Comment by seanshpark** [comment]
`circle-inspect` also has `Reader`

**Comment by seanshpark** [comment]
done
