### ISSUE TITLE
[luci-eval-driver] major defect detected

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#9043]
Our analysis tool reports;

> Return value of a function 'circle::GetModel' is dereferenced at EvalDriver.cpp:59 without checking for null, but it is usually checked for this function (6/7).

analysis ID: 1290146

**Comment by chunseoklee** [comment]
Note that it is not urgent one for 1.20.0 release.

**Comment by seanshpark** [comment]
close as change landed
