### ISSUE TITLE
[onert/acl] ACL debug build fail on 20.04

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#9085]
ACL debug build for armv7l linux fail on my local PC (x64 ubuntu 20.04) with below message.

```
armv7a-linux.debug/src/core/CL -Ibuild/armv7a-linux.debug/src/core/CL -Ibuild/armv7a-linux.debug/build/armv7a-linux.debug/src/core -Ibuild/armv7a-linux.debug/src/core -Ibuild/armv7a-linux.debug/src/core/NEON/kernels/convolution/common -Isrc/core/NEON/kernels/convolution/common -Ibuild/armv7a-linux.debug/src/core/NEON/kernels/convolution/winograd -Isrc/core/NEON/kernels/convolution/winograd -Ibuild/armv7a-linux.debug/src/core/NEON/kernels/convolution/depthwise -Isrc/core/NEON/kernels/convolution/depthwise -Ibuild/armv7a-linux.debug/src/core/NEON/kernels/assembly -Isrc/core/NEON/kernels/assembly -Ibuild/armv7a-linux.debug/arm_compute/core/NEON/kernels/assembly -Iarm_compute/core/NEON/kernels/assembly src/core/NEON/kernels/arm_conv/pooling/pooling_u8q.cpp
In file included from src/core/NEON/kernels/arm_gemm/merges/list.hpp:24,
                 from src/core/NEON/kernels/arm_gemm/mergeresults.cpp:98:
src/core/NEON/kernels/arm_gemm/merges/a32_merge_float_8x6.hpp: In function ‘void arm_gemm::MergeResults(Tout*, const Tin*, int, int, int, int, int, const Tout*, arm_gemm::Activation, bool) [with unsigned int twidth = 8; unsigned int height = 6; bool sve = false; Tin = float; Tout = float]’:
src/core/NEON/kernels/arm_gemm/merges/a32_merge_float_8x6.hpp:306:22: error: ‘asm’ operand has impossible constraints
  306 |                     );
```

But success on docker image `nnfw/one-devtools:focal`, I'm using docker container for ACL debug build. (so it's not critical issue now)

Installed cross build tools on local PC

```
$ apt list | grep arm- | grep install

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

binutils-arm-linux-gnueabihf/focal-updates,focal-security,now 2.34-6ubuntu1.3 amd64 [installed,automatic]
cpp-9-arm-linux-gnueabihf/focal-updates,focal-security,now 9.4.0-1ubuntu1~20.04.1cross2 amd64 [installed,automatic]
cpp-arm-linux-gnueabihf/focal,now 4:9.3.0-1ubuntu2 amd64 [installed,automatic]
g++-9-arm-linux-gnueabihf/focal-updates,focal-security,now 9.4.0-1ubuntu1~20.04.1cross2 amd64 [installed,automatic]
g++-arm-linux-gnueabihf/focal,now 4:9.3.0-1ubuntu2 amd64 [installed]
gcc-9-arm-linux-gnueabihf-base/focal-updates,focal-security,now 9.4.0-1ubuntu1~20.04.1cross2 amd64 [installed,automatic]
gcc-9-arm-linux-gnueabihf/focal-updates,focal-security,now 9.4.0-1ubuntu1~20.04.1cross2 amd64 [installed,automatic]
gcc-arm-linux-gnueabihf/focal,now 4:9.3.0-1ubuntu2 amd64 [installed,automatic]
qemu-arm-static/unknown,now 1.6.0rc3-tizen20200617 amd64 [installed,automatic]
```

**Comment by hseok-oh** [comment]
g++ version on docker image `nnfw/one-devtools:focal`: 9.3 

```
g++-9-arm-linux-gnueabihf/focal-updates,focal-security,now 9.3.0-17ubuntu1~20.04cross2 amd64 [installed,automatic]
```

g++ version on local PC: 9.4

```
g++-9-arm-linux-gnueabihf/focal-updates,focal-security,now 9.4.0-1ubuntu1~20.04.1cross2 amd64 [installed,automatic]
```

Local's `g++` is latest version. When I try to upgrade to latest package by `apt update && apt upgrade` on docker container, I met same error message.

**Comment by hseok-oh** [comment]
I checked on g++10, and passed.

**Comment by hseok-oh** [comment]
I found bug in `infra/docker/focal/Dockerfile` and `infra/docker/bionic/Dockerfile`, but we can't update dockerfile until this issue is resolved. If we update dockerfile, updated docker image will have `arm-linux-gnueabihf-g++` 9.4 version.

**Comment by hseok-oh** [comment]
Other build issue: XNNPack (found from https://review.tizen.org/gerrit/gitweb?p=platform/upstream/tensorflow2.git;a=commit;h=10eaa7ff3c7d1e5e388a27847e82141c71613e69)

`https://github.com/google/XNNPACK/issues/1465`

We don't meet this issue yet. But may meet someday.

**Comment by hseok-oh** [comment]
We used ACL debug build because we need debugging ACL internal. But now we don't debug ACL, and we may debug ACL on very rare case. 

I suggest changing ACL build as release type on default, and allow debug build on special case.

@ragmani @chunseoklee Can you give your opinion about this?

**Comment by chunseoklee** [comment]
> I suggest changing ACL build as release type on default, and allow debug build on special case.
@ragmani @chunseoklee Can you give your opinion about this?

No objection.

**Comment by ragmani** [comment]
>> I suggest changing ACL build as release type on default, and allow debug build on special case.
@ragmani @chunseoklee Can you give your opinion about this?

> No objection. 

Me too.

**Comment by hseok-oh** [comment]
Resolved by using release
