### ISSUE TITLE
[nnpackage] Packaging partitioned model

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#9116]
### What?

Let's decide spec for partitioned model and support partitioned model packaging on `model2nnpkg.sh` (or new script?).

### Why?

We need to support partitioned model packaging for trix + cpu mixed backend. 

It may be partitioned by circle-partitioner (https://github.com/Samsung/ONE/tree/master/compiler/circle-partitioner) with additional compilation step for binary generation.

**Comment by seanshpark** [comment]
FYI, `compiler/one-cmds/one-partion`, which is one-cmds wrapper of `circle-partitioner` will be used as user command tool.

**Comment by hseok-oh** [comment]
TODO

### NNPackage Spec

- [ ] Connection information

### model2nnpkg.sh

- [ ] Connection information input
- [ ] Multiple models input

Enough to represent partitioned model for npu + cpu (or other backend) ?

Then we can go next step - runtime loader

cc/ @chunseoklee @glistening @seanshpark

**Comment by seanshpark** [comment]
Q) what is `Multiple models input` ?

**Comment by hseok-oh** [comment]
>Q) what is Multiple models input ?

Multiple models: Model files to packaging. Model file type can be `circle`, `tflite`, or `tvn`.
input: `model2nnpkg.sh` 's input

If we use `one-partition` (and one of model file is compiled to npu binary), then we need to package multiple model files.

**Comment by hseok-oh** [comment]
I've updated item
- Connection information input -> Support connection information packaging
- Multiple models input -> Support multiple model files packaging

**Comment by glistening** [comment]
I will take a look with concrete example -- perhaps [Net_InstanceNorm_003.zip](https://github.com/Samsung/ONE/files/8608844/Net_InstanceNorm_003.zip). But it is float32 model.

@hseok-oh, @chunseoklee What models do you use as example model?

**Comment by chunseoklee** [comment]
> concrete example 

You mean a set of partitioned circle and partitioned tvn from a source circle file ? Since there is no tool for that. We need to generate them manually.  

> What models do you use as example model?

For non-RNN case, https://github.com/Samsung/ONE/files/8608844/Net_InstanceNorm_003.zip is OK for me.

For RNN case, maybe https://github.com/Samsung/ONE/files/8368702/gru.zip ?

**Comment by glistening** [comment]
As I understand, partitioning is mainly for npu and cpu. `ONERT` already is capable of running multiple backends (cpu and gpu) a few years ago. Thus I think,
- The two models need to be converted to q-circle since npu handles integer only.
  - Does anyone already has q-circle or know how to quantize these models?
- The two models are not for showing performance improvement by cpu + npu execution. They are representative models for simple sequential model and loop model.
  - Performance is not considered yet. Am I right?

**Comment by lemmaa** [comment]
> As I understand, partitioning is mainly for npu and cpu execution. `ONERT` is already capable of running multiple backends (cpu and gpu) a few years ago. 

I hope that partition support will equally consider multiple backends, such as CPU, GPU, and NPU, apart from ONERT's existing mixed-backend inference capabilities.

**Comment by glistening** [comment]
I think we need to update `onert` (`nnfw`) API also for multiple partitions (or models).

I am writing here because it is seemingly the root issue.

Q. is nnpkg going to support multiple models in general? Or partitioned models from a single source model only?

**Comment by hseok-oh** [comment]
>I think we need to update onert (nnfw) API also for multiple partitions (or models).

We have package loading API, input/output setting API, input/output count and info getting API. Could you explain which APIs are required on your scenario to use multiple model package?

**Comment by glistening** [comment]
I thought there is additional parameter to specify a model from multiple `models`, but after reading our API, I found that we don't have API that takes an index to models. Then, how we can select a model if an nnpackage have multiple models w/o connection information perhaps which means the models have no dependencies for each other.

Anyway, if we assume that nnpkg's inputs and outputs are specified in nnpackage spec perhaps by `conns`, we don't need to update API.

**Comment by glistening** [comment]
@hseok-oh 

> Q. is nnpkg going to support multiple models in general? Or partitioned models from a single source model only?

I asked the same question and got answer like https://github.com/Samsung/ONE/issues/9126#issuecomment-1134298290.
Do you also assume that `models` come from a single original model ?

**Comment by hseok-oh** [comment]
>I thought there is additional parameter to specify a model from multiple models, but after reading our API, I found that we don't have API that takes an index to models. Then, how we can select a model if an nnpackage have multiple models w/o connection information perhaps which means the models have no dependencies for each other.

I thought that user don't need to select model to set input and output. If user load multiple models in one package at once, API can return package level inputs and outputs info to user. So I thought I/O info can be independent with connection information.

For example, package has model A  (input: a_in1, a_in2 / output: a_out1) and B  (input: b_in1, b_in2 / output: b_out1), ordering is A - B with no connection, then package's input and output is (input: a_in1, a_in2, b_in1, b_in2 / output a_out1, b_out1). If there is connection between (a_out1 : b_in1), package's input and output is (input: a_in1, b_in2 / output b_out1).

**Comment by glistening** [comment]
Q. What does API will use inputs and outputs if nnpkg has multiple models and has no `conn` info?

I think we may always use the 1st model's inputs and outputs by default. It is the way we've chosen.
I don't remember all, but a few years ago, @chunseoklee and I thought we are going to extend API when multiple models use case become more clear.

**Comment by glistening** [comment]
> 

You and I wrote at the same time. : ) There seem at least two options for multiple models w/o `conn`.

@hseok-oh Then, what model will be executed after loading multiple models if they have no conn info?

**Comment by hseok-oh** [comment]
>Then, what model will be executed after loading multiple models if they have no conn info?

I didn't think that user can select inference on model level. I thought API support package level inference, so multiple model package inference may done at once.

**Comment by glistening** [comment]
I am not saying that the user need to select inference on model level. I am just worrying that unclear point in our spec. I am also not sure that we need to give a way for user to select inference on model level when given nnpk has no conn information.

**Comment by hseok-oh** [comment]
One remain item is `Support connection information packaging`. I'll close this issue, and remain item will be handled on different issue.
