### ISSUE TITLE
[nnpackage] Extend manifest for connection information

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#9123]
To represent connection information between multiple models, we need additional field to find connection information file.
It will be essential to load partitioned models.

Example) Additional "connection" property

```
{
  "major-version" : "1",
  "minor-version" : "2",
  "patch-version" : "0",
  "models"      : [ "example.cpu.circle", "example.trix.tvn" ],
  "connection" : "example.conn.ini",
  "model-types" : [ "circle", "tvn" ]
}
```

Connection information may be generated by `one-partition` command (`circle-partition`)
- Connection property is not list: maybe only one file for package

@chunseoklee @glistening Please give any opinion about this

cc/ @seanshpark

**Comment by hseok-oh** [comment]
Additional consideration: multiple models packaging without connection information
- Will we allow multiple model packaging without connection information?
- What is usage of multiple models packaging without connection information?

**Comment by chunseoklee** [comment]
> @chunseoklee @glistening Please give any opinion about this

No objection.

**Comment by hseok-oh** [comment]
Based on this suggestion, I've made draft: #9129

**Comment by glistening** [comment]
- At first, I thought embedding the connection info in `manifest` w/o introducing another file. But it may be okay.
- I prefer `model-conns` or `model-edges` over `connection`. I would like to add prefix this field is about `model`.

**Comment by glistening** [comment]
> * Will we allow multiple model packaging without connection information?

Yes

>   * If we allow, what is usage of multiple models packaging without connection information?

I always think `nnpkg` as packages to pack several things to use the models.
It can contain multiple models, and the models may be independent to each other.

**Comment by hseok-oh** [comment]
>At first, I thought embedding the connection info in manifest w/o introducing another file. But it may be okay.

I didn't embed connection info because we may need to change info spec yet. By using info file, we can update connection info file spec without updating packaging script. If we ready before official support, we can change to embed in `manifest`.

**Comment by hseok-oh** [comment]
>I prefer model-conns or model-edges over connection. I would like to add prefix this field is about model.

I changed to `model-connect` on draft #9129

**Comment by chunseoklee** [comment]
#9129 do not contain an example of connection between circle and tvn models. 
Will you add that case into PR before merging ? or make another commit for tvn ?

**Comment by glistening** [comment]
I also would like to see big picture and check more before merging #9129.

- What is the format in connection info file? (whether embedded or not)
  - same format with one-partition tool's *.conn ?
  - something else?

- Also, I would like to check it may work for several possible cases. Here I gathered some:
  - circle + tvn (e.g. tvn doesn't have string node name.)
    - https://github.com/Samsung/ONE/issues/9126#issue-1236796844
  - If we divide model on non-main subgraph, ...
    - https://github.com/Samsung/ONE/issues/9126#issuecomment-1128366645
  - loop
    - multiple subgraph
  - ...

**Comment by chunseoklee** [comment]
> Also, I would like to check it may work for several possible cases. Here I gathered some:

PR does not cover listed cases. Thus, we should discuss more and define something new

**Comment by hseok-oh** [comment]
https://github.com/Samsung/ONE/pull/9129 is draft, and I don't want to merge until we support multi model packaging and loading officially.

**Comment by hseok-oh** [comment]
I made draft to construct pipeline from `compiler partitioning` -> `packaging` -> `runtime loading`. After deciding small example package, we can construct pipeline for small example, then expand supporting case on each step. So draft doesn't consider tvn compile, connect info, subgraph, etc.

**Comment by hseok-oh** [comment]
Let's discuss issue about npu backend and subgraph at #9126
