### ISSUE TITLE
[one-quantize] Evaluate quantized model

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#9124]
## What

Let's implement an option to evaluate quantized model

![image](https://user-images.githubusercontent.com/5449554/168549057-659c9322-93d0-4eaf-91fc-24070c78f04b.png)

I'm thinking about the interface as follows.

```
[one-quantize]
input_path=test.circle
output_path=test.q.circle
input_data=representative.h5
test_data=test.h5
```

If `test_data` option is given, one-quantize will run the data with the fp32 model and the quantized model, and print the evaluation results (e.g., MAE (Mean Absolute Error), MPEIR (Mean Peak Error to Interval Ratio)).

CC @Samsung/one_quantizer

**Comment by seanshpark** [comment]
FYI using dark theme doesn't show the lines or text in the image.

**Comment by jinevening** [comment]
I've added white background :)

**Comment by jinevening** [comment]
Interface will be updated as below. (from https://github.com/Samsung/ONE/pull/9143#issuecomment-1132282943)

---

The current interface (using `test_data`) is simple but limited. For example, we may not give `test_data` to use random data for simple testing. The current interface cannot support such a scenario.

I'd like to update the interface as below.

```
[one-quantize]
input_path=..
output_path=..
quantized_dtype=..
evaluate_result=True
test_data=..
print_mpeir=True
print_top1_match=True
print_top5_match=True
```

Evaluation is conducted when `evaluate_result` is True. And more detailed control would be possible for test_data or metrics.

**Comment by seanshpark** [comment]
@jinevening , just to be sure; is current change you are doing is backward compatible?

**Comment by jinevening** [comment]
> is current change you are doing is backward compatible?

I think so. In the viewpoint of interface, I'm not changing the existing interface but just adding new options.

In the viewpoint of modules, `circle-eval-diff` uses modules already used by other tools (record-minmax, circle-quantizer).

**Comment by jinevening** [comment]
Done.
