### ISSUE TITLE
[one-cmds]  onecc look for one-build

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#9125]
Our internal CI is changing to use `onecc` from `one-build`.
- that is, our main tool is going to be `onecc` at last
- we have shared `.cfg` files with `one-build` for our customers and the source files now has changed to `onecc`
- it would be greate if _onecc_ also checks for `one-build` if `onecc` section is absent
   - with a warning to upgrade

**Comment by seanshpark** [comment]
@mhs4670go , are you interested in this?

**Comment by mhs4670go** [comment]
@seanshpark I think it is a good idea. Let me do this work:)

**Comment by seanshpark** [comment]
CC @lemmaa

**Comment by seanshpark** [comment]
will check with release packge.

**Comment by seanshpark** [comment]
@mhs4670go this is the result
```
$ onecc -C 1605145760-q8.cfg
/usr/bin/onecc:154: UserWarning: [one-build] section will be deprecated. Please use [onecc] section.
  warnings.warn("[one-build] section will be deprecated. Please use [onecc] section.")
```

I think this would be nice.
> UserWarning: [one-build] section will be deprecated. Please use [onecc] section.

**Comment by seanshpark** [comment]
done
