### ISSUE TITLE
[nnpackage] Support multiple model packaging on model2nnpkg.sh

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#9155]
### What?

Let's support multiple model packaging on `model2nnpkg.sh` script as experimental feature.

### Why?

Currently, `model2nnpkg.sh` allows one model packaging only. But package spec allow multiple model. (It is independent with partitioned model)

We cannot use multiple model package on runtime yet, so let's support this feature as experimental.

**Comment by hseok-oh** [comment]
### How to get multiple model?

Option 1) All remain arguments are model files
```
./model2nnpkg.sh -o out model1.circle model2.circle
```

Option 2) Introduce new option for model files (ex. `-m`)
- If only one argument remain, last argument is model file (backward compatibility)

Option 2-1) All argument between option `-m` and new option are model files
```
./model2nnpkg.sh -m model1.circle model2.circle -o out
```
Option 2-2) Use option `-m` for each model file
```
./model2nnpkg.sh -m model1.circle -m model2.circle -o out 
```

### Package name

Option 1) Use 1st model file name if package name argument (option `-p`) is not passed 
Option 2) Always require package name argument if multiple model file

**Comment by hseok-oh** [comment]
PR #9167: 
- Model input: select option 1 - all remain arguments are model files
- Name: select option 1 - use 1st model file name if package name argument (option `-p`) is not passed

**Comment by glistening** [comment]
As I mentioned in https://github.com/Samsung/ONE/pull/9167#issuecomment-1135435386, I don't have clear idea and even I am not sure it is good to extend model2nnpkg.sh for multiple models support. When I first wrote `model2nnpkg.sh`, it is a tool for just a single model. I am thinking yet another tool for packaging multiple models and connection information, and nnpkg input/output information into a nnpkg. It may get the input not from command line, but from a kind of configurations or the output from other tool (e.g. `circle-partitioner`). But I would like to decide after getting our assumption and requirements and so on. I hope it can be more specific after on-coming discussions (including offline).

**Comment by glistening** [comment]
See https://github.com/Samsung/ONE/pull/9167#discussion_r881066114 and so on for discussion and conclusion about how to get multiple configs.

For short,
```
$ model2nnpkg -c c1 c2 c3 -m m1 m2 m3
```
