### ISSUE TITLE
Experiment for Mixed-precision Quantization (MPQ) on MobileNet V1

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#9166]
This issue shares the experimental result that shows possible advantages of mixed-precision quantization (MPQ) feature of our quantizer.

We quantized _MobileNet V1_ with different quantization configurations and measured accuracy (top-k match with the original fp32 model) and inference latency on the Samsung's vision NPU. Test data was 10 images randomly selected in the ImageNet dataset.

- Full s16: All layers (including weights and activations) are quantized into int16
- Full u8: All layers (including weights and activations) are quantized into uint8
- mixed: Layers are quantized into int16 by default while some are quantized into uint8. For example, `MobileNet V1` has 30 layers, so `u8 (26~)` indicates that layers (26\~30) are quantized into uint8 while layers (1\~25) are quantized into int16.

<img src=https://user-images.githubusercontent.com/5449554/170190617-3e7b6e92-293b-4622-9949-6a6c039dc568.png  width="475" height="385" />

The table shows that MPQ provides new choices between full s16 and full u8 quantization, enabling fine-grained control of the accuracy/performance/size of the quantized model. Users can select the best configuration that meets the app requirement.

For example, let's assume an app requires top-5 accuracy > 0.9 and inference latency < 8 ms. The below graph visualizes the requirement on the 2D space. Each point indicates the accuracy/latency of the configuration in the above table. We can find a valid configuration on the upper-left quadrant.

![image](https://user-images.githubusercontent.com/5449554/170190464-b92ebf38-3487-4a31-8da3-1a0587b3f1ce.png)

CC @Samsung/one_quantizer

**Comment by seanshpark** [comment]
FYI, for dark theme users, white background image would be helpful.

**Comment by jinevening** [comment]
@seanshpark I added white background.

**Comment by jinevening** [comment]
I close this issue as time has passed.
