### ISSUE TITLE
[one-cmds] Generate warning (or error) message for typo in config file

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#9172]
## What

Let's warn (or generate error) when typo exists in config file

## Why

Users can use config file with typos, but there is no warning or error. What I've seen is

wrong: `forward_reshape_to_unary_op`
right: `forward_reshape_to_unaryop`

wrong: `substitue_transpose_to_reshape`
right: `substitute_transpose_to_reshape`

**Comment by seanshpark** [comment]
FYI, both options are not used in our internal model zoo.

**Comment by jinevening** [comment]
> Some of our customers are using these options.

Yes. I posted this issue because I found those typos in the config files from multiple customers.
