### ISSUE TITLE
[onert] Support multiple model nnpkg (loader, ir)

### ISSUE THREAD

**Issue by glistening** [Samsung/ONE#9206]
Let's support multiple models nnpkg.

- [x] Create a sample multiple model nnpkg
- [x] IR
- [x] Loader
- [x] nnfw_session 

This issue will focus on **frontend** (loader and IR building) of onert.
**Backend** of onert (e.g. executor) will be handled in other issue by other members.
_~Perhaps onert **API** will be covered in another issue by discussing together.~_ ←I have to cover API to check the feasibility of extended IR.

## Related
- #6274 : last year draft by @hseok-oh

**Comment by glistening** [comment]
## Create a sample multiple model nnpkg

I created the prerequisite models using mobilenet v1 uint8 model.

Here is [mv1.mm.zip](https://github.com/Samsung/ONE/files/8850805/mv1.mm.zip):
- mv1.01.circle  ( Conv2D - DepthwiseConv2D ) <sub> <I>I cannot upload screenshot. </I></sub>
  - model by selecting first two ops from mobilnet v1 q8 model
  - `python tools/tflitefile_tool/select_operator.py mobilenet_v1.220207.quantized.random.channel.uint8.circle <( echo 0-1 ) 
mv1.01.tflite`
  - `build/release/nncc/compiler/tflite2circle/tflite2circle mv1.12.{tflite,circle}`
- mv1.0.circle ( Conv2D )
  - model by selecting first op from mv1.01.circle
- mv1.1.circle ( DepthwiseConv2D )
  - model by selecting second op from mv1.01.circle
- mv1.1.tvn ( I don't upload this file. )
  - model by compiling mv1.1.circle

I will add more (e.g. `MANIFEST`) later.

**Comment by glistening** [comment]
I am trying to complete `MANIFEST`.

### A. Combination of #9129 and #9126

#### MANIFEST

Provide a separate json for connection via _**model-connect**_
```
{
  "major-version" : "1",
  "minor-version" : "2",
  "patch-version" : "0",
  "configs"       : [  ],
  "models"        : [ "mv1.0.circle", "mv1.1.tvn" ],
  "model-types"   : [ "circle", "tvn" ],
  "model-connect" : "conn.json"
}
```
#### conn.json
Use _**source**_ and _**conn**_ fields.
```
{
  "source" : {
    "inputs" : [ "0:0:0" ],
    "outputs" : [ "0:0:1"]
  },
  "conn" : [
    { from: "0:0:1", to: [ "1:0:0" ] } ,
  ]
}
```

### B. Embedded
```
{
  "major-version" : "1",
  "minor-version" : "2",
  "patch-version" : "0",
  "configs"       : [  ],
  "models"        : [ "mv1.0.circle", "mv1.1.tvn" ],
  "model-types"   : [ "circle", "tvn" ],
  "model-inputs"  : [ "0:0:0" ],
  "model-outputs" : [ "1:0:0" ],
  "model-connect" : { from: "0:0:0", to: [ "1:0:0" ] }
}
```

**Comment by hseok-oh** [comment]
```diff
-  "model-connect" : { from: "0:0:0", to: [ "1:0:0" ] }
+  "model-connect" : [ { from: "0:0:0", to: [ "1:0:0" ] } ],
```

models can have multiple connection.

**Comment by glistening** [comment]
The meaning of each functions and members needs to be checked and redefined in the midst of the possibility of multiple models in a session.

## Loader

### 3 Functions

- **load_circle_from_buffer**
  - It gets only a model file. There is no connection information. 
  - It will create a nnpkg with a single model  - 
- **load_model_from_modelfile**
  - It gets only either circle buffer. There is no connection information.
  - It will create a nnpkg with a single model
- **load_model_from_nnpackage**
  - It gets the path to nnpackage. It can get all information for multiple models.
  - `models`
  - connection info ( `pkg-inputs`, `pkg-outputs`, `model-connect`)
    - TBD
  - `configs`
    - per-model, different from global config as it is
    - will not considered at this moment)

**Comment by hseok-oh** [comment]
`load_model_from_modelfile`: load tflite file. for test only (unittest, `tflite_comparator`)
`load_circle_from_buffer`: read buffer directly. for test only(`nnfw_api_gtest`)
