### ISSUE TITLE
[circle-eval-diff] Support random and directory input

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#9224]
## What

Let's support random and directory input.

## Why

As of now, `circle-eval-diff` supports only hdf5 input data format. But sometimes, user want to run it without data set. And, directory input is needed as well.

**Comment by seanshpark** [comment]
> But sometimes, user want to run it without data set. 

Q) how is the test done without data set?

**Comment by mhs4670go** [comment]
@seanshpark Well, I thought test can be done because it is about comparing outputs of two model - output diff. But, after offline meeting with @jinevening, random input seems not to be needed because it is a bit useless because the random data has absolutely nothing to do with the data needed for quantization.
