### ISSUE TITLE
[one-cmds] TensorFlow Probability error

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#9240]
Error while loading TensorFlow for `one-import`

> ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.9; Detected an installation of version 2.8.0. Please upgrade TensorFlow to proceed.

**Comment by seanshpark** [comment]
There was protobuf issue and now tensorflow_probability ...

**Comment by seanshpark** [comment]
https://github.com/tensorflow/probability/releases

> 4 Hours ago, TensorFlow Probability 0.17.0

**Comment by hseok-oh** [comment]
@seanshpark Can we resolve issue https://github.com/Samsung/ONE/issues/9154#issuecomment-1149280718 by this?

**Comment by seanshpark** [comment]
> Can we resolve issue https://github.com/Samsung/ONE/issues/9154#issuecomment-1149280718 by this?

I'm not sure.
9154 error is strange. I could not find download failure but there seems to be problem with test material...

**Comment by seanshpark** [comment]
Patch seems working.
