### ISSUE TITLE
[onert] Map bulk operation to trix backend on compile phase

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#9246]
### What?

Let's map bulk operation to trix backend on operation mapping table as workaround. (like bcq operation)

### Why?

We don't have feature to pass configuration for each model. So we cannot pass backend mapping for each partitioned model yet.

We need to map bulk operation to trix backend without configuration until we ready to support passing configuration to runtime compiler for each partitioned model.

**Comment by chunseoklee** [comment]
closed by done
