### ISSUE TITLE
Implement NPU daemon

### ISSUE THREAD

**Issue by jyoungyun** [Samsung/ONE#9258]
# NPU daemon

### Role
- Optimal management of NPU HW from runtime point of view
- Share NPU HW efficiently with 3rd party

### Features
- Priority scheduling
- Core allocation
- Hardware abstraction layer

### Relationship with ONE-Runtime

<img src="https://user-images.githubusercontent.com/7223627/173320682-b1ede497-f417-4815-b30b-2f4e108abe45.png" width=500 />

### Architecture

_This architecture will develop as it is implemented._

<img src="https://user-images.githubusercontent.com/7223627/173491282-758351ae-caf7-46b6-8941-56f66b62455a.png" width=400 />

* NPU daemon library
   - User level API collection to request job to NPU daemon
* Core
   - Run background
   - IPC communication with application
* Scheduler
   - Prioritization between multiple application requests
* Resource manager(?)
   - NPU core management
* HAL (Hardware Abstraction Layer)
   - Interact with hardware device at a general or abstract level
   - Support hardware
      - TRIX

## Implement

* Code location : `ONE/runtime/service/npud`
* Package dependencies
   - trix-engine (git://git.tizen.org/platform/adaptation/npu/trix-engine)

**Comment by seanshpark** [comment]
@jyoungyun , can you explain a bit more about this?

**Comment by jyoungyun** [comment]
Yes, I'm doing. This issue is created from https://github.com/Samsung/ONE/projects/8. So this issue was briefly created and I'm filling in the details now..

**Comment by seanshpark** [comment]
> ONE/service/npud

I think this service is for onert(runtime).
I suggest to move this into `ONE/runtime/service/npud`,
as putting in `ONE/service`. I would think this service can be used in `compiler` (frontend).

**Comment by jyoungyun** [comment]
No more progress.
