### ISSUE TITLE
[one-cmds] Introduce `npy2h5` as `one-infer` option

### ISSUE THREAD

**Issue by yunjayh** [Samsung/ONE#9282]
### WHAT

Let's introduce a option to `one-infer` to convert I/O npy data file to h5 data file with hierarchy description. (Its name is `npy2h5` for now)

### WHY

To compare the inference results from variety backend drivers, which are triggered by `one-infer`, the data type and format should be well known. If we change the I/O data from backend drivers to preset `one-infer`-standard-format, value test would be more easier to implement. 

- Why h5? 
As it is shown in the name, `npy` is a data format which is python native. In some develop environment, it's not easy to handle npy format. (For example, `ONE-vscode` project is using typescript with node.js) We thought `h5` is universal enough format to use.

---

Here is a brief example about using `one-infer` with `npy2h5`. The option names and rules are never discussed, or confirmed. I imagined and wrote down in an hour. 

```
$ one-infer -d npu-infer --npy2h5-npy-input aaa.0.npy:aaa.1.npy --npy2h5-npy-output bbb.0.npy \
  --npy2h5-h5-name ccc -- [COMMAND]
```

NOTE) `[COMMAND]` is a command of `npu-infer`, and it's supposed to infer a model using `aaa.0.npy` and `aaa.1.npy` as input data and generates `bbb.0.npy` as output. 

Then, `npy2h5` will merge the npy data to one `ccc.h5`.

**Comment by mhs4670go** [comment]
@yunjayh I'm not familiar with the `one-infer`. Is this option is for the driver whose output format is `npy`?

**Comment by yunjayh** [comment]
> @yunjayh I'm not familiar with the `one-infer`. Is this option is for the driver whose output format is `npy`?

Yes it is. I updated the example usage of this tool or option. If there's something missing point, please let me know :D

**Comment by mhs4670go** [comment]
@yunjayh Above example means `npu-infer` infers a model with `h5` format input? Seems it does.

As you said in other issue, `one-infer` is for doing inference with various drivers. But, it also means their format of inputs and outputs are literally various. Moreover, some drivers just print the outputs instead of dumping the outputs. Even though some drivers dumps the outputs as `h5` format but `h5` can have various data hierarchy. The `one-infer` has general interface as much as it should?

**Comment by yunjayh** [comment]
> Above example means `npu-infer` infers a model with `h5` format input? Seems it does.

The example infers a model with `npy` format and emits `npy` output. After its inference step (by running the driver) is done, `one-infer` converts the `npy`s to `h5` with some predefined rules. 



> Even though some drivers dumps the outputs as `h5` format but `h5` can have various data hierarchy.

From the other issue, we specified the `h5` format and its hierarchy. It seems as general as enough to represent multiple data formats generated from multiple backends. 

With defining and introducing this `npy2h5` option and tool, I expect that `onecc` can provide standard data format for each backends. 

> But, it also means their format of inputs and outputs are literally various. Moreover, some drivers just print the outputs instead of dumping the outputs.

As your concerns, there can be literally various cases. IMHO It's impossible to cover every cases for the first approach. This issue will be a start of cover various cases.

**Comment by yunjayh** [comment]
I discussed with @mhs4670go in offline. 

First of all, I suggested this concept `npy2h5` to meet various backend drivers' output data to one standard format. 
@mhs4670go was concerned about `npy2h5` is not general enough for infinite backend drivers. He suggested to get post processing script from user which converts the backend drivers' input to the standard format of data, and I agree with this approach. 

The draft command will be like this.
`one-infer -d npu-infer --post-process "./npy2h5.py aaa.0.npy aaa.1.npy bbb.0.npy ccc.h5" -- [COMMAND]`

If there is any suggestion or other tips please let me know and fix it.

**Comment by yunjayh** [comment]
It doesn't matter at all :D It depends on the script and the user. Thank you for your suggestion :smile:

**Comment by yunjayh** [comment]
I opened #9290 to continue the task with new item. Thank you everyone. :heart:
