### ISSUE TITLE
[one-init] Discuss level of expectation on cfg file

### ISSUE THREAD

**Issue by hyunsik-yoon** [Samsung/ONE#9313]
Related to #9260, #9191, #9264

While reading previous issues and having brief discussion with related people,
I think we first need to make consensus on level of expectation on the cfg file produced by `one-init`.

Assume that 
- `one-init` generates a cfg file _C_ for a model _M_ 
- whole compiling procedure comprises of 
  - p1) original model (e.g., tflite) -> circle
  - p2) circle to circle (optimization, quantization, ..)
  - p3) circle -> backend code (_BC_)

What's our expectation with cfg file _C_?

- level 1) Compiling _M_ with _C_ could fail at p1 or p2.
- level 2) Compiling _M_ with _C_ is expected to succeed at p1 and p2 but could fail at p3.
- level 3) p1, p2, and p3 are expected to succeed
   - level 3-1) Latency or memory when running _BC_ is not a concern of _C_. It's user's job.
   - level 3-2) Latency or memory when running _BC_ needs to be close(?) to the optimized one. 

I guess that `one-init` produces _C_ with some level between 3-1) and 3-2).

Any opinion?

/cc @seanshpark @mhs4670go @jinevening @lemmaa @Samsung/one-vscode

**Comment by lemmaa** [comment]
> I guess that `one-init` produces _C_ with some level between 3-1) and 3-2).

Agree.
