### ISSUE TITLE
[onert] Revisit CompilerOptions for multiple models nnpkg

### ISSUE THREAD

**Issue by glistening** [Samsung/ONE#9328]
- There is a single `CompilerOptions` in `nnfw_session`.
- `CompilerOptions` constructor requires `Model`.

It was okay till now because there is only 1 Compiler and 1 Model in 1 nnfw_session.

But now things changed.

- nnpackage may have several models.
- there may be config for each model, not only global config.

Related: #9206, #9254

**Comment by glistening** [comment]
If `CompilerOptions` will be still an option for `nnfw_session` (not for `Model`) in the possiblity of multiple models.

I think `CompilerOptions` should not take `Model` in constructor, it must take `NNPkg`.

I investigated why `CompilerOptions` requires `Model`. It is used in 

```
void CompilerOptions::fetchCompilerOptionsFromGlobalConfig(const ir::Model &model)
{
...
    auto map_str = util::getConfigString(util::config::OP_BACKEND_MAP);
    ms_options.setBackendMap(model, map_str);
```

```
void ManualSchedulerOptions::setBackendMap(const ir::Model &model, const std::string &str)
{
...
    auto key = static_cast<uint32_t>(std::stoi(key_str));

    model.at(ir::SubgraphIndex{0})
      ->operations()
      .at(ir::OperationIndex{key}); // Check if exist, or this wil throw
```
It is used to check whether the operation index exists or not in 1st model (hardcoded).

(To be continued)

**Comment by glistening** [comment]
`ManualSchedulerOptions::setBackendMap` is used in two ways.

1) From GlobalConfig
2) From `nnfw_set_backends_per_operation`, which is declared in `nnfw_experimental.h`

How will we handle them in possibility of multiple models nnpkg?

Option 1: `setBackendMap` works only when # of model = 1
- These values are ignored or warned when it is set for multiple model nnpkg

Option 2: `setBackendMap` applied to 1st model (as it does silently in hardcoded code).
- It applies the given backed map only for 1st model.
- Its value has "`OP_BACKEND_MAP=\"0=acl_cl;1=cpu;2=acl_cl\"`"

I would choose option 1.

I don't consider in this comment how it will work when `configs` is set for each model.

We may need another revisit to support multiple configs.

**Comment by glistening** [comment]
@hseok-oh, @chunseoklee

Q. Will we create Compiler for each model? Or 1 Compiler will handle several models?

**Comment by chunseoklee** [comment]
> I think 1).

I have option 2 in mind since Compiler takes (model + compilation option) to produce ExecutorMap. I am not sure that we need multiple Compiler for multiple model.

**Comment by glistening** [comment]
@chunseoklee Okay. Let's suppose 1 compiler for 1 session even with multiple models.  

But, for model-specific option (e.g. `backend_per_operation`), we need to have multiple `CompilerOptions`.

Who will keep this option? Will `Compiler` have multiple compiler options?

How will we set different compiler option for each model?

Then, switch compiler option for each `Compiler::compile()` ( <- it compiles model, not nnpkg) from `Compiler::pkgcompile()` ( <-- suppose it is new method to compile nnpkg, ) ?

**Comment by chunseoklee** [comment]
> How will we set different compiler option for each model?

Not imagine yet.

> Then, switch compiler option for each Compiler::compile() ( <- it compiles model, not nnpkg) from Compiler::pkgcompile() ( <-- suppose it is new method to compile nnpkg, ) ?

Compiler::compile() will compile the whole ModelGraph. Thus, compile() will generate compilation result(not sure how it looks like for now. kind of collection of CompilationResult) of ModelGraph

**Comment by glistening** [comment]
@chunseoklee Please find my updated comment. I will update my draft PR based on our discussion and my last thought.

**Comment by chunseoklee** [comment]
> @chunseoklee Please find my updated comment. I will update my draft PR based on our discussion and my last thought.
> 
> * There will be N of CompilerOptions when nnpkg have N models.
>   
>   * By default, they will get the values from GlobalConfig as it does.
> * N CompilerOptions will exist in `nnfw_session`
> * 1 Compiler will be used even there are N models in an `NNPkg` (= previously a.k.a `ModelGraph`).
> * Some APIs (perhaps `nnfw_set_backends_per_operation`, `nnfw_set_config`, `nnfw_get_config`) which access compiler options need to have 1 additional parameter to specify what model's config it is going to modify.
>   
>   * By default, `model_idx` will be 0 (1st model) for backward compatibility.

Totally,  agreed. Thank you.

**Comment by glistening** [comment]
### How config APIs will be interpreter or extended (if necessary) in multiple-model era?

Let's think more for each existing APIs.

- `set_available_backend`
- `set_op_backend`
- `get_config`
- `set_backends_per_operation`

**Comment by glistening** [comment]
Just Note:

Existing 5 APIs may be interpreted as 1) for all models 2) for 1st model.

API | All Models | 1st Model
---- | ---- | ----
set_available_backend | O | O
set_op_backend | O | O
get_config | X <sup>1 | O
set_config | O | ? <sup>2
set_backends_per_operation | X<sup>3 | O

1) `get_config` for all models is not clear. Each model may have different config.
2) For `set_config`, I am not sure what is more likely to be used. For all models? or for specific model
3) `set_backends_per_operation` is not likely to be used since it sets backend by op index.

We may choose the default value differently, for example

`set_available_backend` sets backends for all models
`set_op_backend` sets backend for op kind for all models.
`get_config` and `set_backends_per_operation` are for 1st model, 

But for consistency, it will work for 1st model.
We will add API if necessary (e.g. `set_available_backend_for_all_models`.)

Related: https://github.com/Samsung/ONE/pull/9373#discussion_r911724210
