### ISSUE TITLE
[luci] Revisit Passes that are not necessarily be Passes

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#9356]
## What

Let's revisit Passes that are not necessarily to be Passes

## Why

Some Passes do not have to be Passes.

For example, `QuantizeWithMinMaxPass`  inherits `logo::Pass`, but it runs just once, so the return value of `run` method is not used.

It would be better to make it not inherit `Pass` to reduce code complexity.

List of such Passes.
- QuantizeWithMinMaxPass
- QuantizeDequantizeWeightsPass
- ConvertToFakeQuantizedModelPass
- RequantizePass
- QuantizePreCheckerPass
- CopyQuantParamPass
- ForceQuantParamPass

**Comment by seanshpark** [comment]
> It would be better to make it not inherit Pass to reduce code complexity.

From change #9357 , I could not see merits from not inherit from `Pass` class.
Is there other reasons for this change?

My thoughts
- it's OK to stay in `Pass` folder althought not inherit from `Pass` class
- it's OK to ignore return value and run just once
- basically all the classes does changes to the model

**Comment by jinevening** [comment]
> Is there other reasons for this change?

No, the only reason is to reduce redundant codes (for sw quality). Is it ok to leave them?

**Comment by seanshpark** [comment]
>  Is it ok to leave them?

IMHO, yes :)

**Comment by jinevening** [comment]
I see. I close this PR.
