### ISSUE TITLE
[one-cmds] Revisit naming in python script

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#9359]
## What

Let's revisit the naming in python script.

## Why

Most of function names in python script starts from `_` as of now. I did it because I wanted to make them internal function. But, I think it is not good-looking and they doesn't have to be done like that even if they are private function. So, let's revisit them. Also, I'm gonna refactor some small things to make them look better.

- Remove `_` from each function name
- Move `utils.py` to `onelib` and import it as `oneutils`

**Comment by seanshpark** [comment]
Q) using `_` prefix is not general in python for private functions?

> it is not good-looking 

I think it's OK :)

> doesn't have to be done like that even if they are private function

Is there another way of explicitly expressing like this?

**Comment by seanshpark** [comment]
> Move utils.py to onelib and import it as oneutils

IMHO, it would be better to split to separate files with file name expressing its purpose not using general `Utility`

**Comment by mhs4670go** [comment]
> Is there another way of explicitly expressing like this?

AFAIK, no.

> IMHO, it would be better to split to separate files with file name expressing its purpose not using general `Utility`

Yeah, actually, https://github.com/Samsung/ONE/issues/8169 is still being progressed:)
