### ISSUE TITLE
[onert] DC score down to 3.99

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/ONE#9525]
DC score about runtime down to 3.99 at 76d38707bfadded5d7271de7fc1a1ba400f59454

internal analysis : [link](https://analysishub.sec.samsung.net/service/analyses/1492629)

Let's fix this.

**Comment by glistening** [comment]
Internal Analysis Report says:

```
DC Top 25

No 1. runtime/onert/core/src/util/ConfigSource.cc
No 2. runtime/service/npud/util/ConfigSource.cc
...
```

I think we may factor out `ConfigSource.*` under `runtime/libs`.

**Comment by hseok-oh** [comment]
Now DC score is 4.01

**Comment by glistening** [comment]
@chunseoklee Is it okay to close it?

**Comment by chunseoklee** [comment]
> @chunseoklee Is it okay to close it?

Yes
