### ISSUE TITLE
[onert] NYI CPU backend kernel - uint8, per-channel

### ISSUE THREAD

**Issue by glistening** [Samsung/ONE#9609]
- [x] CONV2D
- [x] DEPTHWISE_CONV2D

`onert` cannot run per-channel quantized mobilenet v1 circle.

It fails at the 1st op due to lack of kernel.

```
$ ./build/install/bin/circledump 0c/0.circle
Dump: 0c/0.circle

===================================================================
Model version: 0
 # sub graphs: 1

Operator Codes: [order] OpCodeName (OpCode Enum)
[0] CONV_2D (code: 3, version: 1)

Buffers: B(index) (length) values, if any
B(0) (0)
B(1) (0)
B(2) (864) 0xe0 0x7c 0x40 0xfa 0x8b 0x4e 0xff 0x87 0x40 0xa4 0x25 0xa 0xbf 0x4f 0x1e 0x8e ...
B(3) (128) 0x73 0x4d 0xd1 0xff 0xab 0x75 00 00 0x15 0xf8 0xff 0xff 0x92 0x7e 0xef 0xff ...
B(4) (0)

-------------------------------------------------------------------
Sub-Graph: #0 (noname)

Data Format:
CHANNEL_LAST (NHWC for 2d, NDHWC for 3d data)

Operands: T(subgraph index : tensor index) TYPE (shape) (shape_signature) B(buffer index) OperandName
T(0:0) UINT8 (1, 224, 224, 3) B(1) input
    Quantization: scale(0.0392156) zeropt(128) quantized_dimension(0)

T(0:1) UINT8 (32, 3, 3, 3) B(2) MobilenetV1/Conv2d_0/weights
    Quantization: scale((32) 1.03063e-05, 0.00192652, 0.00438276, 1e-05 ... )
                  zeropt((32) 166, 189, 71, 123 ... )
                  quantized_dimension(0)

T(0:2) INT32 (32) B(3) MobilenetV1/MobilenetV1/Conv2d_0/Conv2D_bias
    Quantization: scale((32) 4.04168e-07, 7.55498e-05, 0.000171873, 3.92156e-07 ... )
                  zeropt((32) 0, 0, 0, 0 ... )
                  quantized_dimension(0)

T(0:3) UINT8 (1, 112, 112, 32) B(4) MobilenetV1/MobilenetV1/Conv2d_0/Relu6
    Quantization: scale(0.0235294) zeropt(0) quantized_dimension(0)

Operators: O(subgraph index : operator index) OpCodeName
    Option(values) ... <-- depending on OpCode
    I T(tensor index) OperandName <-- as input
    O T(tensor index) OperandName <-- as output
O(0:0) CONV_2D
    Padding(0) Stride.W(2) Stride.H(2) Dilation.W(1) Dilation.H(1) Activation(RELU6)
    I T(0:0) input
    I T(0:1) MobilenetV1/Conv2d_0/weights
    I T(0:2) MobilenetV1/MobilenetV1/Conv2d_0/Conv2D_bias
    O T(0:3) MobilenetV1/MobilenetV1/Conv2d_0/Relu6

Inputs/Outputs: I(input)/O(output) T(tensor index) OperandName
I T(0:0) input
O T(0:3) MobilenetV1/MobilenetV1/Conv2d_0/Relu6
===================================================================

$ BACKENDS="cpu" Product/out/bin/nnpackage_run 0c
Package Filename 0c
nnpackage_run: /home/gyu/z/ONE/runtime/onert/core/include/ir/TypeInfo.h:55: float onert::ir::TypeInfo::scale() const: Assertion `_quant.scales.size() == 1' failed.
Aborted (core dumped)
```

Other ops (not related per-channel) are okay: `SQUEEZE`, `SOFTMAX`.

**Comment by glistening** [comment]
## How to implement?

### Option 1. Use luci-interpreter kernel
It is already capable of running per-channel operators above.
Let's bring the verified kernel.

### Option 2. Implemement kernel based on existing kernel (like tflite)
Note tflite is `int8`, circle is `uint8`.

## How to verify?

### Option 1. Use luci-interpreter's verification
I don't know how luci-interpreter did.

### Option 2. Do something in new way
It will take much time. I don't have a specific idea.

**Comment by glistening** [comment]
Let's use `luci-interpreter/src/kernels/Conv2D.{,test.}cpp`, especially, `void Conv2D::evalQuantizedPerChannel() const`.

https://github.com/Samsung/ONE/blob/fae66969d9f4b7acb5c35f0c5eb536ea76f367ab/compiler/luci-interpreter/src/kernels/Conv2D.cpp#L238-L243

**Comment by ragmani** [comment]
> ## How to implement?

> ### Option 1. Use luci-interpreter kernel
> It is already capable of running per-channel operators above.
> Let's bring the verified kernel.

> ### Option 2. Implemement kernel based on existing kernel (like tflite)
> Note tflite is `int8`, circle is `uint8`.

In my opinion, the option 2 looks better because performance is one of the important factors in `onert`.






> ## How to verify?

> ### Option 1. Use luci-interpreter's verification
> I don't know how luci-interpreter did.

> ### Option 2. Do something in new way
> It will take much time. I don't have a specific idea.

You can add tests in https://github.com/Samsung/ONE/blob/master/tests/nnfw_api/src/one_op_tests/Conv2D.test.c for the option 2. And you can also test by moving https://github.com/Samsung/ONE/blob/master/tests/nnapi/specs/skip/V1_2/conv2d_per_channel.mod.py to https://github.com/Samsung/ONE/blob/master/tests/nnapi/specs/V1_2/ .

There is also a way to find and add a tflite model.

**Comment by glistening** [comment]
@ragmani Thank you for opinion. Performance kernel is always welcomed. But we always lack of time. We usually prepare reference kernel first, then, introduce performance kernel later. I hope someone may introduce optimized kernel, too.

**Comment by glistening** [comment]
## CONV2D (con'td) : test

There is one test from luci-interpreter `Conv2D.test.cpp` : `Uint8_CWQ`.

`luci-interpreter` verifies the output by `dequantize` and `FloatArrayNear`. 

https://github.com/Samsung/ONE/blob/ccea177ca16f6f3af6dc2702e01f2abba345211f/compiler/luci-micro/luci-interpreter/src/kernels/Conv2D.test.cpp#L311-L319

**Comment by ragmani** [comment]
> tflite is different to ours. It is based on int8. It takes more time without getting more. 

If so, there might be no tflite kernel, but I'm not sure. 
Considering the schedule and the existence of kernel in tflite, the option 2 seems difficult.

**Comment by glistening** [comment]
@ragmani 

> > 2. And you can also test by moving https://github.com/Samsung/ONE/blob/master/tests/nnapi/specs/skip/V1_2/conv2d_per_channel.mod.py to https://github.com/Samsung/ONE/blob/master/tests/nnapi/specs/V1_2/ .
> 
> tflite is different to ours. It is based on int8. It takes more time without getting more.

I will take a look `nnapi` test also. I mis-considered it is about `tflite`. Thank you!!

**Comment by glistening** [comment]
Conv2D implementation is merged.
```
$ Product/out/bin/nnpackage_run 0c
Package Filename 0c
===================================
MODEL_LOAD   takes 4.147 ms
PREPARE      takes 5.965 ms
EXECUTE      takes 250.627 ms
- MEAN     :  250.627 ms
- MAX      :  250.627 ms
- MIN      :  250.627 ms
- GEOMEAN  :  250.627 ms
===================================
```
But we need a way to compare the value for per-channel quantized model.
I will make another issue for this.

**Comment by glistening** [comment]
### How to verify (cont'd)

I first tried to use `flatc`. But `flatc` float is not lossless (https://github.com/google/flatbuffers/issues/5371#issuecomment-497516874). I will try to manipulate circle in Python using flatbuffer python API. (In short, add quantize at the input, add dequantize at the output.)

**Comment by glistening** [comment]
I finished to verify `conv2d` kernel.

```
$ tools/nnpackage_tool/gen_golden/gen_golden.py mv1.0.tflite
$ ls *.h5
input.h5
expected.h5
$ mv input.h5 input.f32.h5

# convert input in f32 to q8u using circle input quantization parameter
$ f2q
$ ls *.h5
expected.h5 input.f32.h5 input.q8u.h5

$ Product/out/bin/nnpackage_run --load input.q8u.h5 --dump output.q8u.h5 0c
$ ls *.h5
expected.h5 input.f32.h5 input.q8u.h5 output.q8u.h5

# convert output in q8u to f32 using circle output quantization parameter
$ q2f
$ ls *.h5
expected.h5 input.f32.h5 input.q8u.h5 output.q8u.h5 output.f32.h5

# check the quantization error is in expected range using your method
# example, h5diff or plotting, or several error unit or https://www.tensorflow.org/lite/performance/quantization_debugger

$ h5diff -d xxx -v output.f32.h5 expected.h5

$ ls
1614584 Aug 29 10:29 expected.h5 
 611064 Aug 29 10:29 input.f32.h5
 159480 Aug 29 10:31 input.q8u.h5
1614584 Aug 29 10:36 output.f32.h5
 403840 Aug 29 10:35 output.q8u.h5
```

[c0.h5.zip](https://github.com/Samsung/ONE/files/9441037/c0.h5.zip)
