### ISSUE TITLE
[onert] Support simple multiple model nnpackage execution

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/ONE#9610]
Now we support multiple models nnpacakge loading for tvn and circle model. To inference this package, we need to support TRIX + general backend mixed execution. To support this, let's implement compilation and execution simple multiple model nnpackage

### Simple multiple model package 

- Only 2 model file (ex. 1 tvn model, 1 circle model or 2 circle model)
- Only 1 edge between two model for link
- 1 package input and 1 package output
- 1 package input is in 1 model, 1 package output is in remain model
- Each model will use only 1 backend
- Each model has only 1 subgraph

### Why simple model?

- Expect avoiding serious performance issue
- Expect easy implementation without modifying pipeline implementation
- Expect simple implementation on `Compiler::compile`
- Expect small (or no) additional implementation on Exeuction phase

Draft: #9616

**Comment by glistening** [comment]
You may use #9391 (two tflite models of nnpkg). It is waiting for multiple models execution implementaiton. It does not require mixed execution.

**Comment by hseok-oh** [comment]
Next step - Support simply partitioned model 

- Package has two model
- Package's all input = 1st model's all inputs 
- Package's all output = 2nd model's all outputs
- 1st model's all output = 2nd model's all inputs

**Comment by hseok-oh** [comment]
Done
