### ISSUE TITLE
Introduce `circle-interpreter` as driver of `luci-interpreter`

### ISSUE THREAD

**Issue by yunjayh** [Samsung/ONE#9634]
### What

Let's publish `circle-interpreter` as driver of luci-interpreter. 

### Why

Currently, `luci_eval_driver` is published in `one-compiler-test` package which is mostly used for test. Here are few reasons to introduce a new binary, `circle-interpreter` for package. 

  * `luci-eval-driver` has `num_inputs` argument, which can be derived from circle model. Let's reduce the end-user's effort.
  * `luci`, which is a internal module name, is not proper to exposed to end-user. 
  * some internal tests are using `luci-eval-driver`. For theirs compatibility, it needs not to deprecate or fix arguments.

**Comment by yunjayh** [comment]
TODO: 

> Is this behavior (succeed for larger size input data) intended?

IMHO, it would be better to generate an error (ex: throw an exception) in `circle-interpreter` when the size of input data mismatches with the size of the model input. There may be a way to get the size of input file in cpp code.

So, it would be better to remove this test, because error message may not be the same with the current one.

_Originally posted by @jinevening in https://github.com/Samsung/ONE/pull/9658#discussion_r972605270_

**Comment by seanshpark** [comment]
@yunjayh , I think we need to add circle-interpreter and test to `infra/scripts/compiler_modules.sh`
CC @hseok-oh

**Comment by yunjayh** [comment]
I read the script and related scripts, and here is a question about it. 

`compiler_modules.sh` is only referenced in `infra/scripts/configure_compiler_coverage.sh`. However I cannot find `configure_compiler_coverage.sh` in this repository anymore. Could you please share what and why the script is needed?

**Comment by seanshpark** [comment]
ping @hseok-oh

**Comment by seanshpark** [comment]
https://github.com/Samsung/ONE/blob/master/infra/scripts/configure_compiler_coverage.sh

**Comment by yunjayh** [comment]
It's been confirmed that nightly released package successfully included `circle-interpreter`. Thank you for your kind help and reviews, everyone.

```text
$ onecc infer -d circle-interpreter -- -h
What circle-interpreter does: Interpreter driver for circle models

Usage: ./circle-interpreter [-h] [--version] model_path input_prefix output_prefix 

[Positional argument]
model_path   	Circle model filepath
input_prefix 	Input data filepath for circle model. n-th input data is rea
             	d from ${input_prefix}n, for example, Add.circle.input0, Add
             	.circle.input1
output_prefix	Output data filepath for circle model. Output data is writte
             	n in ${output_file}n, for example, Add.circle.output0

[Optional argument]
-h, --help   	Show help message and exit
--version    	Show version information and exit
```
