### ISSUE TITLE
[quantizer] Visualize layer-wise qerror

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#9694]
## What

Let's visualize quantization error in the quantized model

## Why

To observe which quantized layer harms accuracy.

## How

Input: fp32 circle, q circle, test data

Steps
1. Fake quantize q circle
2. Dump intermediate FMs of fp32 model with test data
3. Dump intermediate FMs of fq model with test data
4. Compare intermediate FMs and compute qerror
5. Generate DOT graph

![image](https://user-images.githubusercontent.com/5449554/189035647-15c47c53-f239-4e35-9ed4-630e644e16f3.png)

Nodes with higher qerror will be more red.

## Sample (MobileNet V2 full uint8)

![image](https://user-images.githubusercontent.com/5449554/189035823-02a76555-858e-433f-8244-a48c1b10c036.png)

[full graph](https://dreampuf.github.io/GraphvizOnline/#digraph%20%22mobilenet_v2_conv2d_relu6.0to68.circle%22%20%7B%0Ainput_2%3B%0ABiasAdd%3B%0A%22Conv1_pad_1%2FPad%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D1%2C%20style%3Dfilled%5D%3B%0Ainput_2%20-%3E%20%22Conv1_pad_1%2FPad%22%3B%0A%22Conv1_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D1%2C%20style%3Dfilled%5D%3B%0A%22Conv1_pad_1%2FPad%22%20-%3E%20%22Conv1_relu_1%2FRelu6%22%3B%0A%22expanded_conv_depthwise_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D1%2C%20style%3Dfilled%5D%3B%0A%22Conv1_relu_1%2FRelu6%22%20-%3E%20%22expanded_conv_depthwise_relu_1%2FRelu6%22%3B%0A%22expanded_conv_project_BN_1%2FFusedBatchNorm%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D1%2C%20style%3Dfilled%5D%3B%0A%22expanded_conv_depthwise_relu_1%2FRelu6%22%20-%3E%20%22expanded_conv_project_BN_1%2FFusedBatchNorm%22%3B%0A%22block_1_expand_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22expanded_conv_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_1_expand_relu_1%2FRelu6%22%3B%0A%22block_1_pad_1%2FPad%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22block_1_expand_relu_1%2FRelu6%22%20-%3E%20%22block_1_pad_1%2FPad%22%3B%0A%22block_1_depthwise_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_1_pad_1%2FPad%22%20-%3E%20%22block_1_depthwise_relu_1%2FRelu6%22%3B%0A%22block_1_project_BN_1%2FFusedBatchNorm%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D1%2C%20style%3Dfilled%5D%3B%0A%22block_1_depthwise_relu_1%2FRelu6%22%20-%3E%20%22block_1_project_BN_1%2FFusedBatchNorm%22%3B%0A%22block_2_expand_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22block_1_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_2_expand_relu_1%2FRelu6%22%3B%0A%22block_2_depthwise_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D4%2C%20style%3Dfilled%5D%3B%0A%22block_2_expand_relu_1%2FRelu6%22%20-%3E%20%22block_2_depthwise_relu_1%2FRelu6%22%3B%0A%22block_2_project_BN_1%2FFusedBatchNorm%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_2_depthwise_relu_1%2FRelu6%22%20-%3E%20%22block_2_project_BN_1%2FFusedBatchNorm%22%3B%0A%22block_2_add_1%2Fadd%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_1_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_2_add_1%2Fadd%22%3B%0A%22block_2_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_2_add_1%2Fadd%22%3B%0A%22block_3_expand_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D4%2C%20style%3Dfilled%5D%3B%0A%22block_2_add_1%2Fadd%22%20-%3E%20%22block_3_expand_relu_1%2FRelu6%22%3B%0A%22block_3_pad_1%2FPad%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D4%2C%20style%3Dfilled%5D%3B%0A%22block_3_expand_relu_1%2FRelu6%22%20-%3E%20%22block_3_pad_1%2FPad%22%3B%0A%22block_3_depthwise_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22block_3_pad_1%2FPad%22%20-%3E%20%22block_3_depthwise_relu_1%2FRelu6%22%3B%0A%22block_3_project_BN_1%2FFusedBatchNorm%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_3_depthwise_relu_1%2FRelu6%22%20-%3E%20%22block_3_project_BN_1%2FFusedBatchNorm%22%3B%0A%22block_4_expand_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22block_3_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_4_expand_relu_1%2FRelu6%22%3B%0A%22block_4_depthwise_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D4%2C%20style%3Dfilled%5D%3B%0A%22block_4_expand_relu_1%2FRelu6%22%20-%3E%20%22block_4_depthwise_relu_1%2FRelu6%22%3B%0A%22block_4_project_BN_1%2FFusedBatchNorm%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_4_depthwise_relu_1%2FRelu6%22%20-%3E%20%22block_4_project_BN_1%2FFusedBatchNorm%22%3B%0A%22block_4_add_1%2Fadd%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_3_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_4_add_1%2Fadd%22%3B%0A%22block_4_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_4_add_1%2Fadd%22%3B%0A%22block_5_expand_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D5%2C%20style%3Dfilled%5D%3B%0A%22block_4_add_1%2Fadd%22%20-%3E%20%22block_5_expand_relu_1%2FRelu6%22%3B%0A%22block_5_depthwise_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D5%2C%20style%3Dfilled%5D%3B%0A%22block_5_expand_relu_1%2FRelu6%22%20-%3E%20%22block_5_depthwise_relu_1%2FRelu6%22%3B%0A%22block_5_project_BN_1%2FFusedBatchNorm%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_5_depthwise_relu_1%2FRelu6%22%20-%3E%20%22block_5_project_BN_1%2FFusedBatchNorm%22%3B%0A%22block_5_add_1%2Fadd%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_4_add_1%2Fadd%22%20-%3E%20%22block_5_add_1%2Fadd%22%3B%0A%22block_5_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_5_add_1%2Fadd%22%3B%0A%22block_6_expand_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D4%2C%20style%3Dfilled%5D%3B%0A%22block_5_add_1%2Fadd%22%20-%3E%20%22block_6_expand_relu_1%2FRelu6%22%3B%0A%22block_6_pad_1%2FPad%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D4%2C%20style%3Dfilled%5D%3B%0A%22block_6_expand_relu_1%2FRelu6%22%20-%3E%20%22block_6_pad_1%2FPad%22%3B%0A%22block_6_depthwise_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D4%2C%20style%3Dfilled%5D%3B%0A%22block_6_pad_1%2FPad%22%20-%3E%20%22block_6_depthwise_relu_1%2FRelu6%22%3B%0A%22block_6_project_BN_1%2FFusedBatchNorm%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_6_depthwise_relu_1%2FRelu6%22%20-%3E%20%22block_6_project_BN_1%2FFusedBatchNorm%22%3B%0A%22block_7_expand_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D4%2C%20style%3Dfilled%5D%3B%0A%22block_6_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_7_expand_relu_1%2FRelu6%22%3B%0A%22block_7_depthwise_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22block_7_expand_relu_1%2FRelu6%22%20-%3E%20%22block_7_depthwise_relu_1%2FRelu6%22%3B%0A%22block_7_project_BN_1%2FFusedBatchNorm%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D1%2C%20style%3Dfilled%5D%3B%0A%22block_7_depthwise_relu_1%2FRelu6%22%20-%3E%20%22block_7_project_BN_1%2FFusedBatchNorm%22%3B%0A%22block_7_add_1%2Fadd%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_6_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_7_add_1%2Fadd%22%3B%0A%22block_7_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_7_add_1%2Fadd%22%3B%0A%22block_8_expand_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22block_7_add_1%2Fadd%22%20-%3E%20%22block_8_expand_relu_1%2FRelu6%22%3B%0A%22block_8_depthwise_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22block_8_expand_relu_1%2FRelu6%22%20-%3E%20%22block_8_depthwise_relu_1%2FRelu6%22%3B%0A%22block_8_project_BN_1%2FFusedBatchNorm%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_8_depthwise_relu_1%2FRelu6%22%20-%3E%20%22block_8_project_BN_1%2FFusedBatchNorm%22%3B%0A%22block_8_add_1%2Fadd%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_7_add_1%2Fadd%22%20-%3E%20%22block_8_add_1%2Fadd%22%3B%0A%22block_8_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_8_add_1%2Fadd%22%3B%0A%22block_9_expand_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22block_8_add_1%2Fadd%22%20-%3E%20%22block_9_expand_relu_1%2FRelu6%22%3B%0A%22block_9_depthwise_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D4%2C%20style%3Dfilled%5D%3B%0A%22block_9_expand_relu_1%2FRelu6%22%20-%3E%20%22block_9_depthwise_relu_1%2FRelu6%22%3B%0A%22block_9_project_BN_1%2FFusedBatchNorm%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_9_depthwise_relu_1%2FRelu6%22%20-%3E%20%22block_9_project_BN_1%2FFusedBatchNorm%22%3B%0A%22block_9_add_1%2Fadd%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_8_add_1%2Fadd%22%20-%3E%20%22block_9_add_1%2Fadd%22%3B%0A%22block_9_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_9_add_1%2Fadd%22%3B%0A%22block_10_expand_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D4%2C%20style%3Dfilled%5D%3B%0A%22block_9_add_1%2Fadd%22%20-%3E%20%22block_10_expand_relu_1%2FRelu6%22%3B%0A%22block_10_depthwise_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D6%2C%20style%3Dfilled%5D%3B%0A%22block_10_expand_relu_1%2FRelu6%22%20-%3E%20%22block_10_depthwise_relu_1%2FRelu6%22%3B%0A%22block_10_project_BN_1%2FFusedBatchNorm%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_10_depthwise_relu_1%2FRelu6%22%20-%3E%20%22block_10_project_BN_1%2FFusedBatchNorm%22%3B%0A%22block_11_expand_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22block_10_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_11_expand_relu_1%2FRelu6%22%3B%0A%22block_11_depthwise_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22block_11_expand_relu_1%2FRelu6%22%20-%3E%20%22block_11_depthwise_relu_1%2FRelu6%22%3B%0A%22block_11_project_BN_1%2FFusedBatchNorm%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_11_depthwise_relu_1%2FRelu6%22%20-%3E%20%22block_11_project_BN_1%2FFusedBatchNorm%22%3B%0A%22block_11_add_1%2Fadd%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_10_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_11_add_1%2Fadd%22%3B%0A%22block_11_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_11_add_1%2Fadd%22%3B%0A%22block_12_expand_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22block_11_add_1%2Fadd%22%20-%3E%20%22block_12_expand_relu_1%2FRelu6%22%3B%0A%22block_12_depthwise_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D4%2C%20style%3Dfilled%5D%3B%0A%22block_12_expand_relu_1%2FRelu6%22%20-%3E%20%22block_12_depthwise_relu_1%2FRelu6%22%3B%0A%22block_12_project_BN_1%2FFusedBatchNorm%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_12_depthwise_relu_1%2FRelu6%22%20-%3E%20%22block_12_project_BN_1%2FFusedBatchNorm%22%3B%0A%22block_12_add_1%2Fadd%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_11_add_1%2Fadd%22%20-%3E%20%22block_12_add_1%2Fadd%22%3B%0A%22block_12_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_12_add_1%2Fadd%22%3B%0A%22block_13_expand_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22block_12_add_1%2Fadd%22%20-%3E%20%22block_13_expand_relu_1%2FRelu6%22%3B%0A%22block_13_pad_1%2FPad%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22block_13_expand_relu_1%2FRelu6%22%20-%3E%20%22block_13_pad_1%2FPad%22%3B%0A%22block_13_depthwise_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22block_13_pad_1%2FPad%22%20-%3E%20%22block_13_depthwise_relu_1%2FRelu6%22%3B%0A%22block_13_project_BN_1%2FFusedBatchNorm%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_13_depthwise_relu_1%2FRelu6%22%20-%3E%20%22block_13_project_BN_1%2FFusedBatchNorm%22%3B%0A%22block_14_expand_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22block_13_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_14_expand_relu_1%2FRelu6%22%3B%0A%22block_14_depthwise_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D5%2C%20style%3Dfilled%5D%3B%0A%22block_14_expand_relu_1%2FRelu6%22%20-%3E%20%22block_14_depthwise_relu_1%2FRelu6%22%3B%0A%22block_14_project_BN_1%2FFusedBatchNorm%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D2%2C%20style%3Dfilled%5D%3B%0A%22block_14_depthwise_relu_1%2FRelu6%22%20-%3E%20%22block_14_project_BN_1%2FFusedBatchNorm%22%3B%0A%22block_14_add_1%2Fadd%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22block_13_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_14_add_1%2Fadd%22%3B%0A%22block_14_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_14_add_1%2Fadd%22%3B%0A%22block_15_expand_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D4%2C%20style%3Dfilled%5D%3B%0A%22block_14_add_1%2Fadd%22%20-%3E%20%22block_15_expand_relu_1%2FRelu6%22%3B%0A%22block_15_depthwise_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D5%2C%20style%3Dfilled%5D%3B%0A%22block_15_expand_relu_1%2FRelu6%22%20-%3E%20%22block_15_depthwise_relu_1%2FRelu6%22%3B%0A%22block_15_project_BN_1%2FFusedBatchNorm%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D4%2C%20style%3Dfilled%5D%3B%0A%22block_15_depthwise_relu_1%2FRelu6%22%20-%3E%20%22block_15_project_BN_1%2FFusedBatchNorm%22%3B%0A%22block_15_add_1%2Fadd%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22block_14_add_1%2Fadd%22%20-%3E%20%22block_15_add_1%2Fadd%22%3B%0A%22block_15_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22block_15_add_1%2Fadd%22%3B%0A%22block_16_expand_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D6%2C%20style%3Dfilled%5D%3B%0A%22block_15_add_1%2Fadd%22%20-%3E%20%22block_16_expand_relu_1%2FRelu6%22%3B%0A%22block_16_depthwise_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D6%2C%20style%3Dfilled%5D%3B%0A%22block_16_expand_relu_1%2FRelu6%22%20-%3E%20%22block_16_depthwise_relu_1%2FRelu6%22%3B%0A%22block_16_project_BN_1%2FFusedBatchNorm%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0A%22block_16_depthwise_relu_1%2FRelu6%22%20-%3E%20%22block_16_project_BN_1%2FFusedBatchNorm%22%3B%0A%22out_relu_1%2FRelu6%22%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D9%2C%20style%3Dfilled%5D%3B%0A%22block_16_project_BN_1%2FFusedBatchNorm%22%20-%3E%20%22out_relu_1%2FRelu6%22%3B%0AMean%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D5%2C%20style%3Dfilled%5D%3B%0A%22out_relu_1%2FRelu6%22%20-%3E%20Mean%3B%0ABiasAdd%20%5Bcolorscheme%3Dylorrd9%2C%20fillcolor%3D3%2C%20style%3Dfilled%5D%3B%0AMean%20-%3E%20BiasAdd%3B%0A%7D%0A) (visible on web)

**Comment by mhs4670go** [comment]
I think it's a good idea!

Let me ask some questions:)

1. After observing the harms, where can we use them?

2. Is there any chance to have a difference between the qerror with fake quant and the one with normal quant?

3. Above graph seems that qerror is not accumulated to the bottom layers. So, even if the qerror of upper layers are reduced, isn't there any possibility that the result of below layers will be worse?

**Comment by jinevening** [comment]
Thanks for good questions!

> where can we use them?

I can think of two possible use cases.
1. Model design: Model developers can concentrate on sensitive layers of a model. Those layers may be replaced with other types of layers, or quantized with different parameters.
2. Mixed-precision quantization: We can quantize sensitive layers with higher bits e.g., int16 rather than uint8.

> Diff between qerror with fake quant and normal quant

Of course there exist differences. Using quant kernels (instead of fake quant) can be another option, but it is difficult to implement a wide coverage of quant kernels.

Fake quant is used in other ML frameworks (TF, PyTorch), and our experiments show that fake-quant kernels can mimic quant kernels quite accurately.

> Qerror accumulation

We compare the same points in fp32 model and quant model, so qerrors are in fact accumulated. We can observe in which points qerrors are increased.

I think that in general, the reduction of qerror in any layer will lead to the reduction of the qerror of the final result. There can be counter-examples, but they may be very rare cases.

**Comment by jinevening** [comment]
I'm finding a good name for this module

Candidates: `visqerror` (visualize qerror), or `visq`

Interface will be like below.

```bash
$ visqerror --fp32_circle sample.circle \
  --q_circle sample.q.circle \
  --data test.h5 \
  --peir_output peir_output.dot \
  --mse_output mse_output.dot
```

The above command will compute peir and mse between `sample.circle` and `sample.q.circle`, and generate qerror dot graphs  `peir_output.dot` and `mse_output.dot`.

Any suggestion for naming or interface is welcome!

CC @lemmaa @seanshpark @mhs4670go

**Comment by seanshpark** [comment]
`visq` looks nice for module name in `compiler`.
for the tool name, `visqerror` or `visqerr` looks OK.

**Comment by lemmaa** [comment]
I like both names. But, the `visqerror` feels uniquely like something snakes wriggling. :)

Anyway, when I first saw the picture of https://github.com/Samsung/ONE/issues/9694#issue-1365521751, I felt something like this. It would be interesting to have a name that conveys this feeling. :)

https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=kintex&logNo=221199771917&view=img_1

**Comment by seanshpark** [comment]
1 + 5 -> RarelyWellDone -> in Korean; "거의 잘 된적이 없는..." -_-;

**Comment by seanshpark** [comment]
Had a short offline talk with @jinevening ,
- best UI would be to generate(?) a html file and drop to a browser and see the graph
- looking inside, we can generate some model file (in JSON?) and use (1) browser as viewer (2) some eletron app as a viewer (3) netron-visq, modified netron like netron-circle
- we can also think of ONE-vscode too
- using HTML-JS-CSS would take time so we can go with in parallel to DOT file viewing.

**Comment by seanshpark** [comment]
With this scenario,
1. user creates `.json` file with `visq` command line
2. `visq` will create(or mayby just copy from somewhere) `html` and the data `.json` file
3. with something like `--view-in-browser` option, `visq` will invoke the browser with `html` file
4. browser will show the quantization error graph

I'v done some test with loading a local file from local .html in the browser.
- we can use `FileReader` class ONLY with `<input>` tag, that is, user MUST select the file in HTML view. --> this seems odd with above scenario
- we can NOT use `XMLHttpRequest` as browser rejests by security reasons
- we can put as json object in `.js` file and use it from the rendering logic
   ```js
   const data = { ... };
   ```

We can use nodejs as local file server but seems getting too far...

**Comment by seanshpark** [comment]
Found an issue when we use `.circle` file for the model and `.json` for the error data.
- reading a local file in the javascript is impossible cause of security reasons (mentioned above)
- cannot read `.circle`

To resolve this...
- convert `.circle` file also to `.js` in form of `.json` ? --> done this in ONE-vscode and it's not good
- use nodejs as local web server
- use electron app
- ...

**Comment by seanshpark** [comment]
I'm doing some experiment using nodejs and seems working.
But not sure with this usage scenario;
1. user runs visq tool to create error json file
2. user runs visquv tool (to see error json file, with the default web browser, through nodejs.

**Comment by jinevening** [comment]
I'm thinking of two scenarios.

1. Using web server

We can make a web page running the `visquv` server (ex: by github page).

Users will generate qerror json file using `visq`, and upload the json file to the web page to visualize qerror.

pros: Qerrors can be saved in a single json file.
cons: Users should access to our web page to see the `visq` graph.

2. Creating local html file

`visquv` can generate a full html file (locally executable) from the json file.

Users will open the html file on their local environment.

pros: Users can directly see qerror graph in local environment.
cons: Qerror results will be saved in a complex form (ex: html/css/js ...).

My first thought was the second option, which allows users to open the qerror graph using their browser in local environment.

It seems that #9852 is more appropriate for the first scenario. And I think the first scenario is also good :)

**Comment by jinevening** [comment]
Thanks. The example looks good to me!

1) How about removing "scheme" and renaming "range" to "colorscheme"? It seems that rgb values are duplicate.

2) I think "metric" can be added to "meta" section, which describes the metric of qerror. For example,

```json
"metric": "PEIR"
```

**Comment by seanshpark** [comment]
experiment result of draft code

![image](https://user-images.githubusercontent.com/4616940/195261286-b6b1d9ff-1ff7-4b2c-9f80-992226667897.png)

**Comment by seanshpark** [comment]
TODO with draft
- [ ] text color to white with dark node
- [ ] show legend table
- [ ] show PEIR value in node
- [ ] ...

**Comment by seanshpark** [comment]
@jinevening , current qerror json format cannot provide for multiple subgraphs.
for now, we may support for only single subgraph, but the format should support this.
I'll update the the format.

**Comment by seanshpark** [comment]
@Samsung/nncc , I'd like to get some opinions about the draft code in #9862,
- basic external code struture is from ONE-vscode media/CircleGraph; is this OK for ONE too?
- we had mostly c/c++ and python codes. js is new. what do you guys think of this?
- our debian package may need depedency to nodejs if we continue with current implementation.
- any other things about the implementation

**Comment by seanshpark** [comment]
Had a short offline talk with @lemmaa and,
- providing a viewer tool as _visquv_ in ONE itself is OK
- I have a plan to provide this in ONE-vscode, which will be a duplicate
- duplicate is not nice to maintain
- conclusion; it would be better to move _visquv_ to ONE-vscode

Other's thoughts are welcome :)

**Comment by jinevening** [comment]
Since we decided to use multiple viewers (dot and web), I think we should use repos as below.

`visq` in ONE: Generate qerror (json) file. `visqerror` executable is included in `one-compiler` package

Example
```bash
$ visqerror --fp32_circle sample.circle \
  --q_circle sample.q.circle \
  --data test.h5 \
  --mpeir_output mpeir_qerror.json \
  --mse_output mse_qerror.json
```

`visquv` in ONE-vscode
`visqdot` in python-tools

This will make less duplicate codes and simplify dependency (`visquv` and `visqdot` will depend on `visqerror` in `one-compiler`).

**Comment by seanshpark** [comment]
@jinevening , about the visq json file extension, how about using `*.visq.json` ?
- we already use `something.feature.json` file name convention

**Comment by jinevening** [comment]
>  about the visq json file extension, how about using *.visq.json ?

Using convention looks good to me :) Something like `inception_v3.mpeir.visq.json` or `inception_v3.mse.visq.json`.

**Comment by seanshpark** [comment]
Q) I assume mpeir file and mse have the same format.. correct?
Q) `"metric": "PEIR"` exist for mpeir file and `"metric": "MSE` for mse file?
Q) in the graph, legend table, we should show `MSE aaa ~ bbb` for MSE metric?

**Comment by jinevening** [comment]
Answers to all of the questions are yes.

For mpeir, `"metric": "MPEIR"` would be right.

**Comment by seanshpark** [comment]
@jinevening , FYI, initial version of Visquv in ONE-vscode has landed.
As I know there is no daily release of ONE-vscode so you may need to build from source.

**Comment by jinevening** [comment]
I close this issue as `visq` with dot graph printer is not successfully landed.
