### ISSUE TITLE
[Dockerizing]  onecc version selection code for dockerizing

### ISSUE THREAD

**Issue by morumoru** [Samsung/ONE#9701]
## What
I wrote onecc version selection code part for dockerizing with python and bash shell script 

but I'm not sure it is well organized so I want to get a review from other people

Is there a better way to choose a version?

Please check my code and give me any advice for better code

## Code
``` 
#!/usr/bin/env bash
''''command -v onecc > /dev/null && version=(`onecc --version`) && exec "python3" "onecc-docker.py" "${version[2]}" "$@" && exit 0  #'''
''''exec "python3" "onecc-docker.py" "0" "$@" && exit 0  #'''

import re
import sys
import subprocess

def main():
    onecc_version = sys.argv[1]
    versions_str = subprocess.check_output("git ls-remote -t --sort=v:refname https://github.com/Samsung/ONE/", shell=True ,encoding='utf-8')
    versions = re.findall(r"\d+\.\d+\.\d+", versions_str)
#    print(versions_str)
#    print(versions)
    chosen_version = ""
    while 1:
        for i in range(18, len(versions)):
            print(versions[i])
        chosen_version = input("choose version: ")
        flag = False
        for i in range(18, len(versions)):
            if(chosen_version == versions[i]):
                flag = True
                break
        if(flag):
            break
        else:
            print("choose right version")
    if(chosen_version == onecc_version):
        print("onecc is installed in computer")
        #if onecc version is same with installed version, forward flag to installed onecc
        exit(0)
    #if installed onecc version is different with selected version, write Dockerfile
    

if __name__ == "__main__":
	main()
```

## Output
![캡처](https://user-images.githubusercontent.com/19775516/189799521-bb52113b-2d5c-4a1b-9cfa-2326d9f845a3.JPG)

/cc @Samsung/ootpg

**Comment by mhs4670go** [comment]
Can you just post a draft pull request instead? It would be easier to review the codes:)

**Comment by jyoungyun** [comment]
Can you create a pull request for this issue? PR helps code review to be easy. You can use a draft PR. :)

**GitHub Docs**
[Creating a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

**Articles**
[Create pull request github](https://opensource.com/article/19/7/create-pull-request-github)
[Introducing draft pull requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

The current version of Git available in the Ubuntu 18.04 repository is v2.17.
And Git v2.17 version does not support to sort by `refname`. :(

Even if we uses sorting with `refname` on `git ls-remote` command, this command can only be executed in git repository.
However we need to support to get the ONE version list even outside git repository.

You can use the GitHub REST API.
https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api

**Comment by morumoru** [comment]
Thank you for your advices
I'll fix my code and make draft pull request for this issue later

I checked that refname can't be used in Ubuntu 18.04
but I thought that git ls-remote can be excuted without pulling git repository
Is excuting without pulling git repository not same with executing outside git repository? 

@jyoungyun

**Comment by jyoungyun** [comment]
> Is excuting without pulling git repository not same with executing outside git repository?

Oh, I tested it again, the `git ls-remote` command worked outside git repository. :)

```bash
$ pwd
/
$ git ls-remote
fatal: No remote configured to list refs from.
$ git ls-remote -t https://github.com/Samsung/ONE/
7d429808a18874fca72acbfa22d6bed4d49a2200        refs/tags/1.10.0
23f78eed673e0824306e1c3cec607b438e724993        refs/tags/1.11.0
24b64bc10db3787dd290da93e4044fe0e4b59024        refs/tags/1.11.1
7e368586a43022858ae7c6f4d68f3e072ba3bff3        refs/tags/1.12.0
...
```

You can use this command, but I don't know if installing the `git` tool to use this command is better than using `curl`. Since the size of the `git` is larger than the `curl`, I think it is expensive way. :)

**Comment by morumoru** [comment]
Thank you for advices! I'll find the way to use curl instead git!

**Comment by morumoru** [comment]
Should I use SSDC-S002 repository for pull request? or can use my personal repository?
and When I make draft pull request, Is there any commit message format?
and How can I use -s in pull request? or just write ONE-DCO-1.0-Signed-off-by: on pull request like other people?
Thank you

@jyoungyun
