### ISSUE TITLE
[ONE-Dockerizing] Q) about onecc-docker -h option

### ISSUE THREAD

**Issue by morumoru** [Samsung/ONE#9801]
I am wondering about handling -h option to onecc- docker.
There are onecc-docker's -h option and onecc's -h option and onecc's subtool's -h option.
I thought about making a new flag for onecc's -h option (e.g -a) but in this case, subtool's -h option must be handled too.
How can I handle this situaltion?

#related draft PR #9800

**Comment by seanshpark** [comment]
@morumoru , you don't need to add WHAT and WHY

Just add question body, and I don't think you need the `Question` header.
And instead of `Add argparse to onecc-docker`, `Q) about onecc-docker -h option` would be better to express this question issue.

**Comment by mhs4670go** [comment]
How about introduce a double dash("--")? It could indicate the end of _onecc-docker_'s option. You can refer to https://github.com/Samsung/ONE/blob/5573f5b11a6d63a803c6d9892292fbed72a23b11/compiler/one-cmds/one-infer.

https://github.com/Samsung/ONE/blob/5573f5b11a6d63a803c6d9892292fbed72a23b11/compiler/one-cmds/one-infer#L114

**Comment by morumoru** [comment]
Oh! than we can get onecc's help message by calling ./onecc-docker -- -h!
Thank you for your advice!

**Comment by jyoungyun** [comment]
Then `onecc-docker -h` always outputs the `onecc-docker`'s help message?

**Comment by mhs4670go** [comment]
> Then `onecc-docker -h` always outputs the `onecc-docker`'s help message?

Yes. Is there any other case?

**Comment by jyoungyun** [comment]
First, we decided not to consider help message in various cases. Now, only `onecc-docker` help messages will be displayed. We will think about the next step later.

**Comment by jyoungyun** [comment]
I will make a new issue when I proceed with this issue. I will close it.
