### ISSUE TITLE
[onert] Revisit TracingCtx, ExecutionObserver, ...

### ISSUE THREAD

**Issue by glistening** [Samsung/ONE#9834]
I am about introducing event hook after op execution.

I need to revisit the related code.

My interested event is different from existing ones. (TracingObserver, ProfileObserver, ...)
- It will read the value of output tensor. (Existing ones focuses on just time duration.)
- It may be used in release mode also, not only for debug mode.

(Let me introduce another issue for my interested one.)

This is to revisit the existing code that I've found confusing or seemingly redundant.

### 1. Remove the duplicated code in `LinearExecutor::executeImpl()`

There is `if` and `else` in `LinearExecutor::executeImpl()`. Basically, it is twins (copy and pasted).

<sub> I would like to put the diff in image, but it is not allowed to put image from office. Thus, here is text diff </sub>

```diff
@@ -1,16 +1,11 @@
-  if (_tracing_ctx)
+  else
   {
-    auto profiling_subg_index = _tracing_ctx->getSubgraphIndex(&_graph);
-
-    _subject.notifySubgraphBegin(profiling_subg_index);
     for (auto &&code : _code)
     {
-      const auto backend = code.lower_info->backend();
 // TODO : Move ruy profiler into ExecutionObserver
 #ifdef RUY_PROFILER
       ruy::profiler::ScopeLabel label(code.op->name());
 #endif
-      _subject.notifyJobBegin(this, profiling_subg_index, code.op_ind, backend);
 
       auto &fn_seq = code.fn_seq;
 
@@ -20,8 +15,5 @@
         _lowered_graph->getHasDynamicTensor(code.op_ind) || hasDynamicInput();
       fn_seq->enableDynamicShapeInferer(handle_dynamic_tensor);
       fn_seq->run();
-
-      _subject.notifyJobEnd(this, profiling_subg_index, code.op_ind, backend);
     }
-    _subject.notifySubgraphEnd(profiling_subg_index);
   }
```

- `TracingContext` is always created whether tracing is enabled or not.
- I guess at first, the implement would like to minimize the overhead, but it seems not true any longer.
- `DataFlowExecutor::executeImpl()` doesn't check `_tracing_ctx`.
```cc
void DataflowExecutor::executeImpl()
{
  ...
  auto profiling_subg_index = _tracing_ctx->getSubgraphIndex(&_graph);

  _subject.notifySubgraphBegin(profiling_subg_index);

  while (!_ready_jobs.empty())
  {
    auto job = std::move((_ready_jobs.begin())->second);
    _ready_jobs.erase(_ready_jobs.begin());
    auto job_index = job->index();
    auto op_ind = _job_to_op[job_index];
    const backend::Backend *backend = _lowered_graph->lower_info().operation.at(op_ind).backend();
    _subject.notifyJobBegin(this, profiling_subg_index, op_ind, backend);
```

### 2. (optional) Conditional event notification

If someone is sure, it is important to remove event notification overhead, `if` condition is not proper.
It should check whether there is any event observer, not by `tracing_ctx` is enabled. (There may be other observer except for `tracing_ctx`).

I will create a PR for item 1. Please let me know if there is misunderstanding or history, which is still important.

cc @Samsung/one_onert

**Comment by hseok-oh** [comment]
Checking `_tracing_ctx` is inserted for pipeline. Compilation for pipeline does not create `tracing_ctx`.
And currently, multiple model package also doesn't create `_tracing_ctx` yet.

**Comment by hseok-oh** [comment]
>I don't think current code is good

Agree :)

**Comment by glistening** [comment]
I should close the PR, not this issue.

**Comment by glistening** [comment]
I don't want to have duplicated code in `LinearExecutor::executeImpl` for maintenance <sub> and efficiency ←I guess the overhead is not big because it checks per lowered graph.) </sub>

## How ?

I think `if (_tracing_ctx)` has at least two meanings:

1) Event notification is needed
   - The condition should be # of observer > 0
   - This conditional notification could be introduced after we encounter the case
2) `subgraph *` →subgraph index map exists
  - I would like to keep this information all configuration.
  - I don't think the memory overhead is big. Again, it could be optimized if size matters.

**Comment by glistening** [comment]
@hseok-oh I wonder why #9835 passed w/o failure. Is there any test case for pipeline feature? From #6973, I find some test, but it seems just to prepare. How can I confirm my refactoring does not break `pipeline`. In addition, do we need to keep this feature?

**Comment by glistening** [comment]
> And currently, multiple model package also doesn't create TracingCtx yet.

I start this. See #9840.

**Comment by hseok-oh** [comment]
>I wonder why https://github.com/Samsung/ONE/pull/9835 passed w/o failure. Is there any test case for pipeline feature?

There is test case for pipeline loading, compilation. But there is no test case for pipeline inference. I checked and found that yesterday.

**Comment by glistening** [comment]
I am going to get the map
```cc
std::unordered_map<const ir::Graph *, ir::SubgraphIndex> _subgraph_indices;
```
out of `TracingContext`. I will create a draft PR to discuss more.

**Comment by glistening** [comment]
I talked with @hseok-oh and during discussion, I found several dependencies more which makes it hard to revisit and assumption @hseok-oh would like to keep. ...) Thus, I will minimize the change in existing code. I will extend on top of the existing ones.
