### ISSUE TITLE
[onert] Remove experimental API: nnfw_prepare_pipeline

### ISSUE THREAD

**Issue by glistening** [Samsung/ONE#9854]
I see several if-conditions around our code for pipelined execution. 

- It is not documented much
- seems not be used
- make it hard to introduce new feature and maintain, 
- its execution is not tested in CI
- authors are inactive in this repo

Thus, I would like to remove this experimental API. Do you have any idea or history?

I have to read and spend time to figure out what is `_executions`.
But it was hard to understand for the reason above.
I was told it is for pipeline. 

Here is the related code I've found:
```cc
/*
 * Prepare session to be ready for inference
 * This phase may finalize model compilation, scheduling, and additional settings.
 *
 * @param session the session to be prepared
 * @return NNFW_STATUS_NO_ERROR if successful
 */
NNFW_STATUS nnfw_prepare_pipeline(nnfw_session *session, const char *map_file_path = nullptr);
```

What is map file? I cannot find the documentation.

@Samsung/one_onert, @intom

**Comment by hseok-oh** [comment]
Pipeline is introduced by two PR: #6973 and #6900.
If there is no opposition, let's remove this experimental feature.

**Comment by hseok-oh** [comment]
#10150 removes pipeline feature introduced by #6900 and #6973
