### ISSUE TITLE
[record-minmax] Improve error messages

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#9892]
## What

Let's improve error messages.

1. Unsupported operator
```
/usr/share/one/bin/record-minmax: ERROR: Unsupported operator: 70 LayerName
```

70 is the number of opcode. It would be better to print the name of the operator (ex: SquaredDifference)

2. Unsupported custom operator

```
/usr/share/one/bin/record-minmax: ERROR: Unsupported Custom operator. LayerName
```

It would be better to print the name of the custom operator (both with the layer name).

---
Added 2022/10/04

3. Input tensor size mismatch

No error message.

Need to check size of input data and the size of model input.

**Comment by jinevening** [comment]
@parjong suggested to print suggestion (ex: Please exclude the node)

**Comment by seanshpark** [comment]
> (not the layer name)

I'd prefer operator code name and also layer name

**Comment by jinevening** [comment]
Done.
