### ISSUE TITLE
[CFE] Ubuntu and Python upgrade

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#9962]
Out default platform Ubuntu 18.04 will end support Apr 2023, less than a year left.
And we now have Ubuntu 22.04, it's time to support new platform.
But also support old 18.04 for a while...

Let's see how versions exist;

Ubuntu | default | support upto| with deadsnakes/ppa | tentative
--- | --- | --- | ---- | ---
Ubuntu 18.04 | 3.6 | 3.8 | 3.11 | 3.8 (as-is)
Ubuntu 20.04 | 3.8 | 3.9 | 3.12 | 3.8 (as-is)
Ubuntu 22.04 | 3.10 | 3.11 | 3.12 | 3.10 (default)

- latest python version is 3.11

Purpose of this task
- decide python version (or versions)
- use single python version if possible (currently 3.8)
   - Ubuntu officially doesn't support all version --> test not confirmed
- to reduce code complexity
   - --> 22.04 use default 3.10
   - --> 18.04 / 20.04 go as-is
   - from draft, management is possible

**Comment by seanshpark** [comment]
Reference
- https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa

**Comment by seanshpark** [comment]
From Ubuntu vs Python version table...
- we can't go with one python version, unless we use deadsnakes/ppa

When using different python versions...
- cmake codes needs modification to support different versions by different platform
- some scripts may also need modification

**Comment by seanshpark** [comment]
### Issues with build/test in Ubuntu 22.04

- TBA...

**Comment by seanshpark** [comment]
### Issues with build/test in Ubuntu 22.04 : `one-prepare-venv` 실행

`python3.8` not found --> let's use `python3` for the moment... 

I'm behind corporate firewall and using proxy

> Could not fetch URL https://pypi.org/simple/tensorflow-cpu/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/tensorflow-cpu/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)'))) - skipping

--> ?

**Comment by mhs4670go** [comment]
Just for others information, 
> ### Issues with build/test in Ubuntu 22.04 : `one-prepare-venv` run

We need to write dedicated venv script for 22.04 named `one-prepare-venv_2204`(or `one-prepare-venv-jammy`..?).

And, there are a few options to include the script to the package.

1. Replace existing `one-prepare-venv` script with the script for 22.04 when building in the CI.
```bash
$ cp compiler/one-cmds/one-prepare-venv-jammy compiler/one-cmds/one-prepare-venv
```
2. Add if statement to the debian _postinst_.
```bash
$ cat infra/debian/compiler/postinst
# ..
# if codename == jammy
su - $(whoami) -p -c '/usr/share/one/bin/one-prepare-venv-jammy' # $(whoami) = root
# else
su - $(whoami) -p -c '/usr/share/one/bin/one-prepare-venv' # $(whoami) = root
```

After the offline discussion with @seanshpark, first option seems a better option as of now.

**Comment by seanshpark** [comment]
`one-cmds` test works OK with Ubuntu 22.04.

I'll continue on to get some solution to manage fixed codes that use `python3.8` ...

**Comment by seanshpark** [comment]
@mhs4670go , in `common-artifacts` and `dalgona` these exist in front of CMakeLists.txt

```cmake
find_package(PythonInterp 3.8 QUIET)
find_package(PythonLibs 3.8 QUIET)
```
can you share any documents what these two do? like what variables does it set? how are these used as library or tools? etc...

As I see, these are OK on Ubuntu22.04 where only python3.10 exist but not sure something might go wrong.

**Comment by mhs4670go** [comment]
Please see below documents.
https://cmake.org/cmake/help/v3.10/module/FindPythonInterp.html
https://cmake.org/cmake/help/v3.10/module/FindPythonLibs.html

### FindPythonInterp

> finds if Python interpreter is installed and determines where the executables are.

This code sets the following variables:

PYTHONINTERP_FOUND         - Was the Python executable found
PYTHON_EXECUTABLE          - path to the Python interpreter
PYTHON_VERSION_STRING      - Python version found e.g. 2.5.2
PYTHON_VERSION_MAJOR       - Python major version found e.g. 2
PYTHON_VERSION_MINOR       - Python minor version found e.g. 5
PYTHON_VERSION_PATCH       - Python patch version found e.g. 2

### FindPythonLibs

> finds if Python is installed and determines where the include files and libraries are.

This code sets the following variables:

PYTHONLIBS_FOUND           - have the Python libs been found
PYTHON_LIBRARIES           - path to the python library
PYTHON_INCLUDE_PATH        - path to where Python.h is found (deprecated)
PYTHON_INCLUDE_DIRS        - path to where Python.h is found
PYTHON_DEBUG_LIBRARIES     - path to the debug library (deprecated)
PYTHONLIBS_VERSION_STRING  - version of the Python libs found (since CMake 2.8.8)

**Comment by seanshpark** [comment]
> Please see below documents.

Thank you!

**Comment by seanshpark** [comment]
TODO
- [ ] add one-prepare-venv for Ubuntu22.04
- [ ] revise debian package files for Ubuntu22.04
- [ ] test Ubuntu22.04 package installation

**Comment by seanshpark** [comment]
@mhs4670go , can you please continue with debian package generation for Ubuntu22.04 ?

**Comment by mhs4670go** [comment]
@seanshpark Okay, can I proceed it after the internal docker images are relocated into a new artifacts repository?

**Comment by seanshpark** [comment]
> can I proceed it after the internal docker images are relocated into a new artifact repository?

sure! this is not urgent so please take your time :)

**Comment by seanshpark** [comment]
@mhs4670go , is your time OK to continue this task?

**Comment by mhs4670go** [comment]
@seanshpark It must have slipped my mind,, I'll get to proceed this task.

**Comment by mhs4670go** [comment]
```bash
01:15:51  It will use default overlay path
01:15:51  Using docker image rs7-runtimentools-docker-local.bart.sec.samsung.net/one-devtools:jammy-proxy
01:15:52  -- Use '20221125' SDK preset
01:15:52  -- The C compiler identification is GNU 11.3.0
01:15:52  -- The CXX compiler identification is GNU 11.3.0
01:15:52  -- Detecting C compiler ABI info
01:15:52  -- Detecting C compiler ABI info - failed
01:15:52  -- Check for working C compiler: /usr/bin/cc
01:15:52  -- Check for working C compiler: /usr/bin/cc - broken
01:15:52  CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCCompiler.cmake:69 (message):
01:15:52    The C compiler
01:15:52  
01:15:52      "/usr/bin/cc"
01:15:52  
01:15:52    is not able to compile a simple test program.
01:15:52  
01:15:52    It fails with the following output:
01:15:52  
01:15:52      Change Dir: /home/jenkins/jenkins_agent/workspace/nnfw/test/sw4670.chae/daily-publish-package@3/build/nncc/CMakeFiles/CMakeTmp
01:15:52      
01:15:52      Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_2b8e2/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_2b8e2.dir/build.make CMakeFiles/cmTC_2b8e2.dir/build
01:15:52      gmake: /usr/bin/gmake: Operation not permitted
01:15:52      gmake: *** [Makefile:127: cmTC_2b8e2/fast] Error 127
01:15:52      
01:15:52      
01:15:52  
01:15:52    
01:15:52  
01:15:52    CMake will not be able to correctly generate this project.
01:15:52  Call Stack (most recent call first):
01:15:52    CMakeLists.txt:3 (project)
```
@hseok-oh Do you have any idea about this error?

**Comment by seanshpark** [comment]
> Using docker image rs7-runtimentools-docker-local.bart.sec.samsung.net/one-devtools:jammy-proxy

I'll also try with this

**Comment by hseok-oh** [comment]
> `gmake: /usr/bin/gmake: Operation not permitted`  

Maybe related with this message?

**Comment by seanshpark** [comment]
google search result, try
```
docker run --privileged 
```

**Comment by seanshpark** [comment]
local build is OK without `docker run --privileged`

@mhs4670go , is this build inside CI ?

**Comment by mhs4670go** [comment]
> local ~build~ configure is OK without `docker run --privileged`
> 
> @mhs4670go , is this build inside CI ?

Yes,, that log was from the inside CI.

**Comment by mhs4670go** [comment]
> google search result, try
> 
> ```
> docker run --privileged 
> ```

```bash
--- a/infra/nncc/command/docker-run
+++ b/infra/nncc/command/docker-run
@@ -2,7 +2,7 @@
 
 import "docker.configuration"
 
-docker run $DOCKER_RUN_OPTS $DOCKER_ENV_VARS $DOCKER_VOLUMES $DOCKER_IMAGE_NAME "$@"
+docker run --privileged $DOCKER_RUN_OPTS $DOCKER_ENV_VARS $DOCKER_VOLUMES $DOCKER_IMAGE_NAME "$@"
 EXITCODE=$?
 
 docker_cleanup
```
This works. Hmm.. but why is needed just only for jammy,,

**Comment by mhs4670go** [comment]
FYI, there were some trial and error as follows.

### gmake -> make

```bash
sudo docker run --rm -it rs7-runtimentools-docker-local.bart.sec.samsung.net/one-devtools:jammy-proxy                  
root@195505edab7b:/# ls -al /usr/bin/gmake
lrwxrwxrwx 1 root root 4 Feb 15  2022 /usr/bin/gmake -> make
```

_gmake_ is just a _make_ command.

### change cmake program

```bash
diff --git a/infra/packaging/preset/20221125 b/infra/packaging/preset/20221125
index 9237de802..8b2ea1e6a 100644
--- a/infra/packaging/preset/20221125
+++ b/infra/packaging/preset/20221125
@@ -51,6 +51,7 @@ function preset_configure()
   # TODO Use "nncc configure" and "nncc build"
   cmake \
     -DCMAKE_INSTALL_PREFIX="${NNCC_INSTALL_PREFIX}" \
+    -DCMAKE_MAKE_PROGRAM="/usr/bin/make" \ ### NOTE HERE ###
     -DCMAKE_BUILD_TYPE=release \
     -DBUILD_WHITELIST=$(join_by ";" "${REQUIRED_UNITS[@]}") \
     -DEXTERNALS_BUILD_THREADS=$((NPROC/2)) \
```

Even if I change a make program to `/usr/bin/make` explicitly, it results in the same error.
```bash
It fails with the following output:
03:10:34  
03:10:34      Change Dir: /home/jenkins/jenkins_agent/workspace/nnfw/test/sw4670.chae/daily-publish-package/build/nncc/CMakeFiles/CMakeTmp
03:10:34      
03:10:34      Run Build Command(s):/usr/bin/make -f Makefile cmTC_c4bb9/fast && /usr/bin/make  -f CMakeFiles/cmTC_c4bb9.dir/build.make CMakeFiles/cmTC_c4bb9.dir/build
03:10:34      make: /usr/bin/make: Operation not permitted ### NOTE HERE ###
03:10:34      make: *** [Makefile:127: cmTC_c4bb9/fast] Error 127
```

### Compile in the docker
```bash
cat << EOL > test.cpp
#include <iostream>
int main(void) { std::cout << "hello" << std::endl; }
EOL

./nncc docker-run g++ test.cpp
./nncc docker-run ./a.out
```

It printed "hello" as expected.

**Comment by mhs4670go** [comment]
I also tested with simple cmake project.
```bash
diff --git a/cmake_test/CMakeLists.txt b/cmake_test/CMakeLists.txt
new file mode 100644
index 000000000..68dcc4ca2
--- /dev/null
+++ b/cmake_test/CMakeLists.txt
@@ -0,0 +1,7 @@
+cmake_minimum_required(VERSION 3.10)
+
+# set the project name
+project(print_hello)
+
+# add the executable
+add_executable(print_hello test.cpp)
diff --git a/cmake_test/test.cpp b/cmake_test/test.cpp
new file mode 100644
index 000000000..7c161136d
--- /dev/null
+++ b/cmake_test/test.cpp
@@ -0,0 +1,7 @@
+#include <iostream>
+
+int main(void)
+{
+  std::cout << "hello" << std::endl;
+  return 0;
+}
diff --git a/infra/scripts/docker_build_nncc.sh b/infra/scripts/docker_build_nncc.sh
index 2e603b550..923375f6e 100755
--- a/infra/scripts/docker_build_nncc.sh
+++ b/infra/scripts/docker_build_nncc.sh
@@ -58,6 +58,9 @@ set -e
 pushd $ROOT_PATH > /dev/null
 
 mkdir -p ${NNCC_INSTALL_PREFIX}
+./nncc docker-run cmake cmake_test
+./nncc docker-run make
+./nncc docker-run ./print_hello
 ./nncc docker-run ./nnas create-package --prefix "${PWD}/${NNCC_INSTALL_PREFIX}" -- "${CONFIG_OPTIONS}"

```

And, the same error has been occurred.

Hmm.. I guess some restrictions are added to ubuntu 22.04 for security reason.

**Comment by ragmani** [comment]
Could you show me permission of `/usr/bin/make`?

**Comment by mhs4670go** [comment]
> Could you show me permission of `/usr/bin/make`?

```bash
-rwxr-xr-x 1 root root 255696 Feb 15  2022 /usr/bin/make
```

**Comment by ragmani** [comment]
I don't know why this error occurs.
It looks similar to https://discuss.circleci.com/t/unable-to-use-make/40552 and https://gitlab.alpinelinux.org/alpine/aports/-/issues/12396 but the errors there are related to alpine docker image.
Anyway the errors there was resolved by upgrading docker version to 20.10.0 or higher.

**Comment by mhs4670go** [comment]
> I don't know why this error occurs. It looks similar to https://discuss.circleci.com/t/unable-to-use-make/40552 and https://gitlab.alpinelinux.org/alpine/aports/-/issues/12396 but the errors there are related to alpine docker image. Anyway the errors there was resolved by upgrading docker version to 20.10.0 or higher.

Thanks for your information. I also saw the articles but jenkins CI has the docker version higher than that..
```bash
Docker version 20.10.7, build f0df350
```

**Comment by ragmani** [comment]
> I also saw the articles but jenkins CI has the docker version higher than that..

 :cry:

**Comment by mhs4670go** [comment]
For the time being, I will turn on privileged option only on jammy. 

But, there is on more issue.

> error: Unmet build dependencies: python3.8 python3.8-venv

Since default python version of jammy is python3.10, the one-compiler package cannot be build where python3.8 packages are required.

**Comment by mhs4670go** [comment]
> Since default python version of jammy is python3.10, the one-compiler package cannot be build where python3.8 packages are required.

python3.8 can be installed via apt-get on bionic and focal but jammy cannot.. T_T

**Comment by mhs4670go** [comment]
@hseok-oh Could we apply below codes into jammy Dockerfile?
```diff
diff --git a/infra/docker/jammy/Dockerfile b/infra/docker/jammy/Dockerfile
index 17db70718..42f9633ed 100644
--- a/infra/docker/jammy/Dockerfile
+++ b/infra/docker/jammy/Dockerfile
@@ -39,6 +39,12 @@ RUN apt-get update && \
 RUN python3 -m pip install --upgrade pip
 RUN python3 -m pip install yapf==0.22.0 numpy flatbuffers
 
+# Install python3.8 for one-compiler
+RUN add-apt-repository ppa:deadsnakes/ppa
+RUN apt-get update && apt-get -qqy install python3.8 python3.8-venv python3.8-dev
+RUN python3.8 -m pip install --upgrade pip
+RUN python3.8 -m pip install numpy flatbuffers
+
 # Install google test (source)
 RUN apt-get update && apt-get -qqy install libgtest-dev
```

**Comment by seanshpark** [comment]
Issue about `protobuf` version, with TF2.10.1

```
tensorflow-cpu 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.1 which is incompatible.
tensorboard 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.1 which is incompatible.
onnx 1.13.0 requires protobuf<4,>=3.20.2, but you have protobuf 3.20.1 which is incompatible.
```

**Comment by mhs4670go** [comment]
I moved debian package generation things into #10389 because it has some issues which is too verbose.

**Comment by seanshpark** [comment]
close for old done issue
