### ISSUE TITLE
[loco] unit test segmentation fault 

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#9968]
Runing `loco_test` as-is is OK, but running single test fails

```
cd build/compiler/loco

./loco_test --gtest_filter="*consturctor_with_param_node*"

Note: Google Test filter = *consturctor_with_param_node*
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from GraphTest
[ RUN      ] GraphTest.consturctor_with_param_node
[1]    1556778 segmentation fault  ./loco_test --gtest_filter="*consturctor_with_param_node*"
```

code
```cxx
  ASSERT_NO_THROW(g->nodes()->destroy(test_node));
  ASSERT_THROW(g->nodes()->destroy(test_node), std::invalid_argument);  <-- THIS
```

Also this may fail too
```
./loco_test --gtest_filter="*create_and_destroy_node*"
```

**Comment by seanshpark** [comment]
Found from https://github.com/Samsung/ONE/issues/9962#issuecomment-1297947575
- Ubuntu 22.04 fails with `./loco_test` so cannot pass test / CI
- Ubuntu 18.04/22.04 is success with `./loco_test` but fails with running single test

**Comment by seanshpark** [comment]
What is happening

&nbsp; | ./loco_test | create_and_destroy_node | consturctor_with_param_node
--- | --- | --- | ---
U1804 | OK | Segmentation fault | Segmentation fault
U2204 | Segmentation fault | OK | Segmentation fault

where `create_and_destroy_node ` is
```
./loco_test --gtest_filter=*create_and_destroy_node
```
`consturctor_with_param_node` is
```
./loco_test --gtest_filter=*consturctor_with_param_node
```

**Comment by seanshpark** [comment]
Anyway, as `destroy(node)` will delete node object, using already deleted object seems unsafe.

**Comment by mhs4670go** [comment]
```cxx
g->nodes()->destroy(pull);
g->nodes()->destroy(pull); // seg fault
```
but
```cxx
g->nodes()->destroy(pull);
g->nodes()->destroy(nullptr);
g->nodes()->destroy(pull); // end successfully
```
..???

**Comment by seanshpark** [comment]
> ..???

o_O;;;

**Comment by mhs4670go** [comment]
After doing some research, the segfault occurs when the `destroy` method is called.
```cxx
void destroy(Node *node)
  {
    if (!ObjectPool<Node>::erase(node))
    {
      throw std::invalid_argument{"node"};
    }
  }

# ..
# main
g->nodes()->destroy(pull); // pull becomes invalid
g->nodes()->destroy(pull);
```

When the `destroy` method is called again, invalid `pull` variable whose data type is `loco::Pull` is dynamic-casted into `Node *`. Dynamic casting of invalid pointer causes undefined behavior.

To resolve this problem,..

1. Tell users not to do it.
2. Change API

First option seems better now.

**Comment by seanshpark** [comment]
we can close this as of now
