### ISSUE TITLE
[one-quantize] Improve interface for quantization dataset of multi-input models

### ISSUE THREAD

**Issue by jinevening** [Samsung/ONE#9977]
## What

Let's discuss interface for quantization dataset of multi-input models.

## Why

Currently, multi-input data should be concatenated for `directory` (or `list`) format. This may not be intuitive to users.

**Comment by jinevening** [comment]
To use separate files for multiple inputs, we may need "**naming convention**".

Under the specified directory, data can be saved as below.

`<data_index>.<input_index>`

`data_index`: Index of data
`input_index`: Index of input

For example, if there are three data for the model with two inputs, data will be saved as below.

```
/0.0
/0.1
/1.0
/1.1
/2.0
/2.1
```

NOTE data_index can be replaced with a string unique for each data. For example, `fish.0`, `fish.1`, `cow.0`, `cow.1` ...

For backward compatibility, we'll need a logic to fallback to the single-input format unless data is saved in the multi-input-supported format.

**Comment by staddy** [comment]
Test data:
[img_files_enumerated.zip](https://github.com/Samsung/ONE/files/10154290/img_files_enumerated.zip)
[add_299_299_3.zip](https://github.com/Samsung/ONE/files/10154291/add_299_299_3.zip)

**Comment by staddy** [comment]
I would like to work on this issue.

**Comment by jinevening** [comment]
Previous interface.

- Data for multiple inputs have to be concatenated in the correct order. https://github.com/Samsung/ONE/blob/master/compiler/record-minmax/driver/Driver.cpp#L129-L135

```cpp
    // Each data file is composed of inputs of a model, concatenated in
    // the same order with the input index of the model
    //
    // For example, for a model with n inputs, the contents of each data
    // file can be visualized as below
    // [input 1][input 2]...[input n]
    // |start............end of file|
```

Proposed interface

- Data for multiple inputs are separate files, but they should have pre-defined naming format (https://github.com/Samsung/ONE/issues/9977#issuecomment-1316620779).

`<data_name>.<input_idx>`

@seanshpark proposed a datalist format.

datalist.txt
```
car.data, box.data // first and second inputs
dog.data cat.data
...
```

Data list format also looks good to me, but our client complained that it is difficult to use the list format in the docker environment.

@seanshpark @lemmaa Could you give any suggestion?

**Comment by seanshpark** [comment]
>  but our client complained

As you told me, `client` is SDK developer team. I hope they can solve the issue :)
Maybe we need some conditions such as the list and the data files should have same parent folder.

**Comment by jinevening** [comment]
Sorry, I used the wrong term. I changed the `client` -> `mdk` team

**Comment by seanshpark** [comment]
As I understand
- record-minmax wants to read data in some ordered way for two or more inputs
- current method is to ask the user to prepare them

for this,
- user should prepare by some rule
- where user may misunderstand the rule
- or may have to do some labor intensive things or to prepare some script for this
- which can be error prone

to understand better from the users environment, we need to get some real situation from our clients...
- asking users to follow some rules from us may not be realistic

**Comment by staddy** [comment]
@seanshpark
> to understand better from the users environment, we need to get some real situation from our clients...

Do we have a way to clarify user needs now, or this task is postponed?

**Comment by jinevening** [comment]
@lemmaa Could you give any feedback on https://github.com/Samsung/ONE/issues/9977#issuecomment-1338595317?

**Comment by jinevening** [comment]
This is resolved with https://github.com/Samsung/ONE/issues/11724.
